'use client'
import { useMemo, useState } from 'react'
import { CalculatorLayout } from '@/components/ui/CalculatorLayout'
import { Card, ResultCard } from '@/components/ui/Card'
import { InputField, SelectField } from '@/components/ui/InputField'
import { FAQSection } from '@/components/ui/FAQSection'
import { SEOContent, SEOContentProps } from '@/components/ui/SEOContent'
interface Props { faqs:any[]; structuredData:object[]; relatedCalculators?:any[]; seoContent?: SEOContentProps }
export default function CalculatorClient({faqs,structuredData,relatedCalculators,seoContent}:Props){
 const [age,setAge]=useState(55),[sex,setSex]=useState<'male'|'female'>('male'),[sbp,setSbp]=useState(135),[chol,setChol]=useState(5.5),[af,setAf]=useState(false),[diabetes,setDiabetes]=useState(false),[smoker,setSmoker]=useState(false),[prior,setPrior]=useState(false)
 const result=useMemo(()=>{const factors=[age>=65,sbp>=140,chol>=6,af,diabetes,smoker,prior]; const count=factors.filter(Boolean).length; return {count, flags:[age>=65?'Age 65+':'',sbp>=140?'Elevated systolic BP':'',chol>=6?'Higher total cholesterol input':'',af?'Atrial fibrillation':'',diabetes?'Diabetes':'',smoker?'Current smoking':'',prior?'Prior stroke/TIA':''].filter(Boolean)}},[age,sbp,chol,af,diabetes,smoker,prior])
 return <CalculatorLayout title="Stroke Risk Factor Calculator" description="Review selected stroke risk factors with a transparent educational score. This page does not estimate an individual 10-year stroke probability." icon="🧠" category="Health" structuredData={structuredData} relatedCalculators={relatedCalculators} slug="stroke-risk-calculator">
 <div className="grid grid-cols-1 lg:grid-cols-3 gap-6"><Card className="lg:col-span-1"><h2 className="text-sm font-semibold text-rose-400 uppercase tracking-wider mb-5">Risk Factors</h2><div className="space-y-4"><SelectField label="Sex" value={sex} onChange={v=>setSex(v as any)} options={[{value:'male',label:'Male'},{value:'female',label:'Female'}]}/><InputField label="Age" value={age} onChange={setAge} min={20} max={100} step={1} suffix="yrs"/><InputField label="Systolic blood pressure" value={sbp} onChange={setSbp} min={80} max={220} step={1} suffix="mmHg"/><InputField label="Total cholesterol" value={chol} onChange={setChol} min={2} max={10} step={0.1} suffix="mmol/L"/>{[['Atrial fibrillation',af,setAf],['Diabetes',diabetes,setDiabetes],['Current smoker',smoker,setSmoker],['Prior stroke/TIA',prior,setPrior]].map(([l,v,s]:any)=><button key={l} onClick={()=>s(!v)} className={`w-full text-left p-3 rounded-xl border text-xs font-semibold ${v?'bg-rose-50 border-rose-300 text-rose-700':'bg-gray-50 border-gray-200 text-gray-600'}`}>{v?'✓ ':'○ '}{l}</button>)}</div></Card>
 <div className="lg:col-span-2 space-y-4"><div className="grid grid-cols-2 gap-3"><ResultCard label="Factors flagged" value={`${result.count}/7`} highlight/><ResultCard label="Prior stroke/TIA" value={prior?'Present':'Not selected'}/></div><Card><h3 className="font-bold text-gray-900 mb-3">Flagged factors</h3>{result.flags.length?<ul className="space-y-2 text-sm text-gray-700">{result.flags.map(f=><li key={f}>• {f}</li>)}</ul>:<p className="text-sm text-gray-600">No selected factors crossed the educational thresholds.</p>}<p className="text-xs text-gray-500 mt-4"><strong>Methodology:</strong> transparent factor count. <strong>Limitations:</strong> the factor count is not a validated risk percentage. A validated model must use its exact population, variables and coefficients.</p></Card><Card><h3 className="font-bold text-gray-900 mb-2">Emergency warning</h3><p className="text-sm text-gray-600">Sudden facial droop, arm weakness, speech difficulty, vision loss, severe imbalance or another sudden neurologic change can be an emergency. Do not use a calculator to decide whether to seek urgent care.</p></Card></div></div>
 <div className="mt-8">{seoContent && <SEOContent {...seoContent} category="health" />}</div><div className="mt-6"><FAQSection faqs={faqs}/></div></CalculatorLayout>
}
