import type { Metadata } from 'next'
import { generateCalculatorMetadata, generateFAQStructuredData, generateWebAppStructuredData } from '@/lib/seo/metadata'
import dynamic from 'next/dynamic'
const CalculatorClient = dynamic(() => import('./CalculatorClient'), {  loading: () => <div className="min-h-[400px] bg-white rounded-2xl border border-gray-100 animate-pulse m-4" /> })
export const metadata: Metadata = generateCalculatorMetadata({ title: 'Joint Mobility Calculator — Range of Motion Score 2026 | ToolTrio', description: 'Free joint mobility calculator 2026. Score your range of motion at shoulder, hip, ankle, neck, thoracic spine, and wrist against clinical norms. Identify your tightest joint and get targeted stretching priorities.', slug: 'joint-mobility-calculator', category: 'health', region: 'usa', keywords: ['joint mobility calculator', 'range of motion calculator', 'ROM test online free', 'joint flexibility score', 'shoulder hip ankle mobility calculator'] })
const relatedCalculators = [{'name': 'Flexibility Calculator', 'href': '/calculators/health/flexibility-calculator', 'icon': '🤸', 'desc': 'ROM and flexibility'}, {'name': 'Sit and Reach', 'href': '/calculators/health/sit-and-reach-calculator', 'icon': '📏', 'desc': 'Hamstring flexibility'}, {'name': 'Posture Assessment', 'href': '/calculators/health/posture-assessment-calculator', 'icon': '🧍', 'desc': 'Postural deviations'}, {'name': 'Muscle Recovery Time', 'href': '/calculators/health/muscle-recovery-time-calculator', 'icon': '💪', 'desc': 'Recovery time'}]
const faqs = [
  {"question": "What is the difference between flexibility and mobility?", "answer": "Flexibility is the passive range of motion of a muscle or muscle group — how far it can be stretched. Mobility is the active, controlled range of motion around a joint — the ability to move through a range with strength and neuromuscular control. Flexibility is necessary but not sufficient for mobility; you can be passively flexible but have poor motor control through that range (common in hypermobile individuals). Functional mobility requires strength through range of motion, which is why mobility training emphasises active exercises like controlled articular rotations (CARs) over passive stretching alone."},
  {"question": "Why does mobility decline with age?", "answer": "Joint mobility decreases with age due to several mechanisms: reduced collagen elasticity and increased crosslinking in connective tissue, decreased synovial fluid viscosity and production, accumulated microtrauma and scar tissue from years of activity, reduction in type I muscle fibre percentage (slow-twitch fibres provide postural stability), and reduced proprioceptive sensitivity (joint position sense). However, research consistently shows that regular mobility training can maintain joint range of motion into advanced age — the declines seen in sedentary older adults are largely disuse-related rather than inevitable aging."},
  {"question": "How much does restricted mobility increase injury risk?", "answer": "Mobility restrictions alter movement mechanics and force distribution. A restricted ankle (poor dorsiflexion) in a squat forces compensatory knee cave or forward lean, increasing anterior cruciate ligament (ACL) and patellofemoral stress. Restricted hip flexion compensation through lumbar flexion is a primary contributor to lumbar disc injuries in deadlifts and running. Restricted thoracic rotation forces cervical or lumbar compensation, increasing neck and lower back injury risk. Functional Movement Screen (FMS) research shows athletes with asymmetrical or restricted movement patterns have significantly higher injury rates than those with adequate fundamental movement."}
]
export default function Page() {
  const _faqSchema = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faqs.map((f: any) => ({ '@type': 'Question', name: f.question, acceptedAnswer: { '@type': 'Answer', text: f.answer } })) }
  return (<><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(_faqSchema) }} /><CalculatorClient faqs={faqs} structuredData={[generateFAQStructuredData(faqs), generateWebAppStructuredData({ name: 'Joint Mobility Score Calculator', description: 'Free joint mobility calculator 2026. Score your range of motion at shoulder, hip, ankle, neck, thora', url: 'https://tooltrio.com/calculators/health/joint-mobility-calculator', category: 'HealthApplication' })]} relatedCalculators={relatedCalculators} /></>)
}
