'use client'
import { useMemo, useState } from 'react'
import { CalculatorLayout } from '@/components/ui/CalculatorLayout'
import { Card, ResultCard } from '@/components/ui/Card'
import { InputField, SelectField } from '@/components/ui/InputField'
import { FAQSection } from '@/components/ui/FAQSection'
interface Props { faqs:any[]; structuredData:object[]; relatedCalculators?:any[] }
export default function CalculatorClient({faqs,structuredData,relatedCalculators}:Props){
 const [age,setAge]=useState(45),[sex,setSex]=useState<'male'|'female'>('male'),[exercise,setExercise]=useState(3),[sleep,setSleep]=useState(7),[stress,setStress]=useState(5),[bmi,setBmi]=useState(26),[alcohol,setAlcohol]=useState(5)
 const result=useMemo(()=>{let score=50; score += exercise>=3?10:exercise===0?-10:0; score += sleep>=7?10:sleep<6?-10:0; score += stress<=4?8:stress>=8?-8:0; score += bmi>=18.5&&bmi<25?8:bmi>=30?-8:0; score += alcohol<=2?5:alcohol>=14?-8:0; return Math.max(0,Math.min(100,Math.round(score)))},[exercise,sleep,stress,bmi,alcohol])
 return <CalculatorLayout title="Testosterone Lifestyle Context Calculator" description="Explore lifestyle factors that can support general hormone health. This tool does not estimate a blood testosterone level." icon="⚡" category="Health" structuredData={structuredData} relatedCalculators={relatedCalculators} slug="testosterone-age-calculator">
 <div className="grid grid-cols-1 lg:grid-cols-3 gap-6"><Card className="lg:col-span-1"><h2 className="text-sm font-semibold text-rose-400 uppercase tracking-wider mb-5">Lifestyle Inputs</h2><div className="space-y-4"><SelectField label="Sex" value={sex} onChange={v=>setSex(v as any)} options={[{value:'male',label:'Male'},{value:'female',label:'Female'}]}/><InputField label="Age" value={age} onChange={setAge} min={18} max={90} step={1} suffix="yrs"/><InputField label="Exercise" value={exercise} onChange={setExercise} min={0} max={7} step={1} suffix="days/week"/><InputField label="Sleep" value={sleep} onChange={setSleep} min={4} max={12} step={0.5} suffix="hrs/night"/><InputField label="Stress" value={stress} onChange={setStress} min={1} max={10} step={1} suffix="/10"/><InputField label="BMI" value={bmi} onChange={setBmi} min={15} max={50} step={0.5} suffix="kg/m²"/><InputField label="Alcohol" value={alcohol} onChange={setAlcohol} min={0} max={50} step={1} suffix="units/week"/></div></Card><div className="lg:col-span-2 space-y-4"><Card><div className="text-center"><p className="text-xs uppercase tracking-wide text-gray-500">Lifestyle-support score</p><p className="text-7xl font-black my-3">{result}</p><p className="text-sm text-gray-600">0–100 educational score; not a hormone measurement.</p></div></Card><Card><h3 className="font-bold text-gray-900 mb-3">Limitations</h3><p className="text-sm text-gray-600 leading-6">Methodology: transparent lifestyle-support score. Limitations: the score summarizes selected lifestyle inputs. It does not infer serum testosterone. Testosterone status is assessed with appropriate laboratory testing and clinical context; the Endocrine Society notes that diagnosis of hypogonadism requires symptoms/signs plus repeated early-morning testosterone measurements.</p></Card></div></div><div className="mt-6"><FAQSection faqs={faqs}/></div></CalculatorLayout>
}
