import { CalculatorBatch48DeepDive } from '@/components/ui/CalculatorBatch48DeepDive'
import type { Metadata } from 'next'
import { generateCalculatorMetadata, generateFAQStructuredData, generateWebAppStructuredData } from '@/lib/seo/metadata'
import dynamic from 'next/dynamic'
const CalculatorClient = dynamic(() => import('./CalculatorClient'), {  loading: () => <div className="min-h-[400px] bg-white rounded-2xl border border-gray-100 animate-pulse m-4" /> })
export const metadata: Metadata = generateCalculatorMetadata({ title: 'Nutrition Timing Calculator — Circadian Eating Windows 2026 | ToolTrio', description: 'Free nutrition timing calculator 2026. Optimise meal timing for fat loss, muscle gain, performance, or longevity. Calculates pre/post workout windows, intermittent fasting schedules, and circadian eating alignment.', slug: 'nutrition-timing-calculator', category: 'health', region: 'usa', keywords: ['nutrition timing calculator', 'meal timing calculator', 'intermittent fasting timing calculator', 'pre workout meal timing', 'circadian eating calculator'] })
const relatedCalculators = [{'name': 'Caloric Needs', 'href': '/calculators/health/caloric-needs-calculator', 'icon': '🍽️', 'desc': 'Daily calorie target'}, {'name': 'Macro Calculator', 'href': '/calculators/health/macro-calculator', 'icon': '🥗', 'desc': 'Macronutrient targets'}, {'name': 'Intermittent Fasting', 'href': '/calculators/health/intermittent-fasting-calculator', 'icon': '⏱️', 'desc': 'IF schedule calculator'}, {'name': 'Protein Synthesis', 'href': '/calculators/health/protein-synthesis-calculator', 'icon': '💪', 'desc': 'MPS optimizer'}]
const faqs = [
  {"question": "Does meal timing actually matter for body composition?", "answer": "Meal timing has meaningful but secondary effects compared to total calorie intake and food quality. The most evidence-backed timing strategies: (1) Caloric front-loading (eating more earlier in the day) — a 12-week Israeli RCT showed the same diet eaten as a large breakfast/medium lunch/small dinner produced 2.5× more weight loss than the reverse; (2) Post-workout protein within 4-6 hours of training stimulates MPS; (3) Avoiding large meals within 2-3 hours of bedtime reduces insulin levels during sleep and improves overnight fat oxidation; (4) Time-restricted eating (16:8 or 14:10) shows modest benefits for metabolic markers independent of calorie restriction."},
  {"question": "What is circadian eating and why does it matter?", "answer": "Circadian eating aligns food intake with the body's biological clock — specifically with the circadian patterns of insulin sensitivity, digestive enzyme activity, and metabolic gene expression that peak in the morning and decline by evening. Insulin sensitivity is highest in the morning (7-10am) and lowest at night — the same meal causes a 50% higher blood glucose spike at 8pm vs 8am. The CALERIE trial and Satchidananda Panda's time-restricted feeding research show that limiting eating to a 10-12 hour window aligned with daylight improves blood pressure, blood glucose, and cholesterol even without calorie reduction."},
  {"question": "What is the optimal pre-workout meal?", "answer": "Pre-workout nutrition depends on session type and timing: for sessions 2-3 hours after a meal, no additional pre-workout fuel is needed. For morning fasted training: 20-30g fast-digesting protein + 30-50g simple carbs 45-60 minutes before maximises performance without excessive caloric load. For endurance training > 90 minutes: carb load 3-4 hours before (3-5g/kg body weight); caffeine 60 minutes before (3-6 mg/kg body weight) consistently improves endurance performance by 2-4%. For strength training: pre-workout carbs do not consistently improve performance in trained athletes eating adequate carbs overall — total daily intake matters more than pre-workout meal."}
]
export default function Page() {
  const _faqSchema = generateFAQStructuredData(faqs)
  return (<><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(_faqSchema) }} /><CalculatorClient faqs={faqs} structuredData={[generateFAQStructuredData(faqs), generateWebAppStructuredData({ name: 'Nutrition Timing Calculator', description: 'Free nutrition timing calculator 2026. Optimise meal timing for fat loss, muscle gain, performance, ', url: 'https://tooltrio.com/calculators/health/nutrition-timing-calculator', category: 'HealthApplication' })]} relatedCalculators={relatedCalculators} />      <CalculatorBatch48DeepDive slug="nutrition-timing-calculator" />
</>)
}
