'use client'
import { useState } from 'react'

const US_STATES = [
  ['AL', 'Alabama'],
  ['AK', 'Alaska'],
  ['AZ', 'Arizona'],
  ['AR', 'Arkansas'],
  ['CA', 'California'],
  ['CO', 'Colorado'],
  ['CT', 'Connecticut'],
  ['DE', 'Delaware'],
  ['FL', 'Florida'],
  ['GA', 'Georgia'],
  ['HI', 'Hawaii'],
  ['ID', 'Idaho'],
  ['IL', 'Illinois'],
  ['IN', 'Indiana'],
  ['IA', 'Iowa'],
  ['KS', 'Kansas'],
  ['KY', 'Kentucky'],
  ['LA', 'Louisiana'],
  ['ME', 'Maine'],
  ['MD', 'Maryland'],
  ['MA', 'Massachusetts'],
  ['MI', 'Michigan'],
  ['MN', 'Minnesota'],
  ['MS', 'Mississippi'],
  ['MO', 'Missouri'],
  ['MT', 'Montana'],
  ['NE', 'Nebraska'],
  ['NV', 'Nevada'],
  ['NH', 'New Hampshire'],
  ['NJ', 'New Jersey'],
  ['NM', 'New Mexico'],
  ['NY', 'New York'],
  ['NC', 'North Carolina'],
  ['ND', 'North Dakota'],
  ['OH', 'Ohio'],
  ['OK', 'Oklahoma'],
  ['OR', 'Oregon'],
  ['PA', 'Pennsylvania'],
  ['RI', 'Rhode Island'],
  ['SC', 'South Carolina'],
  ['SD', 'South Dakota'],
  ['TN', 'Tennessee'],
  ['TX', 'Texas'],
  ['UT', 'Utah'],
  ['VT', 'Vermont'],
  ['VA', 'Virginia'],
  ['WA', 'Washington'],
  ['WV', 'West Virginia'],
  ['WI', 'Wisconsin'],
  ['WY', 'Wyoming'],
  ['DC', 'District of Columbia'],
]



function copyResult(result: any) {

  const text =
    `${result.matchedAddress}\nZIP Code: ${result.zip}`

  navigator.clipboard.writeText(text)
    .then(() => alert('Address copied!'))

}


function shareAddressResult(
  result: any,
  zipDetails: any
) {

  const text =
`📮 Address to ZIP Result

${result.matchedAddress}

ZIP Code: ${result.zip}
${zipDetails?.county ? `County: ${zipDetails.county}` : ''}
${zipDetails?.tzLabel ? `Timezone: ${zipDetails.tzLabel}` : ''}

Find a ZIP code:
tooltrio.com/zip/address-to-zip`

  if (navigator.share) {

    navigator.share({
      title: 'Address to ZIP',
      text
    })

  } else {

    navigator.clipboard
      .writeText(text)
      .then(() =>
        alert('Result copied!')
      )

  }
}


function downloadAddressResult(
  result: any,
  zipDetails: any
) {

  const text =
`TOOLTRIO — Address to ZIP Report

Matched Address
${result.matchedAddress}

ZIP Code
${result.zip}

City: ${zipDetails?.city || 'N/A'}
State: ${zipDetails?.state || 'N/A'}
County: ${zipDetails?.county || 'N/A'}
Timezone: ${zipDetails?.tzLabel || zipDetails?.timezone || 'N/A'}
Area Code: ${zipDetails?.areaCode || 'N/A'}
ZIP Type: ${zipDetails?.type || 'N/A'}
Population: ${zipDetails?.population || 'N/A'}

Latitude: ${result.coordinates?.lat ?? zipDetails?.lat ?? 'N/A'}
Longitude: ${result.coordinates?.lng ?? zipDetails?.lng ?? 'N/A'}

Generated by ToolTrio
tooltrio.com/zip/address-to-zip
`

  const blob =
    new Blob(
      [text],
      { type: 'text/plain' }
    )

  const url =
    URL.createObjectURL(blob)

  const a =
    document.createElement('a')

  a.href = url

  a.download =
    `address-to-zip-${result.zip}.txt`

  a.click()

  URL.revokeObjectURL(url)

}


export default function ZipToolClient() {
const [street, setStreet] = useState('')
const [city, setCity] = useState('')
const [state, setState] = useState('')

const [result, setResult] = useState<any>(null)
const [zipDetails, setZipDetails] = useState<any>(null)

const [loading, setLoading] = useState(false)
const [error, setError] = useState('')

const EXAMPLES = [
  {
    label: 'Washington, DC',
    street: '4600 Silver Hill Rd',
    city: 'Washington',
    state: 'DC',
  },
  {
    label: 'New York, NY',
    street: '350 5th Ave',
    city: 'New York',
    state: 'NY',
  },
  {
    label: 'Los Angeles, CA',
    street: '200 N Spring St',
    city: 'Los Angeles',
    state: 'CA',
  },
]

async function lookup() {

   if (loading) return

  if (street.trim().length < 3) {
    setError(
      'Please enter a valid street address.'
    )
    return
  }

  if (city.trim().length < 2) {
    setError(
      'Please enter a valid city.'
    )
    return
  }

  if (!state) {
    setError(
      'Please select a state.'
    )
    return
  }
  try {

    setLoading(true)
    setError('')
    setResult(null)
    setZipDetails(null)

    // STEP 1:
    // Address → ZIP

    const params = new URLSearchParams({
      street: street.trim(),
      city: city.trim(),
      state: state.trim().toUpperCase(),
    })

    const addressResponse = await fetch(
      `/api/zip/address?${params.toString()}`
    )

    const addressData =
      await addressResponse.json()

    if (!addressResponse.ok) {
      throw new Error(
        addressData.error ||
        'Address could not be found.'
      )
    }

    setResult(addressData)


    // STEP 2:
    // ZIP → full ZIP information

    const zipResponse = await fetch(
      `/api/zip/lookup?zip=${addressData.zip}`
    )

    const zipData =
      await zipResponse.json()

    if (zipResponse.ok) {
      setZipDetails(zipData)
    }

  } catch (err: any) {

    setError(
      err?.message ||
      'Unable to look up this address.'
    )

  } finally {

    setLoading(false)

  }
}

async function lookupExample(
  example: {
    street: string
    city: string
    state: string
  }
) {

  setStreet(example.street)
  setCity(example.city)
  setState(example.state)

  setError('')
  setResult(null)
  setZipDetails(null)

  try {

    setLoading(true)

    const params = new URLSearchParams({
      street: example.street,
      city: example.city,
      state: example.state,
    })

    const addressResponse = await fetch(
      `/api/zip/address?${params.toString()}`
    )

    const addressData =
      await addressResponse.json()

    if (!addressResponse.ok) {
      throw new Error(
        addressData.error ||
        'Address could not be found.'
      )
    }

    setResult(addressData)

    const zipResponse = await fetch(
      `/api/zip/lookup?zip=${addressData.zip}`
    )

    const zipData =
      await zipResponse.json()

    if (zipResponse.ok) {
      setZipDetails(zipData)
    }

  } catch (err: any) {

    setError(
      err?.message ||
      'Unable to look up this address.'
    )

  } finally {

    setLoading(false)

  }
}



  return (
    <div>
      {/* Quick examples */}
      <div className="mb-4">
        <p className="text-xs font-bold text-gray-500 uppercase tracking-wide mb-2">Quick Examples</p>
        <div className="flex flex-wrap gap-2">
          {EXAMPLES.map(ex => (
           <button
  key={ex.label}
  onClick={() => {
    setStreet(ex.street)
    setCity(ex.city)
    setState(ex.state)
    setResult(null)
    setZipDetails(null)
    setError('')
  }}
  className="px-3 py-1 rounded-lg border text-xs font-bold hover:bg-green-50 hover:border-green-400 transition-all"
  style={{
    borderColor: '#e2e8f0',
    color: '#6b7280'
  }}
>
  {ex.label}
</button>
          ))}
        </div>
      </div>

     <div className="space-y-3 mb-6">

  {/* Street */}

  <div>
    <label className="block text-xs font-bold text-gray-600 mb-1">
      Street Address
    </label>

    <input
      value={street}
      onChange={e => {
  setStreet(e.target.value)
  setError('')
}}
      onKeyDown={e => e.key === 'Enter' && lookup()}
      placeholder="e.g. 4600 Silver Hill Rd"
      className="w-full border-2 rounded-xl px-4 py-3
                 focus:outline-none focus:border-green-500"
      style={{
        borderColor: '#e2e8f0',
        background: 'rgba(255,255,255,0.9)'
      }}
    />
  </div>


  {/* City + State */}

  <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">

    <div className="sm:col-span-2">

      <label className="block text-xs font-bold text-gray-600 mb-1">
        City
      </label>

      <input
        value={city}
        onChange={e => setCity(e.target.value)}
        onKeyDown={e => e.key === 'Enter' && lookup()}
        placeholder="e.g. Washington"
        className="w-full border-2 rounded-xl px-4 py-3
                   focus:outline-none focus:border-green-500"
        style={{
          borderColor: '#e2e8f0'
        }}
      />

    </div>


    <div>

      <label className="block text-xs font-bold text-gray-600 mb-1">
        State
      </label>

    <select
  value={state}
  onChange={e => {
    setState(e.target.value)
    setError('')
  }}
  className="
    w-full
    border-2
    rounded-xl
    px-4
    py-3
    bg-white
    focus:outline-none
    focus:border-green-500
  "
  style={{
    borderColor: '#e2e8f0'
  }}
>
  <option value="">
    Select state
  </option>

  {US_STATES.map(([code, name]) => (
    <option
      key={code}
      value={code}
    >
      {code} — {name}
    </option>
  ))}
</select>

    </div>

  </div>


  {/* Search */}

  <button
    onClick={lookup}
    disabled={loading}
    className="w-full px-6 py-3.5 text-white
               font-bold rounded-xl
               disabled:opacity-60"
    style={{
      background:
        'linear-gradient(135deg,#22c55e,#16a34a)',

      boxShadow:
        '0 4px 16px rgba(34,197,94,0.3)'
    }}
  >

   {loading ? (
  <span className="flex items-center justify-center gap-2">
    <span
      className="
        inline-block
        w-4
        h-4
        border-2
        border-white/40
        border-t-white
        rounded-full
        animate-spin
      "
    />
    Finding address...
  </span>
) : (
  <span>
    🏠 Find ZIP Code
  </span>
)}

  </button>

</div>

{error && (
  <div
    className="
      mb-4
      rounded-xl
      border
      border-red-200
      bg-red-50
      px-4
      py-3
      text-sm
      text-red-700
    "
  >
    ⚠️ {error}
  </div>
)}

{result && (
  <div className="space-y-4">

<div className="grid grid-cols-2 sm:grid-cols-4 gap-2">

  <button
    onClick={() => copyResult(result)}
    className="py-2.5 px-3 rounded-xl border-2 border-green-200 bg-white text-green-700 font-bold text-xs hover:bg-green-50 transition"
  >
    📋 Copy
  </button>


  <button
    onClick={() =>
      shareAddressResult(
        result,
        zipDetails
      )
    }
    className="py-2.5 px-3 rounded-xl border-2 border-green-200 bg-white text-green-700 font-bold text-xs hover:bg-green-50 transition"
  >
    📤 Share
  </button>


  <button
    onClick={() =>
      downloadAddressResult(
        result,
        zipDetails
      )
    }
    className="py-2.5 px-3 rounded-xl border-2 border-green-200 bg-white text-green-700 font-bold text-xs hover:bg-green-50 transition"
  >
    ⬇️ Download
  </button>


  <a
    href={
      `https://www.google.com/maps/search/?api=1&query=${
        result.coordinates?.lat ??
        zipDetails?.lat
      },${
        result.coordinates?.lng ??
        zipDetails?.lng
      }`
    }
    target="_blank"
    rel="noopener noreferrer"
    className="py-2.5 px-3 rounded-xl border-2 border-blue-200 bg-white text-blue-700 font-bold text-xs hover:bg-blue-50 transition text-center"
  >
    📍 Map
  </a>

</div>



    {/* Main Address Result */}
    <div
      className="rounded-2xl border p-5"
      style={{
        background:
          'linear-gradient(135deg, rgba(240,253,244,0.95), rgba(236,253,245,0.75))',
        borderColor: '#bbf7d0'
      }}
    >

      {/* Success badge */}
      <div className="text-center mb-5">

        <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-green-100 text-green-700 text-xs font-black uppercase tracking-wide mb-3">
          ✓ Address Match Found
        </div>

        <div className="text-sm font-semibold text-gray-700 max-w-xl mx-auto">
          {result.matchedAddress}
        </div>
        <p className="text-[11px] text-gray-400 mt-1">
  Matched using U.S. Census geocoding data
</p>

        <div className="mt-4 text-5xl sm:text-6xl font-black font-mono text-green-600 tracking-tight">
          {result.zip}
        </div>

        <div className="text-xs font-bold text-gray-400 uppercase tracking-widest mt-1">
          ZIP Code
        </div>

      </div>


{result && !zipDetails && loading && (
  <div className="border-t border-green-200 pt-4 mt-4">

    <div className="flex items-center justify-center gap-2 text-sm text-gray-500">

      <span
        className="
          inline-block
          w-4
          h-4
          border-2
          border-green-200
          border-t-green-600
          rounded-full
          animate-spin
        "
      />

      Loading ZIP details...

    </div>

  </div>
)}

      {/* Full ZIP information */}
      {zipDetails && (

        <div>

          <div className="border-t border-green-200 pt-4">

            <p className="text-xs font-black text-gray-500 uppercase tracking-wide mb-3">
              📋 ZIP Code Details
            </p>

            <div className="grid grid-cols-2 sm:grid-cols-3 gap-2">

              {[
                {
                  label: '🏙️ City',
                  value: zipDetails.city
                },
                {
                  label: '🗺️ State',
                  value:
                    zipDetails.stateCode
                      ? `${zipDetails.state} (${zipDetails.stateCode})`
                      : zipDetails.state
                },
                {
                  label: '🏛️ County',
                  value: zipDetails.county
                },
                {
                  label: '🕐 Timezone',
                  value:
                    zipDetails.tzLabel ||
                    zipDetails.timezone
                },
                {
                  label: '📞 Area Code',
                  value:
                    zipDetails.areaCode
                      ? `(${zipDetails.areaCode})`
                      : 'N/A'
                },
                {
                  label: '📦 ZIP Type',
                  value:
                    zipDetails.type || 'N/A'
                },

                {
                  label: '👥 Population',
                  value:
                    zipDetails.population > 0
                      ? zipDetails.population.toLocaleString()
                      : 'N/A'
                },

                {
                  label: '🏠 Est. Households',
                  value:
                    zipDetails.population > 0
                      ? Math.round(
                          zipDetails.population / 2.53
                        ).toLocaleString()
                      : 'N/A'
                },

                {
                  label: '⛰️ Elevation',
                  value:
                    zipDetails.elevation != null
                      ? `${zipDetails.elevation} ft`
                      : 'N/A'
                },

              ].map(item => (

                <div
                  key={item.label}
                  className="rounded-xl border border-gray-200 bg-white/80 p-3"
                >

                  <div className="text-[11px] text-gray-400 mb-1">
                    {item.label}
                  </div>

                  <div className="font-bold text-gray-900 text-sm break-words">
                    {item.value || 'N/A'}
                  </div>

                </div>

              ))}

            </div>

          </div>


          {/* Coordinates */}
          <div className="grid grid-cols-2 gap-2 mt-2">

            <div className="rounded-xl border border-gray-200 bg-white/80 p-3">

              <div className="text-[11px] text-gray-400">
                🌐 Latitude
              </div>

              <div className="font-bold text-gray-900 text-sm font-mono">
                {result.coordinates?.lat != null
                  ? Number(result.coordinates.lat).toFixed(6)
                  : zipDetails.lat != null
                    ? Number(zipDetails.lat).toFixed(6)
                    : 'N/A'}
              </div>

            </div>


            <div className="rounded-xl border border-gray-200 bg-white/80 p-3">

              <div className="text-[11px] text-gray-400">
                🌐 Longitude
              </div>

              <div className="font-bold text-gray-900 text-sm font-mono">
                {result.coordinates?.lng != null
                  ? Number(result.coordinates.lng).toFixed(6)
                  : zipDetails.lng != null
                    ? Number(zipDetails.lng).toFixed(6)
                    : 'N/A'}
              </div>

            </div>

          </div>

        </div>

      )}

    </div>

  </div>
)}


    </div>
  )
}
