import type { Metadata } from 'next'
import { generateCalculatorMetadata, generateFAQStructuredData, generateWebAppStructuredData } from '@/lib/seo/metadata'
import dynamic from 'next/dynamic'
const CalculatorClient = dynamic(() => import('./CalculatorClient'), {  loading: () => <div className="min-h-[400px] bg-white rounded-2xl border border-gray-100 animate-pulse m-4" /> })
export const metadata: Metadata = generateCalculatorMetadata({ title: 'PCOS Risk Calculator — Symptom Score & Investigations 2026 | ToolTrio', description: 'Free PCOS risk score calculator 2026. Assess polycystic ovary syndrome likelihood from cycle irregularity, acne, hirsutism, BMI, insulin levels, family history, and polycystic ovaries. Get investigation checklist.', slug: 'pcos-risk-calculator', category: 'health', region: 'usa', keywords: ['PCOS risk calculator', 'polycystic ovary syndrome calculator', 'PCOS symptom score', 'PCOS test online free', 'Rotterdam criteria PCOS calculator'] })
const relatedCalculators = [{'name': 'Menstrual Health', 'href': '/calculators/health/menstrual-health-calculator', 'icon': '🌙', 'desc': 'Cycle health score'}, {'name': 'Ovulation Calculator', 'href': '/calculators/health/ovulation-calculator', 'icon': '📅', 'desc': 'Fertile window'}, {'name': 'Testosterone Age', 'href': '/calculators/health/testosterone-age-calculator', 'icon': '⚡', 'desc': 'Hormone optimization'}, {'name': 'Insulin Resistance', 'href': '/calculators/health/diabetes-risk-calculator', 'icon': '🩸', 'desc': 'Diabetes risk'}]
const faqs = [
  {"question": "What are the Rotterdam criteria for PCOS diagnosis?", "answer": "PCOS is diagnosed when 2 of the following 3 Rotterdam criteria are met: (1) Irregular or absent ovulation — cycles outside 21-35 days, or fewer than 8 cycles per year; (2) Clinical or biochemical hyperandrogenism — excess androgen effects such as acne, hirsutism (male-pattern hair growth), or elevated testosterone/DHEAS on blood test; (3) Polycystic ovaries on ultrasound — ≥ 12 follicles in either ovary or ovarian volume > 10 mL. PCOS affects 6-12% of reproductive-age women and is the leading cause of ovulatory infertility. Diagnosis requires excluding other causes of hyperandrogenism."},
  {"question": "Is PCOS always associated with polycystic ovaries?", "answer": "No — this is a common misconception. 'Polycystic' in PCOS is a misnomer; the ovarian cysts are actually normal follicles that failed to ovulate, not true pathological cysts. About 20-30% of women with PCOS do not have polycystic ovaries on ultrasound yet still meet diagnostic criteria through the other two Rotterdam criteria. Conversely, polycystic ovarian morphology (PCOM) on ultrasound is present in 20-25% of women without PCOS. This is why ultrasound alone cannot diagnose PCOS — it must be interpreted alongside clinical symptoms and hormonal tests."},
  {"question": "What are the long-term health implications of PCOS?", "answer": "PCOS significantly increases risk of metabolic complications: insulin resistance affects 50-70% of women with PCOS regardless of weight, conferring 5× higher lifetime T2D risk. Cardiovascular risk is elevated, particularly in obese PCOS. Endometrial cancer risk is 2-3× higher due to chronic anovulation causing unopposed oestrogen exposure to the endometrium. Mental health impact is significant — depression and anxiety prevalence is 2-3× higher in PCOS, partly hormonal and partly related to the multiple physical symptoms affecting appearance and fertility. Holistic management addresses metabolic, reproductive, and psychological dimensions."}
]
export default function Page() {
  const _faqSchema = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faqs.map((f: any) => ({ '@type': 'Question', name: f.question, acceptedAnswer: { '@type': 'Answer', text: f.answer } })) }
  return (<><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(_faqSchema) }} /><CalculatorClient faqs={faqs} structuredData={[generateFAQStructuredData(faqs), generateWebAppStructuredData({ name: 'PCOS Risk Score Calculator', description: 'Free PCOS risk score calculator 2026. Assess polycystic ovary syndrome likelihood from cycle irregul', url: 'https://tooltrio.com/calculators/health/pcos-risk-calculator', category: 'HealthApplication' })]} relatedCalculators={relatedCalculators} /></>)
}
