export type FinanceBatch05Status =
  | 'reviewed'
  | 'formula_review'
  | 'tax_rule_review'
  | 'custom_estimate'
  | 'needs_manual_review'

export interface FinanceBatch05Profile {
  slug: string
  status: FinanceBatch05Status
  methodology: string
  limitations: string[]
  sources: Array<{ title: string; url: string; accessed?: string }>
  currentYear: number
}

const IRS = 'https://www.irs.gov'
const HUD = 'https://www.hud.gov'
const CFPB = 'https://www.consumerfinance.gov'
const SSA = 'https://www.ssa.gov'
const FINRA = 'https://www.finra.org'

export const FINANCE_BATCH_05: FinanceBatch05Profile[] = [
  { slug: 'estate-tax-calculator', status: 'tax_rule_review', methodology: 'Simplified federal estate-tax scenario using gross estate, entered deductions/transfers and the 2026 basic exclusion.', limitations: ['Does not reproduce Form 706, prior adjusted taxable gifts, all credits, valuation rules or state death taxes.', 'Portability and marital-deduction treatment require additional facts and elections.'], sources: [{ title: 'IRS — Estate Tax', url: `${IRS}/businesses/small-businesses-self-employed/estate-tax` }], currentYear: 2026 },
  { slug: 'euro-auto-loan-calculator', status: 'custom_estimate', methodology: 'Amortizing vehicle-finance scenario using user-entered amount, APR, term and balloon/finance assumptions.', limitations: ['PCP, HP and personal-loan structures differ by country and lender.', 'Taxes, fees, commissions and consumer-protection rules vary by jurisdiction.'], sources: [], currentYear: 2026 },
  { slug: 'euro-bonds-vs-etf-calculator', status: 'custom_estimate', methodology: 'Scenario comparison of bond and ETF returns using user-entered yield, growth, fees and holding-period assumptions.', limitations: ['Does not model every country-specific tax regime or fund structure.', 'Market returns and future yields are uncertain.'], sources: [{ title: 'FINRA — Investing Basics', url: `${FINRA}/investors/investing/investing-basics` }], currentYear: 2026 },
  { slug: 'europe-etf-vs-property-calculator', status: 'custom_estimate', methodology: 'Scenario comparison of ETF total return and property cash flow/appreciation assumptions.', limitations: ['Property taxes, transaction costs, financing and rental rules vary by country.', 'ETF returns, volatility and taxes are scenario assumptions.'], sources: [], currentYear: 2026 },
  { slug: 'europe-growth-vs-value-etf-calculator', status: 'custom_estimate', methodology: 'Total-return scenario comparison between growth and value ETF assumptions.', limitations: ['Does not forecast future factor performance.', 'Fund fees, taxes, currency and index composition affect actual results.'], sources: [], currentYear: 2026 },
  { slug: 'europe-msci-world-vs-sp500-calculator', status: 'custom_estimate', methodology: 'Historical/assumption-driven total-return comparison between broad global and U.S. equity exposures.', limitations: ['Historical returns are not forecasts.', 'Currency, valuation, dividends, fees and tax treatment can change outcomes.'], sources: [], currentYear: 2026 },
  { slug: 'europe-property-vs-reit-calculator', status: 'custom_estimate', methodology: 'Scenario comparison of direct property economics with REIT investment assumptions.', limitations: ['Property leverage, maintenance, vacancy and taxes are highly jurisdiction-specific.', 'REIT distributions and market prices fluctuate.'], sources: [], currentYear: 2026 },
  { slug: 'european-mortgage-calculator', status: 'formula_review', methodology: 'Mortgage-payment scenario using amortization mathematics and user-entered European loan assumptions.', limitations: ['European mortgages differ substantially in fixed periods, refinancing, fees, taxes and repayment conventions.', 'This is not a lender quote or eligibility determination.'], sources: [], currentYear: 2026 },
  { slug: 'family-budget-planner-calculator', status: 'reviewed', methodology: 'Cash-flow budgeting from user-entered household income, fixed expenses, variable expenses, savings and debt payments.', limitations: ['Does not predict future expenses or household behavior.'], sources: [], currentYear: 2026 },
  { slug: 'fd-calculator', status: 'custom_estimate', methodology: 'Fixed-deposit maturity calculation using principal, rate, tenure and compounding assumptions.', limitations: ['Bank rates, premature-withdrawal penalties, tax treatment and senior-citizen rates vary.'], sources: [], currentYear: 2026 },
  { slug: 'fd-comparison-calculator', status: 'custom_estimate', methodology: 'Scenario comparison of fixed deposits using user-entered bank rates, terms and tax assumptions.', limitations: ['Does not verify live bank rates or deposit-insurance limits.'], sources: [], currentYear: 2026 },
  { slug: 'federal-contractor-tax-calculator', status: 'tax_rule_review', methodology: 'Simplified Virginia 1099 contractor scenario including self-employment tax and a modeled federal income-tax estimate.', limitations: ['Uses a flat federal rate rather than full progressive tax computation.', 'Virginia tax, QBI, retirement deductions and estimated-tax requirements require taxpayer-specific analysis.'], sources: [{ title: 'IRS Publication 15', url: `${IRS}/publications/p15` }], currentYear: 2026 },
  { slug: 'fha-vs-conventional-calculator', status: 'formula_review', methodology: 'Scenario comparison of FHA and conventional mortgage costs, including modeled mortgage insurance and financing assumptions.', limitations: ['FHA limits vary by county and property type.', 'Conventional PMI, rate and eligibility vary by lender and borrower.'], sources: [{ title: 'HUD — 2026 FHA Loan Limits', url: `${HUD}/news/hud-no-25-145` }, { title: 'CFPB — Buying a House', url: `${CFPB}/buy-a-house/` }], currentYear: 2026 },
  { slug: 'fica-tax-calculator', status: 'tax_rule_review', methodology: 'FICA estimate using 2026 Social Security wage base, Medicare tax and Additional Medicare Tax thresholds.', limitations: ['Actual payroll tax depends on wage type, year-to-date wages, filing status for Additional Medicare Tax and employer/payroll handling.', 'Self-employment tax is a separate calculation with different mechanics.'], sources: [{ title: 'IRS Topic 751 — Social Security and Medicare withholding rates', url: `${IRS}/taxtopics/tc751` }], currentYear: 2026 },
  { slug: 'fire-calculator', status: 'custom_estimate', methodology: 'Financial-independence projection from spending, savings, portfolio balance, return and withdrawal assumptions.', limitations: ['Withdrawal rates are planning assumptions, not guarantees.', 'Taxes, sequence risk, inflation and changing spending can materially alter outcomes.'], sources: [], currentYear: 2026 },
  { slug: 'fire-europe-calculator', status: 'custom_estimate', methodology: 'European financial-independence scenario using user-entered spending, savings, returns and pension assumptions.', limitations: ['State pension and tax systems differ by country.', 'Currency, inflation and healthcare costs can change outcomes.'], sources: [], currentYear: 2026 },
  { slug: 'fire-number-calculator', status: 'custom_estimate', methodology: 'Target-portfolio calculation based on annual spending and an entered withdrawal-rate assumption.', limitations: ['The withdrawal-rate assumption is not a guaranteed safe rate for every horizon or portfolio.'], sources: [], currentYear: 2026 },
  { slug: 'forbearance-cost-calculator', status: 'custom_estimate', methodology: 'Loan-cost scenario comparing scheduled payments with a modeled forbearance period and capitalization assumptions.', limitations: ['Servicer and loan-program rules determine whether interest capitalizes and how repayment is structured.'], sources: [], currentYear: 2026 },
  { slug: 'france-pea-vs-assurance-vie-calculator', status: 'tax_rule_review', methodology: 'France-specific investment scenario comparing PEA and assurance-vie assumptions.', limitations: ['French tax treatment depends on holding period, withdrawals, contributions and policy/account structure.'], sources: [], currentYear: 2026 },
  { slug: 'freelance-income-tax-calculator', status: 'tax_rule_review', methodology: 'Simplified self-employed income-tax scenario using user-entered revenue, expenses and tax assumptions.', limitations: ['Not a full Form 1040 or state-return calculation.', 'Estimated-tax safe harbors and filing requirements depend on the complete household tax picture.'], sources: [{ title: 'IRS Publication 505 — Tax Withholding and Estimated Tax', url: `${IRS}/publications/p505` }], currentYear: 2026 },
  { slug: 'freelancer-quarterly-tax-calculator', status: 'tax_rule_review', methodology: 'Quarterly estimated-tax budgeting using modeled annual income, deductions and federal self-employment tax.', limitations: ['2026 installment due dates are April 15, June 15, September 15 and January 15, 2027.', 'Safe-harbor rules depend on prior-year tax, current-year tax, withholding and household facts.'], sources: [{ title: 'IRS Publication 505 — Tax Withholding and Estimated Tax', url: `${IRS}/publications/p505` }], currentYear: 2026 },
  { slug: 'fsa-calculator', status: 'tax_rule_review', methodology: 'Health FSA contribution and tax-savings scenario using the 2026 salary-reduction limit and plan-specific carryover assumption.', limitations: ['Employers choose whether to allow carryover or a grace period within applicable rules.', 'Tax savings depend on payroll-tax and income-tax circumstances.'], sources: [{ title: 'IRS — 2026 tax inflation adjustments', url: `${IRS}/newsroom/irs-releases-tax-inflation-adjustments-for-tax-year-2026-including-amendments-from-the-one-big-beautiful-bill` }], currentYear: 2026 },
  { slug: 'germany-etf-vs-tagesgeld-calculator', status: 'custom_estimate', methodology: 'Germany-specific scenario comparing deposit interest with ETF return assumptions.', limitations: ['German tax treatment, deposit rates and ETF taxation can change.', 'The calculator does not provide a personalized German tax assessment.'], sources: [], currentYear: 2026 },
  { slug: 'gift-tax-calculator', status: 'tax_rule_review', methodology: 'Simplified U.S. federal gift-tax scenario using annual exclusion, taxable gifts and lifetime basic exclusion assumptions.', limitations: ['Form 709 filing can be required in situations not captured by a simple annual-exclusion test.', 'Gift splitting, future interests, marital/charitable deductions and direct education/medical payments have special rules.'], sources: [{ title: 'IRS — Gift Tax FAQs', url: `${IRS}/businesses/small-businesses-self-employed/frequently-asked-questions-on-gift-taxes` }], currentYear: 2026 },
  { slug: 'gig-economy-tax-calculator', status: 'tax_rule_review', methodology: 'Simplified gig-worker scenario using modeled net self-employment income, mileage, QBI and federal tax assumptions.', limitations: ['2026 business mileage is 72.5 cents/mile for Jan–Jun and 76 cents/mile for Jul–Dec.', 'The calculator does not implement the full progressive income-tax system, wage-base coordination, credits or all deduction rules.'], sources: [{ title: 'IRS — 2026 Standard Mileage Rates', url: `${IRS}/tax-professionals/standard-mileage-rates` }], currentYear: 2026 },
]

export const FINANCE_BATCH_05_SLUGS = FINANCE_BATCH_05.map((profile) => profile.slug)
