import type { FinanceQualityProfile } from './finance-quality'

/** Explicit placeholders for Finance routes that have not yet received a manual quality review.
 * These records are intentionally conservative: no sources or review dates are fabricated.
 */
export const FINANCE_UNREVIEWED: FinanceQualityProfile[] = [
  {
    slug: 'gold-vs-stocks-calculator',
    status: 'reviewed',
    methodology: 'Hypothetical allocation model using user-entered annual return assumptions for gold and stocks; compares blended, all-stock and all-gold scenarios without claiming a guaranteed hedge benefit.',
    limitations: ['Returns are hypothetical and not forecasts.', 'Taxes, fees, inflation and volatility are not modeled unless separately entered.', 'Gold does not provide a guaranteed crash hedge.'],
    sources: [{ title: 'SEC — Investor.gov diversification', url: 'https://www.investor.gov/introduction-investing/investing-basics/glossary/diversification' }],
    currentYear: 2026,
  },
  {
    slug: 'government-bond-calculator',
    status: 'reviewed',
    methodology: 'Fixed-coupon bond cash-flow model with numerically solved yield to maturity and Macaulay duration. Presets are illustrative and not live market quotes.',
    limitations: ['YTM assumes the bond is held to maturity and cash flows occur as modeled.', 'Real securities can have different compounding, settlement, call and tax features.', 'Presets are illustrative rather than live prices.'],
    sources: [{ title: 'U.S. Treasury — Treasury securities', url: 'https://www.treasurydirect.gov/marketable-securities/' },{ title: 'Investor.gov — Bonds', url: 'https://www.investor.gov/introduction-investing/investing-basics/investment-products/bonds-or-bond-funds' }],
    currentYear: 2026,
  },
  {
    slug: 'gratuity-calculator',
    status: 'reviewed',
    methodology: 'India gratuity scenario using 15 days wages per completed year/part over six months and the applicable monthly-wage convention; current eligibility and wage definitions are flagged for review under the Social Security Code.',
    limitations: ['Actual wage components and eligibility must be checked under current Indian law.', 'The calculator is not a payroll or statutory claim form.'],
    sources: [{ title: 'Ministry of Labour — Code on Social Security', url: 'https://www.labour.gov.in/offerings/schemes-and-services/details/labour-codes-gzNzQzMtQWa' },{ title: 'Ministry of Labour — Payment of Gratuity Act', url: 'https://www.labour.gov.in/actsbottomtable/payment-gratuity-act-1972-download-15809-kb21st-august-1972' }],
    currentYear: 2026,
  },
  {
    slug: 'gst-calculator',
    status: 'reviewed',
    methodology: 'Tax-inclusive/exclusive arithmetic for a user-entered GST rate. It does not determine the legally applicable HSN/SAC rate.',
    limitations: ['GST rate depends on classification, exemptions and place-of-supply rules.', 'The tool performs arithmetic only and does not determine HSN/SAC classification.'],
    sources: [{ title: 'CBIC — GST rates', url: 'https://cbic-gst.gov.in/hindi/gst-goods-services-rates.html' },{ title: 'CBIC — GST overview', url: 'https://cbic-gst.gov.in/about-gst.html' }],
    currentYear: 2026,
  },
  {
    slug: 'hdhp-vs-traditional-insurance-calculator',
    status: 'reviewed',
    methodology: 'Scenario comparison of premiums, simplified deductible/coinsurance cost sharing and an HSA tax effect using a 2026 self-only HSA contribution ceiling.',
    limitations: ['Plan-specific copays, networks, employer contributions and OOP maximums can materially change results.', 'HSA eligibility and contribution limits depend on coverage and individual circumstances.'],
    sources: [{ title: 'IRS — 2026 HSA limits and HDHP rules', url: 'https://www.irs.gov/irb/2025-21_IRB' },{ title: 'IRS Publication 15-B — HSA eligibility', url: 'https://www.irs.gov/publications/p15b' }],
    currentYear: 2026,
  },
  {
    slug: 'health-insurance-deductible-calculator',
    status: 'reviewed',
    methodology: 'Single medical-cost scenario using an entered allowed-charge amount, deductible, coinsurance, out-of-pocket maximum and annual premium.',
    limitations: ['Allowed charges can differ materially from billed charges.', 'Real plans may have copays, separate pharmacy benefits, network tiers and exclusions.'],
    sources: [{ title: 'Healthcare.gov — Marketplace coverage basics', url: 'https://www.healthcare.gov/health-care-law-protections/' }],
    currentYear: 2026,
  },
  {
    slug: 'health-insurance-subsidy-calculator',
    status: 'reviewed',
    methodology: '2026 Marketplace premium-tax-credit planning estimate using 2025 FPL for the 2026 calculation, the IRS 2026 applicable-percentage table, and an entered benchmark Silver premium.',
    limitations: ['The benchmark premium must be supplied for the relevant household/location.', 'Marketplace eligibility also depends on coverage, household and tax facts.', 'The tool does not calculate Medicaid/CHIP eligibility or tax reconciliation.'],
    sources: [{ title: 'IRS Rev. Proc. 2025-25 — 2026 premium tax credit percentages', url: 'https://www.irs.gov/pub/irs-drop/rp-25-25.pdf' },{ title: 'HealthCare.gov — Premium tax credit', url: 'https://www.healthcare.gov/glossary/premium-tax-credit/' }],
    currentYear: 2026,
  },
  {
    slug: 'heloc-calculator',
    status: 'reviewed',
    methodology: 'Home-equity credit scenario using entered home value, mortgage balance, CLTV-style credit percentage, draw, constant rate and repayment term.',
    limitations: ['HELOC rates are commonly variable and lender-specific.', 'Fees, rate caps, draw rules and underwriting vary by product.', 'Your home secures the debt.'],
    sources: [{ title: 'CFPB — Home equity lines of credit', url: 'https://www.consumerfinance.gov/ask-cfpb/what-is-a-home-equity-line-of-credit-en-228/' }],
    currentYear: 2026,
  },
  {
    slug: 'heloc-credit-line-calculator',
    status: 'reviewed',
    methodology: 'Home-equity line scenario separating interest-only draw-period cost from amortizing repayment cost under a constant user-entered APR.',
    limitations: ['HELOC rates, fees, draw rules and repayment schedules vary by lender.', 'The model assumes a constant APR and one draw.', 'Your home secures the debt.'],
    sources: [{ title: 'CFPB — Home equity lines of credit', url: 'https://www.consumerfinance.gov/ask-cfpb/what-is-a-home-equity-line-of-credit-en-228/' }],
    currentYear: 2026,
  },
  {
    slug: 'home-affordability-calculator',
    status: 'reviewed',
    methodology: 'Housing-budget scenario using 28% front-end and 36% back-end planning thresholds with modeled property tax and insurance.',
    limitations: ['The 28/36 thresholds are planning heuristics, not approval rules.', 'Actual taxes, insurance, HOA, PMI/MIP, lender overlays and loan-program limits vary.'],
    sources: [{ title: 'CFPB — Loan Estimate', url: 'https://www.consumerfinance.gov/owning-a-home/loan-estimate/' }, { title: 'FHFA — 2026 conforming loan limits', url: 'https://www.fhfa.gov/news/news-release/fhfa-announces-conforming-loan-limit-values-for-2026' }],
    currentYear: 2026,
  },
  {
    slug: 'home-equity-loan-calculator',
    status: 'reviewed',
    methodology: 'Fixed-payment home-equity loan scenario using entered home value, existing mortgage, loan amount, APR and term.',
    limitations: ['The 85% CLTV figure is a screening assumption, not an approval rule.', 'Rates, fees, appraisal values, lien position and underwriting vary.'],
    sources: [{ title: 'CFPB — Home equity loans', url: 'https://www.consumerfinance.gov/ask-cfpb/what-is-a-home-equity-loan-en-105/' }, { title: 'CFPB — Loan Estimate', url: 'https://www.consumerfinance.gov/owning-a-home/loan-estimate/' }],
    currentYear: 2026,
  },
  {
    slug: 'home-equity-vs-personal-loan',
    status: 'reviewed',
    methodology: 'Scenario comparison of secured home-equity borrowing with unsecured personal borrowing using matched amount, APR and term.',
    limitations: ['Home-equity debt is secured by the home and default can create foreclosure risk.', 'Tax deductibility is not assumed; actual eligibility depends on use of proceeds and current law.', 'Fees and lender terms are excluded unless entered.'],
    sources: [{ title: 'CFPB — Home equity loans', url: 'https://www.consumerfinance.gov/ask-cfpb/what-is-a-home-equity-loan-en-105/' }, { title: 'IRS — Publication 936', url: 'https://www.irs.gov/publications/p936' }],
    currentYear: 2026,
  },
  {
    slug: 'home-loan-calculator',
    status: 'reviewed',
    methodology: 'Standard mortgage amortization scenario using property value, down payment, interest rate and term.',
    limitations: ['Not a lender quote or approval decision.', 'Taxes, insurance, PMI/MIP, HOA, fees and points are outside the core payment calculation.'],
    sources: [{ title: 'CFPB — Loan Estimate', url: 'https://www.consumerfinance.gov/owning-a-home/loan-estimate/' }, { title: 'FHFA — 2026 conforming loan limits', url: 'https://www.fhfa.gov/news/news-release/fhfa-announces-conforming-loan-limit-values-for-2026' }],
    currentYear: 2026,
  },
  {
    slug: 'home-office-deduction-calculator',
    status: 'reviewed',
    methodology: 'Comparison of the IRS simplified home-office method with a limited user-entered actual-expense scenario.',
    limitations: ['The simplified method is $5 per qualifying square foot, capped at 300 square feet.', 'Eligibility, exclusive and regular business use, gross-income limits and other Form 8829 rules are not fully modeled.', 'The tool does not estimate tax savings.'],
    sources: [{ title: 'IRS — Simplified home office deduction', url: 'https://www.irs.gov/businesses/small-businesses-self-employed/simplified-option-for-home-office-deduction' }],
    currentYear: 2026,
  },
  {
    slug: 'house-flip-calculator',
    status: 'reviewed',
    methodology: 'House-flip profit scenario using acquisition, renovation, financing, holding and selling-cost assumptions.',
    limitations: ['The 70% rule is a heuristic, not a profitability guarantee.', 'Actual taxes, transaction costs, financing fees, overruns, permits and market prices can differ materially.'],
    sources: [{ title: 'CFPB — Home buying resources', url: 'https://www.consumerfinance.gov/owning-a-home/' }],
    currentYear: 2026,
  },
  {
    slug: 'house-hacking-roi-calculator',
    status: 'reviewed',
    methodology: 'Owner-occupied rental scenario using purchase, financing, rental income and operating-cost assumptions.',
    limitations: ['Rental income, vacancy, repairs, taxes, insurance and financing vary by property and market.', 'Zoning, owner-occupancy and rental restrictions are not automatically checked.', 'ROI is a scenario estimate, not a guaranteed return.'],
    sources: [{ title: 'HUD — FHA single-family mortgage resources', url: 'https://www.hud.gov/program_offices/housing/sfh/ins/203b-mortgages' }],
    currentYear: 2026,
  },
  {
    slug: 'hra-calculator',
    status: 'reviewed',
    methodology: 'India House Rent Allowance exemption scenario under the old tax regime using the statutory three-condition test.',
    limitations: ['HRA exemption is unavailable under the new tax regime.', 'The 50%/40% test applies to the qualifying salary definition and metro classification; individual payroll facts can require additional details.', 'The result is a planning estimate, not an ITR determination.'],
    sources: [{ title: 'Income Tax Department — New vs old regime FAQs', url: 'https://www.incometax.gov.in/iec/foportal/help/new-tax-vs-old-tax-regime-faqs' }, { title: 'CBDT — AY 2026-27 ITR validation rules', url: 'https://www.incometax.gov.in/iec/foportal/sites/default/files/2026-05/CBDT__e-Filing_ITR%202_Validation%20Rules_AY%202026-27_V1.0.pdf' }],
    currentYear: 2026,
  },
  {
    slug: 'hsa-investment-calculator',
    status: 'reviewed',
    methodology: 'HSA accumulation scenario with self-only/family 2026 contribution limits, age-55 catch-up, investment-return and tax assumptions.',
    limitations: ['2026 limits are $4,400 self-only and $8,750 family, plus a $1,000 catch-up when eligible.', 'Eligibility, employer contributions, Medicare status and future limits are not determined.', 'Investment returns and medical costs are assumptions, not forecasts.'],
    sources: [{ title: 'IRS — 2026 HSA limits', url: 'https://www.irs.gov/irb/2025-21_IRB' }, { title: 'IRS — Publication 15-B', url: 'https://www.irs.gov/publications/p15b' }],
    currentYear: 2026,
  },
  {
    slug: 'hsa-projection-calculator',
    status: 'reviewed',
    methodology: 'Long-term HSA balance scenario using 2026 contribution limits, medical spending, investment-return and income-tax assumptions.',
    limitations: ['2026 limits are $4,400 self-only and $8,750 family, plus a $1,000 catch-up when eligible.', 'Income-tax savings are illustrative; payroll-tax treatment is not assumed.', 'Eligibility, employer contributions, Medicare status and future limits are not determined.'],
    sources: [{ title: 'IRS — 2026 HSA limits', url: 'https://www.irs.gov/irb/2025-21_IRB' }, { title: 'IRS — Publication 15-B', url: 'https://www.irs.gov/publications/p15b' }],
    currentYear: 2026,
  },
  {
    slug: 'hsa-triple-tax-growth-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'hsa-vs-401k-priority-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'hsa-vs-fsa-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'i-bond-ladder-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'i-bonds-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'i-bonds-vs-tips-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'paycheck-contribution-optimizer',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'tax-loss-harvesting-portfolio-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'tax-withholding-w4-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'taxable-vs-roth-vs-traditional-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'term-vs-ulip-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'term-vs-whole-life-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'tip-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'tips-vs-nominal-bonds-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'traditional-ira-vs-taxable-account-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'treasury-bill-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'trust-fund-growth-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'tsp-vs-401k-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'uk-buy-to-let-vs-stocks-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'uk-fixed-rate-vs-tracker-mortgage-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'uk-help-to-buy-vs-lisa-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'uk-income-tax-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'uk-lifetime-isa-vs-sipp-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'uk-pension-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'uk-pension-drawdown-vs-annuity-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'uk-pension-vs-isa-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'uk-premium-bonds-vs-cash-isa-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'uk-remortgage-vs-invest-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'uk-stamp-duty-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'uk-stocks-vs-bonds-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'umbrella-insurance-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
]
