import type { FinanceQualityProfile } from './finance-quality'

const IRS = 'https://www.irs.gov'
const TREASURY = 'https://www.treasurydirect.gov'
const CMS = 'https://www.cms.gov'
const profiles: FinanceQualityProfile[] = [
  ['gold-vs-stocks-calculator','custom_estimate','Portfolio scenario comparing user-entered gold and equity assumptions.',['Historical returns are not forecasts.','Allocation and crash-protection outputs are scenario assumptions, not guarantees.'],[],2026],
  ['government-bond-calculator','custom_estimate','Bond price, coupon and yield scenario using user-entered security terms.',['Security-specific conventions, accrued interest, taxes, liquidity and call features are simplified.'],[],2026],
  ['gratuity-calculator','needs_manual_review','India gratuity planning scenario using salary, service and coverage inputs.',['Current Indian labour-law applicability and wage definitions can depend on worker status and effective-date rules; verify against current government guidance.'],[],2026],
  ['gst-calculator','tax_rule_review','India GST arithmetic for a selected rate and inclusive/exclusive pricing.',['GST rate depends on the actual HSN/SAC classification and applicable notification; selecting a rate does not determine legal classification.'],[{title:'CBIC — GST rates',url:'https://cbic-gst.gov.in/hindi/gst-goods-services-rates.html'}],2026],
  ['hdhp-vs-traditional-insurance-calculator','tax_rule_review','Scenario comparing premiums, out-of-pocket costs and HSA tax effects for health-plan choices.',['Plan-specific networks, negotiated rates, employer contributions, eligibility and tax treatment are simplified.'],[{title:'IRS — Publication 15-B, 2026 HSA rules',url:`${IRS}/publications/p15b`}],2026],
  ['health-insurance-deductible-calculator','custom_estimate','Simplified annual premium, deductible, coinsurance and out-of-pocket comparison.',['Actual plan benefit designs, copays, negotiated rates and covered services can differ materially.'],[],2026],
  ['health-insurance-subsidy-calculator','tax_rule_review','Simplified Marketplace premium-tax-credit scenario using household and income inputs.',['Official eligibility depends on MAGI, household composition, benchmark premium, employer coverage and Marketplace rules.'],[{title:'HealthCare.gov — Premium tax credit',url:'https://www.healthcare.gov/glossary/premium-tax-credit/'}],2026],
  ['heloc-calculator','custom_estimate','HELOC borrowing scenario using home value, mortgage balance, credit-line percentage, rate and term.',['Lender CLTV limits, variable rates, fees, draw periods and underwriting vary.'],[],2026],
  ['heloc-credit-line-calculator','custom_estimate','Scenario estimate of available HELOC credit from home equity and a user-entered CLTV limit.',['A lender may use a different valuation, CLTV, underwriting standard and fee structure.'],[],2026],
  ['home-affordability-calculator','reviewed','Housing-budget scenario using 28% front-end and 36% back-end planning thresholds with modeled property tax and insurance.',['The 28/36 thresholds are planning heuristics, not approval rules.', 'Actual taxes, insurance, HOA, PMI/MIP, lender overlays and loan-program limits vary.'],[{title:'CFPB — Loan Estimate',url:'https://www.consumerfinance.gov/owning-a-home/loan-estimate/'}, {title:'FHFA — 2026 conforming loan limits',url:'https://www.fhfa.gov/news/news-release/fhfa-announces-conforming-loan-limit-values-for-2026'}],2026],,
  ['home-equity-loan-calculator','reviewed','Fixed-payment home-equity loan scenario using entered home value, existing mortgage, loan amount, APR and term.',['The 85% CLTV figure is a screening assumption, not an approval rule.', 'Rates, fees, appraisal values, lien position and underwriting vary.'],[{title:'CFPB — Home equity loans',url:'https://www.consumerfinance.gov/ask-cfpb/what-is-a-home-equity-loan-en-105/'}, {title:'CFPB — Loan Estimate',url:'https://www.consumerfinance.gov/owning-a-home/loan-estimate/'}],2026],,
  ['home-equity-vs-personal-loan','reviewed','Scenario comparison of secured home-equity borrowing with unsecured personal borrowing using matched amount, APR and term.',['Home-equity debt is secured by the home and default can create foreclosure risk.', 'Tax deductibility is not assumed; actual eligibility depends on use of proceeds and current law.', 'Fees and lender terms are excluded unless entered.'],[{title:'CFPB — Home equity loans',url:'https://www.consumerfinance.gov/ask-cfpb/what-is-a-home-equity-loan-en-105/'}, {title:'IRS — Publication 936',url:'https://www.irs.gov/publications/p936'}],2026],,
  ['home-loan-calculator','reviewed','Standard mortgage amortization scenario using property value, down payment, interest rate and term.',['Not a lender quote or approval decision.', 'Taxes, insurance, PMI/MIP, HOA, fees and points are outside the core payment calculation.'],[{title:'CFPB — Loan Estimate',url:'https://www.consumerfinance.gov/owning-a-home/loan-estimate/'}, {title:'FHFA — 2026 conforming loan limits',url:'https://www.fhfa.gov/news/news-release/fhfa-announces-conforming-loan-limit-values-for-2026'}],2026],,
  ['home-office-deduction-calculator','reviewed','Comparison of the IRS simplified home-office method with a limited user-entered actual-expense scenario.',['The simplified method is $5 per qualifying square foot, capped at 300 square feet.', 'Eligibility, exclusive and regular business use, gross-income limits and other Form 8829 rules are not fully modeled.', 'The tool does not estimate tax savings.'],[{title:'IRS — Simplified home office deduction',url:'https://www.irs.gov/businesses/small-businesses-self-employed/simplified-option-for-home-office-deduction'}],2026],,
  ['house-flip-calculator','reviewed','House-flip profit scenario using acquisition, renovation, financing, holding and selling-cost assumptions.',['The 70% rule is a heuristic, not a profitability guarantee.', 'Actual taxes, transaction costs, financing fees, overruns, permits and market prices can differ materially.'],[{title:'CFPB — Home buying resources',url:'https://www.consumerfinance.gov/owning-a-home/'}],2026],,
  ['house-hacking-roi-calculator','reviewed','Owner-occupied rental scenario using purchase, financing, rental income and operating-cost assumptions.',['Rental income, vacancy, repairs, taxes, insurance and financing vary by property and market.', 'Zoning, owner-occupancy and rental restrictions are not automatically checked.', 'ROI is a scenario estimate, not a guaranteed return.'],[{title:'HUD — FHA single-family mortgage resources',url:'https://www.hud.gov/program_offices/housing/sfh/ins/203b-mortgages'}],2026],,
  ['hra-calculator','reviewed','India House Rent Allowance exemption scenario under the old tax regime using the statutory three-condition test.',['HRA exemption is unavailable under the new tax regime.', 'The 50%/40% test applies to the qualifying salary definition and metro classification; individual payroll facts can require additional details.', 'The result is a planning estimate, not an ITR determination.'],[{title:'Income Tax Department — New vs old regime FAQs',url:'https://www.incometax.gov.in/iec/foportal/help/new-tax-vs-old-tax-regime-faqs'}, {title:'CBDT — AY 2026-27 ITR validation rules',url:'https://www.incometax.gov.in/iec/foportal/sites/default/files/2026-05/CBDT__e-Filing_ITR%202_Validation%20Rules_AY%202026-27_V1.0.pdf'}],2026],,
  ['hsa-investment-calculator','reviewed','HSA accumulation scenario with self-only/family 2026 contribution limits, age-55 catch-up, investment-return and tax assumptions.',['2026 limits are $4,400 self-only and $8,750 family, plus a $1,000 catch-up when eligible.', 'Eligibility, employer contributions, Medicare status and future limits are not determined.', 'Investment returns and medical costs are assumptions, not forecasts.'],[{title:'IRS — 2026 HSA limits',url:'https://www.irs.gov/irb/2025-21_IRB'}, {title:'IRS — Publication 15-B',url:'https://www.irs.gov/publications/p15b'}],2026],,
  ['hsa-projection-calculator','reviewed','Long-term HSA balance scenario using 2026 contribution limits, medical spending, investment-return and income-tax assumptions.',['2026 limits are $4,400 self-only and $8,750 family, plus a $1,000 catch-up when eligible.', 'Income-tax savings are illustrative; payroll-tax treatment is not assumed.', 'Eligibility, employer contributions, Medicare status and future limits are not determined.'],[{title:'IRS — 2026 HSA limits',url:'https://www.irs.gov/irb/2025-21_IRB'}, {title:'IRS — Publication 15-B',url:'https://www.irs.gov/publications/p15b'}],2026],,
  ['hsa-triple-tax-growth-calculator','tax_rule_review','HSA contribution and investment-growth scenario illustrating tax treatment for qualified medical withdrawals.',['Tax treatment depends on eligibility, qualified expenses and contribution method.'],[{title:'IRS — 2026 HSA rules',url:`${IRS}/irb/2025-21_IRB`}],2026],
  ['hsa-vs-401k-priority-calculator','tax_rule_review','Planning comparison between capturing a 401(k) match and using HSA tax advantages.',['The suggested priority order is a planning heuristic, not universal advice.'],[{title:'IRS — 2026 retirement limits',url:`${IRS}/retirement-plans/cola-increases-for-dollar-limitations-on-benefits-and-contributions`}],2026],
  ['hsa-vs-fsa-calculator','tax_rule_review','Scenario comparison of HSA and health FSA tax benefits and long-term growth.',['HSA eligibility, FSA carryover/grace-period rules, employer contributions and plan design vary.'],[{title:'IRS — 2026 HSA rules',url:`${IRS}/irb/2025-21_IRB`}],2026],
  ['i-bond-ladder-calculator','tax_rule_review','Series I savings-bond ladder scenario using purchase cadence and a user-entered/current composite-rate assumption.',['Rates reset every six months; purchase limits, redemption restrictions and historical issue rates matter.'],[{title:'TreasuryDirect — I Bond rates',url:`${TREASURY}/news/2026/release-05-01-rates/`}],2026],
  ['i-bonds-calculator','tax_rule_review','Series I bond value scenario using fixed and semiannual inflation-rate inputs.',['The composite rate changes every six months and an exact historical redemption value requires the bond issue date and rate history.'],[{title:'TreasuryDirect — I Bond rates',url:`${TREASURY}/news/2026/release-05-01-rates/`}],2026],
  ['i-bonds-vs-tips-calculator','custom_estimate','Scenario comparison of I Bonds and TIPS using user-entered real-return, inflation, tax and liquidity assumptions.',['I Bond purchase limits and redemption rules differ from marketable TIPS; rates and market prices change.'],[{title:'TreasuryDirect — I Bond rates',url:`${TREASURY}/news/2026/release-05-01-rates/`}],2026],
].map(([slug,status,methodology,limitations,sources,currentYear]) => ({slug,status,methodology,limitations,sources,currentYear} as FinanceQualityProfile))

export const FINANCE_BATCH_17 = profiles
export const FINANCE_BATCH_17_SLUGS = profiles.map(p => p.slug)
