import type { FinanceQualityProfile } from './finance-quality'

const IRS = 'https://www.irs.gov'
const HUD = 'https://www.hud.gov'
const CFPB = 'https://www.consumerfinance.gov'
const SEC = 'https://www.investor.gov'

export const FINANCE_BATCH_11: FinanceQualityProfile[] = [
  { slug:'relocation-mortgage-calculator', status:'custom_estimate', methodology:'Scenario comparison of a current home and a relocation using mortgage, salary, housing and cost-of-living assumptions.', limitations:['Local taxes, transaction costs, insurance and actual lender terms vary.','This is a relocation scenario, not a complete financial plan.'], sources:[{title:'CFPB — Mortgages',url:`${CFPB}/consumer-tools/mortgages/`}], currentYear:2026 },
  { slug:'rent-increase-calculator', status:'reviewed', methodology:'Compares modeled rent after an entered increase with an alternative rent and moving costs.', limitations:['Rent-control, notice and tenant-protection rules vary by jurisdiction.','The current model uses annualized comparison assumptions; lease-month inputs must not be interpreted as legal guidance.'], sources:[], currentYear:2026 },
  { slug:'rent-vs-buy-calculator', status:'custom_estimate', methodology:'Long-term housing-cost scenario comparing rent and ownership costs, financing, appreciation and opportunity cost.', limitations:['Returns, home appreciation, maintenance, taxes, insurance, transaction costs and rent growth are uncertain.'], sources:[{title:'CFPB — Buying a home',url:`${CFPB}/owning-a-home/`}], currentYear:2026 },
  { slug:'rental-property-depreciation-calculator', status:'tax_rule_review', methodology:'Simplified residential and commercial depreciation scenario based on depreciable basis and recovery period.', limitations:['Land is not depreciable; actual classification, placed-in-service date, conventions, improvements and recapture rules require a complete tax analysis.'], sources:[{title:'IRS — Publication 946',url:`${IRS}/publications/p946`}], currentYear:2026 },
  { slug:'rental-property-investment-calculator', status:'custom_estimate', methodology:'Rental-property scenario using rent, vacancy, operating costs, financing, appreciation and holding-period assumptions.', limitations:['Returns are estimates and omit or simplify many property-specific costs and tax effects.'], sources:[], currentYear:2026 },
  { slug:'rental-property-tax-strategy-calculator', status:'tax_rule_review', methodology:'Simplified after-tax rental cash-flow scenario using income, expenses, interest and depreciation assumptions.', limitations:['Passive-activity rules, basis, at-risk rules, depreciation, recapture, NIIT and state taxes are simplified.'], sources:[{title:'IRS — Publication 527',url:`${IRS}/publications/p527`}], currentYear:2026 },
  { slug:'rental-yield-calculator', status:'custom_estimate', methodology:'Calculates gross yield, net yield and cash-on-cash return from user-entered property and operating assumptions.', limitations:['Yield definitions differ; financing, taxes, vacancy and capital expenditures can materially change returns.'], sources:[], currentYear:2026 },
  { slug:'renters-insurance-calculator', status:'custom_estimate', methodology:'Coverage-planning scenario based on personal-property value, liability assumptions and an illustrative premium estimate.', limitations:['Actual premiums and coverage depend on insurer, location, deductible, limits, claims history and policy details.'], sources:[], currentYear:2026 },
  { slug:'required-minimum-distribution-calculator', status:'tax_rule_review', methodology:'Simplified RMD calculation using the applicable IRS life-expectancy factor for the modeled account type and age.', limitations:['Inherited accounts and a spouse more than 10 years younger can require different tables; beneficiary and plan rules can materially change the result.'], sources:[{title:'IRS — Publication 590-B',url:`${IRS}/publications/p590b`}], currentYear:2026 },
  { slug:'retirement-bucket-strategy-calculator', status:'custom_estimate', methodology:'Illustrative allocation of retirement assets across short-, intermediate- and long-term spending buckets.', limitations:['Bucket sizes and asset allocations are planning choices, not universally optimal recommendations.'], sources:[], currentYear:2026 },
  { slug:'retirement-calculator', status:'custom_estimate', methodology:'Retirement projection using savings, return, inflation, spending and withdrawal assumptions.', limitations:['The 4% rule is a historical planning heuristic, not a guaranteed safe withdrawal rate. Sequence risk, taxes, fees, longevity and changing spending matter.'], sources:[], currentYear:2026 },
  { slug:'retirement-healthcare-bridge-calculator', status:'custom_estimate', methodology:'Scenario for funding healthcare expenses between retirement and Medicare eligibility using user-entered cost assumptions.', limitations:['Premiums, subsidies, healthcare utilization and policy rules vary; the model is not an insurance quote or eligibility determination.'], sources:[], currentYear:2026 },
  { slug:'retirement-healthcare-cost-calculator', status:'custom_estimate', methodology:'Retirement healthcare spending projection using user-entered premiums, out-of-pocket costs and inflation assumptions.', limitations:['Healthcare spending varies substantially by coverage, location, health status and plan design.'], sources:[], currentYear:2026 },
  { slug:'retirement-withdrawal-calculator', status:'custom_estimate', methodology:'Portfolio-withdrawal projection using balance, return, inflation, withdrawal and longevity assumptions.', limitations:['No withdrawal rate is guaranteed; market sequence, taxes, fees and spending flexibility affect sustainability.'], sources:[], currentYear:2026 },
  { slug:'reverse-mortgage-calculator', status:'reviewed', methodology:'Simplified HECM scenario using age, home value, interest and modeled program limits.', limitations:['Actual HECM proceeds depend on HUD factors, rates, mortgage insurance, fees, counseling, borrower eligibility and lender calculations.'], sources:[{title:'HUD — HECM program and 2026 maximum claim amount',url:`${HUD}/stat/sfh/hecm`},{title:'HUD — 2026 FHA/HECM loan limits',url:`${HUD}/news/hud-no-25-145`}], currentYear:2026 },
  { slug:'roi-calculator', status:'reviewed', methodology:'Calculates total ROI and CAGR from initial investment, proceeds and holding period.', limitations:['ROI does not by itself measure risk, cash-flow timing, taxes, liquidity or opportunity cost.'], sources:[], currentYear:2026 },
  { slug:'roth-conversion-calculator', status:'tax_rule_review', methodology:'Scenario comparison of traditional-IRA assets converted to Roth using user-entered conversion amount, tax assumptions and growth.', limitations:['Actual tax liability depends on taxable income, filing status, basis, state taxes and other income; this is not a Form 1040 calculation.'], sources:[{title:'IRS — Roth IRA distributions and conversions',url:`${IRS}/publications/p590a`}], currentYear:2026 },
  { slug:'roth-conversion-ladder-calculator', status:'tax_rule_review', methodology:'Illustrative multi-year Roth conversion ladder showing conversion timing and modeled five-year access windows.', limitations:['The five-year rules have different applications to conversions and qualified distributions; actual access and tax results require account-specific analysis.'], sources:[{title:'IRS — Publication 590-B',url:`${IRS}/publications/p590b`}], currentYear:2026 },
  { slug:'roth-conversion-tax-calculator', status:'tax_rule_review', methodology:'Simplified federal/state tax scenario for a Roth conversion using modeled taxable income and filing assumptions.', limitations:['Current implementation does not reproduce all federal brackets, deductions, credits, IRMAA or every state tax system.'], sources:[{title:'IRS — Roth IRA distributions',url:`${IRS}/publications/p590b`}], currentYear:2026 },
  { slug:'roth-ira-calculator', status:'tax_rule_review', methodology:'Compound-growth projection for a Roth IRA using contribution, return and retirement-age assumptions.', limitations:['2026 IRA contribution limit is $7,500 with a $1,100 catch-up for eligible taxpayers; direct-contribution income limits also apply. Projection returns are assumptions, not guarantees.'], sources:[{title:'IRS — 2026 retirement plan limits',url:`${IRS}/retirement-plans/cola-increases-for-dollar-limitations-on-benefits-and-contributions`}], currentYear:2026 },
  { slug:'roth-ira-vs-401k-employer-match-calculator', status:'custom_estimate', methodology:'After-tax retirement scenario comparing Roth IRA growth with a 401(k) employer-match scenario.', limitations:['Plan fees, vesting, contribution limits, tax rates and employer-match formulas vary.'], sources:[{title:'IRS — 2026 retirement plan limits',url:`${IRS}/retirement-plans/cola-increases-for-dollar-limitations-on-benefits-and-contributions`}], currentYear:2026 },
  { slug:'roth-ira-vs-hsa-calculator', status:'custom_estimate', methodology:'Scenario comparison of Roth IRA and HSA contributions using tax treatment, growth and qualified-use assumptions.', limitations:['HSA eligibility, contribution limits and qualified medical expenses must be satisfied; tax treatment differs by circumstance.'], sources:[{title:'IRS — 2026 retirement plan limits',url:`${IRS}/retirement-plans/cola-increases-for-dollar-limitations-on-benefits-and-contributions`}], currentYear:2026 },
  { slug:'roth-ira-vs-traditional-ira-calculator', status:'custom_estimate', methodology:'After-tax wealth comparison using current and future tax-rate assumptions.', limitations:['Actual results depend on deductions, income limits, RMDs, tax law, state taxes and withdrawal timing.'], sources:[{title:'IRS — 2026 retirement plan limits',url:`${IRS}/retirement-plans/cola-increases-for-dollar-limitations-on-benefits-and-contributions`}], currentYear:2026 },
  { slug:'roth-vs-traditional-401k-calculator', status:'custom_estimate', methodology:'After-tax retirement comparison between Roth and traditional 401(k) contributions using current/future tax assumptions.', limitations:['Employer plans, matching, tax rates, contribution limits, RMD rules and withdrawal timing can change the result.'], sources:[{title:'IRS — 2026 retirement plan limits',url:`${IRS}/retirement-plans/cola-increases-for-dollar-limitations-on-benefits-and-contributions`}], currentYear:2026 },
]

export const FINANCE_BATCH_11_SLUGS = FINANCE_BATCH_11.map(p => p.slug)
