import type { FinanceQualityProfile } from './finance-quality'

const IRS = 'https://www.irs.gov'

export const FINANCE_BATCH_16: FinanceQualityProfile[] = [
  {slug:'401k-calculator',status:'reviewed',methodology:'Retirement projection using employee contributions, employer match, salary growth, return and time assumptions.',limitations:['Investment returns are assumptions.','Plan-specific match formulas, vesting, fees and distribution taxes are simplified.'],sources:[{title:'IRS — 401(k) contribution limits',url:`${IRS}/retirement-plans/plan-participant-employee/retirement-topics-401k-and-profit-sharing-plan-contribution-limits`}],currentYear:2026},
  {slug:'401k-early-withdrawal-vs-loan-calculator',status:'reviewed',methodology:'Scenario comparison of a 401(k) distribution versus a plan loan using entered tax, penalty and investment assumptions.',limitations:['Plan loan rules vary.','Penalty exceptions and tax treatment depend on facts; this is not a plan-administration or tax-return calculation.'],sources:[{title:'IRS — Retirement plan distributions',url:`${IRS}/retirement-plans/plan-participant-employee/retirement-topics-tax-on-early-distributions`}],currentYear:2026},
  {slug:'401k-vs-pension-calculator',status:'custom_estimate',methodology:'Scenario comparison of defined-contribution accumulation against pension income using user-entered assumptions.',limitations:['Pension guarantees, COLAs, survivor options, PBGC coverage and plan-specific formulas are simplified.','4% withdrawal-rate shortcuts are not guarantees.'],sources:[],currentYear:2026},
  {slug:'401k-vs-roth-ira-calculator',status:'reviewed',methodology:'After-tax retirement scenario comparing a workplace 401(k) with a Roth IRA under current contribution and income-limit assumptions.',limitations:['Employer match, tax rates, plan fees, contribution eligibility and future law are simplified.'],sources:[{title:'IRS — 2026 retirement limits',url:`${IRS}/newsroom/401k-limit-increases-to-24500-for-2026-ira-limit-increases-to-7500`}],currentYear:2026},
  {slug:'401k-vs-taxable-account-calculator',status:'reviewed',methodology:'After-tax scenario comparison of a traditional 401(k) and taxable account using user-entered contribution, return, current-tax, retirement-tax and taxable-account tax-drag assumptions.',limitations:['Actual plan fees, employer matching, capital-gains timing, dividend income, deductions and future tax rates vary.','The taxable tax-drag input is a simplified assumption and does not model individual securities.','Not a personalized investment recommendation.'],sources:[{title:'IRS — 401(k) contribution limits',url:`${IRS}/retirement-plans/plan-participant-employee/retirement-topics-401k-and-profit-sharing-plan-contribution-limits`}],currentYear:2026},
  {slug:'529-to-roth-rollover-calculator',status:'reviewed',methodology:'Scenario for the special 529-to-Roth IRA rollover using the annual IRA limit and $35,000 lifetime cap.',limitations:['The 15-year account-age rule, five-year contribution lookback, beneficiary rules and earned-income requirement must all be satisfied.'],sources:[{title:'IRS — Qualified tuition programs',url:`${IRS}/taxtopics/tc313`}],currentYear:2026},
  {slug:'529-vs-roth-ira-education-calculator',status:'reviewed',methodology:'Education-funding scenario comparing 529 and Roth IRA treatment under user-entered assumptions.',limitations:['FAFSA treatment, state benefits, contribution eligibility and qualified-expense rules are simplified.'],sources:[{title:'IRS — Qualified tuition programs',url:`${IRS}/taxtopics/tc313`}],currentYear:2026},
  {slug:'529-vs-utma-calculator',status:'tax_rule_review',methodology:'Scenario comparison of education savings through a 529 versus custodial UTMA assets.',limitations:['Kiddie-tax thresholds, FAFSA treatment, state tax benefits and investment taxation are simplified.'],sources:[],currentYear:2026},
  {slug:'72t-sepp-calculator',status:'tax_rule_review',methodology:'Substantially equal periodic payment planning scenario using user-entered balance, age, rate and method assumptions.',limitations:['Actual SEPP compliance is governed by IRS rules and plan/IRA facts; changing payments can trigger recapture tax and penalties.'],sources:[{title:'IRS — Topic no. 558, additional tax on early distributions',url:`${IRS}/taxtopics/tc558`}],currentYear:2026},
  {slug:'alimony-calculator',status:'tax_rule_review',methodology:'Alimony cash-flow scenario with date-sensitive federal tax treatment.',limitations:['Federal treatment depends on the divorce/separation instrument and later modifications; state treatment can differ.'],sources:[{title:'IRS — Alimony',url:`${IRS}/taxtopics/tc452`}],currentYear:2026},
  {slug:'alimony-tax-calculator',status:'tax_rule_review',methodology:'Federal alimony tax-treatment scenario keyed to the applicable agreement date.',limitations:['Post-2018 federal agreements generally have different treatment from qualifying pre-2019 instruments; this is not a tax-return calculation.'],sources:[{title:'IRS — Alimony',url:`${IRS}/taxtopics/tc452`}],currentYear:2026},
  {slug:'alternative-minimum-tax-calculator',status:'tax_rule_review',methodology:'Simplified AMT calculation using 2026 exemption and phaseout assumptions.',limitations:['Does not reproduce Form 6251, all preference items, credits, special income or state AMT.'],sources:[{title:'IRS — 2026 AMT adjustments',url:`${IRS}/irb/2025-45_IRB`}],currentYear:2026},
  {slug:'annual-bonus-tax-calculator',status:'tax_rule_review',methodology:'Bonus withholding scenario comparing supplemental-wage withholding and user-entered marginal assumptions.',limitations:['Payroll withholding is not the same as final annual tax liability; employer payroll practices and W-4 elections matter.'],sources:[{title:'IRS — Publication 15',url:`${IRS}/publications/p15`}],currentYear:2026},
  {slug:'annual-income-calculator',status:'reviewed',methodology:'Annualizes recurring income inputs such as hourly, weekly, biweekly or monthly pay.',limitations:['Does not calculate complete payroll taxes unless explicitly included in the selected scenario.'],sources:[],currentYear:2026},
  {slug:'annuity-certain-vs-lifetime-calculator',status:'reviewed',methodology:'Present-value and cumulative-income scenario comparing period-certain and lifetime annuity payment assumptions with an explicit discount-rate input.',limitations:['Life expectancy is a simplified planning assumption, not an actuarial or insurer quote.','Actual contracts differ in mortality assumptions, survivor benefits, COLAs, fees and guarantees.'],sources:[{title:'Investor.gov — Annuities',url:'https://www.investor.gov/introduction-investing/investing-basics/investment-products/annuities'},{title:'NAIC — Annuities',url:'https://content.naic.org/insurance-topics/annuities'}],currentYear:2026},
  {slug:'annuity-income-calculator',status:'reviewed',methodology:'Illustrative annuity-income projection from premium, product type, deferral period and an age-based payout assumption.',limitations:['Payout assumptions are illustrative, not insurer quotes or guarantees.','Actual income depends on contract terms, age, rates, fees, options and insurer underwriting.'],sources:[{title:'Investor.gov — Annuities',url:'https://www.investor.gov/introduction-investing/investing-basics/investment-products/annuities'},{title:'NAIC — Annuities',url:'https://content.naic.org/insurance-topics/annuities'}],currentYear:2026},
  {slug:'annuity-vs-lumpsum-calculator',status:'reviewed',methodology:'Scenario comparison of an illustrative annuity payout rate against a lump-sum investment return over a user-selected horizon.',limitations:['The annuity payout rate is an assumption, not an insurer quote or guarantee.','Taxes, fees, inflation, survivor benefits, liquidity and longevity are simplified.'],sources:[{title:'Investor.gov — Annuities',url:'https://www.investor.gov/introduction-investing/investing-basics/investment-products/annuities'}],currentYear:2026},
  {slug:'auto-loan-calculator',status:'reviewed',methodology:'Standard fixed-rate auto-loan amortization with price, down payment, APR, term, taxes and fees.',limitations:['Actual APR, dealer fees, taxes and lender terms vary.'],sources:[],currentYear:2026},
  {slug:'backdoor-roth-ira-calculator',status:'tax_rule_review',methodology:'Scenario for a nondeductible traditional IRA contribution followed by Roth conversion.',limitations:['The pro-rata rule applies across traditional, SEP and SIMPLE IRA balances; tax basis and year-end balances are simplified.'],sources:[{title:'IRS — IRA contribution limits',url:`${IRS}/retirement-plans/plan-participant-employee/retirement-topics-ira-contribution-limits`}],currentYear:2026},
  {slug:'background-check-roi-calculator',status:'reviewed',methodology:'Employer ROI scenario comparing screening spend with user-entered estimates of avoided turnover, loss or hiring costs.',limitations:['Avoided-loss estimates are organization-specific and should be supported by internal data.','The model does not assess legal compliance, adverse-action procedures or discrimination risk.'],sources:[],currentYear:2026},
  {slug:'barista-fire-calculator',status:'reviewed',methodology:'Semi-retirement projection combining portfolio withdrawals with part-time earned income using a simplified 4% withdrawal-rate planning assumption.',limitations:['Returns, inflation, taxes, healthcare, sequence risk and withdrawal sustainability are simplified.','The 4% assumption is not a guarantee of retirement success.'],sources:[],currentYear:2026},
  {slug:'biweekly-mortgage-calculator',status:'reviewed',methodology:'Mortgage amortization comparison between monthly and accelerated biweekly payment schedules.',limitations:['Actual lender biweekly programs may differ; some simply hold half-payments and apply them monthly rather than applying 26 payments.'],sources:[],currentYear:2026},
  {slug:'bond-ladder-calculator',status:'reviewed',methodology:'Fixed-income ladder scenario using user-entered principal allocations, maturities, yields and reinvestment assumptions.',limitations:['Future reinvestment rates, bond prices, calls, credit risk, liquidity and taxes vary by security.','The calculator does not quote live securities or guarantee yields.'],sources:[{title:'Investor.gov — Bonds',url:'https://www.investor.gov/introduction-investing/investing-basics/investment-products/bonds-or-fixed-income-products'}],currentYear:2026},
  {slug:'bonds-vs-cds-usa-calculator',status:'tax_rule_review',methodology:'Scenario comparison of Treasury/bond and CD yields after user-entered federal and state tax assumptions.',limitations:['Treasury interest generally receives state/local tax exemption while CD interest generally does not; actual yields, call features, credit risk and FDIC coverage vary by security/institution.'],sources:[{title:'IRS — Tax-exempt interest',url:`${IRS}/taxtopics/tc403`}],currentYear:2026},
  {slug:'bonus-depreciation-calculator',status:'tax_rule_review',methodology:'Simplified Section 179 and additional first-year depreciation scenario for eligible business property.',limitations:['Eligibility, placed-in-service date, recovery period, business-use percentage and elections are simplified; not Form 4562.'],sources:[{title:'IRS — Publication 946',url:`${IRS}/publications/p946`}],currentYear:2026},
]
export const FINANCE_BATCH_16_SLUGS = FINANCE_BATCH_16.map(p=>p.slug)
