import type { FinanceQualityProfile } from './finance-quality'

const IRS = 'https://www.irs.gov'
const CFPB = 'https://www.consumerfinance.gov'
const SEC = 'https://www.investor.gov'
const DEA = 'https://dea.gov.in'

export const FINANCE_BATCH_10: FinanceQualityProfile[] = [
  { slug:'personal-finance-score-calculator', status:'custom_estimate', methodology:'Heuristic five-part planning score based on savings, emergency reserves, debt, retirement savings and credit inputs.', limitations:['The score is not a credit score or professional financial-health standard.','It omits insurance, taxes, asset allocation, dependents and other household risks.'], sources:[{title:'California Courts — Prenuptial agreements',url:'https://selfhelp.courts.ca.gov/prenuptial-agreements'}], currentYear:2026 },
  { slug:'personal-loan-calculator', status:'reviewed', methodology:'Standard amortizing-loan calculation using principal, APR and term with optional fee assumptions.', limitations:['Actual APR, fees, underwriting and prepayment terms vary by lender.','Market rate ranges are not embedded as universal facts.'], sources:[{title:'CFPB — Personal loans',url:`${CFPB}/consumer-tools/personal-loans/`}], currentYear:2026 },
  { slug:'pmi-calculator', status:'custom_estimate', methodology:'Conventional PMI scenario using LTV, credit-score bands and amortization toward the modeled 80% balance threshold.', limitations:['Actual PMI pricing depends on insurer, loan type, LTV, credit, occupancy and other factors.','FHA mortgage insurance follows different rules.'], sources:[{title:'CFPB — PMI cancellation',url:`${CFPB}/ask-cfpb/when-can-i-remove-private-mortgage-insurance-pmi-from-my-loan-en-202/`}], currentYear:2026 },
  { slug:'portfolio-rebalancing-calculator', status:'custom_estimate', methodology:'Calculates trades needed to move current holdings toward target allocations and compares simple tax-aware scenarios.', limitations:['Taxes, spreads, transaction costs and account-specific restrictions can change the optimal trade sequence.','No rebalancing frequency is universally optimal.'], sources:[{title:'SEC Investor.gov — Diversification',url:`${SEC}/introduction-investing/investing-basics/diversification`}], currentYear:2026 },
  { slug:'ppf-calculator', status:'tax_rule_review', methodology:'India PPF compounding scenario using contributions, a user-entered/assumed rate and the account tenure rules modeled by the calculator.', limitations:['PPF rates are declared for applicable periods and can change.','Withdrawal, extension and tax rules are simplified.'], sources:[{title:'Department of Economic Affairs — Small savings',url:`${DEA}/budget-division/475`}], currentYear:2026 },
  { slug:'ppf-vs-fd-calculator', status:'tax_rule_review', methodology:'India scenario comparison between PPF and bank fixed-deposit returns using user-entered rate and tax assumptions.', limitations:['PPF and FD rates and terms differ.','Bank FD taxation depends on the taxpayer and applicable rules.'], sources:[{title:'Department of Economic Affairs — Small savings',url:`${DEA}/budget-division/475`}], currentYear:2026 },
  { slug:'ppf-vs-nps-calculator', status:'tax_rule_review', methodology:'India retirement-saving scenario comparison between PPF and NPS using contribution, return and exit assumptions.', limitations:['NPS is market-linked and has distinct exit rules.','Tax treatment and annuity assumptions are simplified.'], sources:[{title:'PFRDA — NPS',url:'https://pfrda.org.in/'},{title:'Department of Economic Affairs — Small savings',url:`${DEA}/budget-division/475`}], currentYear:2026 },
  { slug:'prenup-asset-protection-calculator', status:'reviewed', methodology:'Scenario worksheet for separate property, future earnings and business-value assumptions under a simplified marital-property model.', limitations:['Prenuptial agreements are governed by state law and enforceability requirements.','Community-property and equitable-distribution systems differ substantially.'], sources:[{title:'California Courts — Prenuptial agreements',url:'https://selfhelp.courts.ca.gov/prenuptial-agreements'}], currentYear:2026 },
  { slug:'prepaid-vs-savings-529-calculator', status:'custom_estimate', methodology:'Education-funding scenario comparing prepaid tuition assumptions with a 529 investment-growth scenario.', limitations:['Prepaid-plan availability and terms vary by state.','Investment returns and future tuition growth are assumptions.'], sources:[{title:'IRS — 529 qualified tuition programs',url:`${IRS}/taxtopics/tc313`}], currentYear:2026 },
  { slug:'profit-sharing-plan-calculator', status:'tax_rule_review', methodology:'Employer profit-sharing contribution scenario using compensation and plan assumptions.', limitations:['Actual contribution limits, nondiscrimination testing and plan terms are more complex than this model.'], sources:[{title:'IRS — Retirement plans',url:`${IRS}/retirement-plans`}], currentYear:2026 },
  { slug:'property-tax-calculator', status:'custom_estimate', methodology:'Texas scenario using an explicit 85% assessment assumption, entered exemption and a modeled 1.81% effective-rate assumption.', limitations:['Texas property tax is locally administered; the model is not a county bill.','Assessment ratios, exemptions and taxing-unit rates vary.','Appeal savings is only a scenario assumption.'], sources:[{title:'Texas Comptroller — Property tax',url:'https://comptroller.texas.gov/taxes/property-tax/'}], currentYear:2026 },
  { slug:'qbi-deduction-calculator', status:'tax_rule_review', methodology:'Simplified Section 199A model for a single filer/non-SSTB scenario using the 2026 threshold and phase-in values and a user-entered illustrative tax rate.', limitations:['The UI does not reproduce Form 8995/8995-A.','SSTB, taxable-income, W-2 wage, UBIA and other limitations are simplified.'], sources:[{title:'IRS — Rev. Proc. 2025-45 / 2026 inflation adjustments',url:`${IRS}/irb/2025-45_IRB`}], currentYear:2026 },
  { slug:'qsbs-calculator', status:'tax_rule_review', methodology:'Section 1202 scenario model that distinguishes stock issued after July 4, 2025 from the legacy regime and applies simplified exclusion caps.', limitations:['QSBS eligibility depends on original issuance, C-corporation status, active-business tests, shareholder status, acquisition date and other facts.','The tax calculation remains illustrative.'], sources:[{title:'IRS — Schedule D instructions / Section 1202',url:`${IRS}/instructions/i1040sd`}], currentYear:2026 },
  { slug:'qualified-dividend-tax-calculator', status:'tax_rule_review', methodology:'Simplified 2026 qualified-dividend and capital-gain rate scenario using taxable-income thresholds and NIIT assumptions.', limitations:['Qualified-dividend taxation is stacked with ordinary taxable income and can involve deductions, capital losses and NIIT.','This is not a Form 1040 tax-return calculation.'], sources:[{title:'IRS Publication 505 — 2026 qualified dividends and capital gains',url:`${IRS}/publications/p505`}], currentYear:2026 },
  { slug:'rd-calculator', status:'custom_estimate', methodology:'India recurring-deposit maturity scenario using periodic contributions and an assumed annual rate.', limitations:['Actual bank RD compounding, tax treatment and rates vary by institution and product.'], sources:[], currentYear:2026 },
  { slug:'real-estate-appreciation-calculator', status:'custom_estimate', methodology:'Compound-growth scenario for property value using an assumed appreciation rate and holding period.', limitations:['Future property appreciation is uncertain and highly location-specific.'], sources:[], currentYear:2026 },
  { slug:'real-estate-cost-basis-calculator', status:'tax_rule_review', methodology:'Adjusted-basis and gain scenario using purchase price, qualifying costs, improvements, depreciation and selling costs.', limitations:['Section 121 eligibility, filing status, depreciation recapture, NIIT, state tax and basis adjustments require a fuller tax calculation.'], sources:[{title:'IRS — Publication 523 / Home sales',url:`${IRS}/taxtopics/tc701`}], currentYear:2026 },
  { slug:'real-estate-crowdfunding-calculator', status:'custom_estimate', methodology:'Cash-flow scenario for crowdfunding distributions, appreciation, fees and preferred-return assumptions.', limitations:['Deal structures, fees, liquidity, defaults and sponsor economics vary widely.'], sources:[{title:'SEC Investor.gov — Investing basics',url:`${SEC}/introduction-investing`}], currentYear:2026 },
  { slug:'real-estate-roi-calculator', status:'custom_estimate', methodology:'Property ROI scenario using cash flow, appreciation, financing and investment assumptions.', limitations:['Vacancy, maintenance, financing, taxes, insurance and exit costs can materially change actual returns.'], sources:[], currentYear:2026 },
  { slug:'real-estate-syndication-calculator', status:'custom_estimate', methodology:'Syndication waterfall scenario using preferred return, split and exit assumptions.', limitations:['Actual waterfalls can contain multiple tiers, catch-ups, clawbacks and sponsor fees not represented here.'], sources:[{title:'SEC Investor.gov — Private placements',url:`${SEC}/introduction-investing/investing-basics/investment-products/private-placements`}], currentYear:2026 },
  { slug:'real-return-calculator', status:'reviewed', methodology:'Converts a nominal return and inflation assumption into an inflation-adjusted real return.', limitations:['Real return depends on the inflation measure and period selected.'], sources:[], currentYear:2026 },
  { slug:'real-wage-growth-calculator', status:'reviewed', methodology:'Compares nominal salary growth with cumulative inflation to estimate purchasing-power change.', limitations:['Results depend on the inflation series and period selected. Historical wage patterns do not determine an individual negotiation outcome.'], sources:[{title:'BLS — CPI',url:'https://www.bls.gov/cpi/'}], currentYear:2026 },
  { slug:'refinance-vs-invest-calculator', status:'custom_estimate', methodology:'Scenario comparison between mortgage-refinancing savings and investing the relevant cash flow under user-entered assumptions.', limitations:['Investment returns are uncertain; refinance closing costs, taxes, loan terms and liquidity matter.','The calculator is not a personalized recommendation.'], sources:[{title:'CFPB — Mortgage resources',url:`${CFPB}/consumer-tools/mortgages/`},{title:'SEC Investor.gov — Investing basics',url:`${SEC}/introduction-investing`}], currentYear:2026 },
  { slug:'reit-vs-direct-property-usa-calculator', status:'custom_estimate', methodology:'US scenario comparison between publicly traded REIT exposure and direct rental-property cash flow, appreciation, fees and liquidity assumptions.', limitations:['REIT and property returns are uncertain and structurally different.','Taxes, leverage, vacancy, management and liquidity are simplified.'], sources:[{title:'SEC Investor.gov — REITs',url:'https://www.investor.gov/introduction-investing/investing-basics/investment-products/reits'}], currentYear:2026 },
]

export const FINANCE_BATCH_10_SLUGS = FINANCE_BATCH_10.map(p => p.slug)
