export type FinanceBatch09Status = 'reviewed' | 'tax_rule_review' | 'custom_estimate' | 'needs_manual_review' | 'formula_review'

export interface FinanceBatch09Profile {
  slug: string
  status: FinanceBatch09Status
  methodology: string
  limitations: string[]
  sources: Array<{ title: string; url: string }>
  currentYear?: number
}

const IRS='https://www.irs.gov'
const SSA='https://www.ssa.gov'
const PFRDA='https://pfrda.org.in'
const DEA='https://dea.gov.in'
const INDIA_POST='https://www.indiapost.gov.in'
const GOVUK='https://www.gov.uk'
const SEC='https://www.investor.gov'
const CFPB='https://www.consumerfinance.gov'
const MSRB='https://www.msrb.org'

export const FINANCE_BATCH_09: FinanceBatch09Profile[] = [
  {slug:'mutual-fund-vs-fd-calculator',status:'custom_estimate',methodology:'India-focused comparison of mutual-fund and fixed-deposit scenarios using user-entered return, tax and inflation assumptions.',limitations:['Mutual-fund returns are not guaranteed.','FD rates and taxation vary by institution, tenure and taxpayer.','Exit loads and product-specific tax rules can change the comparison.'],sources:[{title:'SEBI Investor — Mutual funds',url:'https://investor.sebi.gov.in/'},{title:'India Post — Savings schemes',url:INDIA_POST}],currentYear:2026},
  {slug:'nanny-tax-calculator',status:'tax_rule_review',methodology:'Household-employer payroll-tax estimate using 2026 federal household-employee thresholds and user-entered wages.',limitations:['State unemployment and state payroll rules vary.','Household-employee exemptions can change whether FICA applies.','Federal income-tax withholding is generally not mandatory for household employees unless the employer agrees to withhold.'],sources:[{title:'IRS Publication 926 — Household Employer’s Tax Guide',url:`${IRS}/publications/p926`}],currentYear:2026},
  {slug:'net-investment-income-tax-calculator',status:'tax_rule_review',methodology:'Simplified NIIT estimate using the 3.8% rate, filing-status threshold and the lesser of net investment income or MAGI excess.',limitations:['The calculator uses a simplified MAGI proxy and does not reproduce Form 8960.','Net investment income has exclusions and adjustments that depend on the facts.','Thresholds are statutory rather than inflation-indexed.'],sources:[{title:'IRS Topic 559 — Net Investment Income Tax',url:`${IRS}/taxtopics/tc559`},{title:'IRS — NIIT questions and answers',url:`${IRS}/newsroom/questions-and-answers-on-the-net-investment-income-tax`}],currentYear:2026},
  {slug:'net-operating-loss-calculator',status:'tax_rule_review',methodology:'Simplified NOL carryforward scenario with the post-2020 80% future-year limitation represented separately from the modeled loss.',limitations:['Actual NOL computation requires return-level adjustments and Form 172.','Entity type, pre-2018 NOLs, farming losses, excess business losses and other rules can change the result.'],sources:[{title:'IRS — Update to Pub. 536 for post-2020 NOL deductions',url:`${IRS}/forms-pubs/update-to-2021-pub-536-for-certain-post-2020-nol-deductions`}],currentYear:2026},
  {slug:'net-salary-calculator',status:'tax_rule_review',methodology:'Simplified U.S. take-home-pay estimate using 2026 federal brackets, standard deduction, FICA, selected state assumptions and entered pre-tax deductions.',limitations:['State tax is simplified and not a full state return calculation.','Payroll withholding differs from final tax liability.','Additional Medicare Tax, credits and many deductions can affect actual pay.'],sources:[{title:'IRS Publication 505 — 2026 withholding and estimated tax',url:`${IRS}/publications/p505`},{title:'SSA — 2026 contribution and benefit base',url:`${SSA}/OACT/COLA/cbbdet.html`}],currentYear:2026},
  {slug:'net-unrealized-appreciation-calculator',status:'tax_rule_review',methodology:'Illustrative NUA comparison between distributing employer securities from a qualified plan and rolling assets to an IRA.',limitations:['NUA eligibility depends on a qualifying lump-sum distribution and other specific requirements.','Ordinary-income and long-term-capital-gain treatment depends on the transaction details.','This is not a Form 4972 or tax-return calculation.'],sources:[{title:'IRS — Net unrealized appreciation',url:`${IRS}/retirement-plans/plan-participant-employee/retirement-topics-net-unrealized-appreciation`},{title:'IRS — Retirement plans',url:`${IRS}/retirement-plans`}],currentYear:2026},
  {slug:'net-worth-calculator',status:'custom_estimate',methodology:'Balance-sheet calculation: total assets minus total liabilities.',limitations:['Asset values are user-entered estimates.','Net worth is a snapshot and does not by itself measure liquidity, income or retirement readiness.'],sources:[{title:'Federal Reserve — Survey of Consumer Finances',url:'https://www.federalreserve.gov/econres/scfindex.htm'}],currentYear:2026},
  {slug:'net-worth-tracker',status:'custom_estimate',methodology:'User-maintained net-worth snapshot and tracking workflow across assets and liabilities.',limitations:['Values are user-entered and may be stale.','Investment and property values fluctuate.'],sources:[{title:'Federal Reserve — Survey of Consumer Finances',url:'https://www.federalreserve.gov/econres/scfindex.htm'}],currentYear:2026},
  {slug:'netherlands-aow-vs-private-pension-calculator',status:'needs_manual_review',methodology:'Scenario comparison between Dutch AOW income and private-pension income using user-entered assumptions.',limitations:['AOW depends on the individual’s insured years and circumstances.','Private pension terms differ by scheme and provider.','The calculator is not a Dutch pension entitlement determination.'],sources:[{title:'Government of the Netherlands — AOW',url:'https://www.government.nl/topics/general-old-age-pension-aow'}],currentYear:2026},
  {slug:'nps-calculator',status:'tax_rule_review',methodology:'India NPS corpus projection using monthly contributions, assumed return, annuity allocation and assumed annuity rate.',limitations:['Returns and annuity rates are assumptions, not guarantees.','Exit rules differ by NPS model and exit scenario.','Tax treatment depends on the applicable rules at withdrawal.'],sources:[{title:'PFRDA — NPS All Citizen Model',url:`${PFRDA}/w/faqs/nps-all-citizen-model`},{title:'PFRDA — Exit and withdrawal regulations',url:`${PFRDA}/en/web/pfrda/w/regulatory-framework/regulations/pension-fund-regulatory-and-development-authority-exits-and-withdrawals-under-the-national-pension-system-regulations-2015-last-amended-on-16-december-2025-`}],currentYear:2026},
  {slug:'nsc-vs-fd-calculator',status:'tax_rule_review',methodology:'India comparison of NSC and bank-FD scenarios using entered principal, rate, tenure and tax assumptions.',limitations:['Bank FD rates and tax treatment vary.','NSC rates are set by the government and can change for new issues.','The comparison is not a recommendation.'],sources:[{title:'India Post — Savings schemes',url:INDIA_POST},{title:'Department of Economic Affairs — Small savings',url:`${DEA}/budget-division/475`}],currentYear:2026},
  {slug:'nsc-vs-ppf-calculator',status:'tax_rule_review',methodology:'India scenario comparison between NSC and PPF using entered contributions, rates and tenure.',limitations:['PPF and NSC have different maturity, contribution and withdrawal rules.','Rates are subject to government notifications.','Tax treatment depends on the applicable rules.'],sources:[{title:'India Post — Savings schemes',url:INDIA_POST},{title:'Department of Economic Affairs — Small savings',url:`${DEA}/budget-division/475`}],currentYear:2026},
  {slug:'offset-mortgage-vs-savings-uk-calculator',status:'custom_estimate',methodology:'UK scenario comparison of mortgage-interest savings from offsetting deposits versus keeping cash in savings.',limitations:['Mortgage and savings rates change.','Tax on savings interest depends on the individual’s tax position.','Product terms and offset mechanics vary by lender.'],sources:[{title:'GOV.UK — Mortgage Charter 2026',url:`${GOVUK}/government/publications/mortgage-charter-2026`},{title:'FCA — Mortgages',url:'https://www.fca.org.uk/consumers/mortgages'}],currentYear:2026},
  {slug:'opportunity-zone-calculator',status:'tax_rule_review',methodology:'Illustrative Qualified Opportunity Fund scenario comparing current tax and deferred investment outcomes.',limitations:['Eligibility, holding periods, basis rules and QOF requirements are complex.','This calculator does not reproduce Form 8997 or all Opportunity Zone regulations.','Investment returns are hypothetical.'],sources:[{title:'IRS — Opportunity Zones',url:`${IRS}/businesses/small-businesses-self-employed/opportunity-zones`}],currentYear:2026},
  {slug:'options-greeks-calculator',status:'formula_review',methodology:'Black-Scholes model for theoretical option value and standard Greeks under continuous-volatility assumptions.',limitations:['Black-Scholes is a model, not a market price guarantee.','Dividends, early exercise, volatility smiles, liquidity and American-style exercise can change results.','The Greeks are local sensitivities.'],sources:[{title:'SEC Investor.gov — Options',url:`${SEC}/introduction-investing/investing-basics/investment-products/options`},{title:'OCC — Options disclosure',url:'https://www.theocc.com/company-information/documents-and-archives/options-disclosure-document'}],currentYear:2026},
  {slug:'options-pricing-calculator',status:'formula_review',methodology:'Black-Scholes theoretical call/put pricing with user-entered spot, strike, volatility, rate and time assumptions.',limitations:['The model does not guarantee executable market prices.','American options, dividends and changing volatility require additional modeling.','Implied volatility is a market input, not a fixed constant.'],sources:[{title:'SEC Investor.gov — Options',url:`${SEC}/introduction-investing/investing-basics/investment-products/options`},{title:'OCC — Options disclosure',url:'https://www.theocc.com/company-information/documents-and-archives/options-disclosure-document'}],currentYear:2026},
  {slug:'passive-income-portfolio-calculator',status:'custom_estimate',methodology:'Portfolio-size scenario based on target income and user-entered yield assumptions across dividend, bond and rental-income sources.',limitations:['Yield is not the same as total return.','Income can change and capital values can fall.','Taxes, vacancies, defaults and distribution policies vary by asset.'],sources:[{title:'SEC Investor.gov — Investing basics',url:`${SEC}/introduction-investing`}],currentYear:2026},
  {slug:'pay-off-mortgage-vs-invest-calculator',status:'custom_estimate',methodology:'Scenario comparison between extra mortgage principal payments and investing the same cash at a user-entered return.',limitations:['Investment returns are uncertain and taxable.','Mortgage interest may have tax effects that are not fully modeled.','Risk tolerance and liquidity are not captured by the simple break-even result.'],sources:[{title:'CFPB — Mortgage resources',url:`${CFPB}/consumer-tools/mortgages/`},{title:'SEC Investor.gov — Investing basics',url:`${SEC}/introduction-investing`}],currentYear:2026},
  {slug:'paycheck-calculator',status:'tax_rule_review',methodology:'Simplified U.S. paycheck estimate using 2026 federal tax brackets, standard deduction, FICA and selected state-rate assumptions.',limitations:['This is not an employer payroll-engine calculation or final tax liability.','State and local taxes, credits, W-4 details and benefits can materially change withholding.'],sources:[{title:'IRS Publication 505 — 2026 withholding',url:`${IRS}/publications/p505`},{title:'IRS — 2026 tax inflation adjustments',url:`${IRS}/newsroom/irs-releases-tax-inflation-adjustments-for-tax-year-2026-including-amendments-from-the-one-big-beautiful-bill`},{title:'SSA — 2026 wage base',url:`${SSA}/OACT/COLA/cbbdet.html`}],currentYear:2026},
  {slug:'payoff-date-calculator',status:'reviewed',methodology:'Loan amortization using the current balance, rate, required payment and optional extra payment to estimate payoff timing.',limitations:['Actual lender fees, payment timing and variable-rate changes can alter results.','The model assumes a fixed rate for the scenario.'],sources:[{title:'CFPB — Mortgages and loans',url:`${CFPB}/consumer-tools/mortgages/`}],currentYear:2026},
  {slug:'payroll-tax-calculator',status:'formula_review',methodology:'Simplified payroll-tax estimate using 2026 federal brackets, Social Security wage base, Medicare and selected state assumptions.',limitations:['W-4 withholding cannot be represented accurately by legacy allowance counts.','State/local payroll rules vary.','Withholding is not the same as final tax liability.'],sources:[{title:'IRS Publication 505 — 2026 withholding',url:`${IRS}/publications/p505`},{title:'SSA — 2026 wage base',url:`${SSA}/OACT/COLA/cbbdet.html`}],currentYear:2026},
  {slug:'pe-ratio-calculator',status:'custom_estimate',methodology:'Calculates P/E and PEG ratios and provides an illustrative valuation heuristic from user-entered EPS, price and growth assumptions.',limitations:['P/E is not a complete valuation model.','The fair-value heuristic uses arbitrary assumptions and should not be presented as intrinsic value.','Sector, cyclicality, accounting and capital structure matter.'],sources:[{title:'SEC Investor.gov — Investing basics',url:`${SEC}/introduction-investing`}],currentYear:2026},
  {slug:'peer-to-peer-lending-calculator',status:'custom_estimate',methodology:'Scenario model for P2P lending returns after user-entered interest, default, recovery-loss and platform-fee assumptions.',limitations:['Defaults, recoveries, prepayments and platform risk are uncertain.','The fixed tax assumption in the calculator is illustrative only.','Historical platform performance does not guarantee future returns.'],sources:[{title:'SEC Investor.gov — Investing basics',url:`${SEC}/introduction-investing`}],currentYear:2026},
  {slug:'pension-vs-lump-sum-calculator',status:'custom_estimate',methodology:'Present-value and longevity scenario comparison between a pension annuity and a lump-sum alternative.',limitations:['Pension COLA, survivor benefits, discount rate, longevity and investment returns are assumptions.','Plan-specific actuarial rules and PBGC protections vary.','The result is not a recommendation.'],sources:[{title:'PBGC — Guaranteed benefits',url:'https://www.pbgc.gov/workers-retirees/learn/guaranteed-benefits'}],currentYear:2026},
]

export const FINANCE_BATCH_09_SLUGS = FINANCE_BATCH_09.map(p => p.slug)
