import type { FinanceQualityProfile } from './finance-quality'

const IRS = 'https://www.irs.gov'
const TREASURY = 'https://www.treasurydirect.gov'
const CMS = 'https://www.cms.gov'
const profiles: FinanceQualityProfile[] = [
  ['gold-vs-stocks-calculator','custom_estimate','Portfolio scenario comparing user-entered gold and equity assumptions.',['Historical returns are not forecasts.','Allocation and crash-protection outputs are scenario assumptions, not guarantees.'],[],2026],
  ['government-bond-calculator','custom_estimate','Bond price, coupon and yield scenario using user-entered security terms.',['Security-specific conventions, accrued interest, taxes, liquidity and call features are simplified.'],[],2026],
  ['gratuity-calculator','needs_manual_review','India gratuity planning scenario using salary, service and coverage inputs.',['Current Indian labour-law applicability and wage definitions can depend on worker status and effective-date rules; verify against current government guidance.'],[],2026],
  ['gst-calculator','tax_rule_review','India GST arithmetic for a selected rate and inclusive/exclusive pricing.',['GST rate depends on the actual HSN/SAC classification and applicable notification; selecting a rate does not determine legal classification.'],[{title:'CBIC — GST rates',url:'https://cbic-gst.gov.in/hindi/gst-goods-services-rates.html'}],2026],
  ['hdhp-vs-traditional-insurance-calculator','tax_rule_review','Scenario comparing premiums, out-of-pocket costs and HSA tax effects for health-plan choices.',['Plan-specific networks, negotiated rates, employer contributions, eligibility and tax treatment are simplified.'],[{title:'IRS — Publication 15-B, 2026 HSA rules',url:`${IRS}/publications/p15b`}],2026],
  ['health-insurance-deductible-calculator','custom_estimate','Simplified annual premium, deductible, coinsurance and out-of-pocket comparison.',['Actual plan benefit designs, copays, negotiated rates and covered services can differ materially.'],[],2026],
  ['health-insurance-subsidy-calculator','tax_rule_review','Simplified Marketplace premium-tax-credit scenario using household and income inputs.',['Official eligibility depends on MAGI, household composition, benchmark premium, employer coverage and Marketplace rules.'],[{title:'HealthCare.gov — Premium tax credit',url:'https://www.healthcare.gov/glossary/premium-tax-credit/'}],2026],
  ['heloc-calculator','custom_estimate','HELOC borrowing scenario using home value, mortgage balance, credit-line percentage, rate and term.',['Lender CLTV limits, variable rates, fees, draw periods and underwriting vary.'],[],2026],
  ['heloc-credit-line-calculator','custom_estimate','Scenario estimate of available HELOC credit from home equity and a user-entered CLTV limit.',['A lender may use a different valuation, CLTV, underwriting standard and fee structure.'],[],2026],
  ['home-affordability-calculator','custom_estimate','Home-price planning scenario using income, debts, down payment, rate and affordability assumptions.',['The 28/36 rule is a planning heuristic, not a lender approval rule.'],[],2026],
  ['home-equity-loan-calculator','custom_estimate','Fixed-rate home-equity-loan payment and interest scenario.',['Actual rates, fees, CLTV limits and tax treatment vary by lender and borrower.'],[],2026],
  ['home-equity-vs-personal-loan','custom_estimate','Scenario comparison of secured home-equity borrowing with an unsecured personal loan.',['Actual APRs, fees, tax treatment and collateral risk vary.'],[],2026],
  ['home-loan-calculator','custom_estimate','Mortgage amortization scenario from principal, rate, term, taxes and insurance assumptions.',['Not a lender quote or underwriting decision.'],[],2026],
  ['home-office-deduction-calculator','tax_rule_review','Simplified home-office deduction scenario using qualifying area and applicable method.',['Eligibility, exclusive business use, regular use and the regular method are more complex than this calculator.'],[{title:'IRS — Simplified option for home office deduction',url:`${IRS}/businesses/small-businesses-self-employed/simplified-option-for-home-office-deduction`}],2026],
  ['house-flip-calculator','custom_estimate','House-flip profit scenario using acquisition, renovation, financing, selling costs and exit price.',['Taxes, transaction costs, project overruns, financing changes and market risk are simplified.'],[],2026],
  ['house-hacking-roi-calculator','custom_estimate','Rental-income and housing-cost scenario for an owner-occupied house-hacking strategy.',['Vacancy, repairs, financing, taxes, insurance and local rental rules vary.'],[],2026],
  ['hra-calculator','tax_rule_review','Health reimbursement arrangement scenario based on user-entered employer reimbursement assumptions.',['HRA eligibility and tax treatment depend on the specific HRA design and coordination with other coverage.'],[{title:'IRS — Publication 15-B',url:`${IRS}/publications/p15b`}],2026],
  ['hsa-investment-calculator','tax_rule_review','HSA growth scenario using contributions, investment return, expenses and tax assumptions.',['Eligibility, contribution limits, employer contributions and payroll-tax treatment are simplified.'],[{title:'IRS — 2026 HSA rules',url:`${IRS}/irb/2025-21_IRB`}],2026],
  ['hsa-projection-calculator','tax_rule_review','Long-term HSA balance projection with contributions, spending and investment assumptions.',['Does not determine eligibility or future limits; returns and medical spending are assumptions.'],[{title:'IRS — Publication 15-B, 2026 HSA rules',url:`${IRS}/publications/p15b`}],2026],
  ['hsa-triple-tax-growth-calculator','tax_rule_review','HSA contribution and investment-growth scenario illustrating tax treatment for qualified medical withdrawals.',['Tax treatment depends on eligibility, qualified expenses and contribution method.'],[{title:'IRS — 2026 HSA rules',url:`${IRS}/irb/2025-21_IRB`}],2026],
  ['hsa-vs-401k-priority-calculator','tax_rule_review','Planning comparison between capturing a 401(k) match and using HSA tax advantages.',['The suggested priority order is a planning heuristic, not universal advice.'],[{title:'IRS — 2026 retirement limits',url:`${IRS}/retirement-plans/cola-increases-for-dollar-limitations-on-benefits-and-contributions`}],2026],
  ['hsa-vs-fsa-calculator','tax_rule_review','Scenario comparison of HSA and health FSA tax benefits and long-term growth.',['HSA eligibility, FSA carryover/grace-period rules, employer contributions and plan design vary.'],[{title:'IRS — 2026 HSA rules',url:`${IRS}/irb/2025-21_IRB`}],2026],
  ['i-bond-ladder-calculator','tax_rule_review','Series I savings-bond ladder scenario using purchase cadence and a user-entered/current composite-rate assumption.',['Rates reset every six months; purchase limits, redemption restrictions and historical issue rates matter.'],[{title:'TreasuryDirect — I Bond rates',url:`${TREASURY}/news/2026/release-05-01-rates/`}],2026],
  ['i-bonds-calculator','tax_rule_review','Series I bond value scenario using fixed and semiannual inflation-rate inputs.',['The composite rate changes every six months and an exact historical redemption value requires the bond issue date and rate history.'],[{title:'TreasuryDirect — I Bond rates',url:`${TREASURY}/news/2026/release-05-01-rates/`}],2026],
  ['i-bonds-vs-tips-calculator','custom_estimate','Scenario comparison of I Bonds and TIPS using user-entered real-return, inflation, tax and liquidity assumptions.',['I Bond purchase limits and redemption rules differ from marketable TIPS; rates and market prices change.'],[{title:'TreasuryDirect — I Bond rates',url:`${TREASURY}/news/2026/release-05-01-rates/`}],2026],
].map(([slug,status,methodology,limitations,sources,currentYear]) => ({slug,status,methodology,limitations,sources,currentYear} as FinanceQualityProfile))

export const FINANCE_BATCH_17 = profiles
export const FINANCE_BATCH_17_SLUGS = profiles.map(p => p.slug)
