import type { FinanceQualityProfile } from './finance-quality'

const IRS = 'https://www.irs.gov'

export const FINANCE_BATCH_02: FinanceQualityProfile[] = [
  { slug:'break-even-calculator', status:'reviewed', methodology:'Break-even units equal fixed costs divided by contribution margin per unit; break-even revenue divides fixed costs by the contribution-margin ratio.', limitations:['Fixed and variable cost classification is user supplied.','Step costs and changing prices can make a single break-even point misleading.'], sources:[], currentYear:2026 },
  { slug:'bridge-loan-calculator',status:'reviewed', methodology:'Bridge-financing scenario using current-home equity, modeled equity advance, bridge rate, expected sale period and explicit fee assumptions.', limitations:['Lender underwriting, collateral requirements, advance percentages, rates, fees and repayment terms vary.','The calculator does not quote a live loan or determine approval.'], sources:[], currentYear:2026 },
  { slug:'budget-calculator',status:'reviewed', methodology:'Monthly cash-flow budget comparing after-tax income with user-entered spending and savings categories; budgeting rules are benchmarks only.', limitations:['50/30/20 is a planning framework, not a legal or universal requirement.','Actual affordability depends on household structure, location, debt and goals.'], sources:[], currentYear:2026 },
  { slug:'budget-planner-calculator',status:'reviewed', methodology:'Budget planning against user-entered income and expense targets, with savings rates and the 50/30/20 framework treated as optional benchmarks.', limitations:['Savings-rate targets are planning conventions, not guarantees of financial independence.','The model does not forecast irregular expenses or future income changes.'], sources:[], currentYear:2026 },
  { slug:'business-loan-calculator', status:'custom_estimate', methodology:'Amortizing business-loan payment and interest estimate from principal, rate and term.', limitations:['SBA and commercial-loan pricing changes over time and depends on borrower and loan type.','The calculator does not determine SBA eligibility.'], sources:[], currentYear:2026 },
  { slug:'business-startup-calculator', status:'custom_estimate', methodology:'Startup cash requirement and break-even scenario from user-entered startup costs, revenue, margins and operating expenses.', limitations:['Industry margins and startup costs vary widely.','The model is not a financing or valuation opinion.'], sources:[], currentYear:2026 },
  { slug:'business-valuation-calculator', status:'custom_estimate', methodology:'Illustrative valuation using user-entered EBITDA/revenue multiples and discounted-cash-flow assumptions.', limitations:['Market multiples vary by sector, growth, size, concentration, margins and transaction conditions.','A calculator cannot replace a professional valuation.'], sources:[], currentYear:2026 },
  { slug:'buy-vs-lease-vehicle-calculator', status:'custom_estimate', methodology:'Total-cost comparison between financing/purchasing and leasing using user-entered price, payment, term, residual and mileage assumptions.', limitations:['Lease money factors, residuals, taxes, fees and mileage charges are contract-specific.'], sources:[], currentYear:2026 },
  { slug:'cagr-calculator', status:'reviewed', methodology:'Compound annual growth rate equals (ending value / beginning value)^(1/years) minus 1.', limitations:['CAGR describes a smoothed annualized rate and does not describe volatility or interim cash flows.'], sources:[], currentYear:2026 },
  { slug:'cap-rate-calculator', status:'reviewed', methodology:'Capitalization rate equals net operating income divided by property value or purchase price.', limitations:['NOI definitions vary; financing, taxes, appreciation and one-time costs are outside a simple cap-rate calculation.'], sources:[], currentYear:2026 },
  { slug:'capital-gains-harvesting-calculator', status: 'reviewed', methodology:'Illustrative tax-loss harvesting comparison using current-year long-term capital-gain thresholds and the capital-loss deduction limit.', limitations:['Real Schedule D netting is more complex. Wash-sale rules, carryovers, holding periods and state taxes can change the result.'], sources:[{title:'IRS Topic 409 — Capital gains and losses',url:`${IRS}/taxtopics/tc409`}], currentYear:2026 },
  { slug:'capital-gains-tax-calculator', status: 'reviewed', methodology:'Simplified single-transaction federal capital-gain estimate using 2026 long-term thresholds, ordinary-income treatment for short-term gains and a simplified NIIT test.', limitations:['Does not reproduce Schedule D/8949, loss netting, basis adjustments, collectibles, QSBS, depreciation recapture or state tax.'], sources:[{title:'IRS Topic 409 — Capital gains and losses',url:`${IRS}/taxtopics/tc409`},{title:'IRS Net Investment Income Tax',url:`${IRS}/individuals/net-investment-income-tax`}], currentYear:2026 },
  { slug:'car-affordability-calculator', status:'custom_estimate', methodology:'Vehicle affordability estimate from income, debt obligations, down payment, rate and term assumptions.', limitations:['Affordability is a planning judgment; insurance, maintenance, taxes and lender underwriting can materially change the result.'], sources:[], currentYear:2026 },
  { slug:'car-depreciation-calculator', status:'custom_estimate', methodology:'Illustrative vehicle value-decline estimate using user-entered purchase price, age and depreciation assumptions.', limitations:['Actual depreciation depends on model, mileage, condition, market supply and region.'], sources:[], currentYear:2026 },
  { slug:'car-loan-calculator', status:'reviewed', methodology:'Standard amortizing auto-loan payment, interest and payoff calculation from amount, APR and term.', limitations:['Dealer fees, taxes, add-ons and lender-specific terms can change the financed amount and APR.'], sources:[], currentYear:2026 },
  { slug:'career-earnings-calculator', status:'custom_estimate', methodology:'Lifetime earnings projection using user-entered salary, growth, career duration and optional benefits assumptions.', limitations:['Career changes, unemployment, bonuses, taxes and inflation create substantial uncertainty.'], sources:[], currentYear:2026 },
  { slug:'cash-out-refinance-vs-heloc-calculator', status:'custom_estimate', methodology:'Scenario comparison of cash-out refinancing and HELOC borrowing using user-entered balances, rates, fees and term.', limitations:['HELOC rates can vary; refinance resets the mortgage balance/term; tax treatment of interest depends on use and applicable rules.'], sources:[], currentYear:2026 },
  { slug:'cash-value-life-insurance-calculator', status:'custom_estimate', methodology:'Illustrative comparison of premiums, cash value growth and death-benefit assumptions.', limitations:['Actual policy illustrations depend on contract guarantees, non-guaranteed assumptions, insurer expenses and policy design.'], sources:[], currentYear:2026 },
  { slug:'cd-ladder-calculator', status:'custom_estimate', methodology:'Certificate-of-deposit ladder projection from rung count, principal, rates and maturities.', limitations:['APYs are time-sensitive and vary by institution; early-withdrawal penalties and tax treatment can affect results.'], sources:[], currentYear:2026 },
  { slug:'cd-vs-hysa-calculator', status:'custom_estimate', methodology:'Yield comparison between a fixed CD rate and a variable high-yield savings rate under user-entered assumptions.', limitations:['HYSA rates can change while a CD rate is generally fixed for its term; actual APYs and fees vary by institution.'], sources:[], currentYear:2026 },
  { slug:'cd-vs-hysa-vs-money-market-calculator', status:'custom_estimate', methodology:'Scenario comparison of deposit and money-market yields, liquidity and interest under user-entered rates and balances.', limitations:['A money market mutual fund is not the same as a bank money market deposit account; insurance and liquidity differ.'], sources:[], currentYear:2026 },
  { slug:'charitable-bunching-calculator', status: 'reviewed', methodology:'Illustrative 2026 charitable-bunching comparison using the new 0.5% AGI charitable floor and user-entered standard-deduction/tax assumptions.', limitations:['Does not reproduce Schedule A, itemized-deduction limits, carryovers, substantiation, or the separate 2026 non-itemizer cash deduction.'], sources:[{title:'IRS Publication 505 (2026)',url:`${IRS}/publications/p505`}], currentYear:2026 },
  { slug:'charitable-giving-tax-calculator', status: 'reviewed', methodology:'Illustrative after-tax donation comparison for cash and appreciated property using user-entered tax assumptions.', limitations:['Uses a simplified public-charity percentage-limit model and does not reproduce Schedule A, carryovers, substantiation, private-foundation rules or all property-specific limits.','The 20% capital-gain tax assumption is a modeling input, not a universal rate.','2026 itemized charitable deductions are subject to a 0.5% AGI floor; non-itemizers may have a separate cash deduction up to $1,000/$2,000.'], sources:[{title:'IRS Topic 506 — Charitable contributions',url:`${IRS}/taxtopics/tc506`},{title:'IRS Publication 505 (2026)',url:`${IRS}/publications/p505`}], currentYear:2026 },
  { slug:'child-tax-credit-calculator', status: 'reviewed', methodology:'2026 CTC/ACTC estimate using the statutory $2,200 child credit, $1,700 ACTC maximum, earned-income formula and CTC phaseout thresholds, plus a separate simplified child-and-dependent-care calculation.', limitations:['The page does not reproduce Schedule 8812 or Form 2441. It simplifies filing status, qualifying-child requirements, tax liability, SSN requirements, provider rules and dependent-care benefits.'], sources:[{title:'IRS Child Tax Credit',url:`${IRS}/credits-deductions/individuals/child-tax-credit`},{title:'IRS Topic 602 — Child and Dependent Care Credit',url:`${IRS}/taxtopics/tc602`}], currentYear:2026 },
  { slug:'closing-cost-calculator', status:'custom_estimate', methodology:'Estimate of lender, title, prepaid and recording costs from user-entered purchase price, loan and location assumptions.', limitations:['Closing costs vary significantly by state, lender, transaction and property. Percentage ranges are planning estimates, not national guarantees.'], sources:[], currentYear:2026 },
  { slug:'cobra-vs-marketplace-calculator', status: 'reviewed', methodology:'Premium-only comparison using entered COBRA and Marketplace premiums plus a simplified Premium Tax Credit estimate based on household income and size.', limitations:['The model is not Form 8962. It does not determine eligibility from all tax-household, employer-coverage, immigration, residence, benchmark-plan and enrollment rules.'], sources:[{title:'HealthCare.gov Premium Tax Credit',url:'https://www.healthcare.gov/glossary/premium-tax-credit/'},{title:'HealthCare.gov 2026 Federal Poverty Levels',url:'https://www.healthcare.gov/glossary/federal-poverty-level-fpl/'}], currentYear:2026 },
]

export const FINANCE_BATCH_02_SLUGS = FINANCE_BATCH_02.map((profile) => profile.slug)
