export type FinanceBatch08Status = 'reviewed' | 'tax_rule_review' | 'custom_estimate' | 'needs_manual_review' | 'formula_review'

export interface FinanceBatch08Profile {
  slug: string
  status: FinanceBatch08Status
  methodology: string
  limitations: string[]
  sources: Array<{ title: string; url: string }>
  currentYear?: number
}

const IRS = 'https://www.irs.gov'
const CMS = 'https://www.cms.gov'
const SEC = 'https://www.investor.gov'

export const FINANCE_BATCH_08: FinanceBatch08Profile[] = [
  { slug:'loan-prepayment-calculator', status:'reviewed', methodology:'Amortization comparison showing how extra principal payments change interest and payoff time.', limitations:['Actual lender rules may restrict prepayments or charge penalties depending on the loan and jurisdiction.','Taxes and investment opportunity cost are outside the model.'], sources:[{title:'CFPB — Mortgage resources',url:'https://www.consumerfinance.gov/consumer-tools/mortgages/'}], currentYear:2026 },
  { slug:'long-term-care-insurance-calculator', status:'custom_estimate', methodology:'Scenario comparison of potential long-term-care costs, insurance coverage and self-funding assumptions.', limitations:['Care costs vary greatly by location and care setting.','Insurance premiums and underwriting cannot be predicted reliably from a generic model.','There is no universal asset threshold at which self-funding is appropriate.'], sources:[{title:'Medicare — Long-term care',url:'https://www.medicare.gov/coverage/long-term-care'}], currentYear:2026 },
  { slug:'lumpsum-calculator', status:'custom_estimate', methodology:'Future-value projection for a one-time investment under user-entered return and time assumptions.', limitations:['Returns are hypothetical and not guaranteed.','Historical market behavior does not ensure future performance.'], sources:[{title:'SEC — Compound interest',url:`${SEC}/introduction-investing/investing-basics/investment-products`}], currentYear:2026 },
  { slug:'lumpsum-vs-gold-calculator', status:'custom_estimate', methodology:'India-focused scenario comparison of a one-time investment and gold using user-entered return, tax and inflation assumptions.', limitations:['Gold returns vary by instrument such as physical gold, ETF and sovereign products.','Tax treatment varies by product and holding period.','Investment returns are hypothetical.'], sources:[{title:'SEBI Investor — Investment education',url:'https://investor.sebi.gov.in/'}], currentYear:2026 },
  { slug:'lumpsum-vs-sip-calculator', status:'custom_estimate', methodology:'Scenario comparison between investing a lump sum immediately and investing it through periodic contributions.', limitations:['Results depend on the assumed return path and timing.','A smooth return assumption does not reproduce actual market volatility.'], sources:[{title:'SEC — Investor education',url:`${SEC}/introduction-investing`}], currentYear:2026 },
  { slug:'margin-trading-calculator', status:'formula_review', methodology:'Leverage and margin-call scenario based on user-entered position, borrowing and maintenance-margin assumptions.', limitations:['Broker requirements vary.','Margin calls can occur quickly and losses can exceed the initial cash contribution.','Interest, fees and liquidation rules vary by account and security.'], sources:[{title:'FINRA — Margin accounts',url:'https://www.finra.org/investors/investing/investment-products/stocks/margin-accounts'}], currentYear:2026 },
  { slug:'medicare-part-d-calculator', status:'tax_rule_review', methodology:'Simplified 2026 Part D defined-standard cost scenario using the $615 deductible and $2,100 annual out-of-pocket threshold plus the user-entered plan premium.', limitations:['Actual plan costs depend on formulary, pharmacy network, negotiated prices and coverage.','Part D IRMAA is separate from the plan premium.','The calculator is not a plan quote.'], sources:[{title:'CMS — Final CY 2026 Part D Redesign Program Instructions',url:`${CMS}/newsroom/fact-sheets/final-cy-2026-part-d-redesign-program-instructions`},{title:'CMS — 2026 Medicare premiums and Part D IRMAA',url:`${CMS}/newsroom/fact-sheets/2026-medicare-parts-b-premiums-deductibles`}], currentYear:2026 },
  { slug:'medicare-premium-calculator', status:'tax_rule_review', methodology:'2026 Medicare Part B and Part D IRMAA estimate using CMS-published MAGI thresholds and monthly amounts.', limitations:['The UI models a single filer only.','The result excludes the beneficiary-specific Part D plan premium and many other Medicare costs.','IRMAA generally uses tax-return information from two years earlier.'], sources:[{title:'CMS — 2026 Medicare Parts A & B Premiums and Deductibles',url:`${CMS}/newsroom/fact-sheets/2026-medicare-parts-b-premiums-deductibles`}], currentYear:2026 },
  { slug:'medicare-vs-private-insurance-calculator', status:'custom_estimate', methodology:'Scenario comparison of Medicare-related premiums and private/employer coverage assumptions.', limitations:['Coverage, eligibility and plan benefits vary widely.','Not an enrollment or coverage recommendation.'], sources:[{title:'Medicare.gov',url:'https://www.medicare.gov/'}], currentYear:2026 },
  { slug:'mega-backdoor-roth-calculator', status:'tax_rule_review', methodology:'Estimates remaining 2026 defined-contribution annual-additions room after regular employee deferrals and employer contributions.', limitations:['Plan documents determine whether after-tax contributions and Roth conversion/rollover features are available.','The $72,000 annual-additions limit is subject to compensation and plan rules; catch-up contributions are treated separately.'], sources:[{title:'IRS — 401(k) contribution limits',url:`${IRS}/retirement-plans/plan-participant-employee/retirement-topics-401k-and-profit-sharing-plan-contribution-limits`}], currentYear:2026 },
  { slug:'merit-raise-vs-job-change-calculator', status:'custom_estimate', methodology:'Compensation projection comparing entered merit raises with a job-change offer and modeled future raises.', limitations:['The default post-switch raise assumption is a scenario, not a market forecast.','Benefits, equity, taxes, unemployment risk and career progression can change the comparison.'], sources:[], currentYear:2026 },
  { slug:'mortgage-affordability-calculator', status:'custom_estimate', methodology:'Debt-to-income and payment-based home-price scenario using user-entered income, debts, rate and housing-cost assumptions.', limitations:['Lender underwriting standards vary.','Taxes, insurance, HOA fees and mortgage insurance can materially change affordability.'], sources:[{title:'CFPB — Mortgage resources',url:'https://www.consumerfinance.gov/consumer-tools/mortgages/'}], currentYear:2026 },
  { slug:'mortgage-calculator', status:'reviewed', methodology:'Standard fixed-rate mortgage amortization with optional property-tax, insurance and mortgage-insurance assumptions.', limitations:['Actual lender payment depends on rate, fees, escrow, insurance and property-specific costs.'], sources:[{title:'CFPB — Mortgage resources',url:'https://www.consumerfinance.gov/consumer-tools/mortgages/'}], currentYear:2026 },
  { slug:'mortgage-forbearance-impact-calculator', status:'custom_estimate', methodology:'Scenario model for payment suspension and subsequent balance/interest effects.', limitations:['Actual forbearance terms vary by servicer and program.','Interest accrual, repayment options and capitalization rules can differ.'], sources:[{title:'CFPB — Mortgage forbearance',url:'https://www.consumerfinance.gov/coronavirus/mortgage-and-housing-assistance/mortgage-forbearance/'}], currentYear:2026 },
  { slug:'mortgage-points-calculator', status:'formula_review', methodology:'Compares upfront discount-point cost with modeled payment savings and break-even timing.', limitations:['One point is conventionally 1% of principal, but rate reduction varies by lender.','Tax deductibility depends on IRS requirements and is excluded from the break-even calculation.'], sources:[{title:'IRS Topic 504 — Home mortgage points',url:`${IRS}/taxtopics/tc504`},{title:'CFPB — Closing costs',url:'https://www.consumerfinance.gov/owning-a-home/closing-costs/'}], currentYear:2026 },
  { slug:'mortgage-recast-calculator', status:'custom_estimate', methodology:'Re-amortization scenario showing the effect of a lump-sum principal payment while retaining the existing rate and remaining term.', limitations:['Not every lender offers recasting.','Minimum lump sums and fees vary.','The calculator does not model lender-specific eligibility.'], sources:[{title:'CFPB — Mortgage resources',url:'https://www.consumerfinance.gov/consumer-tools/mortgages/'}], currentYear:2026 },
  { slug:'mortgage-refinance-breakeven-calculator', status:'reviewed', methodology:'Calculates the months required for payment savings to offset refinance closing costs.', limitations:['Break-even ignores uncertainty in future rates, taxes and home tenure.','Some costs may be financed rather than paid upfront.'], sources:[{title:'CFPB — Refinance resources',url:'https://www.consumerfinance.gov/owning-a-home/refinance/'}], currentYear:2026 },
  { slug:'mortgage-refinance-calculator', status:'custom_estimate', methodology:'Compares existing and proposed mortgage payment and interest scenarios.', limitations:['Rate offers and closing costs vary by borrower and lender.','Cash-out refinancing introduces additional debt and risk.'], sources:[{title:'CFPB — Refinance',url:'https://www.consumerfinance.gov/owning-a-home/refinance/'}], currentYear:2026 },
  { slug:'mortgage-vs-rent-calculator', status:'custom_estimate', methodology:'Long-horizon rent-versus-buy scenario incorporating mortgage costs, housing expenses and opportunity cost.', limitations:['Home appreciation, rent growth, taxes, maintenance and investment returns are assumptions.','Tax benefits are simplified.'], sources:[{title:'CFPB — Buying a home',url:'https://www.consumerfinance.gov/owning-a-home/'}], currentYear:2026 },
  { slug:'mortgage-vs-renting-usa-calculator', status:'custom_estimate', methodology:'USA rent-versus-buy scenario using user-entered housing and investment assumptions.', limitations:['Results depend heavily on appreciation, rent growth and investment-return assumptions.','Not a universal buy-or-rent recommendation.'], sources:[{title:'CFPB — Buying a home',url:'https://www.consumerfinance.gov/owning-a-home/'}], currentYear:2026 },
  { slug:'municipal-bond-ladder-calculator', status:'custom_estimate', methodology:'Cash-flow scenario for staggered municipal-bond maturities and user-entered yields.', limitations:['Municipal bond credit, call, liquidity and state-tax treatment vary.','Yield assumptions are not guarantees.'], sources:[{title:'MSRB — Municipal securities education',url:'https://www.msrb.org/'}], currentYear:2026 },
  { slug:'municipal-bond-tax-calculator', status:'tax_rule_review', methodology:'Tax-equivalent-yield scenario for tax-exempt municipal income under user-entered marginal tax rates.', limitations:['State and local tax treatment varies.','AMT and bond-specific tax status can affect the result.','The model does not determine whether a specific bond is tax-exempt for a particular taxpayer.'], sources:[{title:'IRS — Tax-exempt interest',url:`${IRS}/taxtopics/tc403`},{title:'MSRB — Municipal securities',url:'https://www.msrb.org/'}], currentYear:2026 },
  { slug:'municipal-bonds-vs-corporate-bonds-calculator', status:'custom_estimate', methodology:'After-tax yield comparison using user-entered municipal and corporate bond yields and tax assumptions.', limitations:['Credit, duration, call risk, liquidity and state taxes can materially change outcomes.','Not an investment recommendation.'], sources:[{title:'MSRB — Municipal securities',url:'https://www.msrb.org/'},{title:'SEC — Bonds',url:`${SEC}/introduction-investing/investing-basics/investment-products/bonds-or-bond-funds`}], currentYear:2026 },
  { slug:'mutual-fund-calculator', status:'tax_rule_review', methodology:'India-focused mutual-fund growth and fee scenario using user-entered investment, return and expense assumptions.', limitations:['Returns are hypothetical.','Tax treatment and exit loads vary by fund category and holding period.','The page should not be interpreted as personalized investment advice.'], sources:[{title:'SEBI Investor — Mutual funds',url:'https://investor.sebi.gov.in/'}], currentYear:2026 },
  { slug:'mutual-fund-return-calculator', status:'reviewed', methodology:'Calculates absolute return and CAGR from units, purchase NAV, current NAV and holding period.', limitations:['For periodic investments, XIRR is generally more appropriate than a simple CAGR calculation.','Taxes and fees can affect realized returns.'], sources:[{title:'SEBI Investor — Mutual funds',url:'https://investor.sebi.gov.in/'}], currentYear:2026 },
]
