import type { FinanceQualityProfile } from './finance-quality'

const IRS = 'https://www.irs.gov'
const SSA = 'https://www.ssa.gov'

export const FINANCE_BATCH_14: FinanceQualityProfile[] = [
  { slug:'sip-vs-fd-calculator', status:'custom_estimate', methodology:'India scenario comparison between SIP market-return assumptions and fixed-deposit interest assumptions.', limitations:['SIP returns are not guaranteed.','FD rates, tenure, taxation, premature-withdrawal rules and bank products vary.'], sources:[{title:'Social Security Administration — Pension and work abroad',url:'https://www.ssa.gov/prepare/government-and-foreign-pensions'}], currentYear:2026 },
  { slug:'sip-vs-gold-calculator', status:'custom_estimate', methodology:'India scenario comparison of SIP growth and gold-price appreciation using user-entered assumptions.', limitations:['Gold returns are volatile and may differ by product, purity, spread and storage costs.','Taxes and transaction costs are simplified.'], sources:[], currentYear:2026 },
  { slug:'sip-vs-mutual-fund-direct-plan-calculator', status:'custom_estimate', methodology:'Scenario comparison of direct-plan and regular-plan mutual-fund outcomes using user-entered return and expense assumptions.', limitations:['Actual expense ratios, commissions, taxes and fund performance vary.','The calculator does not recommend a specific fund.'], sources:[], currentYear:2026 },
  { slug:'sip-vs-nps-calculator', status:'reviewed', methodology:'India retirement scenario comparing SIP investing with NPS contributions using entered return, tax and annuity assumptions.', limitations:['NPS exit, annuity and tax rules depend on the applicable regulations and subscriber circumstances.','Equity-market returns are assumptions.'], sources:[{title:'PFRDA — NPS information',url:'https://pfrda.org.in/'}], currentYear:2026 },
  { slug:'sip-vs-ppf-calculator', status:'reviewed', methodology:'India scenario comparison of SIP growth with PPF using an entered PPF rate and investment assumptions.', limitations:['PPF rates are notified periodically and may change.','SIP returns are not guaranteed.'], sources:[{title:'India Department of Economic Affairs — Small Savings',url:'https://dea.gov.in/budget-division/475'}], currentYear:2026 },
  { slug:'sip-vs-rd-calculator', status:'custom_estimate', methodology:'India comparison of SIP and recurring-deposit accumulation using entered market and deposit rates.', limitations:['RD rates and taxation vary by institution and period.','SIP returns are assumptions.'], sources:[], currentYear:2026 },
  { slug:'sip-vs-real-estate-calculator', status:'custom_estimate', methodology:'Scenario comparison of SIP investing and direct property ownership using entered appreciation, rent, financing and cost assumptions.', limitations:['Property taxes, vacancy, maintenance, leverage, transaction costs and liquidity are simplified.','Market returns are assumptions.'], sources:[], currentYear:2026 },
  { slug:'sip-vs-savings-account-calculator', status:'custom_estimate', methodology:'India comparison between SIP growth and savings-account interest using user-entered assumptions.', limitations:['Savings rates and SIP returns vary.','Taxes and fees are simplified.'], sources:[], currentYear:2026 },
  { slug:'sip-vs-stocks-calculator', status:'custom_estimate', methodology:'Scenario comparison between diversified SIP investing and direct-stock investing using entered return and volatility assumptions.', limitations:['Direct-stock outcomes are highly uncertain and concentrated.','Historical returns do not guarantee future results.'], sources:[], currentYear:2026 },
  { slug:'social-security-breakeven-calculator', status:'reviewed', methodology:'Pairwise Social Security claiming comparison using a user-entered FRA benefit, statutory early/delayed claiming adjustments and an explicit age-62 crossover calculation.', limitations:['Actual Social Security benefits depend on the claimant record, FRA, earnings history and applicable rules.','The break-even comparison excludes COLAs, taxes, survivor/spousal effects, earnings-test withholding and investment returns.'], sources:[{title:'SSA — Retirement benefit calculation',url:`${SSA}/oact/ProgData/retirebenefit2.html`},{title:'SSA — Benefit amounts and 2026 bend points',url:`${SSA}/oact/COLA/Benefits.html`}], currentYear:2026 },
  { slug:'social-security-calculator', status:'reviewed', methodology:'Educational claiming-age comparison using a user-entered FRA benefit and statutory early/delayed claiming adjustments.', limitations:['This is not an SSA benefit estimate.','The model does not reproduce the claimant’s AIME, earnings record, COLAs, taxes, survivor benefits or all claiming rules.'], sources:[{title:'SSA — Retirement benefit calculation',url:`${SSA}/oact/ProgData/retirebenefit2.html`},{title:'SSA — Benefit amounts and 2026 bend points',url:`${SSA}/oact/COLA/Benefits.html`}], currentYear:2026 },
  { slug:'social-security-cola-calculator', status:'reviewed', methodology:'Projects the effect of an entered COLA on a Social Security benefit; current 2026 context uses the 2.8% COLA already announced for 2026.', limitations:['Future COLAs are not known until SSA announces them.','Actual benefit amounts involve PIA calculations and rounding.'], sources:[{title:'SSA — 2026 COLA fact sheet',url:`${SSA}/cola/factsheets/2026.html`}], currentYear:2026 },
  { slug:'social-security-couples-optimizer', status:'reviewed', methodology:'Six-scenario married-couple claiming comparison using FRA PIA inputs, statutory early/delayed adjustments and a user-entered joint longevity assumption.', limitations:['Not an official SSA optimizer.','Spousal top-ups, survivor timing, taxes, earnings tests, COLAs and exact benefit records are simplified or excluded.'], sources:[{title:'SSA — Family benefits',url:`${SSA}/family/eligibility`},{title:'SSA — Retirement benefit calculation',url:`${SSA}/oact/ProgData/retirebenefit2.html`}], currentYear:2026 },
  { slug:'social-security-spousal-calculator', status:'reviewed', methodology:'Simplified spousal-benefit scenario using FRA PIA inputs, own retirement benefit and selected claiming ages.', limitations:['Actual spousal benefits depend on FRA, own benefit, entitlement timing, deemed filing, earnings history and applicable Social Security rules.'], sources:[{title:'SSA — Family benefits',url:`${SSA}/family/eligibility`},{title:'SSA — Spouse benefit estimates',url:`${SSA}/myaccount/spousal-benefits.html`}], currentYear:2026 },
  { slug:'social-security-tax-calculator', status:'reviewed', methodology:'Simplified federal Social Security benefit-taxability estimate using provisional-income assumptions.', limitations:['Actual taxable benefits require the taxpayer’s complete income and filing-status calculation.','State treatment can differ.'], sources:[{title:'IRS — Social Security and equivalent railroad retirement benefits',url:`${IRS}/taxtopics/tc423`}], currentYear:2026 },
  { slug:'social-security-timing-optimizer', status:'reviewed', methodology:'Claiming-age scenario comparison using the statutory early-retirement reduction schedule and delayed-retirement credits through age 70.', limitations:['The optimizer is illustrative and does not access an individual SSA earnings record.','Taxes, COLAs, Medicare premiums, earnings tests and survivor effects are excluded.'], sources:[{title:'SSA — Retirement benefit calculation',url:`${SSA}/oact/ProgData/retirebenefit2.html`},{title:'SSA — Retirement benefit examples',url:`${SSA}/oact/COLA/examplemax.html`}], currentYear:2026 },
  { slug:'social-security-vs-private-pension-calculator', status:'custom_estimate', methodology:'Scenario comparison of Social Security income and a private-pension income stream using entered amounts and longevity assumptions.', limitations:['Private pension guarantees, COLAs, survivor provisions and PBGC coverage vary by plan.','Social Security amounts are not official benefit estimates.'], sources:[{title:'SSA — Get a benefits estimate',url:`${SSA}/prepare/get-benefits-estimate`}], currentYear:2026 },
  { slug:'social-security-wep-calculator', status:'reviewed', methodology:'Historical WEP/GPO educational screen. Current benefit calculations set the WEP/GPO reduction to zero because the Social Security Fairness Act repealed both provisions for benefits payable January 2024 and later.', limitations:['Historical WEP/GPO reductions may still matter when reviewing benefits payable before January 2024.','This page is not a Social Security benefit statement or eligibility determination.'], sources:[{title:'SSA — Social Security program information',url:`${SSA}/oact/`}], currentYear:2026 },
  { slug:'solo-401k-calculator', status:'reviewed', methodology:'Self-employed retirement contribution scenario using 2026 employee-deferral and annual-additions limits.', limitations:['Actual contribution capacity depends on compensation, business structure, aggregation and plan terms.','Catch-up rules and SECURE 2.0 provisions can change the result.'], sources:[{title:'IRS — 401(k) contribution limits',url:`${IRS}/retirement-plans/plan-participant-employee/retirement-topics-401k-and-profit-sharing-plan-contribution-limits`},{title:'IRS — Catch-up contributions',url:`${IRS}/retirement-plans/plan-participant-employee/retirement-topics-catch-up-contributions`}], currentYear:2026 },
  { slug:'sp500-vs-bonds-calculator', status:'custom_estimate', methodology:'Historical/scenario comparison between S&P 500 and bond-return assumptions.', limitations:['Historical returns are not forecasts.','Taxes, fees, inflation and sequence risk are simplified.'], sources:[{title:'SSA — Pension and work abroad',url:'https://www.ssa.gov/prepare/government-and-foreign-pensions'},{title:'SSA — Social Security Fairness Act',url:'https://www.ssa.gov/benefits/retirement/social-security-fairness-act.html'}], currentYear:2026 },
  { slug:'sp500-vs-real-estate-usa-calculator', status:'custom_estimate', methodology:'US scenario comparison of stock-market and direct-property returns using entered appreciation, rent, financing and cost assumptions.', limitations:['Real-estate leverage, taxes, maintenance, vacancy and transaction costs are simplified.','Historical stock and property returns do not guarantee future performance.'], sources:[], currentYear:2026 },
  { slug:'spain-pension-vs-etf-calculator', status:'reviewed', methodology:'Spain-focused retirement scenario comparison between pension income and ETF investing.', limitations:['Spanish pension eligibility, tax treatment and ETF taxation require current Spain-specific rules.','This is not an official pension entitlement calculation.'], sources:[{title:'Spanish Social Security — Maximum pension amounts',url:'https://www.seg-social.es/wps/portal/wss/internet/Pensionistas/30430/30459'}], currentYear:2026 },
  { slug:'spin-off-tax-basis-calculator', status:'reviewed', methodology:'Scenario allocation of tax basis between parent and spun-off securities using an entered allocation ratio.', limitations:['Actual basis allocation depends on the transaction documents and applicable tax rules.','This is not a substitute for the issuer’s official allocation information or tax adviser review.'], sources:[{title:'IRS — Investment income and basis guidance',url:`${IRS}/investments`}], currentYear:2026 },
  { slug:'spy-vs-bitcoin-portfolio-calculator', status:'custom_estimate', methodology:'Historical/scenario portfolio comparison between SPY and Bitcoin using user-entered allocation and return assumptions.', limitations:['Historical crypto and equity returns are not forecasts.','Volatility, drawdowns, taxes and rebalancing are simplified.'], sources:[], currentYear:2026 },  { slug:'ss-vs-private-pension-calculator', status:'custom_estimate', methodology:'Scenario comparison of Social Security income and a private pension using entered benefit amounts, claiming age and longevity assumptions.', limitations:['Social Security is not an official SSA estimate and private pension terms vary by plan.','Survivor benefits, COLAs, taxes and PBGC coverage are simplified.'], sources:[{title:'SSA — Get a benefits estimate',url:`${SSA}/prepare/get-benefits-estimate`}], currentYear:2026 },

]

export const FINANCE_BATCH_14_SLUGS = FINANCE_BATCH_14.map(p => p.slug)
