import type { FinanceQualityProfile } from './finance-quality'

const IRS = 'https://www.irs.gov'
const GOVUK = 'https://www.gov.uk'
const TREASURY = 'https://www.treasurydirect.gov'
const profiles: FinanceQualityProfile[] = [
  ['paycheck-contribution-optimizer','tax_rule_review','Per-paycheck contribution planning for 401(k), HSA and FSA elections using annual limits divided across pay periods.',['Employer contributions, catch-ups, payroll-tax treatment and plan-specific limits are simplified.','The result is a planning estimate, not payroll withholding advice.'],[{title:'IRS — 2026 retirement contribution limits',url:`${IRS}/retirement-plans/plan-participant-employee/retirement-topics-401k-and-profit-sharing-plan-contribution-limits`},{title:'IRS — 2026 HSA amounts',url:`${IRS}/irb/2025-21_IRB`}],2026],
  ['tax-loss-harvesting-portfolio-calculator','tax_rule_review','Portfolio-level capital-loss scenario applying modeled losses against gains, the ordinary-income deduction limit and carryforwards.',['Actual Schedule D/Form 8949 netting, short/long-term ordering, basis and wash-sale adjustments are simplified.'],[{title:'IRS — Publication 550',url:`${IRS}/publications/p550`}],2026],
  ['tax-withholding-w4-calculator','tax_rule_review','Simplified annual federal-tax estimate compared with a modeled withholding amount; it does not reproduce payroll tables.',['Form W-4 entries, payroll frequency, multiple jobs, bonuses, credits and pre-tax benefits can materially change actual withholding.'],[{title:'IRS — Publication 15-T, 2026 withholding methods',url:`${IRS}/publications/p15t`},{title:'IRS — Tax withholding',url:`${IRS}/individuals/employees/tax-withholding`}],2026],
  ['taxable-vs-roth-vs-traditional-calculator','tax_rule_review','After-tax retirement-account comparison under user-entered current/future tax-rate and return assumptions.',['Does not enforce IRA eligibility or model every deduction, contribution limit, capital-gain rule or state tax.'],[{title:'IRS — 2026 IRA limit',url:`${IRS}/newsroom/401k-limit-increases-to-24500-for-2026-ira-limit-increases-to-7500`}],2026],
  ['term-vs-ulip-calculator','custom_estimate','India scenario comparison of term insurance plus investing versus a ULIP using user-entered premiums, returns and charges.',['ULIP charges, tax treatment, insurance needs and market returns vary by policy and insurer; this is not an insurance recommendation.'],[],2026],
  ['term-vs-whole-life-calculator','custom_estimate','Scenario comparison of term insurance plus investing versus permanent life insurance using user-entered assumptions.',['Policy guarantees, cash values, fees, underwriting and tax treatment vary by contract and jurisdiction.'],[],2026],
  ['tip-calculator','reviewed','Simple bill-tip and bill-split arithmetic using a user-entered percentage and party count.',['Tip norms and tax/service-charge practices vary by location and establishment.'],[],2026],
  ['tips-vs-nominal-bonds-calculator','custom_estimate','Scenario comparison of inflation-protected and nominal bonds using user-entered yields and inflation assumptions.',['Market yields, inflation, taxes, duration, liquidity and price volatility are not forecasts.'],[{title:'TreasuryDirect — TIPS',url:`${TREASURY}/marketable-securities/tips/`}],2026],
  ['traditional-ira-vs-taxable-account-calculator','tax_rule_review','After-tax retirement versus taxable-account scenario using user-entered return, tax and contribution assumptions.',['IRA eligibility, deductions, RMDs, capital-gain timing, dividends and state taxes are simplified.'],[{title:'IRS — IRA rules',url:`${IRS}/retirement-plans/individual-retirement-arrangements-iras`}],2026],
  ['treasury-bill-calculator','custom_estimate','T-bill price, discount yield and bond-equivalent-yield arithmetic from user-entered face value, term and rate.',['Actual auction price/yield, settlement, accrued interest and tax effects can differ; market rates change continuously.'],[{title:'TreasuryDirect — Treasury Bills',url:`${TREASURY}/marketable-securities/treasury-bills/`}],2026],
  ['trust-fund-growth-calculator','custom_estimate','Trust corpus projection using contributions, investment return and trustee-fee assumptions.',['Trust taxation, distribution rules and fiduciary fees depend on the trust instrument and applicable law.'],[{title:'IRS — Form 1041 and trust taxation',url:`${IRS}/forms-pubs/about-form-1041`}],2026],
  ['tsp-vs-401k-calculator','tax_rule_review','Federal-retirement scenario comparing TSP savings and a simplified FERS pension assumption with a private 401(k) comparison.',['Actual TSP/FERS benefits depend on service, high-3 pay, eligibility, agency contributions, survivor elections and other rules.'],[{title:'IRS — 2026 retirement limits',url:`${IRS}/retirement-plans/plan-participant-employee/retirement-topics-401k-and-profit-sharing-plan-contribution-limits`}],2026],
  ['uk-buy-to-let-vs-stocks-calculator','custom_estimate','UK scenario comparison of rental-property and equity-investment returns using user-entered assumptions.',['UK property tax, financing, maintenance, vacancy, transaction costs and investment returns vary materially.'],[{title:'GOV.UK — Income Tax rates and allowances',url:`${GOVUK}/income-tax-rates/current-rates-and-allowances`}],2026],
  ['uk-fixed-rate-vs-tracker-mortgage-calculator','custom_estimate','UK mortgage scenario comparing fixed-rate and tracker payment paths under user-entered rates and Bank Rate assumptions.',['Tracker rates, lender margins, fees, remortgage timing and future Bank Rate are uncertain.'],[],2026],
  ['uk-help-to-buy-vs-lisa-calculator','tax_rule_review','Historical Help to Buy ISA versus current Lifetime ISA first-home saving comparison.',['Help to Buy ISA closed to new accounts in 2019; existing accounts follow legacy rules. LISA eligibility and withdrawal rules apply.'],[{title:'GOV.UK — Help to Buy ISA statistics and closure',url:`${GOVUK}/government/statistics/annual-savings-statistics/annual-savings-statistics-background-and-methodology`},{title:'GOV.UK — Individual Savings Accounts',url:`${GOVUK}/individual-savings-accounts/overview`}],2026],
  ['uk-income-tax-calculator','tax_rule_review','UK PAYE income-tax and National Insurance planning model for tax year 2026/27.',['Scotland has separate income-tax bands; payroll, pension, benefits and other income can change actual liability.'],[{title:'GOV.UK — Income Tax rates and Personal Allowances',url:`${GOVUK}/income-tax-rates/current-rates-and-allowances`}],2026],
  ['uk-lifetime-isa-vs-sipp-calculator','tax_rule_review','UK retirement-saving scenario comparing Lifetime ISA bonus mechanics with SIPP tax relief.',['Access age, withdrawal penalties, contribution limits, pension tax rules and individual tax circumstances affect the outcome.'],[{title:'GOV.UK — ISAs',url:`${GOVUK}/individual-savings-accounts/overview`}],2026],
  ['uk-pension-calculator','custom_estimate','UK workplace-pension projection using contributions, investment growth and retirement-income assumptions.',['Auto-enrolment minimums, employer schemes, charges, state pension and annuity/drawdown outcomes vary.'],[{title:'GOV.UK — Workplace pensions',url:`${GOVUK}/workplace-pensions`}],2026],
  ['uk-pension-drawdown-vs-annuity-calculator','custom_estimate','UK retirement-income scenario comparing flexible drawdown with annuity income.',['Annuity quotes, longevity, inflation, investment returns, tax and provider terms are uncertain.'],[],2026],
  ['uk-pension-vs-isa-calculator','tax_rule_review','UK scenario comparing pension saving with Stocks and Shares ISA investing under user-entered tax assumptions.',['Pension tax relief, employer contributions, access rules and ISA treatment differ by individual circumstances.'],[{title:'GOV.UK — ISAs',url:`${GOVUK}/individual-savings-accounts/overview`}],2026],
  ['uk-premium-bonds-vs-cash-isa-calculator','custom_estimate','UK scenario comparison of NS&I Premium Bonds and Cash ISA savings using user-entered return assumptions.',['Premium Bonds use prize-based outcomes rather than a guaranteed interest rate; Cash ISA rates vary by provider and product.'],[{title:'GOV.UK — ISAs',url:`${GOVUK}/individual-savings-accounts/overview`}],2026],
  ['uk-remortgage-vs-invest-calculator','custom_estimate','UK scenario comparing mortgage overpayment/remortgaging with investing surplus cash.',['Future mortgage rates, investment returns, tax, fees, early-repayment charges and risk tolerance vary.'],[],2026],
  ['uk-stamp-duty-calculator','tax_rule_review','England and Northern Ireland residential SDLT calculation using current marginal rates and first-time-buyer relief.',['Scotland and Wales use different property taxes; non-resident surcharges and special transactions are simplified.'],[{title:'GOV.UK — SDLT residential rates',url:`${GOVUK}/stamp-duty-land-tax/residential-property-rates`},{title:'GOV.UK — SDLT overview',url:`${GOVUK}/stamp-duty-land-tax/overview`}],2026],
  ['uk-stocks-vs-bonds-calculator','custom_estimate','UK scenario comparison of equity and bond returns using user-entered assumptions.',['Historical returns are not forecasts; taxes, charges, inflation and currency effects are simplified.'],[],2026],
  ['umbrella-insurance-calculator','custom_estimate','Personal-liability coverage-gap scenario based on assets and existing liability limits.',['Insurer minimum underlying limits, premiums, exclusions and appropriate coverage vary by household and policy.'],[],2026],
].map(([slug,status,methodology,limitations,sources,currentYear]) => ({slug,status,methodology,limitations,sources,currentYear} as FinanceQualityProfile))

export const FINANCE_BATCH_18 = profiles
export const FINANCE_BATCH_18_SLUGS = profiles.map(p => p.slug)
