import type { FinanceQualityProfile } from './finance-quality'

const IRS = 'https://www.irs.gov'
const TREASURY = 'https://www.treasurydirect.gov'
const FHFA = 'https://www.fhfa.gov'
const HUD = 'https://www.hud.gov'
const CBIC = 'https://taxinformation.cbic.gov.in'
const LABOUR = 'https://www.labour.gov.in'

const profile = (slug: string, status: FinanceQualityProfile['status'], methodology: string, limitations: string[], sources: FinanceQualityProfile['sources'] = []): FinanceQualityProfile => ({
  slug, status, methodology, limitations, sources, currentYear: 2026,
})

export const FINANCE_BATCH_06: FinanceQualityProfile[] = [
  profile('gold-vs-stocks-calculator', 'custom_estimate', 'Scenario comparison of user-entered gold and equity allocations, returns, volatility and drawdown assumptions.', ['Historical returns are not forecasts.', 'Gold, equities and mining stocks have different risks; the model does not predict future performance.']),
  profile('government-bond-calculator', 'custom_estimate', 'Bond price, current-yield, yield-to-maturity and duration scenarios from user-entered security terms.', ['Actual bond prices and yields are market-dependent.', 'Tax treatment varies by country and security.', 'Duration is an interest-rate sensitivity measure, not a return guarantee.']),
  profile('gratuity-calculator', 'needs_manual_review', 'India gratuity scenario based on salary, service and the selected employment framework.', ['India labour-law changes effective from 21 November 2025 affect the wage definition and gratuity treatment.', 'This calculator must not be presented as a universal U.S. severance calculator.', 'Tax exemption and eligibility require current law and employment-status review.'], [{ title: 'Ministry of Labour — Additional Labour Code FAQs', url: `${LABOUR}/static/uploads/2026/03/a4ccf4c6d97c4f1f36a6d83f8c64213d.pdf` }]),
  profile('gst-calculator', 'tax_rule_review', 'India GST arithmetic for tax-inclusive and tax-exclusive amounts using a user-selected rate.', ['GST rates depend on the specific goods/services and applicable notification.', 'The rate selector is not a classification engine and should not imply that one rate applies to every item.'], [{ title: 'CBIC GST rate notification', url: `${CBIC}/view-pdf/1010431/ENG/Notifications` }]),
  profile('hdhp-vs-traditional-insurance-calculator', 'tax_rule_review', 'Scenario comparison of premium, deductible, out-of-pocket and HSA-related assumptions between health-plan designs.', ['Plan eligibility and actual benefits are contract-specific.', 'HSA eligibility depends on statutory requirements and other coverage.'], [{ title: 'IRS 2026 HSA limits', url: `${IRS}/irb/2025-21_IRB` }]),
  profile('health-insurance-deductible-calculator', 'custom_estimate', 'Scenario comparison of premiums, deductible, coinsurance and out-of-pocket spending.', ['Actual plan documents control.', 'Copays, coinsurance, network rules and excluded services can change the result.']),
  profile('health-insurance-subsidy-calculator', 'tax_rule_review', 'Illustrative premium-subsidy scenario using user-entered household and premium assumptions.', ['Marketplace eligibility and premium tax credits require current federal rules and household information.', 'This is not an official eligibility determination.'], [{ title: 'HealthCare.gov — Premium Tax Credit', url: 'https://www.healthcare.gov/glossary/premium-tax-credit/' }]),
  profile('heloc-calculator', 'custom_estimate', 'HELOC availability and payment scenario using home value, mortgage balance, CLTV, draw amount, rate and repayment assumptions.', ['Lenders set their own CLTV, credit-score, income and pricing requirements.', 'HELOC rates are usually variable; a displayed rate is a scenario assumption, not a market quote.']),
  profile('heloc-credit-line-calculator', 'custom_estimate', 'Home-equity credit-line scenario from home value, existing mortgage and user-entered CLTV assumption.', ['No universal lender CLTV threshold exists.', 'Actual appraisal, underwriting and lien requirements vary.']),
  profile('home-affordability-calculator', 'reviewed', 'Housing-budget scenario using 28% front-end and 36% back-end planning thresholds with modeled property tax and insurance.', ['The 28/36 thresholds are planning heuristics, not approval rules.', 'Actual taxes, insurance, HOA, PMI/MIP, lender overlays and loan-program limits vary.'], [{ title: 'CFPB — Loan Estimate', url: 'https://www.consumerfinance.gov/owning-a-home/loan-estimate/' }, { title: 'FHFA — 2026 conforming loan limits', url: 'https://www.fhfa.gov/news/news-release/fhfa-announces-conforming-loan-limit-values-for-2026' }]),
  profile('home-equity-loan-calculator', 'reviewed', 'Fixed-payment home-equity loan scenario using entered home value, existing mortgage, loan amount, APR and term.', ['The 85% CLTV figure is a screening assumption, not an approval rule.', 'Rates, fees, appraisal values, lien position and underwriting vary.'], [{ title: 'CFPB — Home equity loans', url: 'https://www.consumerfinance.gov/ask-cfpb/what-is-a-home-equity-loan-en-105/' }, { title: 'CFPB — Loan Estimate', url: 'https://www.consumerfinance.gov/owning-a-home/loan-estimate/' }]),
  profile('home-equity-vs-personal-loan', 'reviewed', 'Scenario comparison of secured home-equity borrowing with unsecured personal borrowing using matched amount, APR and term.', ['Home-equity debt is secured by the home and default can create foreclosure risk.', 'Tax deductibility is not assumed; actual eligibility depends on use of proceeds and current law.', 'Fees and lender terms are excluded unless entered.'], [{ title: 'CFPB — Home equity loans', url: 'https://www.consumerfinance.gov/ask-cfpb/what-is-a-home-equity-loan-en-105/' }, { title: 'IRS — Publication 936', url: 'https://www.irs.gov/publications/p936' }]),
  profile('home-loan-calculator', 'reviewed', 'Standard mortgage amortization scenario using property value, down payment, interest rate and term.', ['Not a lender quote or approval decision.', 'Taxes, insurance, PMI/MIP, HOA, fees and points are outside the core payment calculation.'], [{ title: 'CFPB — Loan Estimate', url: 'https://www.consumerfinance.gov/owning-a-home/loan-estimate/' }, { title: 'FHFA — 2026 conforming loan limits', url: 'https://www.fhfa.gov/news/news-release/fhfa-announces-conforming-loan-limit-values-for-2026' }]),
  profile('home-office-deduction-calculator', 'reviewed', 'Comparison of the IRS simplified home-office method with a limited user-entered actual-expense scenario.', ['The simplified method is $5 per qualifying square foot, capped at 300 square feet.', 'Eligibility, exclusive and regular business use, gross-income limits and other Form 8829 rules are not fully modeled.', 'The tool does not estimate tax savings.'], [{ title: 'IRS — Simplified home office deduction', url: 'https://www.irs.gov/businesses/small-businesses-self-employed/simplified-option-for-home-office-deduction' }]),
  profile('house-flip-calculator', 'reviewed', 'House-flip profit scenario using acquisition, renovation, financing, holding and selling-cost assumptions.', ['The 70% rule is a heuristic, not a profitability guarantee.', 'Actual taxes, transaction costs, financing fees, overruns, permits and market prices can differ materially.'], [{ title: 'CFPB — Home buying resources', url: 'https://www.consumerfinance.gov/owning-a-home/' }]),
  profile('house-hacking-roi-calculator', 'reviewed', 'Owner-occupied rental scenario using purchase, financing, rental income and operating-cost assumptions.', ['Rental income, vacancy, repairs, taxes, insurance and financing vary by property and market.', 'Zoning, owner-occupancy and rental restrictions are not automatically checked.', 'ROI is a scenario estimate, not a guaranteed return.'], [{ title: 'HUD — FHA single-family mortgage resources', url: 'https://www.hud.gov/program_offices/housing/sfh/ins/203b-mortgages' }]),
  profile('hra-calculator', 'reviewed', 'India House Rent Allowance exemption scenario under the old tax regime using the statutory three-condition test.', ['HRA exemption is unavailable under the new tax regime.', 'The 50%/40% test applies to the qualifying salary definition and metro classification; individual payroll facts can require additional details.', 'The result is a planning estimate, not an ITR determination.'], [{ title: 'Income Tax Department — New vs old regime FAQs', url: 'https://www.incometax.gov.in/iec/foportal/help/new-tax-vs-old-tax-regime-faqs' }, { title: 'CBDT — AY 2026-27 ITR validation rules', url: 'https://www.incometax.gov.in/iec/foportal/sites/default/files/2026-05/CBDT__e-Filing_ITR%202_Validation%20Rules_AY%202026-27_V1.0.pdf' }]),
  profile('hsa-investment-calculator', 'reviewed', 'HSA accumulation scenario with self-only/family 2026 contribution limits, age-55 catch-up, investment-return and tax assumptions.', ['2026 limits are $4,400 self-only and $8,750 family, plus a $1,000 catch-up when eligible.', 'Eligibility, employer contributions, Medicare status and future limits are not determined.', 'Investment returns and medical costs are assumptions, not forecasts.'], [{ title: 'IRS — 2026 HSA limits', url: 'https://www.irs.gov/irb/2025-21_IRB' }, { title: 'IRS — Publication 15-B', url: 'https://www.irs.gov/publications/p15b' }]),
  profile('hsa-projection-calculator', 'reviewed', 'Long-term HSA balance scenario using 2026 contribution limits, medical spending, investment-return and income-tax assumptions.', ['2026 limits are $4,400 self-only and $8,750 family, plus a $1,000 catch-up when eligible.', 'Income-tax savings are illustrative; payroll-tax treatment is not assumed.', 'Eligibility, employer contributions, Medicare status and future limits are not determined.'], [{ title: 'IRS — 2026 HSA limits', url: 'https://www.irs.gov/irb/2025-21_IRB' }, { title: 'IRS — Publication 15-B', url: 'https://www.irs.gov/publications/p15b' }]),
  profile('hsa-triple-tax-growth-calculator', 'reviewed', 'HSA long-term growth scenario using 2026 contribution limits and an entered return/tax-rate assumption; the dollar result is an illustrative tax-value proxy, not a tax-return calculation.', ['Qualified-expense rules and eligibility requirements apply.', 'The calculator does not determine a user’s tax bracket or filing outcome.'], [{ title: 'IRS Publication 15-B — HSA rules', url: `${IRS}/publications/p15b` }]),
  profile('hsa-vs-401k-priority-calculator', 'reviewed', 'Planning comparison of a user-entered employer-match assumption, the 2026 self-only HSA limit, the 2026 401(k) employee-deferral limit and the 2026 IRA contribution limit.', ['Contribution priority is personal planning guidance, not individualized investment advice.', 'Employer plan rules and HSA eligibility vary.'], [{ title: 'IRS 2026 HSA limits', url: `${IRS}/irb/2025-21_IRB` }, { title: 'IRS retirement plan limits', url: `${IRS}/retirement-plans/plan-participant-employee/retirement-topics-401k-and-profit-sharing-plan-contribution-limits` }]),
  profile('hsa-vs-fsa-calculator', 'reviewed', 'Comparison of HSA and health-FSA contribution/tax scenarios using the 2026 self-only HSA limit and 2026 health-FSA salary-reduction limit.', ['2026 health FSA salary-reduction limit is $3,400; carryover is only available when the plan permits it, with a federal maximum of $680.', 'HSA eligibility is subject to statutory requirements.'], [{ title: 'IRS 2026 FSA limits', url: `${IRS}/newsroom/irs-releases-tax-inflation-adjustments-for-tax-year-2026-including-amendments-from-the-one-big-beautiful-bill` }, { title: 'IRS 2026 HSA limits', url: `${IRS}/irb/2025-21_IRB` }]),
  profile('i-bond-ladder-calculator', 'reviewed', 'Series I purchase-ladder scenario using the published May–October 2026 composite rate, equal monthly purchases, the $10,000 annual electronic purchase cap, and the three-month early-redemption interest penalty.', ['Electronic I Bond purchases are limited to the applicable annual TreasuryDirect limit.', 'Rates reset and future inflation components are unknown.'], [{ title: 'TreasuryDirect I Bonds', url: `${TREASURY}/savings-bonds/i-bonds/` }]),
  profile('i-bonds-calculator', 'reviewed', 'Series I savings-bond scenario using the Treasury composite-rate formula, semiannual rate inputs and the three-month early-redemption interest penalty.', ['Current rates are period-specific and future inflation rates are unknown.', 'The first 12 months cannot be redeemed and redemptions before five years lose the last three months of interest.'], [{ title: 'TreasuryDirect May–October 2026 I Bond rate', url: `${TREASURY}/news/2026/release-05-01-rates/` }]),
  profile('i-bonds-vs-tips-calculator', 'reviewed', 'Pre-tax real-return scenario comparing an entered I Bond composite rate converted with an entered inflation assumption against an entered TIPS real yield.', ['I Bond rates reset every six months and TIPS prices/yields move with markets.', 'Historical rates are not future-return forecasts.'], [{ title: 'TreasuryDirect I Bond interest rates', url: `${TREASURY}/savings-bonds/i-bonds/i-bonds-interest-rates/` }]),
]

export const FINANCE_BATCH_06_SLUGS = FINANCE_BATCH_06.map((p) => p.slug)
