import type { FinanceQualityProfile } from './finance-quality'

const IRS = 'https://www.irs.gov'
const TREASURY = 'https://www.treasurydirect.gov'
const FHFA = 'https://www.fhfa.gov'
const HUD = 'https://www.hud.gov'
const CBIC = 'https://taxinformation.cbic.gov.in'
const LABOUR = 'https://www.labour.gov.in'

const profile = (slug: string, status: FinanceQualityProfile['status'], methodology: string, limitations: string[], sources: FinanceQualityProfile['sources'] = []): FinanceQualityProfile => ({
  slug, status, methodology, limitations, sources, currentYear: 2026,
})

export const FINANCE_BATCH_06: FinanceQualityProfile[] = [
  profile('gold-vs-stocks-calculator', 'custom_estimate', 'Scenario comparison of user-entered gold and equity allocations, returns, volatility and drawdown assumptions.', ['Historical returns are not forecasts.', 'Gold, equities and mining stocks have different risks; the model does not predict future performance.']),
  profile('government-bond-calculator', 'custom_estimate', 'Bond price, current-yield, yield-to-maturity and duration scenarios from user-entered security terms.', ['Actual bond prices and yields are market-dependent.', 'Tax treatment varies by country and security.', 'Duration is an interest-rate sensitivity measure, not a return guarantee.']),
  profile('gratuity-calculator', 'needs_manual_review', 'India gratuity scenario based on salary, service and the selected employment framework.', ['India labour-law changes effective from 21 November 2025 affect the wage definition and gratuity treatment.', 'This calculator must not be presented as a universal U.S. severance calculator.', 'Tax exemption and eligibility require current law and employment-status review.'], [{ title: 'Ministry of Labour — Additional Labour Code FAQs', url: `${LABOUR}/static/uploads/2026/03/a4ccf4c6d97c4f1f36a6d83f8c64213d.pdf` }]),
  profile('gst-calculator', 'tax_rule_review', 'India GST arithmetic for tax-inclusive and tax-exclusive amounts using a user-selected rate.', ['GST rates depend on the specific goods/services and applicable notification.', 'The rate selector is not a classification engine and should not imply that one rate applies to every item.'], [{ title: 'CBIC GST rate notification', url: `${CBIC}/view-pdf/1010431/ENG/Notifications` }]),
  profile('hdhp-vs-traditional-insurance-calculator', 'tax_rule_review', 'Scenario comparison of premium, deductible, out-of-pocket and HSA-related assumptions between health-plan designs.', ['Plan eligibility and actual benefits are contract-specific.', 'HSA eligibility depends on statutory requirements and other coverage.'], [{ title: 'IRS 2026 HSA limits', url: `${IRS}/irb/2025-21_IRB` }]),
  profile('health-insurance-deductible-calculator', 'custom_estimate', 'Scenario comparison of premiums, deductible, coinsurance and out-of-pocket spending.', ['Actual plan documents control.', 'Copays, coinsurance, network rules and excluded services can change the result.']),
  profile('health-insurance-subsidy-calculator', 'tax_rule_review', 'Illustrative premium-subsidy scenario using user-entered household and premium assumptions.', ['Marketplace eligibility and premium tax credits require current federal rules and household information.', 'This is not an official eligibility determination.'], [{ title: 'HealthCare.gov — Premium Tax Credit', url: 'https://www.healthcare.gov/glossary/premium-tax-credit/' }]),
  profile('heloc-calculator', 'custom_estimate', 'HELOC availability and payment scenario using home value, mortgage balance, CLTV, draw amount, rate and repayment assumptions.', ['Lenders set their own CLTV, credit-score, income and pricing requirements.', 'HELOC rates are usually variable; a displayed rate is a scenario assumption, not a market quote.']),
  profile('heloc-credit-line-calculator', 'custom_estimate', 'Home-equity credit-line scenario from home value, existing mortgage and user-entered CLTV assumption.', ['No universal lender CLTV threshold exists.', 'Actual appraisal, underwriting and lien requirements vary.']),
  profile('home-affordability-calculator', 'custom_estimate', 'Housing-budget scenario based on income, debts, down payment, rate and selected affordability assumptions.', ['Lender underwriting differs by loan program.', 'Taxes, insurance, HOA fees, PMI/MIP and lender overlays can materially change affordability.'], [{ title: 'FHFA 2026 conforming loan limits', url: `${FHFA}/news/news-release/fhfa-announces-conforming-loan-limit-values-for-2026` }, { title: 'HUD 2026 FHA limits', url: `${HUD}/hud-partners/single-family-lender` }]),
  profile('home-equity-loan-calculator', 'custom_estimate', 'Amortizing home-equity loan payment and interest scenario using user-entered amount, APR and term.', ['Actual rates, fees, lien position and underwriting vary.', 'Tax deductibility of interest depends on how proceeds are used and applicable law.']),
  profile('home-equity-vs-personal-loan', 'custom_estimate', 'Scenario comparison of secured home-equity borrowing versus unsecured personal borrowing.', ['Rates and fees vary by borrower and lender.', 'Home-equity borrowing places the home at risk if payments are not made.']),
  profile('home-loan-calculator', 'custom_estimate', 'Mortgage amortization scenario using principal, rate, term and optional recurring costs.', ['The result is not a mortgage approval or loan quote.', 'Property taxes, insurance, PMI/MIP and lender fees vary.'], [{ title: 'FHFA 2026 conforming loan limits', url: `${FHFA}/news/news-release/fhfa-announces-conforming-loan-limit-values-for-2026` }]),
  profile('home-office-deduction-calculator', 'tax_rule_review', 'Comparison of the simplified home-office method and a user-entered actual-expense scenario.', ['The simplified method is $5 per qualifying square foot, capped at 300 square feet.', 'Eligibility and gross-income limitations still apply.', 'This is not Form 8829.'], [{ title: 'IRS simplified home-office method', url: `${IRS}/businesses/small-businesses-self-employed/simplified-option-for-home-office-deduction` }]),
  profile('house-flip-calculator', 'custom_estimate', 'House-flip profit and return scenario using purchase, rehab, financing, holding and selling assumptions.', ['Actual transaction costs, taxes, financing and market price are uncertain.', 'Does not replace a property-specific underwriting model.']),
  profile('house-hacking-roi-calculator', 'custom_estimate', 'Rental-income and housing-cost scenario for an owner-occupied property with shared living space.', ['Local rents, vacancy, maintenance, financing and taxes vary.', 'Legal restrictions such as zoning or lease rules are not automatically checked.']),
  profile('hra-calculator', 'tax_rule_review', 'Scenario for employer-funded health reimbursement arrangements using user-entered benefit assumptions.', ['HRA eligibility and reimbursement rules depend on the plan design.', 'The excepted-benefit HRA indexed maximum for 2026 is not a universal HRA contribution limit.'], [{ title: 'IRS 2026 HRA and HSA inflation adjustments', url: `${IRS}/irb/2025-21_IRB` }]),
  profile('hsa-investment-calculator', 'tax_rule_review', 'HSA accumulation scenario with contributions, investment return, taxes and medical spending assumptions.', ['2026 HSA contribution limits are $4,400 self-only and $8,750 family.', 'Eligibility and catch-up rules are not fully determined by the projection.'], [{ title: 'IRS 2026 HSA limits', url: `${IRS}/irb/2025-21_IRB` }]),
  profile('hsa-projection-calculator', 'tax_rule_review', 'Long-term HSA balance projection using contributions, medical spending and investment-return assumptions.', ['Projection is not a guarantee of investment performance.', 'Applicable contribution limits and eligibility must be checked by year.'], [{ title: 'IRS 2026 HSA limits', url: `${IRS}/irb/2025-21_IRB` }]),
  profile('hsa-triple-tax-growth-calculator', 'tax_rule_review', 'Comparison of HSA tax treatment and long-term growth against taxable alternatives.', ['Qualified-expense rules and eligibility requirements apply.', 'The calculator does not determine a user’s tax bracket or filing outcome.'], [{ title: 'IRS Publication 15-B — HSA rules', url: `${IRS}/publications/p15b` }]),
  profile('hsa-vs-401k-priority-calculator', 'tax_rule_review', 'Scenario comparison of employer retirement matching and HSA tax advantages using user-entered assumptions.', ['Contribution priority is personal planning guidance, not individualized investment advice.', 'Employer plan rules and HSA eligibility vary.'], [{ title: 'IRS 2026 HSA limits', url: `${IRS}/irb/2025-21_IRB` }, { title: 'IRS retirement plan limits', url: `${IRS}/retirement-plans/plan-participant-employee/retirement-topics-401k-and-profit-sharing-plan-contribution-limits` }]),
  profile('hsa-vs-fsa-calculator', 'tax_rule_review', 'Comparison of HSA and health-FSA contribution, tax and rollover scenarios.', ['2026 health FSA salary-reduction limit is $3,400; carryover is only available when the plan permits it, with a federal maximum of $680.', 'HSA eligibility is subject to statutory requirements.'], [{ title: 'IRS 2026 FSA limits', url: `${IRS}/newsroom/irs-releases-tax-inflation-adjustments-for-tax-year-2026-including-amendments-from-the-one-big-beautiful-bill` }, { title: 'IRS 2026 HSA limits', url: `${IRS}/irb/2025-21_IRB` }]),
  profile('i-bond-ladder-calculator', 'tax_rule_review', 'Series I purchase-ladder projection using purchase timing, entered rates and redemption assumptions.', ['Electronic I Bond purchases are limited to the applicable annual TreasuryDirect limit.', 'Rates reset and future inflation components are unknown.'], [{ title: 'TreasuryDirect I Bonds', url: `${TREASURY}/savings-bonds/i-bonds/` }]),
  profile('i-bonds-calculator', 'tax_rule_review', 'Series I savings-bond value projection using fixed rate, semiannual inflation rate and redemption assumptions.', ['Current rates are period-specific and future inflation rates are unknown.', 'The first 12 months cannot be redeemed and redemptions before five years lose the last three months of interest.'], [{ title: 'TreasuryDirect May–October 2026 I Bond rate', url: `${TREASURY}/news/2026/release-05-01-rates/` }]),
  profile('i-bonds-vs-tips-calculator', 'custom_estimate', 'Scenario comparison of I Bonds and TIPS using user-entered real-return, inflation, tax and liquidity assumptions.', ['I Bond rates reset every six months and TIPS prices/yields move with markets.', 'Historical rates are not future-return forecasts.'], [{ title: 'TreasuryDirect I Bond interest rates', url: `${TREASURY}/savings-bonds/i-bonds/i-bonds-interest-rates/` }]),
]

export const FINANCE_BATCH_06_SLUGS = FINANCE_BATCH_06.map((p) => p.slug)
