import type { FinanceQualityProfile } from './finance-quality'

const IRS = 'https://www.irs.gov'
const SBA = 'https://www.sba.gov'
const TREASURY = 'https://www.treasurydirect.gov'

export const FINANCE_BATCH_13: FinanceQualityProfile[] = [
  { slug:'rv-annual-cost-calculator', status:'custom_estimate', methodology:'RV ownership scenario combining financing, insurance, maintenance, storage, fuel and campsite assumptions with a user-entered usage level.', limitations:['Hotel comparison uses a fixed scenario rate rather than live hotel pricing.','Depreciation, registration, taxes, towing-vehicle costs and resale value are excluded from annual cash cost.'], sources:[], currentYear:2026 },
  { slug:'safe-harbor-401k-calculator', status:'tax_rule_review', methodology:'Illustrative employee-deferral and employer-contribution scenarios using the 2026 401(k) elective-deferral and annual-additions limits.', limitations:['Actual plan documents, compensation definitions, eligibility, vesting and safe-harbor design control the result.','The calculator does not determine plan compliance.'], sources:[{title:'IRS — 401(k) contribution limits',url:`${IRS}/retirement-plans/plan-participant-employee/retirement-topics-401k-and-profit-sharing-plan-contribution-limits`}], currentYear:2026 },
  { slug:'salary-calculator', status:'tax_rule_review', methodology:'India CTC-to-in-hand scenario using basic pay, HRA, PF, professional tax and the modeled tax-regime assumptions implemented by the calculator.', limitations:['This is not official payroll or ITR computation.','Employer salary structure, state professional tax, PF treatment and tax rules can change the result.'], sources:[], currentYear:2026 },
  { slug:'salary-hike-calculator', status:'custom_estimate', methodology:'Projects the nominal and inflation-adjusted effect of an initial salary raise plus future annual salary growth.', limitations:['No complete payroll tax engine is implemented.','Returns and inflation are user assumptions, not forecasts.'], sources:[], currentYear:2026 },
  { slug:'salary-negotiation-calculator', status:'custom_estimate', methodology:'Compensation comparison using user-entered salary, bonus, equity, benefits and cost-of-living assumptions.', limitations:['Market compensation varies by role, location, company and experience.','Negotiation outcomes are not predictable from a formula.'], sources:[], currentYear:2026 },
  { slug:'salary-negotiation-lifetime-calculator', status:'custom_estimate', methodology:'Long-term compensation scenario comparing salary paths and modeled raises over time.', limitations:['Career changes, unemployment, taxes, equity vesting and market conditions are simplified.'], sources:[], currentYear:2026 },
  { slug:'savings-goal-calculator', status:'custom_estimate', methodology:'Future-value and required-contribution scenario for a savings target using user-entered return and time assumptions.', limitations:['Investment returns are assumptions and are not guaranteed.','Taxes, fees and volatility are simplified or excluded.'], sources:[], currentYear:2026 },
  { slug:'savings-goal-planner-calculator', status:'custom_estimate', methodology:'Goal-planning scenario using current savings, target amount, contribution and assumed growth.', limitations:['Actual account yields and investment returns vary.','The result is not a guaranteed savings schedule.'], sources:[], currentYear:2026 },
  { slug:'savings-rate-calculator', status:'reviewed', methodology:'Calculates savings rate from income and savings inputs and compares the result with user-selected planning targets.', limitations:['Savings-rate benchmarks are planning heuristics, not universal financial-health thresholds.'], sources:[], currentYear:2026 },
  { slug:'savings-rate-fire-calculator', status:'custom_estimate', methodology:'FIRE planning scenario connecting savings rate, spending, portfolio assumptions and time to financial independence.', limitations:['Withdrawal rates and investment returns are assumptions; sequence risk and taxes are simplified.'], sources:[], currentYear:2026 },
  { slug:'sba-loan-calculator', status:'formula_review', methodology:'Loan amortization plus a simplified DSCR scenario for an SBA-style business loan using user-entered assumptions.', limitations:['DSCR is not an SBA eligibility test.','SBA program limits, guarantees, fees, permitted uses and lender underwriting vary.'], sources:[{title:'SBA — 7(a) loans',url:`${SBA}/funding-programs/loans/7a-loans`}], currentYear:2026 },
  { slug:'scholarship-financial-aid-calculator', status:'needs_manual_review', methodology:'Educational financial-aid scenario based on entered costs and aid assumptions.', limitations:['It does not calculate the official FAFSA Student Aid Index, Pell eligibility or institutional aid award.'], sources:[], currentYear:2026 },
  { slug:'self-employed-retirement-plan-comparison', status:'tax_rule_review', methodology:'Scenario comparison of retirement-plan contribution capacity for self-employed users.', limitations:['Plan eligibility, compensation definitions, aggregation rules and business structure affect actual contributions.'], sources:[{title:'IRS — Retirement plans for small business',url:`${IRS}/retirement-plans`}], currentYear:2026 },
  { slug:'self-employment-tax-calculator', status:'tax_rule_review', methodology:'Simplified federal self-employment tax estimate using the 2026 Social Security wage base and Medicare rates.', limitations:['Actual Schedule SE calculations can include deductions, additional Medicare tax and other income considerations.'], sources:[{title:'IRS — Topic 751, Social Security and Medicare withholding rates',url:`${IRS}/taxtopics/tc751`}], currentYear:2026 },
  { slug:'senior-citizen-savings-vs-fd-calculator', status:'custom_estimate', methodology:'India-focused comparison of senior-citizen fixed-deposit and savings scenarios using entered rates and tenure.', limitations:['Bank rates, tax treatment, premature-withdrawal rules and product eligibility vary.'], sources:[], currentYear:2026 },
  { slug:'sep-ira-calculator', status:'tax_rule_review', methodology:'Simplified SEP-IRA contribution scenario using the 2026 $72,000 ceiling and an approximate sole-proprietor contribution rate.', limitations:['The exact self-employed SEP calculation requires the IRS worksheet and compensation/SE-tax details.','Tax savings use the entered marginal-rate assumption.'], sources:[{title:'IRS — SEP contribution limits',url:`${IRS}/retirement-plans/plan-participant-employee/sep-contribution-limits-including-grandfathered-sarseps`}], currentYear:2026 },
  { slug:'sep-ira-vs-solo-401k-calculator', status:'tax_rule_review', methodology:'Scenario comparison of SEP-IRA and Solo 401(k) contribution capacity under current retirement-plan limits.', limitations:['Business structure, compensation, aggregation and catch-up rules can change the result.'], sources:[{title:'IRS — 401(k) contribution limits',url:`${IRS}/retirement-plans/plan-participant-employee/retirement-topics-401k-and-profit-sharing-plan-contribution-limits`}], currentYear:2026 },
  { slug:'series-ee-bond-calculator', status:'formula_review', methodology:'Simplified Series EE scenario using the current 2026 fixed rate as an illustrative rate for new issues; historical issue-date values require actual Treasury rate history.', limitations:['The calculator is not an exact redemption-value engine for every historical EE bond.','Federal tax depends on actual interest and taxpayer circumstances.'], sources:[{title:'TreasuryDirect — EE Bonds',url:`${TREASURY}/savings-bonds/ee-bonds/`}], currentYear:2026 },
  { slug:'shareholder-loan-calculator', status:'tax_rule_review', methodology:'Interest and tax scenario for a shareholder/corporate loan using an entered AFR and tax assumptions.', limitations:['Actual below-market-loan rules, compensation/dividend characterization and documentation require case-specific tax analysis.'], sources:[{title:'IRS — Applicable Federal Rates',url:`${IRS}/applicable-federal-rates`}], currentYear:2026 },
  { slug:'side-hustle-breakeven-calculator', status:'reviewed', methodology:'Contribution-margin break-even calculation from startup costs, recurring expenses, unit economics and opportunity cost.', limitations:['Demand, taxes and operating variability are not forecast.'], sources:[], currentYear:2026 },
  { slug:'simple-interest-calculator', status:'reviewed', methodology:'Simple-interest calculation using principal, annual rate and time.', limitations:['Simple interest does not model compounding.'], sources:[], currentYear:2026 },
  { slug:'sip-calculator', status:'custom_estimate', methodology:'India SIP future-value scenario using monthly contribution, assumed annual return and time horizon.', limitations:['Returns are assumptions and not guaranteed; actual mutual-fund performance, expenses and taxes vary.'], sources:[], currentYear:2026 },
  { slug:'sip-vs-bonds-calculator', status:'custom_estimate', methodology:'India scenario comparison of SIP growth versus a fixed-income return assumption.', limitations:['Market returns, bond yields, taxation and risk differ by product and time period.'], sources:[], currentYear:2026 },
  { slug:'sip-vs-crypto-calculator', status:'tax_rule_review', methodology:'India scenario comparison between SIP investing and crypto investing using entered return and tax assumptions.', limitations:['Crypto tax treatment and TDS rules depend on the applicable law and transaction facts; investment returns are highly uncertain.'], sources:[{title:'Income Tax Department — Virtual Digital Assets',url:'https://www.incometax.gov.in/'}], currentYear:2026 },
  { slug:'sip-vs-endowment-calculator', status:'custom_estimate', methodology:'India scenario comparison between SIP investing and an endowment-style insurance savings assumption.', limitations:['Actual insurance premiums, bonuses, surrender values, tax treatment and policy terms vary by product.'], sources:[], currentYear:2026 },
]

export const FINANCE_BATCH_13_SLUGS = FINANCE_BATCH_13.map(p => p.slug)
