export type FinanceBatch07Status = 'reviewed' | 'tax_rule_review' | 'custom_estimate' | 'needs_manual_review' | 'formula_review'

export interface FinanceBatch07Profile {
  slug: string
  status: FinanceBatch07Status
  methodology: string
  limitations: string[]
  sources: Array<{ title: string; url: string }>
  currentYear?: number
}

const IRS = 'https://www.irs.gov'
const GOVUK = 'https://www.gov.uk'

export const FINANCE_BATCH_07: FinanceBatch07Profile[] = [
  { slug:'income-replacement-ratio-calculator', status:'custom_estimate', methodology:'Retirement-income replacement scenario using projected retirement income divided by pre-retirement income.', limitations:['There is no universal replacement-rate target.','Social Security, pensions, taxes, healthcare and spending patterns vary.','A planning ratio is not a retirement-readiness guarantee.'], sources:[{title:'Social Security Retirement Benefits',url:'https://www.ssa.gov/retirement'}], currentYear:2026 },
  { slug:'income-tax-calculator', status:'needs_manual_review', methodology:'India FY 2026-27 new/old regime estimate using the calculator implementation and rupee-denominated inputs.', limitations:['The current implementation requires a dedicated 87A rebate and special-rate review before being treated as filing-grade.','It does not reproduce every income head, capital-gain rate, surcharge/marginal-relief rule or ITR form.'], sources:[{title:'Income Tax Department — AY 2026-27 rates and rebate',url:'https://www.incometax.gov.in/iec/foportal/help/all-topics/e-filing-services/file-itr-2-online'}], currentYear:2026 },
  { slug:'income-tax-estimator', status:'tax_rule_review', methodology:'US federal tax planning estimate across the income categories supported by the calculator.', limitations:['Not a Form 1040 replacement.','State taxes, credits, special-rate income and filing-specific rules can change the result.'], sources:[{title:'IRS Tax Information',url:IRS}], currentYear:2026 },
  { slug:'index-fund-fee-calculator', status:'reviewed', methodology:'Projects the effect of recurring expense ratios on investment growth.', limitations:['Actual returns and fund expenses vary.','Taxes and tracking differences may materially affect outcomes.'], sources:[{title:'SEC — Mutual Funds and ETFs',url:'https://www.investor.gov/introduction-investing/investing-basics/glossary/mutual-fund'}], currentYear:2026 },
  { slug:'index-fund-vs-etf-calculator', status:'custom_estimate', methodology:'Scenario comparison of index mutual funds and ETFs using user-entered returns, fees and tax assumptions.', limitations:['Index mutual funds and ETFs can have different tax, trading and tracking characteristics.','Not an investment recommendation.'], sources:[{title:'SEC — Mutual Funds and ETFs',url:'https://www.investor.gov/introduction-investing/investing-basics/glossary/exchange-traded-fund-etf'}], currentYear:2026 },
  { slug:'inflation-calculator', status:'reviewed', methodology:'Uses historical CPI observations to compare purchasing power across dates.', limitations:['Historical CPI is not a forecast of future inflation.','Different households experience different inflation baskets.'], sources:[{title:'U.S. Bureau of Labor Statistics — CPI',url:'https://www.bls.gov/cpi/'}], currentYear:2026 },
  { slug:'inflation-impact-calculator', status:'custom_estimate', methodology:'Projects purchasing-power changes under a user-entered inflation assumption.', limitations:['Future inflation is uncertain.','The scenario is not a market or Federal Reserve forecast.'], sources:[{title:'Federal Reserve — Inflation',url:'https://www.federalreserve.gov/faqs/economy_14400.htm'}], currentYear:2026 },
  { slug:'inflation-protected-bonds-vs-stocks-calculator', status:'custom_estimate', methodology:'Scenario comparison of inflation-protected bonds and stocks under user-entered return, inflation and horizon assumptions.', limitations:['Returns are hypothetical.','TIPS and equities have different duration, liquidity, tax and volatility characteristics.'], sources:[{title:'Treasury — TIPS',url:'https://www.treasurydirect.gov/marketable-securities/tips/'}], currentYear:2026 },
  { slug:'inherited-ira-calculator', status:'tax_rule_review', methodology:'Inherited-IRA distribution scenario under beneficiary and 10-year-rule assumptions.', limitations:['Beneficiary category and owner death date affect distribution rules.','Eligible designated beneficiaries can have different life-expectancy rules.','The calculator is not a substitute for Publication 590-B or custodian guidance.'], sources:[{title:'IRS — RMD FAQs',url:`${IRS}/retirement-plans/retirement-plan-and-ira-required-minimum-distributions-faqs`},{title:'IRS Publication 590-B',url:`${IRS}/publications/p590b`}], currentYear:2026 },
  { slug:'insurance-by-life-stage-calculator', status:'custom_estimate', methodology:'Life-stage planning scenario for insurance needs based on user-entered liabilities, dependents and income.', limitations:['Insurance needs are highly individual.','Premiums and underwriting cannot be predicted from a generic model.'], sources:[{title:'NAIC — Life Insurance',url:'https://content.naic.org/consumer/life-insurance'}], currentYear:2026 },
  { slug:'interest-rate-calculator', status:'reviewed', methodology:'Calculates the implied interest rate from principal, payment, term and compounding assumptions.', limitations:['Fees and irregular payments can change the effective cost.','The result is mathematical, not a lender quote.'], sources:[{title:'CFPB — APR and loan costs',url:'https://www.consumerfinance.gov/consumer-tools/mortgages/'}], currentYear:2026 },
  { slug:'investment-fee-drag-calculator', status:'reviewed', methodology:'Projects the long-term value difference caused by recurring investment fees.', limitations:['Actual returns, taxes and fee schedules vary.','It does not predict fund performance.'], sources:[{title:'SEC — Investor Fees and Expenses',url:'https://www.investor.gov/financial-tools-calculators/calculators/fees-expenses'}], currentYear:2026 },
  { slug:'investment-property-depreciation-calculator', status:'tax_rule_review', methodology:'Simplified rental-property depreciation scenario based on depreciable basis and recovery assumptions.', limitations:['Actual depreciation depends on property classification, placed-in-service date, land allocation, conventions and applicable tax law.','Not a tax-return calculation.'], sources:[{title:'IRS Publication 946',url:`${IRS}/publications/p946`}], currentYear:2026 },
  { slug:'investment-property-leverage-calculator', status:'custom_estimate', methodology:'Compares leveraged property scenarios using user-entered debt, appreciation, rent and expense assumptions.', limitations:['Leverage magnifies gains and losses.','Taxes, vacancies, maintenance, financing costs and property-specific risks can materially change returns.'], sources:[{title:'SEC — Investor Bulletin: Real Estate',url:'https://www.investor.gov/'}], currentYear:2026 },
  { slug:'invoice-calculator', status:'reviewed', methodology:'Adds line items, discounts and taxes to calculate an invoice total.', limitations:['Tax treatment depends on jurisdiction and supply classification.','It does not determine whether a transaction is taxable.'], sources:[], currentYear:2026 },
  { slug:'irs-installment-agreement-calculator', status:'tax_rule_review', methodology:'Payment-plan scenario using user-entered tax debt, payment and interest assumptions.', limitations:['IRS interest and penalty rates can change quarterly.','Actual eligibility, fees and collection status depend on the taxpayer and agreement type.'], sources:[{title:'IRS — Payment Plans',url:`${IRS}/payments/payment-plans-installment-agreements`},{title:'IRS — Interest Rates',url:`${IRS}/newsroom/interest-rates-remain-unchanged-for-the-third-quarter-of-2026`}], currentYear:2026 },
  { slug:'isa-calculator', status:'tax_rule_review', methodology:'UK ISA growth projection with the current annual ISA subscription limit and Lifetime ISA bonus assumptions.', limitations:['ISA rules differ by type.','The overall 2026-27 ISA limit is £20,000; a future Cash ISA reform is scheduled for April 2027.','Investment returns are hypothetical.'], sources:[{title:'GOV.UK — Individual Savings Accounts',url:`${GOVUK}/individual-savings-accounts/overview`},{title:'GOV.UK — ISA reform from April 2027',url:`${GOVUK}/government/publications/fiscal-events-2026-factsheets/isa-reform-2027-anti-circumvention-rules-factsheet`}], currentYear:2026 },
  { slug:'isa-vs-sipp-uk-calculator', status:'tax_rule_review', methodology:'UK retirement-planning comparison between ISA and SIPP scenarios using user-entered contributions, growth and withdrawal assumptions.', limitations:['Tax relief and withdrawal treatment depend on individual circumstances and pension rules.','Not financial advice.'], sources:[{title:'GOV.UK — Individual Savings Accounts',url:`${GOVUK}/individual-savings-accounts/overview`},{title:'GOV.UK — Pension tax relief',url:`${GOVUK}/tax-on-pension/pension-tax-relief`}], currentYear:2026 },
  { slug:'k1-income-tax-calculator', status:'tax_rule_review', methodology:'Simplified US K-1 income-tax scenario for partnership or S-corporation income supported by the calculator.', limitations:['K-1 taxation depends on entity type, basis, passive-activity status, self-employment tax, QBI and other facts.','Not a Schedule K-1 or Form 1040 replacement.'], sources:[{title:'IRS — Partnerships',url:`${IRS}/businesses/partnerships`},{title:'IRS — S corporations',url:`${IRS}/businesses/small-businesses-self-employed/s-corporations`}], currentYear:2026 },
  { slug:'k1-passive-loss-calculator', status:'tax_rule_review', methodology:'Simplified passive-activity-loss scenario under IRC Section 469 assumptions.', limitations:['Real-estate-professional status, material participation, basis and at-risk rules can change deductibility.','Not a complete Form 8582 calculation.'], sources:[{title:'IRS — Passive Activity Losses',url:`${IRS}/publications/p925`}], currentYear:2026 },
  { slug:'lease-vs-buy-calculator', status:'custom_estimate', methodology:'Compares lease and purchase cash flows over a user-selected vehicle horizon.', limitations:['Lease money factors, residuals, taxes, fees and purchase terms vary by offer.','Vehicle depreciation and resale value are estimates.'], sources:[{title:'CFPB — Auto Loans',url:'https://www.consumerfinance.gov/consumer-tools/auto-loans/'}], currentYear:2026 },
  { slug:'leveraged-etf-decay-calculator', status:'custom_estimate', methodology:'Illustrates path-dependent leveraged-ETF compounding under user-entered daily return sequences or volatility assumptions.', limitations:['It is an educational scenario model, not a forecast.','Leveraged ETFs typically reset daily and outcomes depend heavily on path and volatility.'], sources:[{title:'SEC — Leveraged and Inverse ETFs',url:'https://www.investor.gov/introduction-investing/investing-basics/glossary/leveraged-etf'}], currentYear:2026 },
  { slug:'life-insurance-needs-calculator', status:'custom_estimate', methodology:'Income-replacement and obligation-based life-insurance planning estimate.', limitations:['Premiums shown are not insurer quotes.','Actual need depends on dependents, debts, assets, taxes and survivor goals.'], sources:[{title:'NAIC — Life Insurance',url:'https://content.naic.org/consumer/life-insurance'}], currentYear:2026 },
  { slug:'loan-comparison-calculator', status:'reviewed', methodology:'Compares amortizing loan offers by payment, interest and total cost under user-entered terms.', limitations:['APR and fees depend on the lender and loan type.','Actual payment can differ because of taxes, insurance and other charges.'], sources:[{title:'CFPB — Loan and mortgage resources',url:'https://www.consumerfinance.gov/consumer-tools/'}], currentYear:2026 },
  { slug:'loan-origination-fee-calculator', status:'formula_review', methodology:'Compares upfront origination fees against rate/payment differences over a chosen holding period.', limitations:['APR disclosure rules and fee treatment vary by loan type.','The break-even result depends on how long the borrower keeps the loan.'], sources:[{title:'CFPB — Mortgage closing costs',url:'https://www.consumerfinance.gov/owning-a-home/closing-costs/'}], currentYear:2026 },
]
