import type { FinanceQualityProfile } from './finance-quality'

/** Explicit placeholders for Finance routes that have not yet received a manual quality review.
 * These records are intentionally conservative: no sources or review dates are fabricated.
 */
export const FINANCE_UNREVIEWED: FinanceQualityProfile[] = [
  {
    slug: 'gold-vs-stocks-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'government-bond-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'gratuity-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'gst-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'hdhp-vs-traditional-insurance-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'health-insurance-deductible-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'health-insurance-subsidy-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'heloc-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'heloc-credit-line-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'home-affordability-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'home-equity-loan-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'home-equity-vs-personal-loan',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'home-loan-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'home-office-deduction-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'house-flip-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'house-hacking-roi-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'hra-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'hsa-investment-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'hsa-projection-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'hsa-triple-tax-growth-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'hsa-vs-401k-priority-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'hsa-vs-fsa-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'i-bond-ladder-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'i-bonds-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'i-bonds-vs-tips-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'paycheck-contribution-optimizer',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'tax-loss-harvesting-portfolio-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'tax-withholding-w4-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'taxable-vs-roth-vs-traditional-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'term-vs-ulip-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'term-vs-whole-life-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'tip-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'tips-vs-nominal-bonds-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'traditional-ira-vs-taxable-account-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'treasury-bill-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'trust-fund-growth-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'tsp-vs-401k-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'uk-buy-to-let-vs-stocks-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'uk-fixed-rate-vs-tracker-mortgage-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'uk-help-to-buy-vs-lisa-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'uk-income-tax-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'uk-lifetime-isa-vs-sipp-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'uk-pension-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'uk-pension-drawdown-vs-annuity-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'uk-pension-vs-isa-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'uk-premium-bonds-vs-cash-isa-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'uk-remortgage-vs-invest-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'uk-stamp-duty-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'uk-stocks-vs-bonds-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
  {
    slug: 'umbrella-insurance-calculator',
    status: 'needs_manual_review',
    methodology: 'Quality review pending; the route is registered but its calculation, legal rules, sources, and limitations have not yet been manually validated.',
    limitations: ['Manual quality review is still required before this tool can be treated as reviewed.', 'No current-law or medical claim should be inferred from this placeholder profile.'],
    sources: [],
  },
]
