import type { FinanceQualityProfile } from './finance-quality'

const IRS = 'https://www.irs.gov'
const SSA = 'https://www.ssa.gov'
const FSA = 'https://studentaid.gov'

export const FINANCE_BATCH_15: FinanceQualityProfile[] = [
  { slug:'ssdi-benefit-calculator', status:'reviewed', methodology:'Educational SSDI PIA scenario using a user-entered AIME estimate and a separate simplified work-credit screen.', limitations:['SSA determines insured status, disability, AIME and the final benefit from the official record.','The work-credit screen does not reproduce every recent-work requirement or special rule.'], sources:[{title:'SSA — Disability eligibility',url:`${SSA}/disability/eligibility`},{title:'SSA — 2026 Red Book amounts',url:`${SSA}/redbook/newfor2026.htm`},{title:'SSA — Retirement benefit calculation',url:`${SSA}/oact/ProgData/retirebenefit2.html`}], currentYear:2026 },
  { slug:'startup-equity-value-calculator', status:'custom_estimate', methodology:'Scenario value of startup equity after compounded dilution and a hypothetical exit probability.', limitations:['Private-company valuation, liquidation preferences, option terms, taxes and actual exit probability are simplified.'], sources:[], currentYear:2026 },
  { slug:'state-estate-tax-calculator', status:'reviewed', methodology:'Simplified federal and Massachusetts estate-tax screening model.', limitations:['State estate-tax laws differ and change.','The federal calculation does not reproduce Form 706 or all deductions, credits, portability and prior gifts.'], sources:[{title:'IRS — Estate tax',url:`${IRS}/businesses/small-businesses-self-employed/estate-tax`}], currentYear:2026 },
  { slug:'state-tax-relocation-calculator', status:'custom_estimate', methodology:'Scenario comparison of state income-tax effects when relocating.', limitations:['Domicile, sourcing, residency, local taxes and filing rules can be fact-specific.','State rates are simplified assumptions.'], sources:[{title:'IRS — Estate tax',url:'https://www.irs.gov/businesses/small-businesses-self-employed/estate-tax'}], currentYear:2026 },
  { slug:'step-up-sip-calculator', status:'custom_estimate', methodology:'India SIP projection with periodic contribution increases.', limitations:['Market returns are assumptions and not guaranteed.','Tax, fund expenses and cash-flow timing are simplified.'], sources:[], currentYear:2026 },
  { slug:'stock-option-tax-calculator', status:'tax_rule_review', methodology:'Simplified ISO/NSO tax scenario using entered spread, tax rates and holding assumptions.', limitations:['ISO AMT, qualifying dispositions, payroll taxes, holding periods and state taxes require detailed facts.','The calculator is not a Form 3921/3922 or tax-return engine.'], sources:[{title:'IRS — Incentive stock options',url:`${IRS}/taxtopics/tc427`}], currentYear:2026 },
  { slug:'stock-option-vesting-calculator', status:'custom_estimate', methodology:'Equity vesting schedule projection from grant size, vesting period and cliff assumptions.', limitations:['Actual grants can include acceleration, forfeiture, refresh grants and company-specific terms.'], sources:[], currentYear:2026 },
  { slug:'stock-profit-calculator', status:'reviewed', methodology:'Arithmetic profit, return and cost-basis scenario for a stock position.', limitations:['Taxes, fees, dividends and corporate actions may change actual realized results.'], sources:[], currentYear:2026 },
  { slug:'stock-split-calculator', status:'reviewed', methodology:'Adjusts share count and per-share price for a stock split while preserving aggregate market value immediately before the split.', limitations:['A split itself does not create economic value; market prices can move after the event.'], sources:[], currentYear:2026 },
  { slug:'stocks-shares-isa-vs-cash-isa-calculator', status:'tax_rule_review', methodology:'UK scenario comparing investment ISA and Cash ISA outcomes under user-entered return and interest assumptions.', limitations:['ISA rules and allowances can change; investment returns are not guaranteed.'], sources:[{title:'GOV.UK — Individual Savings Accounts',url:'https://www.gov.uk/individual-savings-accounts/overview'}], currentYear:2026 },
  { slug:'student-loan-calculator', status:'reviewed', methodology:'Fixed-rate student-loan amortization scenario using user-entered balance, interest rate, required payment and optional extra payment.', limitations:['Federal repayment-plan eligibility, forgiveness, capitalization, servicer rules and loan-specific protections are not fully modeled.','The calculator is a payment/interest scenario, not a federal benefit or eligibility determination.'], sources:[{title:'Federal Student Aid',url:FSA}], currentYear:2026 },
  { slug:'student-loan-forbearance-calculator', status:'reviewed', methodology:'Scenario for interest accruing during a payment pause with an explicit capitalization assumption and remaining-term payment model.', limitations:['Capitalization treatment depends on loan type and the reason for forbearance.','The calculator does not determine eligibility for a specific federal pause or repayment plan.'], sources:[{title:'Federal Student Aid — Forbearance definition',url:`${FSA}/articles/financial-aid-dictionary/`},{title:'Federal Student Aid — Preparing for payments',url:`${FSA}/articles/prepare-for-payments/`}], currentYear:2026 },
  { slug:'student-loan-forgiveness-calculator', status:'needs_manual_review', methodology:'Legacy educational forgiveness scenario; current federal repayment and forgiveness eligibility require plan-specific rules.', limitations:['SAVE is not a current repayment option and its legacy formula is not presented as current guidance.','PSLF and IDR eligibility require loan, employer, payment-history and program-specific verification.'], sources:[{title:'Federal Student Aid',url:FSA}], currentYear:2026 },
  { slug:'student-loan-refinance-calculator', status:'reviewed', methodology:'Fixed-rate amortization comparison between an existing student loan and a proposed private refinance, including an explicit refinance-fee input and break-even calculation.', limitations:['Refinancing federal loans into private debt can eliminate federal protections.','Actual APR, fees, term, underwriting and lender conditions vary.','Break-even is based only on the entered fee and modeled monthly savings.'], sources:[{title:'Federal Student Aid',url:FSA}], currentYear:2026 },
  { slug:'student-loan-vs-invest-calculator', status:'custom_estimate', methodology:'Scenario comparison of guaranteed interest savings from debt repayment versus assumed investment growth.', limitations:['Investment returns are uncertain and taxes, loan forgiveness, liquidity and risk tolerance are simplified.'], sources:[], currentYear:2026 },
  { slug:'sukanya-samriddhi-vs-ppf-calculator', status:'tax_rule_review', methodology:'India comparison of Sukanya Samriddhi and PPF using notified-rate and contribution assumptions.', limitations:['Government small-savings rates are notified periodically and eligibility is scheme-specific.','Tax treatment and account rules must be verified for the applicable period.'], sources:[{title:'Department of Economic Affairs — Small Savings',url:'https://dea.gov.in/budget-division/475'}], currentYear:2026 },
  { slug:'swp-calculator', status:'custom_estimate', methodology:'India systematic-withdrawal projection from a starting corpus, withdrawal amount and assumed return.', limitations:['Mutual-fund returns are not guaranteed and sequence of returns can materially change sustainability.','Taxation is simplified.'], sources:[], currentYear:2026 },
  { slug:'syndication-k1-tax-calculator', status:'tax_rule_review', methodology:'Simplified pass-through K-1 income scenario for a real-estate syndication.', limitations:['Passive-activity rules, basis, at-risk limits, depreciation, NIIT and state taxes are not fully modeled.'], sources:[{title:'IRS — Passive activity losses',url:`${IRS}/forms-pubs/about-publication-925`}], currentYear:2026 },
  { slug:'tax-bracket-calculator', status:'tax_rule_review', methodology:'2026 federal ordinary-income bracket calculation using filing status and deduction assumptions.', limitations:['Does not reproduce a complete federal return, credits, special-rate income, AMT, NIIT or state taxes.'], sources:[{title:'IRS — Tax inflation adjustments for 2026',url:`${IRS}/newsroom/irs-releases-tax-inflation-adjustments-for-tax-year-2026`}], currentYear:2026 },
  { slug:'tax-bracket-optimizer', status:'tax_rule_review', methodology:'Simplified 2026 federal bracket and capital-gain scenario showing marginal-rate room.', limitations:['Optimization does not model every deduction, credit, special-rate item or filing-status rule.','Not tax advice.'], sources:[{title:'IRS — Tax inflation adjustments for 2026',url:`${IRS}/newsroom/irs-releases-tax-inflation-adjustments-for-tax-year-2026`}], currentYear:2026 },
  { slug:'tax-deferral-benefit-calculator', status:'custom_estimate', methodology:'Scenario comparison of tax-deferred versus taxable/Roth growth under user-entered rates and returns.', limitations:['Future tax rates, account rules, contribution eligibility and investment returns are assumptions.'], sources:[], currentYear:2026 },
  { slug:'tax-efficient-withdrawal-calculator', status:'custom_estimate', methodology:'Retirement withdrawal-order scenario across taxable, traditional and Roth balances.', limitations:['Actual optimal sequencing depends on annual taxable income, RMDs, Roth basis, ACA/IRMAA effects, state tax and other income.'], sources:[{title:'IRS — Required minimum distributions',url:`${IRS}/retirement-plans/plan-participant-employee/retirement-topics-required-minimum-distributions-rmds`}], currentYear:2026 },
  { slug:'tax-exempt-bond-comparison-calculator', status:'tax_rule_review', methodology:'Tax-equivalent-yield comparison for municipal, corporate and Treasury interest using entered federal/state rates.', limitations:['Actual municipal-bond tax treatment depends on issue, AMT status, state residency and other facts.','Yield and credit risk are market-dependent.'], sources:[{title:'IRS — Tax-exempt interest',url:`${IRS}/taxtopics/tc403`}], currentYear:2026 },
  { slug:'tax-free-savings-optimizer', status:'tax_rule_review', methodology:'Scenario prioritization of tax-advantaged accounts based on income, age and user-entered marginal rate.', limitations:['Eligibility, employer matches, contribution limits and account rules vary.','The output is a planning heuristic, not personalized financial advice.'], sources:[{title:'IRS — Retirement plans',url:`${IRS}/retirement-plans`}], currentYear:2026 },
  { slug:'tax-loss-harvesting-calculator', status:'tax_rule_review', methodology:'Scenario estimate of tax savings from realizing investment losses against capital gains and eligible income, subject to applicable limits.', limitations:['Wash-sale rules, basis, carryovers, short/long-term netting and state taxes are simplified.','The result is not a tax-return calculation.'], sources:[{title:'IRS — Capital gains and losses',url:`${IRS}/taxtopics/tc409`}], currentYear:2026 },
]

export const FINANCE_BATCH_15_SLUGS = FINANCE_BATCH_15.map(p => p.slug)
