export type HealthEvidenceStatus = 'reviewed' | 'verified_formula' | 'custom_estimate' | 'needs_formula_review' | 'needs_manual_review' | 'critical_logic_issue' | 'redirect_only'

export type HealthQualityProfile = {
  slug: string
  status: HealthEvidenceStatus
  title: string
  canonicalPath: string
  requiresManualReview: boolean
}

/** Canonical health quality registry. Generated from the route inventory and health audit registries. */
export const HEALTH_QUALITY_REGISTRY: Record<string, HealthQualityProfile> = {
  'pregnancy-due-date-calculator': { slug: 'pregnancy-due-date-calculator', status: 'redirect_only', title: 'Pregnancy Due Date', canonicalPath: '/calculators/health/pregnancy-due-date-calculator', requiresManualReview: true },
  'age-calculator': { slug: 'age-calculator', status: 'reviewed', title: 'Age', canonicalPath: '/calculators/health/age-calculator', requiresManualReview: false },
  'air-quality-health-calculator': { slug: 'air-quality-health-calculator', status: 'reviewed', title: 'Air Quality Health', canonicalPath: '/calculators/health/air-quality-health-calculator', requiresManualReview: false },
  'alcohol-calorie-calculator': { slug: 'alcohol-calorie-calculator', status: 'reviewed', title: 'Alcohol Calorie', canonicalPath: '/calculators/health/alcohol-calorie-calculator', requiresManualReview: false },
  'alcohol-metabolism-calculator': { slug: 'alcohol-metabolism-calculator', status: 'reviewed', title: 'Alcohol Metabolism', canonicalPath: '/calculators/health/alcohol-metabolism-calculator', requiresManualReview: false },
  'altitude-sickness-calculator': { slug: 'altitude-sickness-calculator', status: 'reviewed', title: 'Altitude Sickness', canonicalPath: '/calculators/health/altitude-sickness-calculator', requiresManualReview: false },
  'ankle-brachial-index-calculator': { slug: 'ankle-brachial-index-calculator', status: 'reviewed', title: 'Ankle Brachial Index', canonicalPath: '/calculators/health/ankle-brachial-index-calculator', requiresManualReview: false },
  'army-body-fat-calculator': { slug: 'army-body-fat-calculator', status: 'needs_manual_review', title: 'Army Body Fat', canonicalPath: '/calculators/health/army-body-fat-calculator', requiresManualReview: true },
  'athlete-heart-rate-calculator': { slug: 'athlete-heart-rate-calculator', status: 'reviewed', title: 'Athlete Heart Rate', canonicalPath: '/calculators/health/athlete-heart-rate-calculator', requiresManualReview: false },
  'athletic-performance-calculator': { slug: 'athletic-performance-calculator', status: 'needs_manual_review', title: 'Athletic Performance', canonicalPath: '/calculators/health/athletic-performance-calculator', requiresManualReview: true },
  'bac-calculator': { slug: 'bac-calculator', status: 'reviewed', title: 'Bac', canonicalPath: '/calculators/health/bac-calculator', requiresManualReview: false },
  'blood-pressure-calculator': { slug: 'blood-pressure-calculator', status: 'reviewed', title: 'Blood Pressure', canonicalPath: '/calculators/health/blood-pressure-calculator', requiresManualReview: false },
  'blue-light-exposure-calculator': { slug: 'blue-light-exposure-calculator', status: 'needs_manual_review', title: 'Blue Light Exposure', canonicalPath: '/calculators/health/blue-light-exposure-calculator', requiresManualReview: true },
  'bmi-calculator': { slug: 'bmi-calculator', status: 'reviewed', title: 'Bmi', canonicalPath: '/calculators/health/bmi-calculator', requiresManualReview: false },
  'bmi-for-children-calculator': { slug: 'bmi-for-children-calculator', status: 'reviewed', title: 'Bmi For Children', canonicalPath: '/calculators/health/bmi-for-children-calculator', requiresManualReview: false },
  'bmr-calculator': { slug: 'bmr-calculator', status: 'reviewed', title: 'Bmr', canonicalPath: '/calculators/health/bmr-calculator', requiresManualReview: false },
  'body-age-calculator': { slug: 'body-age-calculator', status: 'needs_manual_review', title: 'Body Age', canonicalPath: '/calculators/health/body-age-calculator', requiresManualReview: true },
  'body-fat-calculator': { slug: 'body-fat-calculator', status: 'needs_manual_review', title: 'Body Fat', canonicalPath: '/calculators/health/body-fat-calculator', requiresManualReview: true },
  'body-recomposition-calculator': { slug: 'body-recomposition-calculator', status: 'needs_manual_review', title: 'Body Recomposition', canonicalPath: '/calculators/health/body-recomposition-calculator', requiresManualReview: true },
  'body-surface-area-calculator': { slug: 'body-surface-area-calculator', status: 'reviewed', title: 'Body Surface Area', canonicalPath: '/calculators/health/body-surface-area-calculator', requiresManualReview: false },
  'bone-density-risk-calculator': { slug: 'bone-density-risk-calculator', status: 'needs_manual_review', title: 'Bone Density Risk', canonicalPath: '/calculators/health/bone-density-risk-calculator', requiresManualReview: true },
  'bone-mineral-density-calculator': { slug: 'bone-mineral-density-calculator', status: 'reviewed', title: 'Bone Mineral Density', canonicalPath: '/calculators/health/bone-mineral-density-calculator', requiresManualReview: false },
  'breastfeeding-calorie-calculator': { slug: 'breastfeeding-calorie-calculator', status: 'reviewed', title: 'Breastfeeding Calorie', canonicalPath: '/calculators/health/breastfeeding-calorie-calculator', requiresManualReview: false },
  'breathing-exercise-calculator': { slug: 'breathing-exercise-calculator', status: 'needs_manual_review', title: 'Breathing Exercise', canonicalPath: '/calculators/health/breathing-exercise-calculator', requiresManualReview: true },
  'caffeine-half-life-calculator': { slug: 'caffeine-half-life-calculator', status: 'reviewed', title: 'Caffeine Half Life', canonicalPath: '/calculators/health/caffeine-half-life-calculator', requiresManualReview: false },
  'calcium-calculator': { slug: 'calcium-calculator', status: 'reviewed', title: 'Calcium', canonicalPath: '/calculators/health/calcium-calculator', requiresManualReview: false },
  'caloric-needs-calculator': { slug: 'caloric-needs-calculator', status: 'verified_formula', title: 'Caloric Needs', canonicalPath: '/calculators/health/caloric-needs-calculator', requiresManualReview: false },
  'calorie-burned-walking-calculator': { slug: 'calorie-burned-walking-calculator', status: 'needs_formula_review', title: 'Calorie Burned Walking', canonicalPath: '/calculators/health/calorie-burned-walking-calculator', requiresManualReview: true },
  'calorie-calculator': { slug: 'calorie-calculator', status: 'verified_formula', title: 'Calorie', canonicalPath: '/calculators/health/calorie-calculator', requiresManualReview: false },
  'calorie-deficit-calculator': { slug: 'calorie-deficit-calculator', status: 'custom_estimate', title: 'Calorie Deficit', canonicalPath: '/calculators/health/calorie-deficit-calculator', requiresManualReview: false },
  'calories-burned-calculator': { slug: 'calories-burned-calculator', status: 'needs_formula_review', title: 'Calories Burned', canonicalPath: '/calculators/health/calories-burned-calculator', requiresManualReview: true },
  'cardiac-output-calculator': { slug: 'cardiac-output-calculator', status: 'needs_formula_review', title: 'Cardiac Output', canonicalPath: '/calculators/health/cardiac-output-calculator', requiresManualReview: true },
  'cholesterol-calculator': { slug: 'cholesterol-calculator', status: 'needs_formula_review', title: 'Cholesterol', canonicalPath: '/calculators/health/cholesterol-calculator', requiresManualReview: true },
  'ckd-progression-calculator': { slug: 'ckd-progression-calculator', status: 'custom_estimate', title: 'Ckd Progression', canonicalPath: '/calculators/health/ckd-progression-calculator', requiresManualReview: false },
  'cognitive-load-calculator': { slug: 'cognitive-load-calculator', status: 'custom_estimate', title: 'Cognitive Load', canonicalPath: '/calculators/health/cognitive-load-calculator', requiresManualReview: false },
  'cold-exposure-calculator': { slug: 'cold-exposure-calculator', status: 'needs_formula_review', title: 'Cold Exposure', canonicalPath: '/calculators/health/cold-exposure-calculator', requiresManualReview: true },
  'cold-shower-benefits-calculator': { slug: 'cold-shower-benefits-calculator', status: 'custom_estimate', title: 'Cold Shower Benefits', canonicalPath: '/calculators/health/cold-shower-benefits-calculator', requiresManualReview: false },
  'cortisol-stress-calculator': { slug: 'cortisol-stress-calculator', status: 'custom_estimate', title: 'Cortisol Stress', canonicalPath: '/calculators/health/cortisol-stress-calculator', requiresManualReview: false },
  'creatine-dosage-calculator': { slug: 'creatine-dosage-calculator', status: 'needs_formula_review', title: 'Creatine Dosage', canonicalPath: '/calculators/health/creatine-dosage-calculator', requiresManualReview: true },
  'creatinine-clearance-calculator': { slug: 'creatinine-clearance-calculator', status: 'verified_formula', title: 'Creatinine Clearance', canonicalPath: '/calculators/health/creatinine-clearance-calculator', requiresManualReview: false },
  'cycling-calories-calculator': { slug: 'cycling-calories-calculator', status: 'needs_formula_review', title: 'Cycling Calories', canonicalPath: '/calculators/health/cycling-calories-calculator', requiresManualReview: true },
  'dehydration-calculator': { slug: 'dehydration-calculator', status: 'needs_formula_review', title: 'Dehydration', canonicalPath: '/calculators/health/dehydration-calculator', requiresManualReview: true },
  'dehydration-status-calculator': { slug: 'dehydration-status-calculator', status: 'custom_estimate', title: 'Dehydration Status', canonicalPath: '/calculators/health/dehydration-status-calculator', requiresManualReview: false },
  'dental-health-calculator': { slug: 'dental-health-calculator', status: 'custom_estimate', title: 'Dental Health', canonicalPath: '/calculators/health/dental-health-calculator', requiresManualReview: false },
  'diabetes-risk-calculator': { slug: 'diabetes-risk-calculator', status: 'needs_formula_review', title: 'Diabetes Risk', canonicalPath: '/calculators/health/diabetes-risk-calculator', requiresManualReview: true },
  'diet-quality-score-calculator': { slug: 'diet-quality-score-calculator', status: 'custom_estimate', title: 'Diet Quality Score', canonicalPath: '/calculators/health/diet-quality-score-calculator', requiresManualReview: false },
  'dietary-inflammatory-index-calculator': { slug: 'dietary-inflammatory-index-calculator', status: 'custom_estimate', title: 'Dietary Inflammatory Index', canonicalPath: '/calculators/health/dietary-inflammatory-index-calculator', requiresManualReview: false },
  'due-date-calculator': { slug: 'due-date-calculator', status: 'verified_formula', title: 'Due Date', canonicalPath: '/calculators/health/due-date-calculator', requiresManualReview: false },
  'emf-exposure-calculator': { slug: 'emf-exposure-calculator', status: 'custom_estimate', title: 'Emf Exposure', canonicalPath: '/calculators/health/emf-exposure-calculator', requiresManualReview: false },
  'erectile-dysfunction-risk-calculator': { slug: 'erectile-dysfunction-risk-calculator', status: 'custom_estimate', title: 'Erectile Dysfunction Risk', canonicalPath: '/calculators/health/erectile-dysfunction-risk-calculator', requiresManualReview: false },
  'ergonomics-score-calculator': { slug: 'ergonomics-score-calculator', status: 'needs_formula_review', title: 'Ergonomics Score', canonicalPath: '/calculators/health/ergonomics-score-calculator', requiresManualReview: true },
  'exercise-addiction-calculator': { slug: 'exercise-addiction-calculator', status: 'custom_estimate', title: 'Exercise Addiction', canonicalPath: '/calculators/health/exercise-addiction-calculator', requiresManualReview: false },
  'eye-health-calculator': { slug: 'eye-health-calculator', status: 'custom_estimate', title: 'Eye Health', canonicalPath: '/calculators/health/eye-health-calculator', requiresManualReview: false },
  'fasting-window-calculator': { slug: 'fasting-window-calculator', status: 'custom_estimate', title: 'Fasting Window', canonicalPath: '/calculators/health/fasting-window-calculator', requiresManualReview: false },
  'fat-loss-rate-calculator': { slug: 'fat-loss-rate-calculator', status: 'custom_estimate', title: 'Fat Loss Rate', canonicalPath: '/calculators/health/fat-loss-rate-calculator', requiresManualReview: false },
  'fiber-intake-calculator': { slug: 'fiber-intake-calculator', status: 'reviewed', title: 'Fiber Intake', canonicalPath: '/calculators/health/fiber-intake-calculator', requiresManualReview: false },
  'flexibility-calculator': { slug: 'flexibility-calculator', status: 'custom_estimate', title: 'Flexibility', canonicalPath: '/calculators/health/flexibility-calculator', requiresManualReview: false },
  'food-sensitivity-calculator': { slug: 'food-sensitivity-calculator', status: 'custom_estimate', title: 'Food Sensitivity', canonicalPath: '/calculators/health/food-sensitivity-calculator', requiresManualReview: false },
  'frailty-index-calculator': { slug: 'frailty-index-calculator', status: 'reviewed', title: 'Frailty Index', canonicalPath: '/calculators/health/frailty-index-calculator', requiresManualReview: false },
  'genetic-height-calculator': { slug: 'genetic-height-calculator', status: 'needs_formula_review', title: 'Genetic Height', canonicalPath: '/calculators/health/genetic-height-calculator', requiresManualReview: true },
  'gfr-egfr-calculator': { slug: 'gfr-egfr-calculator', status: 'reviewed', title: 'Gfr Egfr', canonicalPath: '/calculators/health/gfr-egfr-calculator', requiresManualReview: false },
  'glycemic-load-calculator': { slug: 'glycemic-load-calculator', status: 'reviewed', title: 'Glycemic Load', canonicalPath: '/calculators/health/glycemic-load-calculator', requiresManualReview: false },
  'gratitude-health-calculator': { slug: 'gratitude-health-calculator', status: 'custom_estimate', title: 'Gratitude Health', canonicalPath: '/calculators/health/gratitude-health-calculator', requiresManualReview: false },
  'grip-strength-age-calculator': { slug: 'grip-strength-age-calculator', status: 'needs_formula_review', title: 'Grip Strength Age', canonicalPath: '/calculators/health/grip-strength-age-calculator', requiresManualReview: true },
  'grip-strength-calculator': { slug: 'grip-strength-calculator', status: 'needs_formula_review', title: 'Grip Strength', canonicalPath: '/calculators/health/grip-strength-calculator', requiresManualReview: true },
  'gut-health-calculator': { slug: 'gut-health-calculator', status: 'custom_estimate', title: 'Gut Health', canonicalPath: '/calculators/health/gut-health-calculator', requiresManualReview: false },
  'hangover-recovery-calculator': { slug: 'hangover-recovery-calculator', status: 'custom_estimate', title: 'Hangover Recovery', canonicalPath: '/calculators/health/hangover-recovery-calculator', requiresManualReview: false },
  'hearing-age-calculator': { slug: 'hearing-age-calculator', status: 'custom_estimate', title: 'Hearing Age', canonicalPath: '/calculators/health/hearing-age-calculator', requiresManualReview: false },
  'heart-age-calculator': { slug: 'heart-age-calculator', status: 'needs_formula_review', title: 'Heart Age', canonicalPath: '/calculators/health/heart-age-calculator', requiresManualReview: true },
  'heart-attack-risk-calculator': { slug: 'heart-attack-risk-calculator', status: 'needs_formula_review', title: 'Heart Attack Risk', canonicalPath: '/calculators/health/heart-attack-risk-calculator', requiresManualReview: true },
  'heart-rate-calculator': { slug: 'heart-rate-calculator', status: 'reviewed', title: 'Heart Rate', canonicalPath: '/calculators/health/heart-rate-calculator', requiresManualReview: false },
  'heart-rate-variability-calculator': { slug: 'heart-rate-variability-calculator', status: 'custom_estimate', title: 'Heart Rate Variability', canonicalPath: '/calculators/health/heart-rate-variability-calculator', requiresManualReview: false },
  'hiit-calculator': { slug: 'hiit-calculator', status: 'custom_estimate', title: 'Hiit', canonicalPath: '/calculators/health/hiit-calculator', requiresManualReview: false },
  'hydration-calculator': { slug: 'hydration-calculator', status: 'custom_estimate', title: 'Hydration', canonicalPath: '/calculators/health/hydration-calculator', requiresManualReview: false },
  'hydration-exercise-calculator': { slug: 'hydration-exercise-calculator', status: 'custom_estimate', title: 'Hydration Exercise', canonicalPath: '/calculators/health/hydration-exercise-calculator', requiresManualReview: false },
  'ideal-weight-calculator': { slug: 'ideal-weight-calculator', status: 'reviewed', title: 'Ideal Weight', canonicalPath: '/calculators/health/ideal-weight-calculator', requiresManualReview: false },
  'immune-health-calculator': { slug: 'immune-health-calculator', status: 'custom_estimate', title: 'Immune Health', canonicalPath: '/calculators/health/immune-health-calculator', requiresManualReview: false },
  'immune-strength-calculator': { slug: 'immune-strength-calculator', status: 'custom_estimate', title: 'Immune Strength', canonicalPath: '/calculators/health/immune-strength-calculator', requiresManualReview: false },
  'infant-weight-percentile-calculator': { slug: 'infant-weight-percentile-calculator', status: 'reviewed', title: 'Infant Weight Percentile', canonicalPath: '/calculators/health/infant-weight-percentile-calculator', requiresManualReview: false },
  'inflammation-risk-calculator': { slug: 'inflammation-risk-calculator', status: 'custom_estimate', title: 'Inflammation Risk', canonicalPath: '/calculators/health/inflammation-risk-calculator', requiresManualReview: false },
  'injury-recovery-calculator': { slug: 'injury-recovery-calculator', status: 'custom_estimate', title: 'Injury Recovery', canonicalPath: '/calculators/health/injury-recovery-calculator', requiresManualReview: false },
  'intermittent-fasting-calculator': { slug: 'intermittent-fasting-calculator', status: 'reviewed', title: 'Intermittent Fasting', canonicalPath: '/calculators/health/intermittent-fasting-calculator', requiresManualReview: false },
  'iron-intake-calculator': { slug: 'iron-intake-calculator', status: 'reviewed', title: 'Iron Intake', canonicalPath: '/calculators/health/iron-intake-calculator', requiresManualReview: false },
  'jet-lag-calculator': { slug: 'jet-lag-calculator', status: 'custom_estimate', title: 'Jet Lag', canonicalPath: '/calculators/health/jet-lag-calculator', requiresManualReview: false },
  'joint-mobility-calculator': { slug: 'joint-mobility-calculator', status: 'custom_estimate', title: 'Joint Mobility', canonicalPath: '/calculators/health/joint-mobility-calculator', requiresManualReview: false },
  'keto-macro-calculator': { slug: 'keto-macro-calculator', status: 'custom_estimate', title: 'Keto Macro', canonicalPath: '/calculators/health/keto-macro-calculator', requiresManualReview: false },
  'kidney-function-calculator': { slug: 'kidney-function-calculator', status: 'reviewed', title: 'Kidney Function', canonicalPath: '/calculators/health/kidney-function-calculator', requiresManualReview: false },
  'lean-body-mass-calculator': { slug: 'lean-body-mass-calculator', status: 'needs_formula_review', title: 'Lean Body Mass', canonicalPath: '/calculators/health/lean-body-mass-calculator', requiresManualReview: true },
  'liver-health-calculator': { slug: 'liver-health-calculator', status: 'custom_estimate', title: 'Liver Health', canonicalPath: '/calculators/health/liver-health-calculator', requiresManualReview: false },
  'loneliness-health-calculator': { slug: 'loneliness-health-calculator', status: 'custom_estimate', title: 'Loneliness Health', canonicalPath: '/calculators/health/loneliness-health-calculator', requiresManualReview: false },
  'longevity-calculator': { slug: 'longevity-calculator', status: 'custom_estimate', title: 'Longevity', canonicalPath: '/calculators/health/longevity-calculator', requiresManualReview: false },
  'longevity-risk-calculator': { slug: 'longevity-risk-calculator', status: 'custom_estimate', title: 'Longevity Risk', canonicalPath: '/calculators/health/longevity-risk-calculator', requiresManualReview: false },
  'lung-capacity-calculator': { slug: 'lung-capacity-calculator', status: 'needs_formula_review', title: 'Lung Capacity', canonicalPath: '/calculators/health/lung-capacity-calculator', requiresManualReview: true },
  'macro-calculator': { slug: 'macro-calculator', status: 'custom_estimate', title: 'Macro', canonicalPath: '/calculators/health/macro-calculator', requiresManualReview: false },
  'magnesium-calculator': { slug: 'magnesium-calculator', status: 'reviewed', title: 'Magnesium', canonicalPath: '/calculators/health/magnesium-calculator', requiresManualReview: false },
  'marathon-training-calculator': { slug: 'marathon-training-calculator', status: 'custom_estimate', title: 'Marathon Training', canonicalPath: '/calculators/health/marathon-training-calculator', requiresManualReview: false },
  'meal-timing-calculator': { slug: 'meal-timing-calculator', status: 'custom_estimate', title: 'Meal Timing', canonicalPath: '/calculators/health/meal-timing-calculator', requiresManualReview: false },
  'meditation-benefits-calculator': { slug: 'meditation-benefits-calculator', status: 'custom_estimate', title: 'Meditation Benefits', canonicalPath: '/calculators/health/meditation-benefits-calculator', requiresManualReview: false },
  'menopause-symptom-calculator': { slug: 'menopause-symptom-calculator', status: 'custom_estimate', title: 'Menopause Symptom', canonicalPath: '/calculators/health/menopause-symptom-calculator', requiresManualReview: false },
  'menstrual-cycle-calculator': { slug: 'menstrual-cycle-calculator', status: 'reviewed', title: 'Menstrual Cycle', canonicalPath: '/calculators/health/menstrual-cycle-calculator', requiresManualReview: false },
  'menstrual-health-calculator': { slug: 'menstrual-health-calculator', status: 'custom_estimate', title: 'Menstrual Health', canonicalPath: '/calculators/health/menstrual-health-calculator', requiresManualReview: false },
  'mental-fatigue-calculator': { slug: 'mental-fatigue-calculator', status: 'custom_estimate', title: 'Mental Fatigue', canonicalPath: '/calculators/health/mental-fatigue-calculator', requiresManualReview: false },
  'mental-health-score-calculator': { slug: 'mental-health-score-calculator', status: 'custom_estimate', title: 'Mental Health Score', canonicalPath: '/calculators/health/mental-health-score-calculator', requiresManualReview: false },
  'metabolic-age-calculator': { slug: 'metabolic-age-calculator', status: 'custom_estimate', title: 'Metabolic Age', canonicalPath: '/calculators/health/metabolic-age-calculator', requiresManualReview: false },
  'migraine-risk-calculator': { slug: 'migraine-risk-calculator', status: 'custom_estimate', title: 'Migraine Risk', canonicalPath: '/calculators/health/migraine-risk-calculator', requiresManualReview: false },
  'mold-exposure-calculator': { slug: 'mold-exposure-calculator', status: 'custom_estimate', title: 'Mold Exposure', canonicalPath: '/calculators/health/mold-exposure-calculator', requiresManualReview: false },
  'muscle-gain-calculator': { slug: 'muscle-gain-calculator', status: 'custom_estimate', title: 'Muscle Gain', canonicalPath: '/calculators/health/muscle-gain-calculator', requiresManualReview: false },
  'muscle-recovery-time-calculator': { slug: 'muscle-recovery-time-calculator', status: 'custom_estimate', title: 'Muscle Recovery Time', canonicalPath: '/calculators/health/muscle-recovery-time-calculator', requiresManualReview: false },
  'nicotine-withdrawal-calculator': { slug: 'nicotine-withdrawal-calculator', status: 'custom_estimate', title: 'Nicotine Withdrawal', canonicalPath: '/calculators/health/nicotine-withdrawal-calculator', requiresManualReview: false },
  'night-shift-health-calculator': { slug: 'night-shift-health-calculator', status: 'custom_estimate', title: 'Night Shift Health', canonicalPath: '/calculators/health/night-shift-health-calculator', requiresManualReview: false },
  'nutrition-timing-calculator': { slug: 'nutrition-timing-calculator', status: 'custom_estimate', title: 'Nutrition Timing', canonicalPath: '/calculators/health/nutrition-timing-calculator', requiresManualReview: false },
  'nutritional-deficiency-risk-calculator': { slug: 'nutritional-deficiency-risk-calculator', status: 'custom_estimate', title: 'Nutritional Deficiency Risk', canonicalPath: '/calculators/health/nutritional-deficiency-risk-calculator', requiresManualReview: false },
  'obesity-comorbidity-calculator': { slug: 'obesity-comorbidity-calculator', status: 'needs_formula_review', title: 'Obesity Comorbidity', canonicalPath: '/calculators/health/obesity-comorbidity-calculator', requiresManualReview: true },
  'omega3-calculator': { slug: 'omega3-calculator', status: 'reviewed', title: 'Omega3', canonicalPath: '/calculators/health/omega3-calculator', requiresManualReview: false },
  'one-rep-max-calculator': { slug: 'one-rep-max-calculator', status: 'reviewed', title: 'One Rep Max', canonicalPath: '/calculators/health/one-rep-max-calculator', requiresManualReview: false },
  'oral-health-risk-calculator': { slug: 'oral-health-risk-calculator', status: 'custom_estimate', title: 'Oral Health Risk', canonicalPath: '/calculators/health/oral-health-risk-calculator', requiresManualReview: false },
  'ovulation-calculator': { slug: 'ovulation-calculator', status: 'reviewed', title: 'Ovulation', canonicalPath: '/calculators/health/ovulation-calculator', requiresManualReview: false },
  'pace-calculator': { slug: 'pace-calculator', status: 'reviewed', title: 'Pace', canonicalPath: '/calculators/health/pace-calculator', requiresManualReview: false },
  'pain-score-calculator': { slug: 'pain-score-calculator', status: 'custom_estimate', title: 'Pain Score', canonicalPath: '/calculators/health/pain-score-calculator', requiresManualReview: false },
  'pcos-risk-calculator': { slug: 'pcos-risk-calculator', status: 'custom_estimate', title: 'Pcos Risk', canonicalPath: '/calculators/health/pcos-risk-calculator', requiresManualReview: false },
  'plank-time-calculator': { slug: 'plank-time-calculator', status: 'custom_estimate', title: 'Plank Time', canonicalPath: '/calculators/health/plank-time-calculator', requiresManualReview: false },
  'posture-assessment-calculator': { slug: 'posture-assessment-calculator', status: 'custom_estimate', title: 'Posture Assessment', canonicalPath: '/calculators/health/posture-assessment-calculator', requiresManualReview: false },
  'posture-calculator': { slug: 'posture-calculator', status: 'custom_estimate', title: 'Posture', canonicalPath: '/calculators/health/posture-calculator', requiresManualReview: false },
  'pregnancy-calculator': { slug: 'pregnancy-calculator', status: 'reviewed', title: 'Pregnancy', canonicalPath: '/calculators/health/pregnancy-calculator', requiresManualReview: false },
  'pregnancy-conception-calculator': { slug: 'pregnancy-conception-calculator', status: 'custom_estimate', title: 'Pregnancy Conception', canonicalPath: '/calculators/health/pregnancy-conception-calculator', requiresManualReview: false },
  'pregnancy-nutrition-calculator': { slug: 'pregnancy-nutrition-calculator', status: 'reviewed', title: 'Pregnancy Nutrition', canonicalPath: '/calculators/health/pregnancy-nutrition-calculator', requiresManualReview: false },
  'pregnancy-weight-gain-calculator': { slug: 'pregnancy-weight-gain-calculator', status: 'reviewed', title: 'Pregnancy Weight Gain', canonicalPath: '/calculators/health/pregnancy-weight-gain-calculator', requiresManualReview: false },
  'protein-intake-calculator': { slug: 'protein-intake-calculator', status: 'reviewed', title: 'Protein Intake', canonicalPath: '/calculators/health/protein-intake-calculator', requiresManualReview: false },
  'protein-per-meal-calculator': { slug: 'protein-per-meal-calculator', status: 'custom_estimate', title: 'Protein Per Meal', canonicalPath: '/calculators/health/protein-per-meal-calculator', requiresManualReview: false },
  'protein-synthesis-calculator': { slug: 'protein-synthesis-calculator', status: 'custom_estimate', title: 'Protein Synthesis', canonicalPath: '/calculators/health/protein-synthesis-calculator', requiresManualReview: false },
  'pull-up-calculator': { slug: 'pull-up-calculator', status: 'custom_estimate', title: 'Pull Up', canonicalPath: '/calculators/health/pull-up-calculator', requiresManualReview: false },
  'pushup-calculator': { slug: 'pushup-calculator', status: 'custom_estimate', title: 'Pushup', canonicalPath: '/calculators/health/pushup-calculator', requiresManualReview: false },
  'respiratory-rate-calculator': { slug: 'respiratory-rate-calculator', status: 'needs_formula_review', title: 'Respiratory Rate', canonicalPath: '/calculators/health/respiratory-rate-calculator', requiresManualReview: true },
  'resting-metabolic-rate-calculator': { slug: 'resting-metabolic-rate-calculator', status: 'reviewed', title: 'Resting Metabolic Rate', canonicalPath: '/calculators/health/resting-metabolic-rate-calculator', requiresManualReview: false },
  'running-pace-calculator': { slug: 'running-pace-calculator', status: 'reviewed', title: 'Running Pace', canonicalPath: '/calculators/health/running-pace-calculator', requiresManualReview: false },
  'sauna-benefits-calculator': { slug: 'sauna-benefits-calculator', status: 'custom_estimate', title: 'Sauna Benefits', canonicalPath: '/calculators/health/sauna-benefits-calculator', requiresManualReview: false },
  'sauna-health-calculator': { slug: 'sauna-health-calculator', status: 'custom_estimate', title: 'Sauna Health', canonicalPath: '/calculators/health/sauna-health-calculator', requiresManualReview: false },
  'shift-work-health-calculator': { slug: 'shift-work-health-calculator', status: 'custom_estimate', title: 'Shift Work Health', canonicalPath: '/calculators/health/shift-work-health-calculator', requiresManualReview: false },
  'sit-and-reach-calculator': { slug: 'sit-and-reach-calculator', status: 'custom_estimate', title: 'Sit And Reach', canonicalPath: '/calculators/health/sit-and-reach-calculator', requiresManualReview: false },
  'skin-aging-calculator': { slug: 'skin-aging-calculator', status: 'custom_estimate', title: 'Skin Aging', canonicalPath: '/calculators/health/skin-aging-calculator', requiresManualReview: false },
  'skin-health-calculator': { slug: 'skin-health-calculator', status: 'custom_estimate', title: 'Skin Health', canonicalPath: '/calculators/health/skin-health-calculator', requiresManualReview: false },
  'sleep-cycle-calculator': { slug: 'sleep-cycle-calculator', status: 'custom_estimate', title: 'Sleep Cycle', canonicalPath: '/calculators/health/sleep-cycle-calculator', requiresManualReview: false },
  'sleep-debt-calculator': { slug: 'sleep-debt-calculator', status: 'custom_estimate', title: 'Sleep Debt', canonicalPath: '/calculators/health/sleep-debt-calculator', requiresManualReview: false },
  'sleep-need-calculator': { slug: 'sleep-need-calculator', status: 'reviewed', title: 'Sleep Need', canonicalPath: '/calculators/health/sleep-need-calculator', requiresManualReview: false },
  'sodium-intake-calculator': { slug: 'sodium-intake-calculator', status: 'reviewed', title: 'Sodium Intake', canonicalPath: '/calculators/health/sodium-intake-calculator', requiresManualReview: false },
  'spo2-risk-calculator': { slug: 'spo2-risk-calculator', status: 'needs_formula_review', title: 'Spo2 Risk', canonicalPath: '/calculators/health/spo2-risk-calculator', requiresManualReview: true },
  'sprint-calculator': { slug: 'sprint-calculator', status: 'custom_estimate', title: 'Sprint', canonicalPath: '/calculators/health/sprint-calculator', requiresManualReview: false },
  'squat-calculator': { slug: 'squat-calculator', status: 'custom_estimate', title: 'Squat', canonicalPath: '/calculators/health/squat-calculator', requiresManualReview: false },
  'standing-desk-calculator': { slug: 'standing-desk-calculator', status: 'custom_estimate', title: 'Standing Desk', canonicalPath: '/calculators/health/standing-desk-calculator', requiresManualReview: false },
  'steps-calculator': { slug: 'steps-calculator', status: 'reviewed', title: 'Steps', canonicalPath: '/calculators/health/steps-calculator', requiresManualReview: false },
  'steps-to-calories-calculator': { slug: 'steps-to-calories-calculator', status: 'custom_estimate', title: 'Steps To Calories', canonicalPath: '/calculators/health/steps-to-calories-calculator', requiresManualReview: false },
  'stress-level-calculator': { slug: 'stress-level-calculator', status: 'reviewed', title: 'Stress Level', canonicalPath: '/calculators/health/stress-level-calculator', requiresManualReview: false },
  'stroke-risk-calculator': { slug: 'stroke-risk-calculator', status: 'custom_estimate', title: 'Stroke Risk', canonicalPath: '/calculators/health/stroke-risk-calculator', requiresManualReview: false },
  'sugar-intake-calculator': { slug: 'sugar-intake-calculator', status: 'reviewed', title: 'Sugar Intake', canonicalPath: '/calculators/health/sugar-intake-calculator', requiresManualReview: false },
  'sweat-rate-calculator': { slug: 'sweat-rate-calculator', status: 'custom_estimate', title: 'Sweat Rate', canonicalPath: '/calculators/health/sweat-rate-calculator', requiresManualReview: false },
  'swimming-calories-calculator': { slug: 'swimming-calories-calculator', status: 'custom_estimate', title: 'Swimming Calories', canonicalPath: '/calculators/health/swimming-calories-calculator', requiresManualReview: false },
  'target-weight-calculator': { slug: 'target-weight-calculator', status: 'custom_estimate', title: 'Target Weight', canonicalPath: '/calculators/health/target-weight-calculator', requiresManualReview: false },
  'tdee-calculator': { slug: 'tdee-calculator', status: 'custom_estimate', title: 'Tdee', canonicalPath: '/calculators/health/tdee-calculator', requiresManualReview: false },
  'testosterone-age-calculator': { slug: 'testosterone-age-calculator', status: 'custom_estimate', title: 'Testosterone Age', canonicalPath: '/calculators/health/testosterone-age-calculator', requiresManualReview: false },
  'thyroid-calculator': { slug: 'thyroid-calculator', status: 'reviewed', title: 'Thyroid', canonicalPath: '/calculators/health/thyroid-calculator', requiresManualReview: false },
  'uv-exposure-calculator': { slug: 'uv-exposure-calculator', status: 'custom_estimate', title: 'Uv Exposure', canonicalPath: '/calculators/health/uv-exposure-calculator', requiresManualReview: false },
  'visual-acuity-risk-calculator': { slug: 'visual-acuity-risk-calculator', status: 'needs_formula_review', title: 'Visual Acuity Risk', canonicalPath: '/calculators/health/visual-acuity-risk-calculator', requiresManualReview: true },
  'vitamin-c-calculator': { slug: 'vitamin-c-calculator', status: 'reviewed', title: 'Vitamin C', canonicalPath: '/calculators/health/vitamin-c-calculator', requiresManualReview: false },
  'vitamin-d-calculator': { slug: 'vitamin-d-calculator', status: 'reviewed', title: 'Vitamin D', canonicalPath: '/calculators/health/vitamin-d-calculator', requiresManualReview: false },
  'vitamin-d-status-calculator': { slug: 'vitamin-d-status-calculator', status: 'custom_estimate', title: 'Vitamin D Status', canonicalPath: '/calculators/health/vitamin-d-status-calculator', requiresManualReview: false },
  'vo2-max-calculator': { slug: 'vo2-max-calculator', status: 'custom_estimate', title: 'Vo2 Max', canonicalPath: '/calculators/health/vo2-max-calculator', requiresManualReview: false },
  'waist-hip-ratio-calculator': { slug: 'waist-hip-ratio-calculator', status: 'reviewed', title: 'Waist Hip Ratio', canonicalPath: '/calculators/health/waist-hip-ratio-calculator', requiresManualReview: false },
  'waist-to-height-ratio-calculator': { slug: 'waist-to-height-ratio-calculator', status: 'reviewed', title: 'Waist To Height Ratio', canonicalPath: '/calculators/health/waist-to-height-ratio-calculator', requiresManualReview: false },
  'water-intake-calculator': { slug: 'water-intake-calculator', status: 'custom_estimate', title: 'Water Intake', canonicalPath: '/calculators/health/water-intake-calculator', requiresManualReview: false },
  'workout-volume-calculator': { slug: 'workout-volume-calculator', status: 'reviewed', title: 'Workout Volume', canonicalPath: '/calculators/health/workout-volume-calculator', requiresManualReview: false },
  'wound-healing-calculator': { slug: 'wound-healing-calculator', status: 'custom_estimate', title: 'Wound Healing', canonicalPath: '/calculators/health/wound-healing-calculator', requiresManualReview: false },
  'yoga-calories-calculator': { slug: 'yoga-calories-calculator', status: 'custom_estimate', title: 'Yoga Calories', canonicalPath: '/calculators/health/yoga-calories-calculator', requiresManualReview: false },
  'zinc-calculator': { slug: 'zinc-calculator', status: 'reviewed', title: 'Zinc', canonicalPath: '/calculators/health/zinc-calculator', requiresManualReview: false },
}

export const HEALTH_CANONICAL_SLUGS = Object.keys(HEALTH_QUALITY_REGISTRY)

export const HEALTH_QUALITY_COUNTS = HEALTH_CANONICAL_SLUGS.reduce<Record<string, number>>((acc, slug) => {
  const status = HEALTH_QUALITY_REGISTRY[slug].status
  acc[status] = (acc[status] ?? 0) + 1
  return acc
}, {})
