export type HealthBatch04Audit = {
  status: 'reviewed' | 'custom_estimate' | 'needs_formula_review' | 'critical_logic_issue'
  formula: string
  implementationNotes: string
  limitations: string[]
  sources: { label: string; url: string; reviewed: string }[]
}

/**
 * Health Batch 04: routes 76–100 in canonical health order.
 * Conservative by design: custom scores are never described as validated
 * clinical prediction models, and formula mismatches are explicitly flagged.
 */
export const HEALTH_BATCH_04_AUDITS: Record<string, HealthBatch04Audit> = {
  'immune-health-calculator': { status: 'custom_estimate', formula: 'Custom lifestyle score; current implementation is primarily BMI/age/sex based.', implementationNotes: 'This is not a validated immune-function test. Remove clinical-validation language and avoid implying that BMI or sex can directly quantify immune strength.', limitations: ['The score does not measure immune function, infection susceptibility, or immune competence.', 'Persistent or recurrent infections require clinical assessment.'], sources: [] },
  'immune-strength-calculator': { status: 'custom_estimate', formula: 'Custom lifestyle score using sleep, stress, exercise, diet, alcohol, smoking, BMI, age and other self-reported factors.', implementationNotes: 'Not a validated immune-strength instrument. Keep the result explicitly educational.', limitations: ['No single consumer score can quantify immune-system strength.', 'Lifestyle factors affect health but do not translate into a validated 0–100 immune score.'], sources: [] },
  'infant-weight-percentile-calculator': { status: 'critical_logic_issue', formula: 'Should use official WHO/CDC growth-chart LMS data by exact age and sex rather than polynomial approximations.', implementationNotes: 'The current implementation approximates medians and SDs with ad-hoc equations and therefore must not claim to reproduce WHO/CDC percentiles. A data-backed growth-chart migration is required.', limitations: ['Growth assessment requires an age- and sex-appropriate reference population.', 'Percentiles should be interpreted as growth patterns over time, not as a diagnosis from one measurement.'], sources: [{ label: 'CDC — Clinical Growth Charts', url: 'https://cdc.gov/growth-chart-training/hcp/overview/what-are-clinical-growth-charts.html', reviewed: '2026-08-08' }, { label: 'WHO — Child Growth Standards', url: 'https://www.who.int/tools/child-growth-standards', reviewed: '2026-08-08' }] },
  'inflammation-risk-calculator': { status: 'custom_estimate', formula: 'Custom score driven largely by BMI, age and sex.', implementationNotes: 'The score is not a validated measure of systemic inflammation and should not be presented as a disease-risk probability.', limitations: ['Inflammation cannot be quantified from BMI and age alone.', 'CRP and other biomarkers require appropriate laboratory testing and clinical interpretation.'], sources: [] },
  'injury-recovery-calculator': { status: 'custom_estimate', formula: 'Custom recovery score driven by general lifestyle/body-composition inputs.', implementationNotes: 'Recovery time is injury- and tissue-specific; a generic score cannot predict healing time without injury diagnosis, severity and treatment context.', limitations: ['Do not use the result to return to sport after a significant injury.', 'Persistent pain, loss of function or neurological symptoms warrant assessment.'], sources: [] },
  'intermittent-fasting-calculator': { status: 'reviewed', formula: 'Time-window arithmetic plus an energy target based on the selected goal.', implementationNotes: 'The time calculation is deterministic; health or weight-loss effects should not be represented as guaranteed outcomes.', limitations: ['Fasting is not appropriate for everyone.', 'Energy needs and weight response vary between people.'], sources: [{ label: 'NIH — Time-restricted eating for metabolic syndrome', url: 'https://www.nih.gov/news-events/nih-research-matters/time-restricted-eating-metabolic-syndrome', reviewed: '2026-08-08' }] },
  'iron-intake-calculator': { status: 'reviewed', formula: 'Reference intake estimate with a higher factor used for the selected vegetarian diet option.', implementationNotes: 'Distinguish recommended dietary intake from treatment of iron deficiency; iron supplementation should not be inferred from this calculator alone.', limitations: ['Iron needs depend on age, sex, life stage and dietary pattern.', 'Iron deficiency and anemia require appropriate clinical/laboratory assessment.'], sources: [{ label: 'NIH ODS — Iron Fact Sheet', url: 'https://ods.od.nih.gov/factsheets/Iron-HealthProfessional/', reviewed: '2026-08-08' }] },
  'jet-lag-calculator': { status: 'custom_estimate', formula: 'Time-zone arithmetic with heuristic severity and adaptation-day estimates.', implementationNotes: 'The travel-time calculation is deterministic, but recovery-day estimates are planning heuristics, not validated individual predictions.', limitations: ['Adaptation varies with direction of travel, number of time zones, sleep timing and individual circadian characteristics.', 'Severe symptoms or safety-critical impairment should not be managed from a calculator estimate.'], sources: [] },
  'joint-mobility-calculator': { status: 'custom_estimate', formula: 'Composite mobility score from selected joint range-of-motion inputs.', implementationNotes: 'The composite is not a validated Beighton, goniometric, or clinical mobility instrument unless the exact protocol is implemented.', limitations: ['Joint mobility is joint- and task-specific.', 'Pain, instability and functional limitation need clinical context.'], sources: [] },
  'keto-macro-calculator': { status: 'custom_estimate', formula: 'TDEE estimate followed by a selected calorie adjustment and ketogenic-style macro allocation.', implementationNotes: 'Macro arithmetic is deterministic after assumptions are chosen; ketogenic diets are not universally appropriate and the macro split is a planning convention, not a medical prescription.', limitations: ['Energy expenditure is estimated rather than measured.', 'People with diabetes, kidney disease, pregnancy or other conditions may need individualized dietary guidance.'], sources: [] },
  'kidney-function-calculator': { status: 'reviewed', formula: '2021 CKD-EPI creatinine equation without race.', implementationNotes: 'The implementation was corrected from the older 2009-style coefficients to the 2021 race-free CKD-EPI creatinine equation. Creatinine is converted from µmol/L to mg/dL before calculation.', limitations: ['eGFR is an estimate, not a direct measurement.', 'Clinical interpretation depends on persistence, urine findings and patient context; a single calculated value does not diagnose CKD.'], sources: [{ label: 'National Kidney Foundation — 2021 CKD-EPI Creatinine Equation', url: 'https://www.kidney.org/ckd-epi-creatinine-equation-2021', reviewed: '2026-08-08' }] },
  'lean-body-mass-calculator': { status: 'needs_formula_review', formula: 'Multiple historical lean-body-mass equations with an average plus derived fat/organ/bone components.', implementationNotes: 'The named LBM equations can be described, but derived skeletal-muscle, organ-water and bone components are not directly measured and should not be presented as precise body-composition measurements.', limitations: ['Equation estimates can differ materially from DXA or other measurement methods.', 'Derived component masses are model estimates.'], sources: [] },
  'liver-health-calculator': { status: 'custom_estimate', formula: 'Custom lifestyle score using alcohol, diet, exercise, weight, medications and hydration inputs.', implementationNotes: 'The score is not a validated liver-function or fibrosis score. It must not be used to rule out liver disease.', limitations: ['Liver disease can be present without symptoms or a lifestyle-score warning.', 'Validated clinical tools such as FIB-4 use laboratory and demographic inputs and are distinct from this score.'], sources: [] },
  'loneliness-health-calculator': { status: 'custom_estimate', formula: 'Custom social-connection score based on relationship and social-contact inputs.', implementationNotes: 'Do not convert the score into a numeric mortality or disease-risk probability. Loneliness is a psychosocial construct that requires validated instruments for research/clinical measurement.', limitations: ['Self-reported social connection is subjective.', 'A score cannot diagnose depression or another mental-health condition.'], sources: [] },
  'longevity-calculator': { status: 'custom_estimate', formula: 'Heuristic lifespan estimate from baseline life expectancy plus lifestyle adjustments.', implementationNotes: 'The output is not a validated individual survival model. Fixed “healthy years” percentages and additive year gains must be labeled as illustrative assumptions.', limitations: ['Individual lifespan is highly uncertain.', 'Population life expectancy cannot be converted into a precise personal death date.'], sources: [] },
  'longevity-risk-calculator': { status: 'custom_estimate', formula: 'Custom longevity-risk index using lifestyle and health-factor inputs.', implementationNotes: 'Unless mapped to a named validated survival model with its endpoint and population, the result should be a qualitative educational index rather than a probability of death or years lost.', limitations: ['Risk factors interact in complex ways.', 'The score is not a medical prognosis.'], sources: [] },
  'lung-capacity-calculator': { status: 'needs_formula_review', formula: 'Predicted FVC/FEV1 comparison plus FEV1/FVC ratio.', implementationNotes: 'The current page uses a fixed “<70% = obstruction” rule and a simplified predicted-value model. Modern spirometry interpretation should use appropriate reference equations and lower limits of normal; COPD diagnosis also requires clinical context.', limitations: ['Spirometry quality and reference equation selection matter.', 'A calculator cannot diagnose COPD or another lung disease.'], sources: [] },
  'macro-calculator': { status: 'custom_estimate', formula: 'BMR/TDEE estimate followed by calorie adjustment and macro allocation.', implementationNotes: 'Macro arithmetic is transparent, but the calorie and protein targets are planning assumptions rather than universally optimal clinical prescriptions.', limitations: ['Energy expenditure is estimated.', 'Protein and carbohydrate needs vary with training, age, health and goals.'], sources: [] },
  'magnesium-calculator': { status: 'reviewed', formula: 'Reference magnesium intake with an activity adjustment in the current implementation.', implementationNotes: 'The reference intake should be distinguished from a treatment dose. Supplemental magnesium has an upper limit for supplemental forms that differs from total food intake.', limitations: ['Needs vary by age and life stage.', 'Kidney disease and medication interactions can affect supplement safety.'], sources: [{ label: 'NIH ODS — Magnesium Fact Sheet', url: 'https://ods.od.nih.gov/factsheets/Magnesium-HealthProfessional/', reviewed: '2026-08-08' }] },
  'marathon-training-calculator': { status: 'custom_estimate', formula: 'Training-pace and weekly-volume planning heuristics from current mileage and race target.', implementationNotes: 'The schedule is a planning model, not a validated injury-prevention or race-performance prediction.', limitations: ['Training response varies with experience, health, terrain and recovery.', 'Pain or injury should not be overridden by the calculated plan.'], sources: [] },
  'meal-timing-calculator': { status: 'custom_estimate', formula: 'Meal-window timing based on wake/sleep and selected eating schedule.', implementationNotes: 'The clock arithmetic is deterministic; claims about metabolic or weight-loss superiority of a particular timing schedule require outcome-specific evidence.', limitations: ['Meal timing is only one part of diet quality and energy balance.', 'People with medical or eating-related conditions may need individualized guidance.'], sources: [] },
  'meditation-benefits-calculator': { status: 'custom_estimate', formula: 'Custom consistency score with heuristic stress, sleep and focus estimates.', implementationNotes: 'The output is not a validated prediction of a specific percentage reduction in stress, sleep problems or cognitive outcomes.', limitations: ['Benefits vary by practice, baseline symptoms and adherence.', 'The score cannot diagnose or treat a mental-health condition.'], sources: [] },
  'menopause-symptom-calculator': { status: 'custom_estimate', formula: 'Custom symptom-severity score across common menopause symptoms.', implementationNotes: 'Unless the exact validated instrument is implemented, the score should not be called a Menopause Rating Scale or clinical severity measure.', limitations: ['Symptoms have multiple possible causes.', 'Severe bleeding, new neurological symptoms or other concerning symptoms need medical assessment.'], sources: [] },
  'menstrual-cycle-calculator': { status: 'reviewed', formula: 'Calendar arithmetic using the last menstrual period, average cycle length and a fixed 14-day pre-next-period ovulation assumption.', implementationNotes: 'The date arithmetic is clear, but ovulation timing is an estimate and should not be presented as a reliable contraceptive method or fertility diagnosis.', limitations: ['Cycle variability can shift ovulation and fertile-window timing.', 'Hormonal contraception, postpartum status and irregular cycles can make calendar predictions unreliable.'], sources: [{ label: 'ACOG — Heavy and Abnormal Periods', url: 'https://www.acog.org/womens-health/faqs/heavy-and-abnormal-periods', reviewed: '2026-08-08' }] },
  'menstrual-health-calculator': { status: 'custom_estimate', formula: 'Custom menstrual-health score from cycle length, period duration, pain, flow, irregularity and symptom inputs.', implementationNotes: 'The score is not a validated diagnostic test for endometriosis, PCOS, anemia or other conditions. Red-flag messaging should be symptom-based and not framed as diagnosis.', limitations: ['Menstrual symptoms have many possible causes.', 'Heavy bleeding, severe pain, fainting or other concerning symptoms warrant clinical evaluation.'], sources: [{ label: 'ACOG — Heavy and Abnormal Periods', url: 'https://www.acog.org/womens-health/faqs/heavy-and-abnormal-periods', reviewed: '2026-08-08' }] },
}
