export type HealthBatch07Status =
  | 'reviewed'
  | 'custom_estimate'
  | 'needs_formula_review'
  | 'critical_logic_issue'

export interface HealthBatch07Audit {
  slug: string
  status: HealthBatch07Status
  formula: string
  implementationNotes: string
  limitations: string[]
  sources: string[]
  reviewed: string
}

/**
 * Health Batch 07 (final health batch) audit metadata.
 * Keep claims tied to the actual implementation; do not imply clinical validation
 * for custom estimates.
 */
export const HEALTH_BATCH_07: HealthBatch07Audit[] = [
  { slug: 'steps-to-calories-calculator', status: 'custom_estimate', formula: 'MET × body mass × duration', implementationNotes: 'Uses step-derived distance and selected walking pace to estimate energy expenditure.', limitations: ['Calorie expenditure is an estimate and varies with gait, terrain and individual efficiency.', 'Step count is not a direct measure of energy expenditure.'], sources: ['Compendium of Physical Activities'], reviewed: '2026-08-08' },
  { slug: 'stress-level-calculator', status: 'reviewed', formula: 'PSS-10 scoring', implementationNotes: 'Implements the 10-item Perceived Stress Scale scoring with reverse scoring for items 4, 5, 7 and 8.', limitations: ['PSS is a perceived-stress measure, not a psychiatric diagnosis.'], sources: ['Cohen, Kamarck & Mermelstein (1983)'], reviewed: '2026-08-08' },
  { slug: 'stroke-risk-calculator', status: 'critical_logic_issue', formula: 'Custom heuristic score', implementationNotes: 'Current implementation converts a custom point score into a percentage; it is not a validated stroke-risk model.', limitations: ['Do not interpret the displayed percentage as a validated 10-year individual risk.', 'Replace with a validated model before presenting an individual risk percentage.'], sources: ['AHA/ASA stroke prevention guidance should be used for clinical context'], reviewed: '2026-08-08' },
  { slug: 'sugar-intake-calculator', status: 'reviewed', formula: 'Daily added/free sugar comparison', implementationNotes: 'Compares entered intake against configurable dietary guidance; does not diagnose metabolic disease.', limitations: ['Guidance differs by age, pregnancy status and dietary context.'], sources: ['American Heart Association'], reviewed: '2026-08-08' },
  { slug: 'sweat-rate-calculator', status: 'custom_estimate', formula: 'Pre/post exercise body-mass change + fluid intake', implementationNotes: 'Estimates fluid-loss rate from measured session changes.', limitations: ['Weighing conditions and fluid measurement errors affect the estimate.'], sources: ['ACSM exercise hydration guidance'], reviewed: '2026-08-08' },
  { slug: 'swimming-calories-calculator', status: 'custom_estimate', formula: 'MET × body mass × duration', implementationNotes: 'Uses activity-specific MET values for an energy-expenditure estimate.', limitations: ['Stroke efficiency, pace and pool conditions can materially change energy expenditure.'], sources: ['Compendium of Physical Activities'], reviewed: '2026-08-08' },
  { slug: 'target-weight-calculator', status: 'custom_estimate', formula: 'BMI-range-based weight range', implementationNotes: 'Provides a reference range derived from BMI rather than a personalized clinical target.', limitations: ['BMI does not distinguish muscle from fat and is not a diagnosis.'], sources: ['CDC adult BMI guidance'], reviewed: '2026-08-08' },
  { slug: 'tdee-calculator', status: 'custom_estimate', formula: 'BMR × activity factor', implementationNotes: 'Estimates total daily energy expenditure from a basal metabolic equation and activity multiplier.', limitations: ['Activity multipliers and BMR equations are population estimates.'], sources: ['Mifflin-St Jeor; Compendium of Physical Activities'], reviewed: '2026-08-08' },
  { slug: 'testosterone-age-calculator', status: 'critical_logic_issue', formula: 'Custom age/lifestyle heuristic', implementationNotes: 'Estimates testosterone from age and lifestyle inputs; it does not measure serum testosterone.', limitations: ['A calculated estimate cannot diagnose testosterone deficiency.', 'Serum testing and clinical assessment are required for diagnosis.'], sources: ['Endocrine Society testosterone deficiency guidance'], reviewed: '2026-08-08' },
  { slug: 'thyroid-calculator', status: 'critical_logic_issue', formula: 'Custom symptom/risk heuristic', implementationNotes: 'Does not calculate TSH, free T4 or a validated thyroid-disease probability.', limitations: ['Symptoms alone cannot diagnose thyroid disease.'], sources: ['American Thyroid Association'], reviewed: '2026-08-08' },
  { slug: 'uv-exposure-calculator', status: 'custom_estimate', formula: 'UV index/exposure heuristic', implementationNotes: 'Provides educational exposure context; it is not a clinical skin-cancer risk model.', limitations: ['UV exposure depends on time, altitude, cloud cover, reflection, clothing and sunscreen use.'], sources: ['WHO UV radiation guidance'], reviewed: '2026-08-08' },
  { slug: 'visual-acuity-risk-calculator', status: 'needs_formula_review', formula: 'Reference/heuristic visual score', implementationNotes: 'Requires validation of the relationship between entered acuity and the displayed risk interpretation.', limitations: ['A calculator cannot replace a visual acuity examination or eye examination.'], sources: ['American Academy of Ophthalmology'], reviewed: '2026-08-08' },
  { slug: 'vitamin-c-calculator', status: 'reviewed', formula: 'Age/sex/pregnancy RDA comparison', implementationNotes: 'Compares intake targets with dietary reference values.', limitations: ['RDA comparison does not diagnose vitamin C deficiency.'], sources: ['NIH Office of Dietary Supplements — Vitamin C'], reviewed: '2026-08-08' },
  { slug: 'vitamin-d-calculator', status: 'reviewed', formula: 'Dietary reference intake comparison', implementationNotes: 'Compares intake against reference values; does not infer serum 25-OH vitamin D from intake.', limitations: ['Serum status requires a blood test.'], sources: ['NIH Office of Dietary Supplements — Vitamin D'], reviewed: '2026-08-08' },
  { slug: 'vitamin-d-status-calculator', status: 'critical_logic_issue', formula: 'Custom estimated serum-level model', implementationNotes: 'Current implementation infers a serum 25-OH vitamin D concentration from sun, latitude, BMI and intake; this is not a validated serum prediction model.', limitations: ['Do not use the estimated serum level or suggested dose as a substitute for testing or clinical advice.'], sources: ['NIH Office of Dietary Supplements — Vitamin D'], reviewed: '2026-08-08' },
  { slug: 'vo2-max-calculator', status: 'custom_estimate', formula: 'Exercise-test-based VO₂ max estimate', implementationNotes: 'Provides an estimate from user-entered performance data; laboratory measurement is more direct.', limitations: ['Protocol, fitness level and pacing affect estimates.'], sources: ['ACSM exercise testing guidance'], reviewed: '2026-08-08' },
  { slug: 'waist-hip-ratio-calculator', status: 'reviewed', formula: 'Waist circumference ÷ hip circumference', implementationNotes: 'Deterministic anthropometric ratio; interpretation depends on population and guideline.', limitations: ['Measurement technique affects the ratio.'], sources: ['WHO anthropometric guidance'], reviewed: '2026-08-08' },
  { slug: 'waist-to-height-ratio-calculator', status: 'reviewed', formula: 'Waist circumference ÷ height', implementationNotes: 'Deterministic anthropometric ratio; threshold interpretation requires population context.', limitations: ['Thresholds vary by guideline and population.'], sources: ['NICE waist-to-height guidance'], reviewed: '2026-08-08' },
  { slug: 'water-intake-calculator', status: 'custom_estimate', formula: 'Body-size/activity-based fluid estimate', implementationNotes: 'Provides a practical estimate rather than an individualized medical prescription.', limitations: ['Fluid needs vary with climate, illness, pregnancy, diet and activity.'], sources: ['National Academies dietary reference intakes for water'], reviewed: '2026-08-08' },
  { slug: 'workout-volume-calculator', status: 'reviewed', formula: 'Sets × reps × load', implementationNotes: 'Calculates external training volume for entered resistance-training sets.', limitations: ['Volume alone does not capture intensity, technique, range of motion or fatigue.'], sources: ['ACSM resistance-training guidance'], reviewed: '2026-08-08' },
  { slug: 'wound-healing-calculator', status: 'critical_logic_issue', formula: 'Custom healing-time heuristic', implementationNotes: 'Current estimate uses wound and health inputs to predict healing time; this is not a validated wound-healing prediction model.', limitations: ['Wound assessment requires clinical examination.', 'Do not use estimated days to delay professional wound care.'], sources: ['Clinical wound-care guidance'], reviewed: '2026-08-08' },
  { slug: 'yoga-calories-calculator', status: 'custom_estimate', formula: 'MET × body mass × duration', implementationNotes: 'Uses style-specific MET assumptions to estimate energy expenditure.', limitations: ['Actual energy expenditure varies with intensity, skill and session structure.'], sources: ['Compendium of Physical Activities'], reviewed: '2026-08-08' },
  { slug: 'zinc-calculator', status: 'reviewed', formula: 'Age/sex/pregnancy RDA comparison', implementationNotes: 'Compares zinc intake targets with dietary reference values; plant-based adjustment should be presented as a planning assumption rather than a diagnosis.', limitations: ['RDA comparison does not diagnose zinc deficiency.', 'Chronic high-dose supplementation can cause copper deficiency.'], sources: ['NIH Office of Dietary Supplements — Zinc'], reviewed: '2026-08-08' },
]
