export type HealthBatch03Audit = {
  status: 'reviewed' | 'custom_estimate' | 'needs_formula_review' | 'critical_logic_issue'
  formula: string
  implementationNotes: string
  limitations: string[]
  sources: { label: string; url: string; reviewed: string }[]
}

/**
 * Health Batch 03 (routes 51–75 in the canonical health route order).
 * This registry is intentionally conservative: a custom score is never
 * described as a validated clinical prediction model.
 */
export const HEALTH_BATCH_03_AUDITS: Record<string, HealthBatch03Audit> = {
  'exercise-addiction-calculator': { status: 'custom_estimate', formula: 'Custom behavioral-pattern score using exercise frequency and self-reported compulsive-exercise indicators.', implementationNotes: 'The implementation is not the published Exercise Addiction Inventory instrument. The page must not call this an official or validated EAI score.', limitations: ['This score is educational and cannot diagnose exercise addiction.', 'Exercise dependence and compulsive exercise require contextual assessment.'], sources: [{ label: 'Exercise Addiction Inventory — Griffiths et al.', url: 'https://pubmed.ncbi.nlm.nih.gov/15911594/', reviewed: '2026-08-08' }] },
  'eye-health-calculator': { status: 'custom_estimate', formula: 'Custom eye-strain/risk score combining screen-use and lifestyle inputs.', implementationNotes: 'The score is not a validated probability of glaucoma, AMD, diabetic retinopathy, or permanent eye damage. Disease-specific claims must be separated from the educational score.', limitations: ['A risk score cannot diagnose an eye disease.', 'Vision symptoms or risk factors may require a comprehensive eye examination.'], sources: [{ label: 'AAO EyeWiki — Computer Vision Syndrome / Digital Eye Strain', url: 'https://eyewiki.aao.org/Computer_Vision_Syndrome_%28Digital_Eye_Strain%29', reviewed: '2026-08-08' }] },
  'fasting-window-calculator': { status: 'custom_estimate', formula: 'Time-window arithmetic for fasting and eating periods.', implementationNotes: 'The time calculation is deterministic; claims about weight loss, autophagy, insulin sensitivity, or long-term health benefits are evidence-dependent and should not be derived from the window alone.', limitations: ['A fasting schedule does not predict an individual weight-loss outcome.', 'Some people should avoid fasting or use medical guidance.'], sources: [{ label: 'NIH — Time-restricted eating for metabolic syndrome', url: 'https://www.nih.gov/news-events/nih-research-matters/time-restricted-eating-metabolic-syndrome', reviewed: '2026-08-08' }] },
  'fat-loss-rate-calculator': { status: 'custom_estimate', formula: 'Planning estimate based on selected calorie deficit and body-weight inputs.', implementationNotes: 'The output is a planning target, not a validated prediction of weekly fat loss.', limitations: ['Scale weight changes include water and glycogen, not only fat.', 'Individual energy expenditure adapts over time.'], sources: [{ label: 'CDC — Steps for Losing Weight', url: 'https://www.cdc.gov/healthy-weight-growth/losing-weight/index.html', reviewed: '2026-08-08' }] },
  'fiber-intake-calculator': { status: 'reviewed', formula: 'Daily fiber target derived from age/sex/life-stage guidance and dietary intake assumptions.', implementationNotes: 'Reference targets should be distinguished from a treatment prescription and should account for total dietary intake.', limitations: ['Individual needs and tolerance vary.', 'Sudden large increases in fiber can cause gastrointestinal symptoms without adequate fluid intake.'], sources: [{ label: 'Dietary Guidelines for Americans', url: 'https://www.dietaryguidelines.gov/', reviewed: '2026-08-08' }] },
  'flexibility-calculator': { status: 'custom_estimate', formula: 'Custom mobility/flexibility score from selected range-of-motion inputs.', implementationNotes: 'Unless mapped to a named validated assessment protocol, the score is an educational composite.', limitations: ['Flexibility is joint- and task-specific.', 'A composite score does not diagnose musculoskeletal disorders.'], sources: [] },
  'food-sensitivity-calculator': { status: 'custom_estimate', formula: 'Custom symptom/burden score across selected foods and symptoms.', implementationNotes: 'The score does not diagnose food allergy or intolerance. The previous IgG-panel recommendation was removed because AAAAI recommends against IgG testing for diagnosing food allergy/intolerance.', limitations: ['Food allergy diagnosis requires clinical history and appropriate testing.', 'Severe reactions can be emergencies and should not be managed by a calculator.'], sources: [{ label: 'AAAAI — The Myth of IgG Food Panel Testing', url: 'https://www.aaaai.org/tools-for-the-public/conditions-library/allergies/igg-food-test', reviewed: '2026-08-08' }] },
  'frailty-index-calculator': { status: 'reviewed', formula: 'Five-component Fried frailty phenotype: unintentional weight loss, exhaustion, weakness, slow gait, and low physical activity.', implementationNotes: 'The page uses the Fried phenotype rather than the Rockwood deficit-accumulation Frailty Index. Unsupported hospitalization/fall multipliers were removed.', limitations: ['Screening phenotype is not a diagnosis.', 'Original thresholds can depend on sex, body size, population, and measurement protocol.'], sources: [{ label: 'Fried et al. — Frailty in Older Adults: Evidence for a Phenotype', url: 'https://pubmed.ncbi.nlm.nih.gov/11253156/', reviewed: '2026-08-08' }] },
  'genetic-height-calculator': { status: 'needs_formula_review', formula: 'Mid-parental/target-height estimate using parental heights and sex.', implementationNotes: 'The arbitrary percentile estimate and fixed nutrition effect were removed. Target height is a familial estimate, not an exact adult-height prediction.', limitations: ['Growth depends on genetics, maturation, health and environment.', 'Growth assessment in children should use age- and sex-specific growth charts and clinical context.'], sources: [{ label: 'PubMed — Accurate Prediction of Children’s Target Height from Mid-Parental Height', url: 'https://pubmed.ncbi.nlm.nih.gov/39201851/', reviewed: '2026-08-08' }] },
  'gfr-egfr-calculator': { status: 'reviewed', formula: '2021 CKD-EPI creatinine equation without race.', implementationNotes: 'The obsolete race coefficient and race toggle were removed. The equation requires standardized creatinine and is an estimate of GFR, not a direct measurement.', limitations: ['eGFR is an estimate and has limitations at extremes of age, body size, muscle mass, and changing kidney function.', 'CKD diagnosis requires persistence and/or other evidence of kidney damage.'], sources: [{ label: 'National Kidney Foundation — 2021 CKD-EPI Creatinine Equation', url: 'https://www.kidney.org/ckd-epi-creatinine-equation-2021', reviewed: '2026-08-08' }] },
  'glycemic-load-calculator': { status: 'reviewed', formula: 'Glycemic load is calculated from glycemic index and available carbohydrate amount.', implementationNotes: 'The formula is deterministic when the GI and carbohydrate inputs are valid, but GI itself varies with food, preparation, ripeness and measurement context.', limitations: ['GI values are not fixed biological constants.', 'Glycemic load does not by itself diagnose diabetes or predict an individual glucose response.'], sources: [{ label: 'Harvard T.H. Chan School of Public Health — Glycemic Index and Glycemic Load', url: 'https://nutritionsource.hsph.harvard.edu/healthy-weight/glycemic-index-and-glycemic-load/', reviewed: '2026-08-08' }] },
  'gratitude-health-calculator': { status: 'custom_estimate', formula: 'Self-report wellness score based on gratitude/practice inputs.', implementationNotes: 'The score is a behavioral reflection tool and is not a validated measure of depression, anxiety, or physical-health risk.', limitations: ['Self-report scores are subjective.', 'Do not interpret a gratitude score as a clinical mental-health assessment.'], sources: [] },
  'grip-strength-age-calculator': { status: 'needs_formula_review', formula: 'Age/sex comparison using normative handgrip-strength data.', implementationNotes: 'Normative values depend on protocol, dynamometer, hand, population and body size. The current percentile mapping and mortality threshold need protocol-specific validation before clinical claims.', limitations: ['Grip strength alone does not diagnose sarcopenia.', 'Compare measurements using a consistent protocol.'], sources: [{ label: 'PubMed — International norms for adult handgrip strength', url: 'https://pubmed.ncbi.nlm.nih.gov/39647778/', reviewed: '2026-08-08' }] },
  'grip-strength-calculator': { status: 'needs_formula_review', formula: 'Handgrip-strength result compared with age/sex reference values.', implementationNotes: 'Reference ranges must state the measurement protocol and population. Avoid converting a single measurement directly into disease risk.', limitations: ['Device and protocol affect results.', 'Clinical interpretation requires broader functional context.'], sources: [{ label: 'PubMed — Global variation in grip strength', url: 'https://pubmed.ncbi.nlm.nih.gov/26790455/', reviewed: '2026-08-08' }] },
  'gut-health-calculator': { status: 'custom_estimate', formula: 'Custom self-reported digestive/lifestyle score.', implementationNotes: 'The composite score is not a validated test for microbiome health, IBS, IBD, or other gastrointestinal disease.', limitations: ['Digestive symptoms have many possible causes.', 'Persistent, severe, or alarming symptoms require clinical evaluation.'], sources: [] },
  'hangover-recovery-calculator': { status: 'custom_estimate', formula: 'Time/recovery planning estimate from alcohol exposure and recovery inputs.', implementationNotes: 'The tool cannot reliably calculate sobriety, BAC clearance, or medical safety. Recovery suggestions should not be used to decide whether someone can drive.', limitations: ['Alcohol clearance varies by person and circumstance.', 'Only time reduces alcohol concentration; a calculator cannot accelerate metabolism.'], sources: [] },
  'hearing-age-calculator': { status: 'custom_estimate', formula: 'Educational comparison of hearing-related inputs to age-oriented reference concepts.', implementationNotes: 'A questionnaire cannot produce a clinical hearing age without audiometric testing.', limitations: ['Hearing loss requires appropriate hearing assessment.', 'Noise exposure and age are only some contributors to hearing ability.'], sources: [] },
  'heart-age-calculator': { status: 'needs_formula_review', formula: 'Heart-age estimate based on cardiovascular risk factors.', implementationNotes: 'Heart age is model-specific. The calculator must identify the exact validated risk model, population, endpoint and inputs rather than presenting a custom score as a universal heart-age calculation.', limitations: ['Different models produce different heart-age results.', 'A heart-age estimate is not a diagnosis.'], sources: [{ label: 'Framingham Heart Study — Risk Functions', url: 'https://www.framinghamheartstudy.org/fhs-risk-functions/', reviewed: '2026-08-08' }] },
  'heart-attack-risk-calculator': { status: 'needs_formula_review', formula: 'Cardiovascular-risk estimate from demographic and clinical risk factors.', implementationNotes: 'The implementation must be mapped to a named validated model before using a percentage as an individual event probability.', limitations: ['Risk models are population-specific.', 'A calculator result should complement, not replace, clinical risk assessment.'], sources: [{ label: 'Framingham Heart Study — Risk Functions', url: 'https://www.framinghamheartstudy.org/fhs-risk-functions/', reviewed: '2026-08-08' }] },
  'heart-rate-calculator': { status: 'reviewed', formula: 'Heart-rate training zones derived from a declared maximum-heart-rate or heart-rate-reserve method.', implementationNotes: 'Zone formulas are estimates and should clearly identify which maximum-HR equation and zone convention is used.', limitations: ['Maximum heart rate varies between individuals.', 'Medications and medical conditions can change exercise heart-rate responses.'], sources: [] },
  'heart-rate-variability-calculator': { status: 'custom_estimate', formula: 'RMSSD compared with a custom age/sex reference and readiness thresholds.', implementationNotes: 'The fixed expected-RMSSD equation and readiness score are not a validated clinical diagnostic model. HRV should be interpreted relative to an individual’s own baseline and measurement conditions.', limitations: ['HRV varies with device, posture, breathing, sleep, illness and timing.', 'Low or high HRV alone does not diagnose stress or autonomic disease.'], sources: [] },
  'hiit-calculator': { status: 'custom_estimate', formula: 'HIIT session planning from interval duration, intensity and recovery inputs.', implementationNotes: 'Session arithmetic is deterministic; claims that a specific schedule is universally optimal or clinically validated should be removed.', limitations: ['Training response varies by fitness and health status.', 'High-intensity exercise is not appropriate for everyone.'], sources: [] },
  'hydration-calculator': { status: 'custom_estimate', formula: 'Daily water-intake planning estimate based on body weight, activity duration and climate.', implementationNotes: 'The weight-based 35 mL/kg plus activity/climate adjustment is a planning heuristic, not a universal clinical requirement.', limitations: ['Fluid needs vary with illness, pregnancy, diet, climate, sweat rate and medications.', 'Avoid excessive fluid intake; exercise-associated hyponatremia is a real risk.'], sources: [{ label: 'CDC — About Water and Healthier Drinks', url: 'https://www.cdc.gov/healthy-weight-growth/water-healthy-drinks/index.html', reviewed: '2026-08-08' }] },
  'hydration-exercise-calculator': { status: 'custom_estimate', formula: 'Heuristic sweat-rate and fluid-planning estimate based on duration, intensity, temperature, altitude and exercise type.', implementationNotes: 'The fixed base sweat rate and 900 mg/L sodium assumption are not individualized sweat testing. The tool must not promise exact fluid needs.', limitations: ['Sweat rate varies substantially between individuals and sessions.', 'Overdrinking can cause exercise-associated hyponatremia.', 'For long/hot events, individualized hydration and sodium planning may be appropriate.'], sources: [{ label: 'CDC — About Water and Healthier Drinks', url: 'https://www.cdc.gov/healthy-weight-growth/water-healthy-drinks/index.html', reviewed: '2026-08-08' }] },
  'ideal-weight-calculator': { status: 'reviewed', formula: 'Hamwi, Robinson and Miller ideal-body-weight estimates plus BMI 18.5–24.9 weight range.', implementationNotes: 'The implementation returns three ideal-body-weight formulas, not five. The page copy was corrected to match the implementation.', limitations: ['These formulas are historical estimates, not individualized health prescriptions.', 'BMI and ideal-weight formulas should not be used alone to assess health.'], sources: [] },
}
