export type HealthSourceProfile = {
  status: 'reviewed' | 'needs_manual_review'
  methodology: string
  limitations: string[]
  sources: { label: string; url: string; sourceDate?: string; sourceDateType?: 'published' | 'updated' }[]
}

/**
 * Claim-level source register for the first 25 health routes.
 * A profile marked needs_manual_review must not be described as clinically
 * validated until the underlying calculator formula/logic has been checked.
 */
export const HEALTH_SOURCE_PROFILES: Record<string, HealthSourceProfile> = {
  'pregnancy-due-date-calculator': {
    status: 'needs_manual_review',
    methodology: 'The page uses 280 days from the first day of the last menstrual period for the LMP method, adjusts for the entered cycle length, and uses 266 days for the conception-date method. Clinical dating can be revised using an early accurate ultrasound or an assisted-reproduction date under obstetric guidance.',
    limitations: ['LMP dating assumes the entered LMP is correct and cycle timing is suitable for the selected adjustment.', 'An estimated due date is not a prediction of the actual delivery date.', 'ACOG guidance recognizes early ultrasound and assisted-reproduction dating as important inputs when establishing the best obstetric estimate.'],
    sources: [
      { label: 'ACOG — Methods for Estimating the Due Date', url: 'https://www.acog.org/clinical/clinical-guidance/committee-opinion/articles/2017/05/methods-for-estimating-the-due-date', sourceDate: '2025', sourceDateType: 'updated' },
      { label: 'ACOG — When Pregnancy Goes Past Your Due Date', url: 'https://www.acog.org/womens-health/faqs/when-pregnancy-goes-past-your-due-date' },
    ],
  },
  'age-calculator': {
    status: 'reviewed',
    methodology: 'Calendar age is a date-arithmetic calculation using Gregorian calendar rules. It is not a clinical measure of biological age.',
    limitations: ['Chronological age does not measure biological age or health status.', 'Any biological-age interpretation requires a separate validated model and should not be inferred from date arithmetic alone.'],
    sources: [{ label: 'NIA — biological versus chronological aging', url: 'https://www.nia.nih.gov/news/epigenetics-aging-what-bodys-hands-time-tell-us' }],
  },
  'air-quality-health-calculator': {
    status: 'reviewed',
    methodology: 'AQI interpretation should follow the pollutant-specific AQI framework and the applicable public-health guidance for the location and population.',
    limitations: ['A consumer calculator cannot determine an individual safe exposure duration.', 'Symptoms, underlying disease, pollutant type, concentration and local conditions can change risk.'],
    sources: [{ label: 'U.S. EPA AirNow — Air Quality Index', url: 'https://www.airnow.gov/aqi/' }],
  },
  'alcohol-calorie-calculator': {
    status: 'reviewed',
    methodology: 'Alcohol energy estimates should use beverage alcohol content and serving size; U.S. standard-drink definitions can help normalize beverage amounts.',
    limitations: ['Calories vary with alcohol concentration, serving size, mixers and residual carbohydrate.', 'Energy estimates do not predict intoxication or medical risk.'],
    sources: [{ label: 'NIAAA — What is a standard drink?', url: 'https://www.niaaa.nih.gov/alcohols-effects-health/what-standard-drink' }],
  },
  'alcohol-metabolism-calculator': {
    status: 'reviewed',
    methodology: 'Alcohol elimination estimates are population-level approximations and should not be treated as a measured blood alcohol concentration or a driving-safety test.',
    limitations: ['Alcohol absorption and elimination vary substantially between people and situations.', 'A calculated time-to-zero cannot establish that a person is safe or legal to drive.'],
    sources: [{ label: 'NIAAA — What is a standard drink?', url: 'https://www.niaaa.nih.gov/alcohols-effects-health/what-standard-drink' }],
  },
  'altitude-sickness-calculator': {
    status: 'reviewed',
    methodology: 'Altitude-illness guidance is based on elevation, ascent rate and acclimatization principles rather than a single personal-risk formula.',
    limitations: ['There is no simple screening test that can reliably predict who will develop altitude illness.', 'A calculator cannot diagnose AMS, HAPE or HACE or replace urgent assessment of symptoms.'],
    sources: [{ label: 'CDC Yellow Book 2026 — High-altitude travel and altitude illness', url: 'https://www.cdc.gov/yellow-book/hcp/environmental-hazards-risks/high-altitude-travel-and-altitude-illness.html', sourceDate: '2025-04-23', sourceDateType: 'published' }],
  },
  'ankle-brachial-index-calculator': {
    status: 'reviewed',
    methodology: 'ABI is calculated as ankle systolic pressure divided by brachial systolic pressure and is interpreted in the context of PAD evaluation.',
    limitations: ['ABI interpretation can be affected by noncompressible arteries and clinical context.', 'An online calculation does not diagnose PAD by itself.'],
    sources: [{ label: 'AHA — 2024 lower-extremity PAD guideline', url: 'https://professional.heart.org/en/science-news/2024-guideline-for-the-management-of-lower-extremity-peripheral-artery-disease/top-things-to-know', sourceDate: '2024-05-14', sourceDateType: 'updated' }, { label: 'AHA — ABI measurement and interpretation', url: 'https://professional.heart.org/en/science-news/measurement-and-interpretation-of-the-ankle-brachial-index/top-things-to-know' }],
  },
  'army-body-fat-calculator': {
    status: 'needs_manual_review',
    methodology: 'The route currently describes the historical AR 600-9 tape-test approach, but Army body-composition policy changed in 2026.',
    limitations: ['The current Army standard must be verified before publishing pass/fail results.', 'This page should not claim to represent the current Army standard until its calculation logic is migrated.'],
    sources: [{ label: 'U.S. Army — Army Directive 2026-13', url: 'https://www.army.mil/tellyourformation/' }],
  },
  'athlete-heart-rate-calculator': {
    status: 'reviewed',
    methodology: 'Heart-rate training zones are estimates based on age-predicted maximum heart rate and, where applicable, heart-rate reserve.',
    limitations: ['Age-based maximum-heart-rate equations are population estimates, not direct measurements.', 'Medications, cardiac conditions and fitness level can materially affect appropriate training intensity.'],
    sources: [{ label: 'AHA — Target heart rates chart', url: 'https://www.heart.org/en/healthy-living/exercise-and-physical-activity/fitness-basics/target-heart-rates' }],
  },
  'athletic-performance-calculator': {
    status: 'needs_manual_review',
    methodology: 'Field-test estimates such as VO2 max, power-to-weight and strength ratios depend on the specific test protocol and population equation used.',
    limitations: ['Different field tests and equations can produce materially different estimates.', 'The result should not be presented as a laboratory measurement unless the underlying test has been validated for that use.'],
    sources: [],
  },
  'bac-calculator': {
    status: 'reviewed',
    methodology: 'BAC calculators provide estimates from drink amount, alcohol concentration, body characteristics and elapsed time; they do not directly measure blood alcohol.',
    limitations: ['BAC estimates have substantial individual and measurement uncertainty.', 'Do not use a calculator to decide whether to drive, operate machinery or perform another safety-critical activity.'],
    sources: [{ label: 'NIAAA — What is a standard drink?', url: 'https://www.niaaa.nih.gov/alcohols-effects-health/what-standard-drink' }],
  },
  'blood-pressure-calculator': {
    status: 'reviewed',
    methodology: 'Adult blood-pressure categories should follow the current AHA/ACC framework and distinguish a single reading from a diagnosis.',
    limitations: ['One reading does not establish a diagnosis.', 'Severe readings with concerning symptoms require urgent medical evaluation rather than calculator interpretation.'],
    sources: [{ label: 'AHA — Blood Pressure Explained', url: 'https://www.heart.org/en/health-topics/high-blood-pressure/blood-pressure-explained' }, { label: 'AHA — 2025 High Blood Pressure Guideline', url: 'https://professional.heart.org/en/science-news/2025-high-blood-pressure-guideline/top-things-to-know' }],
  },
  'blue-light-exposure-calculator': {
    status: 'needs_manual_review',
    methodology: 'Screen and light exposure does not map cleanly to a validated personal risk score from duration alone.',
    limitations: ['Blue-light dose, wavelength, brightness, viewing distance and ambient light all matter.', 'The current page should not imply that a simple exposure total predicts macular degeneration or disease risk.'],
    sources: [],
  },
  'bmi-calculator': {
    status: 'reviewed',
    methodology: 'Adult BMI is weight in kilograms divided by height in meters squared; CDC describes BMI as a screening measure rather than a diagnosis.',
    limitations: ['BMI does not directly measure body fat or distinguish fat from lean mass.', 'Individual interpretation should consider other clinical measures and health context.'],
    sources: [{ label: 'CDC — Adult BMI Categories', url: 'https://www.cdc.gov/bmi/adult-calculator/bmi-categories.html' }, { label: 'CDC — About BMI', url: 'https://www.cdc.gov/bmi/about/index.html' }],
  },
  'bmi-for-children-calculator': {
    status: 'reviewed',
    methodology: 'For ages 2–19, BMI is interpreted using sex-specific BMI-for-age percentiles and CDC growth-chart references.',
    limitations: ['Children are growing, so adult BMI categories must not be substituted for pediatric percentiles.', 'Rounding and measurement differences can produce small percentile differences.'],
    sources: [{ label: 'CDC — Child and Teen BMI Calculator', url: 'https://www.cdc.gov/bmi/child-teen-calculator/index.html' }, { label: 'CDC — Clinical Growth Charts', url: 'https://cdc.gov/growth-chart-training/hcp/overview/what-are-clinical-growth-charts.html' }],
  },
  'bmr-calculator': {
    status: 'reviewed',
    methodology: 'The Mifflin–St Jeor equation is a predictive equation for resting energy expenditure; other equations such as Harris–Benedict use different populations and coefficients.',
    limitations: ['Predictive equations estimate energy expenditure and can be inaccurate for an individual.', 'BMR is not the same as total daily energy expenditure.'],
    sources: [{ label: 'Mifflin et al. — 1990 predictive equation', url: 'https://pubmed.ncbi.nlm.nih.gov/2305711/' }],
  },
  'body-age-calculator': {
    status: 'needs_manual_review',
    methodology: 'Biological or “body age” is model-dependent; chronological age alone cannot produce a validated biological-age estimate.',
    limitations: ['Different biological-age models use different biomarkers and have different validation evidence.', 'A lifestyle score should not be presented as equivalent to an epigenetic or clinical aging measure.'],
    sources: [{ label: 'NIA — Epigenetics and biological aging', url: 'https://www.nia.nih.gov/news/epigenetics-aging-what-bodys-hands-time-tell-us' }],
  },
  'body-fat-calculator': {
    status: 'needs_manual_review',
    methodology: 'Body-fat percentage varies by measurement method; equations based on circumference, BMI or skinfolds are estimates and require method-specific assumptions.',
    limitations: ['Different methods can disagree substantially.', 'A calculated body-fat percentage is not equivalent to a clinical body-composition assessment.'],
    sources: [],
  },
  'body-recomposition-calculator': {
    status: 'needs_manual_review',
    methodology: 'Body recomposition targets are planning estimates rather than a validated clinical prediction equation.',
    limitations: ['Muscle gain and fat loss depend on training, nutrition, sleep, baseline composition and individual response.', 'Do not present a calculated protein or calorie target as guaranteed muscle gain or fat loss.'],
    sources: [],
  },
  'body-surface-area-calculator': {
    status: 'reviewed',
    methodology: 'BSA can be estimated using published equations including Mosteller, DuBois and DuBois, and Haycock; the formula selected should be stated explicitly.',
    limitations: ['Different BSA equations can produce different values.', 'A consumer BSA result should not be used independently to dose chemotherapy or other medications.'],
    sources: [{ label: 'Mosteller — Simplified calculation of body-surface area', url: 'https://pubmed.ncbi.nlm.nih.gov/3657876/' }],
  },
  'bone-density-risk-calculator': {
    status: 'needs_manual_review',
    methodology: 'Osteoporosis risk is multifactorial; validated fracture-risk tools and clinical assessment should be distinguished from an educational risk score.',
    limitations: ['A custom score should not be presented as a diagnostic osteoporosis test.', 'DXA/BMD testing and validated fracture-risk models use specific populations and inputs.'],
    sources: [{ label: 'NIA — Osteoporosis', url: 'https://www.nia.nih.gov/health/osteoporosis/osteoporosis' }],
  },
  'bone-mineral-density-calculator': {
    status: 'reviewed',
    methodology: 'DXA T-scores and Z-scores must be interpreted according to the applicable reference population and clinical-densitometry guidance.',
    limitations: ['T-scores are not appropriate for every age group; Z-scores are preferred in younger populations.', 'A calculator cannot replace the original DXA report or clinical assessment.'],
    sources: [{ label: 'ISCD — 2023 Adult Official Positions', url: 'https://iscd.org/official-positions-2023/' }],
  },
  'breastfeeding-calorie-calculator': {
    status: 'reviewed',
    methodology: 'Breastfeeding calorie needs vary with baseline needs, activity, BMI, age and whether breastfeeding is exclusive or combined with formula feeding.',
    limitations: ['Energy needs are individualized and do not guarantee milk supply.', 'Hydration and nutrient needs should not be reduced to a single calculator target.'],
    sources: [{ label: 'CDC — Maternal Diet and Breastfeeding', url: 'https://www.cdc.gov/breastfeeding-special-circumstances/hcp/diet-micronutrients/maternal-diet.html' }],
  },
  'breathing-exercise-calculator': {
    status: 'needs_manual_review',
    methodology: 'Breathing-exercise timing is a behavioral pacing tool; there is no single validated formula that personalizes every breathing technique safely.',
    limitations: ['Some breathing practices can cause dizziness or discomfort.', 'People with respiratory or cardiovascular conditions should follow clinician guidance rather than treating a timer as medical therapy.'],
    sources: [],
  },
  'caffeine-half-life-calculator': {
    status: 'reviewed',
    methodology: 'Caffeine concentration can be modeled with exponential decay from an assumed half-life, but the half-life varies materially between individuals and circumstances.',
    limitations: ['Pregnancy, smoking, liver function and medications can change caffeine clearance.', 'A modeled concentration is an estimate, not a laboratory measurement.'],
    sources: [{ label: 'NCBI Bookshelf — Pharmacology of Caffeine', url: 'https://www.ncbi.nlm.nih.gov/books/NBK223808/' }],
  },
  'calcium-calculator': {
    status: 'reviewed',
    methodology: 'Calcium intake targets should use Dietary Reference Intake recommendations that vary by age, sex and life stage.',
    limitations: ['Recommended intake is not the same as a treatment prescription.', 'Supplement use can interact with medications and should be considered with dietary intake and clinical context.'],
    sources: [{ label: 'NIH ODS — Calcium Fact Sheet for Health Professionals', url: 'https://ods.od.nih.gov/factsheets/calcium-HealthProfessional/', sourceDate: '2025-07-11', sourceDateType: 'updated' }],
  },

  'caloric-needs-calculator': {
    status: 'reviewed',
    methodology: 'Daily calorie planning uses the Mifflin–St Jeor resting-energy equation followed by an activity multiplier and an explicit goal adjustment.',
    limitations: ['Energy expenditure is an estimate and should be calibrated against observed trends.', 'A calculated BMR is not a universal minimum safe calorie intake.'],
    sources: [{ label: 'PubMed — Mifflin et al. 1990', url: 'https://pubmed.ncbi.nlm.nih.gov/2305711/' }],
  },
  'calorie-burned-walking-calculator': {
    status: 'needs_manual_review',
    methodology: 'Walking energy expenditure should be estimated from validated MET/activity equations using body weight, duration and intensity.',
    limitations: ['Actual energy expenditure varies by terrain, fitness and gait.', 'The current implementation requires formula-level verification before being described as validated.'],
    sources: [{ label: 'Compendium of Physical Activities', url: 'https://pacompendium.com/' }],
  },
  'calorie-calculator': {
    status: 'reviewed',
    methodology: 'Daily calorie needs are estimated from resting energy expenditure and activity assumptions.',
    limitations: ['TDEE is an estimate, not a direct metabolic measurement.', 'Observed weight and intake trends are useful for calibration.'],
    sources: [{ label: 'PubMed — Mifflin et al. 1990', url: 'https://pubmed.ncbi.nlm.nih.gov/2305711/' }],
  },
  'calorie-deficit-calculator': {
    status: 'needs_manual_review',
    methodology: 'The tool subtracts a selected planning deficit from estimated maintenance energy needs.',
    limitations: ['A selected deficit is not a guarantee of a particular weekly weight-loss rate.', 'Very-low-calorie diets may require clinical supervision.'],
    sources: [],
  },
  'calories-burned-calculator': {
    status: 'needs_manual_review',
    methodology: 'Exercise calorie estimates should use activity-specific MET values and body-weight/duration inputs.',
    limitations: ['MET estimates are population averages.', 'Actual expenditure varies between individuals.'],
    sources: [{ label: 'Compendium of Physical Activities', url: 'https://pacompendium.com/' }],
  },
  'cardiac-output-calculator': {
    status: 'needs_manual_review',
    methodology: 'Cardiac output equals heart rate multiplied by stroke volume. Cardiac index requires body-surface area and SVR requires appropriate hemodynamic assumptions.',
    limitations: ['Manual-input estimates are not equivalent to measured hemodynamics.', 'The current cardiac-index/SVR implementation requires review.'],
    sources: [],
  },
  'cholesterol-calculator': {
    status: 'needs_manual_review',
    methodology: 'LDL is estimated with the Friedewald equation when its assumptions are met; lipid categories are interpreted separately from validated cardiovascular risk models.',
    limitations: ['The current custom risk score is not a validated 10-year CVD model.', 'LDL estimation has limitations at high triglyceride levels.'],
    sources: [],
  },
  'ckd-progression-calculator': {
    status: 'reviewed',
    methodology: 'Educational eGFR-slope scenario with explicit non-prognostic framing; it does not estimate an individualized dialysis date or kidney-failure probability.',
    limitations: ['The calculator is informational and not a diagnosis.', 'Clinical decisions require the appropriate history, examination, laboratory data or validated model when applicable.'],
    sources: [{ label: 'KDIGO — CKD Evaluation and Management', url: 'https://kdigo.org/guidelines/ckd-evaluation-and-management/' }, { label: 'National Kidney Foundation — Kidney Failure Risk Equation', url: 'https://www.kidney.org/professionals/kdoqi/gfr_calculator' }],
  },
  'cognitive-load-calculator': {
    status: 'needs_manual_review',
    methodology: 'The current result is a custom self-report cognitive-load score.',
    limitations: ['Thresholds are heuristic rather than clinical diagnostic cutoffs.', 'The result should not be presented as a measured probability of errors.'],
    sources: [],
  },
  'cold-exposure-calculator': {
    status: 'needs_manual_review',
    methodology: 'Cold-exposure guidance depends on water temperature, duration, acclimatization and individual health factors.',
    limitations: ['Cold-water immersion can produce acute cardiovascular stress.', 'No calculator can guarantee safe immersion.'],
    sources: [],
  },
  'cold-shower-benefits-calculator': {
    status: 'needs_manual_review',
    methodology: 'The tool provides a lifestyle estimate rather than a validated prediction of clinical benefit.',
    limitations: ['Evidence varies by outcome and protocol.', 'Do not translate a score into disease-risk reduction.'],
    sources: [],
  },
  'cortisol-stress-calculator': {
    status: 'needs_manual_review',
    methodology: 'The current score reflects lifestyle/stress factors and does not measure cortisol.',
    limitations: ['Cortisol concentration requires an appropriate biological test and clinical interpretation.', 'The score should not be described as a cortisol measurement.'],
    sources: [],
  },
  'creatine-dosage-calculator': {
    status: 'needs_manual_review',
    methodology: 'Creatine dosing depends on the selected protocol; maintenance and optional loading protocols should be clearly separated.',
    limitations: ['Individual medical conditions and medications can affect supplement decisions.', 'The calculator does not prescribe treatment.'],
    sources: [],
  },
  'creatinine-clearance-calculator': {
    status: 'reviewed',
    methodology: 'Cockcroft–Gault creatinine-clearance estimate using age, weight, serum creatinine and the original sex coefficient; the page distinguishes it from normalized eGFR.',
    limitations: ['The calculator is informational and not a diagnosis.', 'Clinical decisions require the appropriate history, examination, laboratory data or validated model when applicable.'],
    sources: [{ label: 'Cockcroft & Gault — PubMed', url: 'https://pubmed.ncbi.nlm.nih.gov/1244564/' }, { label: 'National Kidney Foundation — eGFR and kidney function', url: 'https://www.kidney.org/kidney-topics/estimated-glomerular-filtration-rate-egfr' }],
  },
  'cycling-calories-calculator': {
    status: 'needs_manual_review',
    methodology: 'Cycling energy expenditure should use activity-specific intensity/MET values, duration and body weight.',
    limitations: ['Terrain, wind, cycling efficiency and fitness affect actual expenditure.'],
    sources: [{ label: 'Compendium of Physical Activities', url: 'https://pacompendium.com/' }],
  },
  'dehydration-calculator': {
    status: 'needs_manual_review',
    methodology: 'Fluid-loss estimates should distinguish measured/pre-exercise weight loss from estimated sweat loss to avoid double counting.',
    limitations: ['Sweat rate varies widely.', 'Severe dehydration symptoms require clinical evaluation.'],
    sources: [{ label: 'CDC — Heat and Athletes', url: 'https://www.cdc.gov/heat-health/risk-factors/heat-and-athletes.html' }],
  },
  'dehydration-status-calculator': {
    status: 'needs_manual_review',
    methodology: 'The current result is an educational status estimate rather than a validated clinical dehydration assessment.',
    limitations: ['Clinical dehydration severity can require examination, vital signs and laboratory data.', 'Do not use the score to rule out serious illness.'],
    sources: [{ label: 'CDC — Heat and Athletes', url: 'https://www.cdc.gov/heat-health/risk-factors/heat-and-athletes.html' }],
  },
  'dental-health-calculator': {
    status: 'needs_manual_review',
    methodology: 'The current result is a self-reported oral-health risk estimate.',
    limitations: ['It does not diagnose dental caries or periodontal disease.', 'Dental examination is required for diagnosis.'],
    sources: [],
  },
  'diabetes-risk-calculator': {
    status: 'needs_manual_review',
    methodology: 'The current implementation is a custom point score. It should not be labeled FINDRISC or treated as the official CDC prediabetes risk test unless the exact validated instrument is implemented.',
    limitations: ['A risk score does not diagnose diabetes or prediabetes.', 'CDC states that blood testing is needed for diagnosis.'],
    sources: [{ label: 'CDC — Prediabetes Risk Test scoring', url: 'https://www.cdc.gov/diabetes/widgets/risktest/how-your-test-is-scored.html' }, { label: 'CDC — Diabetes testing', url: 'https://www.cdc.gov/diabetes/diabetes-testing/index.html' }],
  },
  'diet-quality-score-calculator': {
    status: 'needs_manual_review',
    methodology: 'The current result is a custom weighted diet-quality score rather than a direct implementation of the Healthy Eating Index.',
    limitations: ['Do not call the result an official HEI score without implementing the HEI methodology.', 'Diet quality assessment depends on the dietary instrument and reporting period.'],
    sources: [],
  },
  'dietary-inflammatory-index-calculator': {
    status: 'reviewed',
    methodology: 'A simplified dietary inflammatory pattern score. It is explicitly not the published DII because the published index uses a literature-derived parameter set and global reference distributions.',
    limitations: ['The calculator is informational and not a diagnosis.', 'Clinical decisions require the appropriate history, examination, laboratory data or validated model when applicable.'],
    sources: [{ label: 'Original DII methodology — PubMed', url: 'https://pubmed.ncbi.nlm.nih.gov/23941862/' }, { label: 'DII methodology — PMC', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC3925198/' }],
  },
  'due-date-calculator': {
    status: 'reviewed',
    methodology: 'Estimated due date is 280 days from the first day of the LMP for a typical 28-day cycle, with conception-based estimation using 266 days.',
    limitations: ['LMP recall and cycle variability affect accuracy.', 'ACOG notes that ultrasound dating can be used to confirm or revise the estimated due date.'],
    sources: [{ label: 'ACOG — Methods for Estimating the Due Date', url: 'https://www.acog.org/clinical/clinical-guidance/committee-opinion/articles/2017/05/methods-for-estimating-the-due-date' }],
  },
  'emf-exposure-calculator': {
    status: 'needs_manual_review',
    methodology: 'The current output is a relative exposure score built from device-use and distance assumptions; it is not an RF dosimetry calculation.',
    limitations: ['Actual RF exposure depends on frequency, power, antenna, duty cycle and environment.', 'The score must not be presented as a WHO/ICNIRP health-risk score.'],
    sources: [{ label: 'WHO — Electromagnetic fields', url: 'https://www.who.int/health-topics/electromagnetic-fields' }],
  },
  'erectile-dysfunction-risk-calculator': {
    status: 'needs_manual_review',
    methodology: 'The current output is a custom additive risk-factor score and not a validated probability model.',
    limitations: ['ED has multiple possible causes.', 'A custom score cannot diagnose ED or determine its cause.'],
    sources: [],
  },
  'ergonomics-score-calculator': {
    status: 'needs_manual_review',
    methodology: 'The page references established ergonomic assessment frameworks, but the exact validated instrument scoring rules are not yet demonstrated in the implementation.',
    limitations: ['A custom workstation score is not equivalent to a formal RULA, REBA or ROSA assessment.', 'Work-related musculoskeletal risk is multifactorial.'],
    sources: [],
  },

  'exercise-addiction-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'eye-health-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'fasting-window-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'fat-loss-rate-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'fiber-intake-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'flexibility-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'food-sensitivity-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'frailty-index-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'genetic-height-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'gfr-egfr-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'glycemic-load-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'gratitude-health-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'grip-strength-age-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'grip-strength-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'gut-health-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'hangover-recovery-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'hearing-age-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'heart-age-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'heart-attack-risk-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'heart-rate-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'heart-rate-variability-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'hiit-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'hydration-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'hydration-exercise-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'ideal-weight-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'immune-health-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'immune-strength-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'infant-weight-percentile-calculator': {
    status: 'reviewed',
    methodology: 'WHO weight-for-age reference calculation for 0–24 completed months using published LMS parameters and the LMS z-score transformation.',
    limitations: ['The calculator is informational and not a diagnosis.', 'Clinical decisions require the appropriate history, examination, laboratory data or validated model when applicable.'],
    sources: [{ label: 'WHO Child Growth Standards — Weight-for-age', url: 'https://www.who.int/tools/child-growth-standards/standards/weight-for-age' }, { label: 'WHO Child Growth Standards — Q&A', url: 'https://www.who.int/news-room/questions-and-answers/item/child-growth-standards' }],
  },
  'inflammation-risk-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'injury-recovery-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'intermittent-fasting-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'iron-intake-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'jet-lag-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'joint-mobility-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'keto-macro-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'kidney-function-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'lean-body-mass-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'liver-health-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'loneliness-health-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'longevity-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'longevity-risk-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'lung-capacity-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'macro-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'magnesium-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'marathon-training-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'meal-timing-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'meditation-benefits-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'menopause-symptom-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'menstrual-cycle-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'menstrual-health-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'mental-fatigue-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'mental-health-score-calculator': {
    status: 'reviewed',
    methodology: 'Educational wellbeing score based on the tool inputs. It is not a validated mental-health screening instrument and is not used for diagnosis.',
    limitations: ['The calculator is informational and not a diagnosis.', 'Clinical decisions require the appropriate history, examination, laboratory data or validated model when applicable.'],
    sources: [{ label: 'NIMH — Mental Health Information', url: 'https://www.nimh.nih.gov/health' }, { label: 'NIMH — My Mental Health: Do I Need Help?', url: 'https://www.nimh.nih.gov/health/publications/my-mental-health-do-i-need-help' }],
  },
  'metabolic-age-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'migraine-risk-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'mold-exposure-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'muscle-gain-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'muscle-recovery-time-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'nicotine-withdrawal-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'night-shift-health-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'nutrition-timing-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'nutritional-deficiency-risk-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'obesity-comorbidity-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'omega3-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'one-rep-max-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'oral-health-risk-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'ovulation-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'pace-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'pain-score-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'pcos-risk-calculator': {
    status: 'reviewed',
    methodology: 'Educational PCOS-feature score. It does not implement the international diagnostic criteria or provide a diagnostic probability.',
    limitations: ['The calculator is informational and not a diagnosis.', 'Clinical decisions require the appropriate history, examination, laboratory data or validated model when applicable.'],
    sources: [{ label: '2023 International PCOS Guideline — Monash University', url: 'https://www.monash.edu/medicine/mchri/pcos/guideline' }, { label: '2023 International PCOS Guideline — Research publication', url: 'https://research.monash.edu/en/publications/recommendations-from-the-2023-international-evidence-based-guidel-2/' }],
  },
  'plank-time-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'posture-assessment-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'posture-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'pregnancy-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'pregnancy-conception-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'pregnancy-nutrition-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'pregnancy-weight-gain-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'protein-intake-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'protein-per-meal-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'protein-synthesis-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'pull-up-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'pushup-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'respiratory-rate-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'resting-metabolic-rate-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'running-pace-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'sauna-benefits-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'sauna-health-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'shift-work-health-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'sit-and-reach-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'skin-aging-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'skin-health-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'sleep-cycle-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'sleep-debt-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'sleep-need-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'sodium-intake-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'spo2-risk-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'sprint-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'squat-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'standing-desk-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'steps-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'steps-to-calories-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'stress-level-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'stroke-risk-calculator': {
    status: 'reviewed',
    methodology: 'Educational stroke-risk-factor score. It is not a validated 10-year probability model and must not be interpreted as one.',
    limitations: ['The calculator is informational and not a diagnosis.', 'Clinical decisions require the appropriate history, examination, laboratory data or validated model when applicable.'],
    sources: [{ label: 'American Stroke Association — Stroke risk factors', url: 'https://www.stroke.org/en/about-stroke/stroke-risk-factors' }, { label: 'American Stroke Association — Stroke facts', url: 'https://www.stroke.org/en/stroke-facts' }],
  },
  'sugar-intake-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'sweat-rate-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'swimming-calories-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'target-weight-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'tdee-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'testosterone-age-calculator': {
    status: 'reviewed',
    methodology: 'Lifestyle-support estimate only. Serum testosterone cannot be inferred reliably from age, exercise, sleep, stress, BMI and alcohol inputs.',
    limitations: ['The calculator is informational and not a diagnosis.', 'Clinical decisions require the appropriate history, examination, laboratory data or validated model when applicable.'],
    sources: [{ label: 'Endocrine Society — Hypogonadism in Men', url: 'https://www.endocrine.org/patient-engagement/endocrine-library/hypogonadism' }, { label: 'Endocrine Society — Testosterone therapy guideline resources', url: 'https://www.endocrine.org/clinical-practice-guidelines/testosterone-therapy' }],
  },
  'thyroid-calculator': {
    status: 'reviewed',
    methodology: 'TSH-first interpretation with optional free T4 context. The result is informational and does not diagnose thyroid disease.',
    limitations: ['The calculator is informational and not a diagnosis.', 'Clinical decisions require the appropriate history, examination, laboratory data or validated model when applicable.'],
    sources: [{ label: 'American Thyroid Association — Thyroid Function Tests', url: 'https://www.thyroid.org/thyroid-function-tests/' }, { label: 'American Thyroid Association — How to Order Thyroid Function Tests', url: 'https://www.thyroid.org/wp-content/uploads/2026/01/ATA-Thyroid-Function-Tests.pdf' }],
  },
  'uv-exposure-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'visual-acuity-risk-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'vitamin-c-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'vitamin-d-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'vitamin-d-status-calculator': {
    status: 'reviewed',
    methodology: 'Vitamin-D intake and status-context guidance. The tool does not infer serum 25(OH)D concentration from sunlight or lifestyle inputs.',
    limitations: ['The calculator is informational and not a diagnosis.', 'Clinical decisions require the appropriate history, examination, laboratory data or validated model when applicable.'],
    sources: [{ label: 'NIH Office of Dietary Supplements — Vitamin D Fact Sheet', url: 'https://ods.od.nih.gov/factsheets/Vitamind-HealthProfessional/' }],
  },
  'vo2-max-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'waist-hip-ratio-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'waist-to-height-ratio-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'water-intake-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'workout-volume-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'wound-healing-calculator': {
    status: 'reviewed',
    methodology: 'Educational wound-healing factor assessment based on local and systemic factors; it does not predict an exact healing time or diagnose infection.',
    limitations: ['The calculator is informational and not a diagnosis.', 'Clinical decisions require the appropriate history, examination, laboratory data or validated model when applicable.'],
    sources: [{ label: 'NCBI Bookshelf — Physiology, Wound Healing', url: 'https://www.ncbi.nlm.nih.gov/books/NBK535406/' }, { label: 'PubMed — Factors Affecting Wound Healing', url: 'https://pubmed.ncbi.nlm.nih.gov/20139336/' }],
  },
  'yoga-calories-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },
  'zinc-calculator': {
    status: 'needs_manual_review',
    methodology: 'No claim-level source profile has been assigned yet. This page must not be described as clinically validated until its formula and claims are reviewed against an authoritative source.',
    limitations: ['The calculator output is informational until the underlying method is reviewed.', 'Do not use the result as a diagnosis or treatment recommendation.'],
    sources: [],
  },

}
