export type HealthBatch05Audit = {
  status: 'reviewed' | 'custom_estimate' | 'needs_formula_review' | 'critical_logic_issue' | 'redirect_only'
  formula: string
  implementationNotes: string
  limitations: string[]
  sources: { label: string; url: string; reviewed: string }[]
}

/**
 * Health Batch 05: canonical health order 101–124 plus the legacy due-date
 * redirect at 125. Conservative by design: bespoke scores are never treated
 * as validated diagnostic or prognostic instruments.
 */
export const HEALTH_BATCH_05_AUDITS: Record<string, HealthBatch05Audit> = {
  'mental-fatigue-calculator': { status: 'custom_estimate', formula: 'Custom fatigue score from work hours, sleep, stress, screen time and recovery habits.', implementationNotes: 'The output is an educational fatigue-load estimate. It is not a validated burnout, depression or cognitive-impairment instrument.', limitations: ['Burnout and mental fatigue require context that this score does not capture.', 'Do not use the score as a diagnosis or to make safety-critical decisions.'], sources: [] },
  'mental-health-score-calculator': { status: 'critical_logic_issue', formula: 'Current implementation calculates a BMI/age/sex-derived wellness score rather than a validated mental-health instrument.', implementationNotes: 'The route name and content imply mental-health assessment, but the inputs and formula do not implement PHQ-9, GAD-7, WHO-5 or another named validated instrument. It must not claim evidence-based mental-health scoring until the UI and calculation are migrated together.', limitations: ['The current result does not measure depression, anxiety, wellbeing or another defined mental-health construct.', 'A mental-health screening tool should use its exact validated items, scoring rules and safety messaging.'], sources: [] },
  'metabolic-age-calculator': { status: 'custom_estimate', formula: 'Heuristic metabolic-age estimate from BMI, resting heart rate, fitness, waist-to-height ratio and chronological age.', implementationNotes: '“Metabolic age” is not a single standardized clinical measurement. Keep the result explicitly heuristic and do not describe it as a biological-age test.', limitations: ['The score is model-dependent and not a clinical diagnosis.', 'Resting heart rate and BMI are influenced by many factors beyond metabolic health.'], sources: [] },
  'migraine-risk-calculator': { status: 'custom_estimate', formula: 'Custom symptom/trigger score from headache frequency, family history, sleep, stress, caffeine and other inputs.', implementationNotes: 'The score is not a validated migraine prediction model. Avoid converting it into a disease probability or recommending a fixed supplement dose.', limitations: ['Headache diagnosis depends on history and clinical features.', 'New, severe or neurologically concerning headaches need medical assessment.'], sources: [] },
  'mold-exposure-calculator': { status: 'custom_estimate', formula: 'Custom exposure/response score based on environment and symptom inputs.', implementationNotes: 'There is no validated consumer formula that converts the listed inputs into a numeric mold-illness probability. Keep the result as an exposure-awareness tool.', limitations: ['Mold species, concentration, duration and individual susceptibility vary.', 'Symptoms can have many causes; a calculator cannot diagnose mold-related illness.'], sources: [] },
  'muscle-gain-calculator': { status: 'custom_estimate', formula: 'Planning estimate based on body size, training and nutrition assumptions.', implementationNotes: 'Expected muscle gain is highly variable and should be presented as a planning range rather than a predicted physiological outcome.', limitations: ['Training history, genetics, diet and measurement method materially affect results.', 'The estimate is not a clinical body-composition measurement.'], sources: [] },
  'muscle-recovery-time-calculator': { status: 'custom_estimate', formula: 'Heuristic recovery-hour estimate from muscle group, volume, rep range, training age, age, sleep and protein.', implementationNotes: 'The calculation is a planning heuristic; it is not a validated tissue-healing or readiness model. The ready date is an estimate, not a clearance to train.', limitations: ['Recovery varies by exercise selection, load, soreness, injury and individual response.', 'Pain or injury should not be overridden by the calculated time.'], sources: [] },
  'nicotine-withdrawal-calculator': { status: 'custom_estimate', formula: 'Timeline estimate for common nicotine-withdrawal symptoms based on quit timing and use pattern.', implementationNotes: 'Withdrawal timing is variable. The calculator should provide general education and cessation-support guidance rather than a deterministic symptom forecast.', limitations: ['Symptoms vary in severity and duration.', 'The tool does not diagnose nicotine dependence or provide individualized medication dosing.'], sources: [] },
  'night-shift-health-calculator': { status: 'custom_estimate', formula: 'Custom night-shift health-impact score from duration, frequency, sleep, caffeine, exercise, meal timing and light exposure.', implementationNotes: 'The prior implementation generated unsupported percentages for diabetes/cardiovascular risk and a simplified cancer-risk statement. Those outputs are now treated as qualitative context only; the score is not a validated risk model.', limitations: ['Night-shift health effects depend on schedule, sleep, circadian timing and individual factors.', 'Do not convert the score into a percentage disease risk.'], sources: [{ label: 'IARC — Night shift work and circadian disruption', url: 'https://www.iarc.who.int/news-events/iarc-monographs-evaluate-the-carcinogenicity-of-night-shift-work/', reviewed: '2026-08-08' }] },
  'nutrition-timing-calculator': { status: 'custom_estimate', formula: 'Time-window arithmetic around waking, exercise, bedtime and an optional fasting window.', implementationNotes: 'The clock arithmetic is deterministic, but claims that a specific timing pattern guarantees fat loss, muscle gain or longevity are not supported by this calculator alone.', limitations: ['Nutrition quality and total energy/protein intake matter in addition to timing.', 'Timing recommendations may need adjustment for medical conditions, medications or eating disorders.'], sources: [] },
  'nutritional-deficiency-risk-calculator': { status: 'custom_estimate', formula: 'Diet-pattern screening score for possible nutrient gaps from food intake and dietary restrictions.', implementationNotes: 'This is a screening/education tool, not a laboratory deficiency diagnosis. Fortified foods and supplements can materially change nutrient exposure.', limitations: ['Diet recall is imperfect.', 'Blood tests and clinical assessment may be needed to diagnose deficiency.', 'Do not infer a treatment dose from a dietary screening result.'], sources: [] },
  'obesity-comorbidity-calculator': { status: 'needs_formula_review', formula: 'BMI plus metabolic-syndrome-style components and heuristic comorbidity flags.', implementationNotes: 'The current implementation mixes established thresholds with custom diabetes, fatty-liver and sleep-apnea heuristics. It should not output percentage disease risk or diagnose conditions without a validated model.', limitations: ['BMI and waist circumference are screening measures, not diagnoses.', 'Validated disease-risk models require their own defined populations and inputs.'], sources: [] },
  'omega3-calculator': { status: 'reviewed', formula: 'Dietary EPA/DHA planning estimate based on fish/seafood intake and supplement inputs.', implementationNotes: 'Keep dietary intake estimates separate from clinical treatment dosing. The calculator should distinguish food sources from supplements.', limitations: ['Food composition varies by species, portion and preparation.', 'People taking anticoagulants or managing medical conditions should discuss high-dose supplementation with a clinician.'], sources: [{ label: 'NIH ODS — Omega-3 Fatty Acids Fact Sheet', url: 'https://ods.od.nih.gov/factsheets/Omega3FattyAcids-HealthProfessional/', reviewed: '2026-08-08' }] },
  'one-rep-max-calculator': { status: 'reviewed', formula: 'Estimated 1RM using named repetition-based equations such as Epley and Brzycki.', implementationNotes: 'These are strength-training prediction equations, not clinical formulas. The result should be presented as an estimate and exercise-specific.', limitations: ['Prediction error varies with rep range and exercise.', 'Maximal lifting carries injury risk; estimates should not be treated as a safety clearance.'], sources: [] },
  'oral-health-risk-calculator': { status: 'custom_estimate', formula: 'Custom oral-health behavior score from brushing, interdental cleaning, diet, smoking, dry mouth and dental-visit history.', implementationNotes: 'The score is not a validated caries, periodontal or oral-cancer risk model. Remove unsupported claims such as a fixed 2× cardiovascular-risk multiplier or 6× oral-cancer multiplier from the calculator output.', limitations: ['A score cannot diagnose cavities, periodontal disease or oral cancer.', 'Dental examination is required for diagnosis.'], sources: [{ label: 'American Dental Association — Toothbrushes', url: 'https://www.ada.org/resources/ada-library/oral-health-topics/toothbrushes', reviewed: '2026-08-08' }, { label: 'American Dental Association — Dental Floss/Interdental Cleaners', url: 'https://www.ada.org/resources/ada-library/oral-health-topics/floss', reviewed: '2026-08-08' }] },
  'ovulation-calculator': { status: 'reviewed', formula: 'Calendar estimate using the expected next period and an approximate 14-day luteal interval.', implementationNotes: 'Ovulation timing is an estimate. It must not be presented as a guaranteed fertile-window detector or contraceptive method.', limitations: ['Cycle variability can shift ovulation.', 'Fertility-awareness methods have different effectiveness depending on the specific method and use.'], sources: [{ label: 'ACOG — Fertility Awareness-Based Methods', url: 'https://www.acog.org/womens-health/faqs/fertility-awareness-based-methods-of-family-planning', reviewed: '2026-08-08' }, { label: 'ACOG — Trying to Get Pregnant', url: 'https://www.acog.org/womens-health/experts-and-stories/the-latest/trying-to-get-pregnant-heres-when-to-have-sex', reviewed: '2026-08-08' }] },
  'pace-calculator': { status: 'reviewed', formula: 'Distance/time arithmetic for running or walking pace, with unit conversion.', implementationNotes: 'This is deterministic arithmetic. Any performance interpretation should remain separate from the pace calculation.', limitations: ['Pace does not predict race performance by itself.', 'Terrain, conditions and fitness affect sustainable pace.'], sources: [] },
  'pain-score-calculator': { status: 'custom_estimate', formula: 'Custom composite from pain intensity, frequency, sleep disruption, activity limitation and quality-of-life inputs.', implementationNotes: 'The composite is not the Numeric Rating Scale, Brief Pain Inventory or another validated pain instrument. Keep the output informational.', limitations: ['Pain is subjective and multidimensional.', 'Severe, sudden or unexplained pain may require urgent evaluation.'], sources: [] },
  'pcos-risk-calculator': { status: 'critical_logic_issue', formula: 'Current implementation uses a custom weighted score but labels it as Rotterdam-criteria based.', implementationNotes: 'Rotterdam criteria are diagnostic criteria, not a points-based percentage model. The current score must not output a “PCOS likelihood” percentage or claim to implement Rotterdam until the inputs and diagnostic logic are redesigned.', limitations: ['PCOS diagnosis requires clinical evaluation and exclusion of alternative causes.', 'Irregular cycles, hyperandrogenism and polycystic ovarian morphology are not interchangeable numeric points.'], sources: [{ label: 'ACOG — Polycystic Ovary Syndrome', url: 'https://www.acog.org/womens-health/faqs/polycystic-ovary-syndrome-pcos', reviewed: '2026-08-08' }] },
  'plank-time-calculator': { status: 'custom_estimate', formula: 'Performance estimate from plank duration and selected training variables.', implementationNotes: 'Strength/endurance categories are heuristic unless tied to a defined population norm.', limitations: ['Performance varies with technique and testing protocol.', 'The result is not a medical assessment.'], sources: [] },
  'posture-assessment-calculator': { status: 'custom_estimate', formula: 'Composite self-assessment of head/shoulder position, pelvic position, knee alignment, feet and sitting exposure.', implementationNotes: 'The score is not RULA, REBA, ROSA or another validated ergonomic instrument.', limitations: ['Posture varies by task and movement.', 'A static self-assessment cannot diagnose musculoskeletal disorders.'], sources: [] },
  'posture-calculator': { status: 'custom_estimate', formula: 'Custom posture score from user-entered alignment and workstation factors.', implementationNotes: 'The result is educational and should not be described as a clinically validated posture or injury-risk prediction.', limitations: ['Pain and function cannot be inferred from posture score alone.', 'Persistent pain or neurological symptoms require assessment.'], sources: [] },
  'pregnancy-calculator': { status: 'reviewed', formula: 'Estimated due date using LMP/conception calendar arithmetic and gestational-age calculations.', implementationNotes: 'ACOG states that 280 days/40 weeks from the first day of LMP is the conventional estimate and that ultrasound may be used to confirm or establish dating when appropriate.', limitations: ['LMP recall and cycle variability affect accuracy.', 'An estimated due date does not replace prenatal care or clinical dating.'], sources: [{ label: 'ACOG — When Pregnancy Goes Past Your Due Date', url: 'https://www.acog.org/womens-health/faqs/when-pregnancy-goes-past-your-due-date', reviewed: '2026-08-08' }, { label: 'ACOG — Methods for Estimating the Due Date', url: 'https://www.acog.org/clinical/clinical-guidance/committee-opinion/articles/2017/05/methods-for-estimating-the-due-date', reviewed: '2026-08-08' }] },
  'pregnancy-conception-calculator': { status: 'custom_estimate', formula: 'Calendar back-calculation from estimated due date/gestational timing.', implementationNotes: 'Conception timing is an estimate because ovulation and fertilization timing vary. Keep it clearly labeled as an estimate.', limitations: ['A conception date cannot usually be known exactly from calendar arithmetic.', 'Ultrasound dating and clinical history can change pregnancy dating.'], sources: [{ label: 'ACOG — Methods for Estimating the Due Date', url: 'https://www.acog.org/clinical/clinical-guidance/committee-opinion/articles/2017/05/methods-for-estimating-the-due-date', reviewed: '2026-08-08' }] },
  'pregnancy-due-date-calculator': { status: 'redirect_only', formula: 'Legacy route redirects permanently to pregnancy-calculator.', implementationNotes: 'Do not publish or index this URL as a canonical calculator page. Preserve the redirect for existing links and bookmarks.', limitations: ['Use /calculators/health/pregnancy-calculator as the canonical destination.'], sources: [] },
}
