import { CalculatorBatch48DeepDive } from '@/components/ui/CalculatorBatch48DeepDive'
import type { Metadata } from 'next'
import { generateCalculatorMetadata, generateFAQStructuredData, generateWebAppStructuredData } from '@/lib/seo/metadata'
import dynamic from 'next/dynamic'
const CalculatorClient = dynamic(() => import('./CalculatorClient'), {  loading: () => <div className="min-h-[400px] bg-white rounded-2xl border border-gray-100 animate-pulse m-4" /> })
export const metadata: Metadata = generateCalculatorMetadata({ title: 'EMF Exposure Calculator — Relative RF Exposure Score 2026 | ToolTrio', description: 'Free EMF (electromagnetic field) exposure calculator 2026. Score your relative RF and EMF exposure from phone use, Wi-Fi, smart meters, and microwave ovens. Educational tool based on WHO and ICNIRP guidelines.', slug: 'emf-exposure-calculator', category: 'health', region: 'usa', keywords: ['EMF exposure calculator', 'RF radiation exposure calculator', 'phone radiation calculator', 'Wi-Fi EMF exposure score', 'electromagnetic field health calculator'] })
const relatedCalculators = [{'name': 'Mental Fatigue', 'href': '/calculators/health/mental-fatigue-calculator', 'icon': '🧠', 'desc': 'Screen time fatigue'}, {'name': 'Sleep Debt', 'href': '/calculators/health/sleep-debt-calculator', 'icon': '😴', 'desc': 'Sleep quality'}, {'name': 'Longevity Risk', 'href': '/calculators/health/longevity-risk-calculator', 'icon': '♾️', 'desc': 'Longevity factors'}, {'name': 'Visual Acuity Risk', 'href': '/calculators/health/visual-acuity-risk-calculator', 'icon': '👁️', 'desc': 'Eye health risk'}]
const faqs = [
  {"question": "What does the science say about EMF health effects?", "answer": "The World Health Organization (WHO) and International Commission on Non-Ionizing Radiation Protection (ICNIRP) regularly review EMF research. Current scientific consensus: no convincing evidence of health harm at typical consumer exposure levels, which are well below international safety limits. The 2011 IARC classification of radiofrequency fields as 'possibly carcinogenic' (Group 2B) is the same category as coffee and pickled vegetables — indicating limited evidence insufficient to confirm a relationship. The 2019 ICNIRP guidelines update maintained existing limits after reviewing all studies through 2018. This calculator is educational — it helps users understand relative exposure patterns, not health risk."},
  {"question": "How does distance affect EMF exposure?", "answer": "EMF intensity follows an inverse square law — doubling distance from a source reduces exposure by 75% (not 50%). Moving a phone from directly against your ear to speakerphone 12 inches away reduces RF exposure to the head by approximately 98%. Similarly, positioning a Wi-Fi router 10 feet away rather than 2 feet reduces exposure by 96%. This principle makes distance-based precaution highly effective for those wishing to minimise exposure. Smart meter RF exposure at 10 feet is comparable to a Wi-Fi router at 10 feet — far less than holding a phone to your ear for a call."},
  {"question": "What simple steps reduce RF exposure most effectively?", "answer": "The highest-impact reductions: (1) Use speakerphone or wired earphones for calls — reduces head RF exposure ~98%; (2) Move phone 6+ feet from sleeping area — eliminates 8+ hours of close proximity; (3) Prefer Wi-Fi or speakerphone for video calls over cellular data; (4) Keep phone in bag rather than pocket when not in use; (5) Move router 6+ feet from frequent sitting areas. These measures cost nothing and dramatically reduce total cumulative exposure for those with concerns, regardless of whether current evidence confirms harm at typical consumer levels."}
]
export default function Page() {
  const _faqSchema = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faqs.map((f: any) => ({ '@type': 'Question', name: f.question, acceptedAnswer: { '@type': 'Answer', text: f.answer } })) }
  return (<><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(_faqSchema) }} /><CalculatorClient faqs={faqs} structuredData={[generateFAQStructuredData(faqs), generateWebAppStructuredData({ name: 'EMF Exposure Score Calculator', description: 'Free EMF (electromagnetic field) exposure calculator 2026. Score your relative RF and EMF exposure f', url: 'https://tooltrio.com/calculators/health/emf-exposure-calculator', category: 'HealthApplication' })]} relatedCalculators={relatedCalculators} />      <CalculatorBatch48DeepDive slug="emf-exposure-calculator" />
</>)
}
