import type { Metadata } from 'next'
import { generateCalculatorMetadata, generateFAQStructuredData } from '@/lib/seo/metadata'
import dynamic from 'next/dynamic'
const CalculatorClient = dynamic(() => import('./CalculatorClient'), { ssr: false, loading: () => <div className="min-h-[400px] bg-white rounded-2xl border border-gray-100 animate-pulse m-4" /> })
export const metadata: Metadata = generateCalculatorMetadata({ title: 'Capital Gains Harvesting Calculator USA 2026 | ToolTrio', description: 'Calculate capital gains tax harvesting opportunities. Find your 0% LTCG tax space, optimize loss harvesting, and minimize capital gains taxes in your investment portfolio.', slug: 'capital-gains-harvesting-calculator', category: 'finance', keywords: ['capital gains harvesting calculator USA', 'tax gain harvesting 2026', '0% capital gains bracket calculator', 'tax loss harvesting calculator USA'] })
const faqs = [('What is tax gain harvesting?', 'Tax gain harvesting deliberately realizes capital gains in years when your income is low enough to qualify for the 0% long-term capital gains rate (below $47,025 single / $94,050 married in 2026). You sell appreciated assets, pay zero tax, then immediately repurchase — resetting your cost basis higher. This reduces future taxable gains. Unlike the wash sale rule (which applies to losses), there is no 30-day restriction for gains.'), ('How does tax-loss harvesting work?', 'Tax-loss harvesting sells investments at a loss to offset capital gains, reducing your tax bill. Losses first offset gains dollar-for-dollar. If losses exceed gains, up to $3,000/year can offset ordinary income, with excess carried forward indefinitely. On $50,000 in gains, $20,000 in harvested losses reduces taxable gains to $30,000, saving $3,000-$4,000 in taxes at LTCG rates.')]
const relatedCalculators = [{'name': 'Tax-Loss Harvesting', 'href': '/calculators/finance/tax-loss-harvesting-calculator', 'icon': '🌱', 'desc': 'Harvest losses'}, {'name': 'Capital Gains Tax', 'href': '/calculators/finance/capital-gains-tax-calculator', 'icon': '📈', 'desc': 'LTCG calculator'}, {'name': 'Qualified Dividend Tax', 'href': '/calculators/finance/qualified-dividend-tax-calculator', 'icon': '💰', 'desc': 'Dividend taxes'}]
const structuredData = [generateFAQStructuredData(faqs)]
export default function Page() { return <>{structuredData.map((s, i) => <script key={i} type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(s) }} />)}<CalculatorClient faqs={faqs} structuredData={structuredData} relatedCalculators={relatedCalculators} /></> }
