import type { Metadata } from 'next'
import { generateCalculatorMetadata, generateFAQStructuredData } from '@/lib/seo/metadata'
import dynamic from 'next/dynamic'
const CalculatorClient = dynamic(() => import('./CalculatorClient'), { ssr: false, loading: () => <div className="min-h-[400px] bg-white rounded-2xl border border-gray-100 animate-pulse m-4" /> })
export const metadata: Metadata = generateCalculatorMetadata({ title: 'Charitable Giving Tax Calculator USA 2026 | ToolTrio', description: 'Calculate the true after-tax cost of charitable donations. Compare cash vs appreciated stock donations, Donor Advised Funds, and maximize your charitable tax deduction.', slug: 'charitable-giving-tax-calculator', category: 'finance', keywords: ['charitable giving tax calculator USA', 'appreciated stock donation tax savings', 'donor advised fund calculator', 'charitable deduction 2026'] })
const faqs = [('Is it better to donate cash or appreciated stock to charity?', 'Donating appreciated stock is almost always better than selling and donating cash. When you donate stock directly, you get a deduction for the full fair market value AND avoid paying capital gains tax on the appreciation. For example, stock worth $10,000 with a $2,000 basis: donating stock saves $1,600 in capital gains vs selling (at 20% rate) plus you still get the full $10,000 deduction.'), ('What is a Donor Advised Fund (DAF)?', 'A DAF lets you make a large charitable contribution in one year for the full tax deduction, then recommend grants to charities over time. This is useful for bunching deductions — combining multiple years of charitable giving into one year to exceed the standard deduction ($15,000 single / $30,000 married in 2026). You can donate appreciated assets to a DAF, avoid capital gains, and the assets grow tax-free until distributed.')]
const relatedCalculators = [{'name': 'Estate Tax Calculator', 'href': '/calculators/finance/estate-tax-calculator', 'icon': '🏛️', 'desc': 'Estate planning'}, {'name': 'Tax Bracket Calculator', 'href': '/calculators/finance/tax-bracket-calculator', 'icon': '🧾', 'desc': 'Your tax bracket'}, {'name': 'Income Tax Calculator', 'href': '/calculators/finance/income-tax-calculator', 'icon': '📋', 'desc': 'Federal tax'}]
const structuredData = [generateFAQStructuredData(faqs)]
export default function Page() { return <>{structuredData.map((s, i) => <script key={i} type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(s) }} />)}<CalculatorClient faqs={faqs} structuredData={structuredData} relatedCalculators={relatedCalculators} /></> }
