'use client'
import { useState } from 'react'
import { ZipQuickFill } from '@/components/ui/ZipQuickFill'
import { zipFetch } from '@/lib/data/zip-client'

function shareResult(result: any) {
  const text = `📬 ZIP+4 Info: ${result.zip}\n📍 ${result.city}, ${result.state}\n👥 Population: ${result.population > 0 ? result.population.toLocaleString() : 'N/A'}\n🕐 ${result.tzLabel}\nGet your ZIP+4: tooltrio.com/zip/zip-plus-4-lookup`
  if (navigator.share) navigator.share({ title: 'ZIP+4 Lookup', text })
  else navigator.clipboard.writeText(text).then(() => alert('Copied!'))
}

function downloadResult(result: any) {
  const text =
`ZIP+4 Lookup Report

Base ZIP: ${result.zip}
City: ${result.city}, ${result.state}
County: ${result.county}
Type: ${result.type}
Population: ${result.population > 0 ? result.population.toLocaleString() : 'N/A'}
Timezone: ${result.tzLabel}
Area Code: (${result.areaCode})

ZIP+4 Format:
${result.zip}-XXXX

The exact four-digit suffix depends on the specific delivery destination.
Use the official USPS ZIP Code Lookup with a complete street address
to determine the correct ZIP+4.

Generated by ToolTrio
tooltrio.com/zip/zip-plus-4-lookup`

  const blob = new Blob([text], { type: 'text/plain' })
  const a = document.createElement('a')

  a.href = URL.createObjectURL(blob)
  a.download = `zip-plus4-${result.zip}.txt`
  a.click()

  URL.revokeObjectURL(a.href)
}

const USPS_LOOKUP = 'https://tools.usps.com/zip-code-lookup.htm?byaddress'





export default function ZipToolClient() {
  const [zip, setZip] = useState('')
  const [result, setResult] = useState<any>(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')

  async function lookup(z?: string) {
    const val = (z || zip).trim(); if (z) setZip(z)
    if (!/^\d{5}$/.test(val)) { setError('Enter a valid 5-digit ZIP'); setResult(null); return }
    setLoading(true); setError('')
    const res = await zipFetch(`/api/zip/lookup?zip=${val}`)
    const data = await res.json(); setLoading(false)
    if (!res.ok) { setError(data.error); setResult(null); return }
    setResult(data)
  }



  return (
    <div>
  <ZipQuickFill onSelect={z => lookup(z)} />

{/* ── ZIP+4 Search ───────────────────────────── */}
<div className="mb-5">

  <div className="mb-2">
    <label
      htmlFor="zip-plus4-input"
      className="block text-sm font-bold text-gray-800"
    >
      Enter a 5-Digit ZIP Code
    </label>

    <p className="text-xs text-gray-500 mt-1">
      Check the base ZIP first, then use your street address to find the exact ZIP+4.
    </p>
  </div>

  <div className="flex flex-col sm:flex-row gap-2">

    <div className="relative flex-1">

      <span
        className="
          absolute
          left-4
          top-1/2
          -translate-y-1/2
          text-gray-400
          pointer-events-none
        "
      >
        📍
      </span>

      <input
        id="zip-plus4-input"
        value={zip}
        onChange={e => {
          setZip(e.target.value.replace(/\D/g, ''))
          setError('')
        }}
        onKeyDown={e => e.key === 'Enter' && lookup()}
        placeholder="e.g. 10001"
        maxLength={5}
        inputMode="numeric"
        autoComplete="postal-code"
        aria-label="Enter 5-digit ZIP code"
        className="
          w-full
          border-2
          border-gray-200
          rounded-xl
          pl-11
          pr-4
          py-3
          text-lg
          font-mono
          font-semibold
          text-gray-900
          bg-white
          focus:outline-none
          focus:border-green-500
          focus:ring-4
          focus:ring-green-100
          transition-all
        "
      />

    </div>

    <button
      onClick={() => lookup()}
      disabled={loading || zip.length !== 5}
      className="
        sm:min-w-[170px]
        px-6
        py-3
        rounded-xl
        text-white
        font-bold
        disabled:opacity-50
        disabled:cursor-not-allowed
        hover:-translate-y-0.5
        transition-all
      "
      style={{
        background: 'linear-gradient(135deg,#22c55e,#16a34a)',
        boxShadow: '0 4px 16px rgba(34,197,94,0.25)'
      }}
    >
      {loading ? 'Checking...' : '🔍 Check ZIP'}
    </button>

  </div>

  <div className="flex flex-wrap gap-x-4 gap-y-1 mt-2 text-[11px] text-gray-400">

    <span>✓ 5-digit US ZIP Codes</span>

    <span>✓ Free lookup</span>

    <span>✓ No signup</span>

  </div>

</div>
      {error && <div className="p-3 rounded-xl bg-red-50 border border-red-200 text-red-700 mb-4 text-sm">{error}</div>}
      {result && (
        <div>
          <div className="rounded-2xl border p-5 mb-4" style={{ background: 'rgba(240,253,244,0.7)', borderColor: 'rgba(187,247,208,0.6)' }}>
            {/* ── ZIP+4 Result Hero ─────────────────────────── */}
<div className="text-center mb-5">

  <div
    className="
      inline-flex
      items-center
      gap-1.5
      px-3
      py-1
      rounded-full
      bg-green-100
      text-green-700
      text-[11px]
      font-bold
      mb-3
    "
  >
    ✓ VALID BASE ZIP CODE
  </div>

  <div className="flex items-center justify-center gap-1 font-mono">

    <span className="text-4xl font-black text-gray-900">
      {result.zip}
    </span>

    <span className="text-4xl font-black text-gray-400">
      -
    </span>

    <span className="text-4xl font-black text-blue-600">
      XXXX
    </span>

  </div>

  <div className="font-bold text-gray-800 mt-2">
    {result.city}, {result.state}
  </div>

  <div className="text-xs text-gray-500 mt-1">
    Base ZIP Code {result.zip}
  </div>

</div>

            <div className="rounded-xl bg-blue-50 border border-blue-100 p-3 mb-4 text-sm text-blue-800">
              <p className="font-bold mb-1">📬 What is ZIP+4?</p>
              <p className="text-xs leading-relaxed">The 4-digit extension (e.g. <span className="font-mono font-bold">{result.zip}-1234</span>) identifies a specific delivery segment within this ZIP — a city block, building floor, or PO Box range. It improves mail delivery accuracy and is required for USPS bulk mail discounts.</p>
            </div>

            <div className="grid grid-cols-2 sm:grid-cols-3 gap-3 mb-4">
             {[
  {
    label: '📍 Base ZIP',
    value: result.zip
  },
  {
    label: '🏙️ City',
    value: result.city
  },
  {
    label: '🗺️ State',
    value: `${result.state} (${result.stateCode})`
  },
  {
    label: '🏛️ County',
    value: result.county
  },
  {
    label: '📬 ZIP Type',
    value: result.type
  },
  {
    label: '🕐 Timezone',
    value: result.tzLabel
  },
].map((r: any) => (
                <div key={r.label} className="rounded-xl border p-3 bg-white/70">
                  <div className="text-xs text-gray-400">{r.label}</div>
                  <div className="font-bold text-gray-900 text-sm">{r.value}</div>
                </div>
              ))}
            </div>

      {/* ZIP+4 explanation */}
<div className="rounded-xl border border-blue-100 bg-white/80 p-4 mb-4">

  <div className="flex items-start gap-3">

    <div className="text-2xl">
      📬
    </div>

    <div>

      <p className="font-bold text-gray-800 text-sm">
        ZIP+4 format for {result.zip}
      </p>

      <div className="mt-2 flex items-center gap-2">

        <span className="font-mono text-lg font-black text-gray-900">
          {result.zip}
        </span>

        <span className="text-gray-400">
          -
        </span>

        <span className="font-mono text-lg font-black text-blue-600">
          XXXX
        </span>

      </div>

      <p className="text-xs text-gray-500 mt-2 leading-relaxed">
        The four additional digits depend on the specific delivery
        destination within ZIP Code {result.zip}. Enter your complete
        street address in the official USPS lookup to find the correct
        ZIP+4.
      </p>

    </div>

  </div>

</div>

          {/* ── Exact ZIP+4 CTA ──────────────────────────── */}
{/* ── Exact ZIP+4 Address Flow ─────────────────── */}
<div className="rounded-2xl border border-blue-200 bg-blue-50/50 p-4 mb-4">

  <div className="text-center mb-4">

    <div className="inline-flex items-center gap-2 text-sm font-bold text-gray-900">
      🏠 Find the Exact ZIP+4 for Your Address
    </div>

    <p className="text-xs text-gray-500 mt-1">
      ZIP {result.zip} is the base ZIP. The exact +4 depends on your
      specific delivery address.
    </p>

  </div>


  {/* Steps */}
  <div className="grid grid-cols-1 sm:grid-cols-3 gap-2 mb-4">

    <div className="rounded-xl border border-blue-100 bg-white p-3">

      <div className="flex items-center gap-2">

        <div className="
          w-6 h-6
          rounded-full
          bg-blue-100
          text-blue-700
          text-xs
          font-black
          flex
          items-center
          justify-center
          shrink-0
        ">
          1
        </div>

        <div className="text-xs font-bold text-gray-800">
          Have Your Address Ready
        </div>

      </div>

      <p className="text-[11px] text-gray-500 mt-2 leading-4">
        Use the complete street address for the destination.
      </p>

    </div>


    <div className="rounded-xl border border-blue-100 bg-white p-3">

      <div className="flex items-center gap-2">

        <div className="
          w-6 h-6
          rounded-full
          bg-blue-100
          text-blue-700
          text-xs
          font-black
          flex
          items-center
          justify-center
          shrink-0
        ">
          2
        </div>

        <div className="text-xs font-bold text-gray-800">
          Open USPS Lookup
        </div>

      </div>

      <p className="text-[11px] text-gray-500 mt-2 leading-4">
        Enter the street address, city, state and ZIP when requested.
      </p>

    </div>


    <div className="rounded-xl border border-blue-100 bg-white p-3">

      <div className="flex items-center gap-2">

        <div className="
          w-6 h-6
          rounded-full
          bg-blue-100
          text-blue-700
          text-xs
          font-black
          flex
          items-center
          justify-center
          shrink-0
        ">
          3
        </div>

        <div className="text-xs font-bold text-gray-800">
          Get Your ZIP+4
        </div>

      </div>

      <p className="text-[11px] text-gray-500 mt-2 leading-4">
        USPS returns the standardized address and applicable ZIP+4.
      </p>

    </div>

  </div>


  {/* Current ZIP */}
  <div className="flex items-center justify-between gap-3 rounded-xl bg-white border border-blue-100 px-4 py-3 mb-3">

    <div>

      <div className="text-[10px] uppercase tracking-wide text-gray-400 font-bold">
        Base ZIP you checked
      </div>

      <div className="font-mono font-black text-gray-900 mt-0.5">
        {result.zip}
      </div>

    </div>

    <div className="text-right">

      <div className="text-[10px] uppercase tracking-wide text-gray-400 font-bold">
        ZIP+4 Format
      </div>

      <div className="font-mono font-black mt-0.5">
        <span className="text-gray-900">{result.zip}</span>
        <span className="text-blue-600">-XXXX</span>
      </div>

    </div>

  </div>


  {/* Official USPS CTA */}
  <a
    href={USPS_LOOKUP}
    target="_blank"
    rel="noopener noreferrer"
    className="
      w-full
      flex
      items-center
      justify-center
      gap-2
      py-3
      px-4
      rounded-xl
      text-sm
      font-bold
      text-white
      hover:-translate-y-0.5
      transition-all
    "
    style={{
      background: 'linear-gradient(135deg,#2563eb,#1d4ed8)',
      boxShadow: '0 4px 14px rgba(37,99,235,0.25)'
    }}
  >
    🏛️ Continue to Official USPS ZIP+4 Lookup
    <span>↗</span>
  </a>


  <p className="text-[10px] text-gray-400 text-center mt-2">
    Opens the official USPS website in a new tab.
  </p>

</div>
          </div>


{/* ── 5-Digit ZIP vs ZIP+4 ───────────────────────── */}
<div className="rounded-2xl border border-gray-200 bg-white p-5 mb-4">

  <div className="text-center mb-4">
    <h3 className="text-lg font-bold text-gray-900">
      5-Digit ZIP vs. ZIP+4
    </h3>

    <p className="text-xs text-gray-500 mt-1">
      ZIP {result.zip} identifies the general delivery area.
      ZIP+4 narrows it to a more specific USPS delivery segment.
    </p>
  </div>

  <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">

    {/* 5-Digit ZIP */}
    <div className="rounded-xl border border-green-200 bg-green-50/60 p-4">

      <div className="flex items-center gap-2 mb-3">
        <span className="text-xl">📍</span>

        <div>
          <div className="text-xs text-gray-500">
            Standard ZIP Code
          </div>

          <div className="text-2xl font-black font-mono text-green-700">
            {result.zip}
          </div>
        </div>
      </div>

      <div className="space-y-2 text-xs text-gray-600">

        <div className="flex gap-2">
          <span className="text-green-600">✓</span>
          <span>Identifies a general USPS delivery area</span>
        </div>

        <div className="flex gap-2">
          <span className="text-green-600">✓</span>
          <span>
            Associated with {result.city}, {result.stateCode}
          </span>
        </div>

        <div className="flex gap-2">
          <span className="text-green-600">✓</span>
          <span>Can cover many addresses</span>
        </div>

      </div>

    </div>

    {/* ZIP+4 */}
    <div className="rounded-xl border border-blue-200 bg-blue-50/60 p-4">

      <div className="flex items-center gap-2 mb-3">
        <span className="text-xl">📬</span>

        <div>
          <div className="text-xs text-gray-500">
            ZIP+4 Code
          </div>

          <div className="text-2xl font-black font-mono">
            <span className="text-gray-900">
              {result.zip}
            </span>

            <span className="text-blue-600">
              -XXXX
            </span>
          </div>
        </div>
      </div>

      <div className="space-y-2 text-xs text-gray-600">

        <div className="flex gap-2">
          <span className="text-blue-600">✓</span>
          <span>Adds four digits to the base ZIP</span>
        </div>

        <div className="flex gap-2">
          <span className="text-blue-600">✓</span>
          <span>Identifies a more specific delivery segment</span>
        </div>

        <div className="flex gap-2">
          <span className="text-blue-600">✓</span>
          <span>Requires the complete address for an exact lookup</span>
        </div>

      </div>

    </div>

  </div>

  <div className="mt-4 rounded-xl bg-gray-50 border border-gray-100 p-3">

    <p className="text-xs text-gray-600 text-center leading-5">
      <strong>Example:</strong>{' '}
      <span className="font-mono font-bold">
        {result.zip}
      </span>{' '}
      is the base ZIP Code, while{' '}
      <span className="font-mono font-bold text-blue-600">
        {result.zip}-1234
      </span>{' '}
      demonstrates the ZIP+4 format. The actual four digits depend on
      the specific delivery address.
    </p>

  </div>

</div>


{/* ── Dynamic ZIP+4 FAQ ─────────────────────────── */}
<div className="rounded-2xl border border-gray-200 bg-white p-5 mb-4">

  {/* Header */}
  <div className="mb-4">

    <h3 className="text-lg font-bold text-gray-900">
      ZIP+4 Questions for {result.zip}
    </h3>

    <p className="text-xs text-gray-500 mt-1">
      Quick answers about ZIP+4 codes for {result.city}, {result.stateCode}.
    </p>

  </div>


  <div className="space-y-2">

    {/* FAQ 1 */}
    <details className="group rounded-xl border border-gray-200 bg-gray-50/50 overflow-hidden">

      <summary
        className="
          flex
          items-center
          justify-between
          gap-3
          cursor-pointer
          list-none
          px-4
          py-3
          text-sm
          font-semibold
          text-gray-800
          hover:bg-gray-50
        "
      >

        <span>
          What is the ZIP+4 format for {result.zip}?
        </span>

        <span className="text-gray-400 group-open:rotate-180 transition-transform">
          ▾
        </span>

      </summary>

      <div className="border-t border-gray-100 px-4 py-3 text-sm text-gray-600 leading-6">

        The ZIP+4 format begins with the 5-digit base ZIP{' '}

        <strong>{result.zip}</strong>

        {' '}followed by a hyphen and four additional digits:

        <strong className="font-mono text-blue-600">
          {' '}{result.zip}-XXXX
        </strong>.

        The exact four digits depend on the specific delivery destination.

      </div>

    </details>


    {/* FAQ 2 */}
    <details className="group rounded-xl border border-gray-200 bg-gray-50/50 overflow-hidden">

      <summary
        className="
          flex
          items-center
          justify-between
          gap-3
          cursor-pointer
          list-none
          px-4
          py-3
          text-sm
          font-semibold
          text-gray-800
          hover:bg-gray-50
        "
      >

        <span>
          Does ZIP Code {result.zip} have more than one ZIP+4 code?
        </span>

        <span className="text-gray-400 group-open:rotate-180 transition-transform">
          ▾
        </span>

      </summary>

      <div className="border-t border-gray-100 px-4 py-3 text-sm text-gray-600 leading-6">

        Yes. A 5-digit ZIP code can have multiple ZIP+4 codes because the
        additional four digits identify more specific USPS delivery
        segments within the base ZIP Code <strong>{result.zip}</strong>.

      </div>

    </details>


    {/* FAQ 3 */}
    <details className="group rounded-xl border border-gray-200 bg-gray-50/50 overflow-hidden">

      <summary
        className="
          flex
          items-center
          justify-between
          gap-3
          cursor-pointer
          list-none
          px-4
          py-3
          text-sm
          font-semibold
          text-gray-800
          hover:bg-gray-50
        "
      >

        <span>
          How do I find the exact ZIP+4 for an address in {result.city}?
        </span>

        <span className="text-gray-400 group-open:rotate-180 transition-transform">
          ▾
        </span>

      </summary>

      <div className="border-t border-gray-100 px-4 py-3 text-sm text-gray-600 leading-6">

        Use the complete street address in the official USPS ZIP Code
        Lookup. For addresses using base ZIP{' '}

        <strong>{result.zip}</strong>,

        USPS can return the standardized mailing address and the
        applicable ZIP+4 when available.

      </div>

    </details>


    {/* FAQ 4 */}
    <details className="group rounded-xl border border-gray-200 bg-gray-50/50 overflow-hidden">

      <summary
        className="
          flex
          items-center
          justify-between
          gap-3
          cursor-pointer
          list-none
          px-4
          py-3
          text-sm
          font-semibold
          text-gray-800
          hover:bg-gray-50
        "
      >

        <span>
          Is {result.zip}-XXXX a complete ZIP+4 code?
        </span>

        <span className="text-gray-400 group-open:rotate-180 transition-transform">
          ▾
        </span>

      </summary>

      <div className="border-t border-gray-100 px-4 py-3 text-sm text-gray-600 leading-6">

        No. <strong className="font-mono">{result.zip}-XXXX</strong> shows
        the ZIP+4 <strong>format only</strong>. The letters XXXX are
        placeholders. A complete ZIP+4 contains four actual digits
        determined from the delivery address.

      </div>

    </details>

  </div>

</div>




{/* ── ZIP+4 Related Tools / Internal Links ───────── */}
<div className="rounded-2xl border border-gray-200 bg-white p-5 mb-4">

  <div className="flex items-start justify-between gap-4 mb-4">

    <div>
      <h3 className="text-lg font-bold text-gray-900">
        Explore More ZIP Code Tools
      </h3>

      <p className="text-xs text-gray-500 mt-1">
        Continue working with ZIP Code {result.zip}.
      </p>
    </div>

    <div className="hidden sm:flex w-9 h-9 rounded-xl bg-green-50 items-center justify-center">
      🧰
    </div>

  </div>


 

</div>




        </div>
      )}
    </div>
  )
}
