'use client'
import { useMemo, useState } from 'react'
import { CalculatorLayout } from '@/components/ui/CalculatorLayout'
import { Card, ResultCard } from '@/components/ui/Card'
import { InputField } from '@/components/ui/InputField'
import { FAQSection } from '@/components/ui/FAQSection'
import { SEOContent, SEOContentProps } from '@/components/ui/SEOContent'
interface Props { structuredData?:object[]; faqs:any[]; relatedCalculators?:any[]; seoContent?: SEOContentProps }
export default function CalculatorClient({faqs,relatedCalculators,structuredData,seoContent}:Props){
 const [tsh,setTsh]=useState(2.5),[ft4,setFt4]=useState(1.2)
 const result=useMemo(()=>{let interpretation='TSH within common adult reference range'; if(tsh>4 && ft4<0.8) interpretation='Pattern may be consistent with primary hypothyroidism'; else if(tsh>4) interpretation='Elevated TSH; free T4 and clinical context matter'; else if(tsh<0.4 && ft4>1.8) interpretation='Pattern may be consistent with hyperthyroidism'; else if(tsh<0.4) interpretation='Low TSH; free T4/T3 and clinical context matter'; return interpretation},[tsh,ft4])
 return <CalculatorLayout title="Thyroid Function Test Context Calculator" description="Interpret TSH with optional free T4 context. Reference ranges vary by laboratory and clinical setting; this is not a diagnosis." icon="🦋" category="Health" structuredData={structuredData} relatedCalculators={relatedCalculators} slug="thyroid-calculator"><div className="grid grid-cols-1 lg:grid-cols-3 gap-6"><Card className="lg:col-span-1"><h2 className="text-sm font-semibold text-rose-400 uppercase tracking-wider mb-5">Lab Values</h2><div className="space-y-4"><InputField label="TSH" value={tsh} onChange={setTsh} min={0.01} max={50} step={0.1} suffix="mIU/L"/><InputField label="Free T4 (optional)" value={ft4} onChange={setFt4} min={0.1} max={5} step={0.1} suffix="ng/dL"/></div></Card><div className="lg:col-span-2 space-y-4"><div className="grid grid-cols-2 gap-3"><ResultCard label="TSH" value={`${tsh} mIU/L`} highlight/><ResultCard label="Context" value={result}/></div><Card><h3 className="font-bold text-gray-900 mb-3">Interpretation limitations</h3><p className="text-sm text-gray-600 leading-6">The American Thyroid Association describes TSH as the usual initial thyroid-function test, with free T4 helping interpret abnormal TSH results. Laboratory reference intervals vary, and pregnancy, age, illness, medications and pituitary disorders can change interpretation.</p></Card></div></div><div className="mt-8">{seoContent && <SEOContent {...seoContent} category="health" />}</div><div className="mt-6"><FAQSection faqs={faqs}/></div></CalculatorLayout>
}
