import type { Metadata } from 'next'
import { generateCalculatorMetadata, generateFAQStructuredData, generateWebAppStructuredData } from '@/lib/seo/metadata'
import dynamic from 'next/dynamic'
const CalculatorClient = dynamic(() => import('./CalculatorClient'), { ssr: false, loading: () => <div className="min-h-[400px] bg-white rounded-2xl border border-gray-100 animate-pulse m-4" /> })
export const metadata: Metadata = generateCalculatorMetadata({ title: 'Obesity Comorbidity Risk Calculator — Metabolic Syndrome 2026 | ToolTrio', description: 'Free obesity comorbidity calculator 2026. Calculate metabolic syndrome components, T2D risk from fasting glucose, NAFLD risk, sleep apnoea risk, and the weight loss target needed to reduce comorbidities.', slug: 'obesity-comorbidity-calculator', category: 'health', region: 'usa', keywords: ['obesity comorbidity calculator', 'metabolic syndrome calculator', 'fasting glucose prediabetes calculator', 'NAFLD risk calculator', 'how much weight loss to improve health calculator'] })
const relatedCalculators = [{'name': 'BMI Calculator', 'href': '/calculators/health/bmi-calculator', 'icon': '⚖️', 'desc': 'Body mass index'}, {'name': 'Waist-Hip Ratio', 'href': '/calculators/health/waist-hip-ratio-calculator', 'icon': '📏', 'desc': 'WHR cardiovascular risk'}, {'name': 'Diabetes Risk', 'href': '/calculators/health/diabetes-risk-calculator', 'icon': '🩸', 'desc': 'T2D risk score'}, {'name': 'Cholesterol', 'href': '/calculators/health/cholesterol-calculator', 'icon': '💊', 'desc': 'LDL/HDL ratio'}]
const faqs = [('What is metabolic syndrome?', 'Metabolic syndrome is diagnosed when 3 or more of these 5 criteria are met: (1) Abdominal obesity — waist > 102 cm (40 in) men, > 88 cm (35 in) women; (2) High triglycerides ≥ 150 mg/dL; (3) Low HDL — < 40 mg/dL men, < 50 mg/dL women; (4) High blood pressure ≥ 130/85 mmHg; (5) Elevated fasting glucose ≥ 100 mg/dL. Metabolic syndrome affects 34% of US adults and confers 2× higher cardiovascular disease risk and 5× higher T2D risk. Each additional component compounds risk multiplicatively, not additively.'), ('How much weight loss is needed to see health benefits?', 'The DPP (Diabetes Prevention Program) trial showed 5-7% body weight loss reduced T2D incidence by 58% in prediabetes — more effective than metformin. For NAFLD, 7-10% weight loss significantly reduces liver fat and inflammation; ≥ 10% can achieve NASH resolution. For sleep apnoea, 10% weight loss reduces AHI (apnoea-hypopnoea index) by 26%. For hypertension, every 1 kg weight loss reduces systolic BP by approximately 1 mmHg. Even modest losses (5-10%) produce meaningful clinical improvements across most obesity comorbidities.'), ('What is NAFLD and how is it connected to obesity?', 'NAFLD (Non-Alcoholic Fatty Liver Disease) affects approximately 25-30% of global adults and 55-75% of people with obesity. In NAFLD, triglycerides accumulate in hepatocytes due to insulin resistance, excess dietary fat, and fructose overload. In up to 25% of NAFLD cases, inflammatory progression to NASH (Non-Alcoholic Steatohepatitis) occurs, which can advance to cirrhosis and hepatocellular carcinoma. NAFLD is now the leading cause of liver transplant in women. Currently there is no approved medication for NAFLD — the primary treatment is 7-10% weight loss through diet and exercise.')]
export default function Page() {
  const _faqSchema = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faqs.map((f: any) => ({ '@type': 'Question', name: f.question, acceptedAnswer: { '@type': 'Answer', text: f.answer } })) }
  return (<><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(_faqSchema) }} /><CalculatorClient faqs={faqs} structuredData={[generateFAQStructuredData(faqs), generateWebAppStructuredData({ name: 'Obesity Comorbidity Risk Calculator', description: 'Free obesity comorbidity calculator 2026. Calculate metabolic syndrome components, T2D risk from fas', url: 'https://tooltrio.com/calculators/health/obesity-comorbidity-calculator', category: 'HealthApplication' })]} relatedCalculators={relatedCalculators} /></>)
}
