import { CalculatorBatch47DeepDive } from '@/components/ui/CalculatorBatch47DeepDive'
import type { Metadata } from 'next'
import { generateCalculatorMetadata, generateFAQStructuredData, generateWebAppStructuredData } from '@/lib/seo/metadata'
import CalculatorClient from './CalculatorClient'
export const metadata: Metadata = generateCalculatorMetadata({ title: 'Obesity Comorbidity Risk Calculator — Metabolic Syndrome 2026 | ToolTrio', description: 'Free obesity comorbidity calculator 2026. Calculate metabolic syndrome components, T2D risk from fasting glucose, NAFLD risk, sleep apnoea risk, and the weight loss target needed to reduce comorbidities.', slug: 'obesity-comorbidity-calculator', category: 'health', region: 'usa', keywords: ['obesity comorbidity calculator', 'metabolic syndrome calculator', 'fasting glucose prediabetes calculator', 'NAFLD risk calculator', 'how much weight loss to improve health calculator'] })
const relatedCalculators = [{'name': 'BMI Calculator', 'href': '/calculators/health/bmi-calculator', 'icon': '⚖️', 'desc': 'Body mass index'}, {'name': 'Waist-Hip Ratio', 'href': '/calculators/health/waist-hip-ratio-calculator', 'icon': '📏', 'desc': 'WHR cardiovascular risk'}, {'name': 'Diabetes Risk', 'href': '/calculators/health/diabetes-risk-calculator', 'icon': '🩸', 'desc': 'T2D risk score'}, {'name': 'Cholesterol', 'href': '/calculators/health/cholesterol-calculator', 'icon': '💊', 'desc': 'LDL/HDL ratio'}]
const faqs = [
  { question: 'What does this obesity comorbidity calculator diagnose?', answer: 'It does not diagnose a condition. It is a screening aid that summarizes entered BMI and metabolic measurements and shows ToolTrio risk flags. Diagnosis requires clinical evaluation.' },
  { question: 'What BMI is considered obesity for adults?', answer: 'CDC adult categories define obesity as BMI 30.0 or greater, with Class 1 from 30.0 to under 35, Class 2 from 35 to under 40, and Class 3 at 40 or greater.' },
  { question: "Why isn't BMI enough to judge health risk?", answer: 'BMI does not distinguish fat from muscle and bone or show where body fat is distributed. Blood pressure, laboratory values, medical history, physical examination and other factors add important context.' },
  { question: 'Can one abnormal glucose, blood-pressure or lipid value diagnose disease?', answer: 'No. Measurement conditions, repeat testing and clinical criteria matter. A flag on this page should be interpreted as a reason to verify the measurement and discuss it with a healthcare professional.' },
  { question: 'Can this calculator predict diabetes, fatty liver disease or sleep apnoea?', answer: 'No. Any condition-specific risk labels are simplified ToolTrio heuristics and are not validated prediction models. Symptoms, laboratory testing and other clinical assessments may be needed.' }
]
export default function Page() {
  const _faqSchema = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faqs.map((f: any) => ({ '@type': 'Question', name: f.question, acceptedAnswer: { '@type': 'Answer', text: f.answer } })) }
  return (<><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(_faqSchema) }} /><CalculatorClient faqs={faqs} structuredData={[generateFAQStructuredData(faqs), generateWebAppStructuredData({ name: 'Obesity Comorbidity Risk Calculator', description: 'Free obesity comorbidity calculator 2026. Calculate metabolic syndrome components, T2D risk from fas', url: 'https://tooltrio.com/calculators/health/obesity-comorbidity-calculator', category: 'HealthApplication' })]} relatedCalculators={relatedCalculators} />      <CalculatorBatch47DeepDive slug="obesity-comorbidity-calculator" />
</>)
}
