import type { Metadata } from 'next'
import { generateDevToolMetadata, generateDevToolJsonLd } from '@/lib/seo/metadata'
import CalculatorClient from './CalculatorClient'

export const metadata: Metadata = generateDevToolMetadata({
  title: 'Fake Data Generator — Realistic Test Data Free Online',
  description: 'Generate realistic fake names, emails, addresses, phone numbers, UUIDs, and more for testing. Bulk output in JSON or CSV. Runs entirely in your browser.',
  slug: 'fake-data-generator',
  keywords: ['fake data generator online free','test data generator browser','mock user data generator','generate dummy names emails free','random person generator online','lorem ipsum data generator','fake api response generator'],
})

const faqs = [
  { question: 'Why use realistic fake data instead of placeholder text like "test123"?', answer: "Realistic test data catches a broader class of bugs. A form tested only with 'test@test.com' will not reveal that your validation rejects email addresses with plus signs (user+tag@example.com is valid). An address field tested with 'test address' will not expose that your geocoding fails on addresses with apartment numbers. A name field with 'Test User' will not reveal that your system breaks on names with apostrophes (O\'Brien) or with non-ASCII characters. Realistic data that covers edge cases in real-world distributions — unusual characters, long values, Unicode — produces more reliable test coverage." },
  { question: 'Is the generated data based on real people?', answer: "No. The names, email addresses, phone numbers, and addresses are procedurally generated by combining from lists of common first names, last names, street names, and city names. The combinations are random and do not correspond to real individuals. Generated phone numbers use realistic formats but are not assigned numbers — they cannot be called. Generated addresses use real street name patterns but are not verified against postal address databases. They are designed to look real for UI testing without referencing any real person's identity." },
  { question: 'What locale options are available for generated data?', answer: "Locale affects name patterns (English names vs Japanese names vs Spanish names), address formats (US street address vs UK postcode format vs German PLZ), phone number formats (US: +1 (555) 123-4567, UK: +44 20 7946 0958), date formats (MM/DD/YYYY vs DD/MM/YYYY vs ISO 8601), and currency symbols. For internationalization testing, generating data in non-English locales is essential — your UI layout may break when names are longer (German compound nouns), when addresses have different line structures, or when text is right-to-left (Arabic, Hebrew)." },
  { question: 'How do I generate test data for a specific database schema?', answer: "This tool generates common field types (name, email, phone, address, UUID, date, number, boolean). For schema-specific data: export JSON and map fields to your column names. If your schema has custom types or enum values (status: active|inactive|pending), configure the generator to use a custom value set, or post-process the JSON with a script to map generated values to your enum. For database seeding at scale (thousands of rows), use Faker.js (JavaScript) or factory_boy (Python) in your codebase — they are faster and more configurable than browser-based tools." },
  { question: 'What is the best format to export — JSON or CSV?', answer: "JSON: use when your application consumes JSON directly (React state, API mocking, Postman), when you need nested data structures, or when field values might contain commas. CSV: use when importing to a spreadsheet, database bulk import tool, or any system that expects tabular input. For database seeding, CSV is often faster to import via COPY (PostgreSQL) or LOAD DATA INFILE (MySQL) than parsing JSON. For API testing and frontend mocking, JSON is the natural format. This tool supports both — generate in whichever format your workflow needs." },
  { question: 'How do I use fake data for API testing and mocking?', answer: "Postman: paste generated JSON into the body of POST requests for creating test records. WireMock / MSW (Mock Service Worker): include generated data as mock response bodies. Cypress/Playwright: load generated JSON as fixture files (cypress/fixtures/users.json) and reference in tests. JSON Server: use a generated JSON file as the database for a mock REST API (json-server db.json). For realistic load testing with k6 or Locust: export bulk CSV and use the test tool's data parameterization to iterate over rows." },
  { question: 'What other test and generation tools are on this site?', answer: "The UUID Generator creates cryptographically secure unique IDs for primary keys in test data. The Password Generator creates realistic passwords for test user accounts. The Lorem Ipsum Generator produces placeholder body text. The JSON Formatter validates and beautifies generated JSON output. The CSV to JSON tool converts generated CSV to JSON if you need to switch formats. All are in the Dev Tools section." },
]

export default function Page() {
  const jsonLd = generateDevToolJsonLd({
    name: 'Fake Data Generator — Realistic Test Data Free Online',
    description: 'Generate realistic fake names, emails, addresses, phone numbers, UUIDs, and more for testing. Bulk output in JSON or CSV. Runs entirely in your browser.',
    slug: 'fake-data-generator',
    faqs,
  })
  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd.webApp) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd.breadcrumb) }} />
      {jsonLd.faqPage && (
        <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd.faqPage) }} />
      )}
      <CalculatorClient faqs={faqs} />
    </>
  )
}
