import { CalculatorBatch48DeepDive } from '@/components/ui/CalculatorBatch48DeepDive'
import type { Metadata } from 'next'
import { generateCalculatorMetadata, generateFAQStructuredData, generateWebAppStructuredData } from '@/lib/seo/metadata'
import dynamic from 'next/dynamic'
const CalculatorClient = dynamic(() => import('./CalculatorClient'), {  loading: () => <div className="min-h-[400px] bg-white rounded-2xl border border-gray-100 animate-pulse m-4" /> })
export const metadata: Metadata = generateCalculatorMetadata({ title: 'Menstrual Health Score Calculator — Cycle Analysis 2026 | ToolTrio', description: 'Free menstrual health score calculator 2026. Assess your cycle length, period duration, pain level, flow heaviness, PMS symptoms, and irregularity. Detect red flags for endometriosis, PCOS, and anaemia.', slug: 'menstrual-health-calculator', category: 'health', region: 'usa', keywords: ['menstrual health calculator', 'period health score', 'menstrual cycle health assessment', 'period pain calculator', 'abnormal uterine bleeding calculator'] })
const relatedCalculators = [{'name': 'PCOS Risk', 'href': '/calculators/health/pcos-risk-calculator', 'icon': '🌀', 'desc': 'PCOS risk assessment'}, {'name': 'Ovulation Calculator', 'href': '/calculators/health/ovulation-calculator', 'icon': '📅', 'desc': 'Fertile window'}, {'name': 'Pregnancy Calculator', 'href': '/calculators/health/pregnancy-calculator', 'icon': '🤰', 'desc': 'Due date and weeks'}, {'name': 'Iron Intake', 'href': '/calculators/health/iron-intake-calculator', 'icon': '💊', 'desc': 'Iron deficiency risk'}]
const faqs = [
  {"question": "What is a normal menstrual cycle?", "answer": "A normal menstrual cycle ranges from 21 to 35 days (average 28 days), with menstrual bleeding lasting 2-7 days. Normal flow involves 20-80mL total blood loss per cycle (most women lose 30-40mL). Cycles outside these ranges, or significant variation from cycle to cycle, may indicate underlying conditions. An important nuance: what is 'normal' for an individual's baseline may differ from population averages — tracking your own pattern over 3-6 months is more meaningful than comparing to a single benchmark."},
  {"question": "What are the signs of endometriosis?", "answer": "Endometriosis affects approximately 10% of women of reproductive age (190 million worldwide) and causes endometrial-like tissue to grow outside the uterus. Key symptoms: severe dysmenorrhoea (pain 7-10/10 that interferes with daily life), deep pain during intercourse, heavy menstrual bleeding, bladder/bowel symptoms during menstruation, and infertility. The average diagnostic delay is 7-9 years because symptoms are frequently dismissed. Endometriosis is definitively diagnosed by laparoscopy, though pelvic MRI or ultrasound can detect advanced disease. If pain ≥ 7/10 consistently, seek gynaecological evaluation proactively."},
  {"question": "When should irregular periods prompt medical evaluation?", "answer": "Seek evaluation for: cycles consistently shorter than 21 days or longer than 35 days; no period for 3+ consecutive months (excluding pregnancy) — called amenorrhoea; soaking through a pad/tampon every hour for 2+ consecutive hours — suggestive of heavy menstrual bleeding possibly indicating fibroids, adenomyosis, or coagulopathy; dysmenorrhoea severe enough to miss work/school consistently; intermenstrual bleeding or postcoital bleeding. Common causes of irregular cycles include polycystic ovary syndrome (PCOS), thyroid dysfunction, hyperprolactinaemia, premature ovarian insufficiency (POI), and eating disorders."}
]
export default function Page() {
  const _faqSchema = generateFAQStructuredData(faqs)
  return (<><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(_faqSchema) }} /><CalculatorClient faqs={faqs} structuredData={[generateFAQStructuredData(faqs), generateWebAppStructuredData({ name: 'Menstrual Health Score Calculator', description: 'Free menstrual health score calculator 2026. Assess your cycle length, period duration, pain level, ', url: 'https://tooltrio.com/calculators/health/menstrual-health-calculator', category: 'HealthApplication' })]} relatedCalculators={relatedCalculators} />      <CalculatorBatch48DeepDive slug="menstrual-health-calculator" />
</>)
}
