import type { Metadata } from 'next'
import { generateCalculatorMetadata, generateFAQStructuredData } from '@/lib/seo/metadata'
import dynamic from 'next/dynamic'
const CalculatorClient = dynamic(() => import('./CalculatorClient'), { ssr: false, loading: () => <div className="min-h-[400px] bg-white rounded-2xl border border-gray-100 animate-pulse m-4" /> })
export const metadata: Metadata = generateCalculatorMetadata({ title: 'Rule 72(t) SEPP Calculator USA 2026 | ToolTrio', description: 'Calculate Substantially Equal Periodic Payments (SEPP) for penalty-free early IRA withdrawals before age 59½ using IRS Rule 72(t).', slug: '72t-sepp-calculator', category: 'finance', keywords: ['72t calculator', 'SEPP calculator USA', 'early IRA withdrawal calculator', 'substantially equal periodic payments 72t'] })
const faqs = [('What is IRS Rule 72(t)?', 'Rule 72(t) allows penalty-free withdrawals from IRA or 401k accounts before age 59½ if you take Substantially Equal Periodic Payments (SEPP). You must continue the payments for at least 5 years or until age 59½, whichever is longer. Three IRS-approved calculation methods are available: RMD, Amortization, and Annuitization.'), ('Which 72(t) method gives the highest payment?', 'The Amortization method typically produces the highest annual payment, followed by the Annuity method, with the RMD method usually lowest. The RMD method recalculates each year based on current balance, while Amortization and Annuity methods are fixed. If you need maximum income, use Amortization; if you want flexibility, RMD allows for market changes.')]
const relatedCalculators = [{'name': 'Retirement Withdrawal', 'href': '/calculators/finance/retirement-withdrawal-calculator', 'icon': '💰', 'desc': 'Withdrawal planning'}, {'name': 'Required Minimum Distribution', 'href': '/calculators/finance/required-minimum-distribution-calculator', 'icon': '📅', 'desc': 'RMD calculator'}, {'name': 'Early Retirement', 'href': '/calculators/finance/early-retirement-calculator', 'icon': '🔥', 'desc': 'Early retirement'}]
const structuredData = [generateFAQStructuredData(faqs)]
export default function Page() { return <>{structuredData.map((s, i) => <script key={i} type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(s) }} />)}<CalculatorClient faqs={faqs} structuredData={structuredData} relatedCalculators={relatedCalculators} /></> }
