import type { Metadata } from 'next'
import { generateCalculatorMetadata, generateFAQStructuredData } from '@/lib/seo/metadata'
import dynamic from 'next/dynamic'
const CalculatorClient = dynamic(() => import('./CalculatorClient'), { ssr: false, loading: () => <div className="min-h-[400px] bg-white rounded-2xl border border-gray-100 animate-pulse m-4" /> })
export const metadata: Metadata = generateCalculatorMetadata({ title: 'Social Security WEP Calculator USA 2026 | ToolTrio', description: 'Calculate the Windfall Elimination Provision (WEP) reduction to your Social Security benefit if you receive a non-covered pension (government, foreign employer).', slug: 'social-security-wep-calculator', category: 'finance', keywords: ['WEP calculator Social Security', 'windfall elimination provision 2026', 'government pension Social Security reduction', 'WEP GPO calculator USA'] })
const faqs = [('What is the Windfall Elimination Provision (WEP)?', "WEP reduces the Social Security benefit formula for workers who receive a pension from a job not covered by Social Security (such as some state/local government jobs). The maximum WEP reduction in 2026 is $621/month. The reduction decreases if you have 21+ years of 'substantial earnings' under Social Security, and disappears entirely at 30 years."), ('What is the Government Pension Offset (GPO)?', 'GPO reduces spousal and survivor Social Security benefits for those receiving a government pension from non-covered work. The reduction equals 2/3 of your government pension. For example, if you receive a $1,500/month government pension, your spousal Social Security benefit is reduced by $1,000/month. In many cases, this eliminates the spousal benefit entirely.')]
const relatedCalculators = [{'name': 'Social Security Calculator', 'href': '/calculators/finance/social-security-calculator', 'icon': '🏛️', 'desc': 'SS benefit estimate'}, {'name': 'Social Security Breakeven', 'href': '/calculators/finance/social-security-breakeven-calculator', 'icon': '⚖️', 'desc': 'Claiming age'}, {'name': 'Defined Benefit Pension', 'href': '/calculators/finance/defined-benefit-pension-calculator', 'icon': '🏛️', 'desc': 'Pension calculator'}]
const structuredData = [generateFAQStructuredData(faqs)]
export default function Page() { return <>{structuredData.map((s, i) => <script key={i} type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(s) }} />)}<CalculatorClient faqs={faqs} structuredData={structuredData} relatedCalculators={relatedCalculators} /></> }
