import type { Metadata } from 'next'
import { generateCalculatorMetadata, generateFAQStructuredData } from '@/lib/seo/metadata'
import dynamic from 'next/dynamic'
const CalculatorClient = dynamic(() => import('./CalculatorClient'), { loading: () => <div className="min-h-[400px] bg-white rounded-2xl border border-gray-100 animate-pulse m-4" /> })
export const metadata: Metadata = generateCalculatorMetadata({ title: 'Treasury Bill (T-Bill) Calculator USA 2026 | ToolTrio', description: 'Calculate Treasury Bill returns, bond equivalent yield, annualized return, and tax advantages. Compare T-Bill rates for 4-week, 13-week, 26-week, and 52-week terms.', slug: 'treasury-bill-calculator', category: 'finance', keywords: ['treasury bill calculator USA', 'T-bill yield calculator 2026', 'bond equivalent yield calculator', 'treasury bill return calculator'] })
const faqs = [
  {"question": "How are Treasury Bills taxed?", "answer": "T-Bills are exempt from state and local income taxes — only federal income tax applies. In high-tax states like California (13.3% top rate) or New York (10.9%), this exemption significantly boosts the effective yield. A T-Bill yielding 5.0% is equivalent to a taxable CD yielding 5.6% for someone in California's top bracket. The tax advantage grows in higher-tax states."},
  {"question": "What is the bond equivalent yield for T-Bills?", "answer": "T-Bills are sold at a discount and mature at face value. The discount rate is quoted on a 360-day bank discount basis. The bond equivalent yield (BEY) converts this to a 365-day basis for comparison with coupon bonds — it's always slightly higher than the discount rate. For example, a 26-week T-Bill at 5.0% discount rate has a BEY of approximately 5.13%. Always use BEY when comparing to savings accounts or CDs."}
]
const relatedCalculators = [{'name': 'Series EE Bond Calculator', 'href': '/calculators/finance/series-ee-bond-calculator', 'icon': '🏛️', 'desc': 'EE bond returns'}, {'name': 'I-Bonds Calculator', 'href': '/calculators/finance/i-bonds-calculator', 'icon': '💰', 'desc': 'I-Bond returns'}, {'name': 'CD vs HYSA', 'href': '/calculators/finance/cd-vs-hysa-calculator', 'icon': '🏦', 'desc': 'CD vs savings account'}]
const structuredData = [generateFAQStructuredData(faqs)]
export default function Page() { return <>{structuredData.map((s, i) => <script key={i} type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(s) }} />)}<CalculatorClient faqs={faqs} structuredData={structuredData} relatedCalculators={relatedCalculators} /></> }
