/**
 * TOOLTRIO — Insult Generator combinatorial libraries
 *
 * Word-bank + template libraries for every insult/roast/comeback generator
 * EXCEPT the Shakespeare Insult Generator, which has its own dedicated
 * combinatorial system in app/fun/shakespeare-insult-generator/CalculatorClient.tsx.
 *
 * Each entry follows the same pattern Shakespeare uses: pools of themed words
 * ("banks") get dropped into sentence templates at random, so the generator
 * can produce thousands of unique, natural-sounding lines instead of cycling
 * through a short fixed list. To expand any generator's library, just add more
 * words to its banks or more sentence templates — everything downstream (the
 * combination count shown on the page, the generator itself) updates automatically.
 */

export interface InsultBankSet {
  /** Named word pools referenced by {placeholder} in templates, e.g. { trait: [...], noun: [...] } */
  banks: Record<string, string[]>
  /** Sentence templates using {bankName} placeholders, filled in at random on each generate() call */
  templates: string[]
}

export const INSULT_BANKS: Record<string, InsultBankSet> = {
  'medieval-insult-generator': {
    banks: {
      trait: [
        'turnip-brained',
        'mud-footed',
        'flea-bitten',
        'dung-shovelling',
        'cart-witted',
        'goose-hearted',
        'straw-stuffed',
        'plague-ridden',
        'donkey-faced',
        'cabbage-headed',
        'swine-mannered',
        'moat-smelling',
        'peasant-fingered',
        'gravy-brained',
        'hovel-raised',
        'gong-farming',
        'weevil-witted',
        'boar-tempered',
        'cesspit-minded',
        'rust-toothed',
        'leech-livered',
        'hay-brained',
        'chicken-hearted',
        'serf-witted',
        'bog-footed',
      ],
      noun: [
        'turnip farmer',
        'gong farmer',
        'stable boy',
        'village fool',
        'pig herder',
        'tavern drunk',
        'hedge knight',
        'court jester',
        'plague rat',
        'moat scrubber',
        'dung collector',
        'hay bale',
        'broken cartwheel',
        'goat thief',
        "leper's bootlace",
        'rusty pitchfork',
        'one-eyed goose',
        'toothless squire',
        'muddy peasant',
        "cow's understudy",
        "beggar's shadow",
        'half-built siege tower',
        'drunken minstrel',
        'royal footstool',
        "kingdom's embarrassment",
      ],
    },
    templates: [
      'You feeble {trait} {noun}, even the pigs pity your company.',
      'Begone, you {trait} {noun}, before the guards remove you.',
      'You argue like a {trait} {noun} who has never once won.',
      'The dungeon has better company than a {trait} {noun} like you.',
      'You smell of the stable and reason like a {trait} {noun}.',
      'Even the court fool refuses to trade barbs with a {trait} {noun}.',
    ],
  },
  'pirate-insult-generator': {
    banks: {
      trait: [
        'bilge-sucking',
        'barnacle-brained',
        'landlubbing',
        'seasick',
        'rum-soaked',
        'scurvy-riddled',
        'one-legged',
        'cross-eyed',
        'fish-gutted',
        'tar-fingered',
        'plank-footed',
        'salt-crusted',
        'mutinous',
        'weevil-eaten',
        'kraken-scared',
        'gull-brained',
        'anchor-headed',
        'parrot-mouthed',
        'bilge-rat-hearted',
        'cannon-shy',
        'shipwrecked',
        'tide-tossed',
        'gangplank-shy',
        'squid-livered',
        'hornswoggled',
      ],
      noun: [
        'landlubber',
        'bilge rat',
        'cabin boy',
        'deckhand',
        'scallywag',
        'sea cook',
        'one-eyed gull',
        'seasick parrot',
        'drunken navigator',
        'broken compass',
        'leaky rowboat',
        'rusty anchor',
        'half-sunk dinghy',
        'mutinous mop',
        'barnacle collection',
        'fish-bait sailor',
        'cursed cabin',
        'empty rum barrel',
        "kraken's leftovers",
        'tide pool troll',
        'soggy map',
        'plank-walker',
        "ghost ship's ghost",
        "captain's disappointment",
      ],
    },
    templates: [
      "Ye {trait} {noun}, ye couldn't swab a deck if yer life depended on it.",
      'Walk the plank, ye {trait} {noun}, and take yer excuses with ye.',
      'Shiver me timbers, has anyone met a bigger {trait} {noun}?',
      'Ye fight like a {trait} {noun} in a hurricane, matey.',
      "Even Davy Jones wouldn't want a {trait} {noun} in his locker.",
      "Ye couldn't find treasure with a map, ye {trait} {noun}.",
    ],
  },
  'victorian-insult-generator': {
    banks: {
      trait: [
        'quaintly',
        'remarkably',
        'charmingly',
        'distressingly',
        'astonishingly',
        'tediously',
        'impertinently',
        'unfashionably',
        'insufferably',
        'provincially',
        'tiresomely',
        'laughably',
        'regrettably',
        'excruciatingly',
        'conspicuously',
        'fashionably-late-to-basic-sense',
        'exhaustingly',
        'tastelessly',
        'preposterously',
        'frightfully',
      ],
      noun: [
        'opinion',
        'bonnet',
        'waistcoat',
        'calling card',
        'drawing-room manner',
        'tea-time remark',
        'carriage etiquette',
        'dinner conversation',
        'penmanship',
        'dance-card entry',
        'parlour gossip',
        'garden-party wit',
        "chaperone's patience",
        'embroidery hoop',
        "footman's restraint",
        "governess's report",
        'seating arrangement',
        'visiting hour',
        'letter of introduction',
        'promenade attire',
      ],
    },
    templates: [
      'How {trait} quaint that you consider that {noun} worth sharing.',
      'I daresay your {noun} is {trait} beneath the standard of polite company.',
      'One does so admire the confidence behind such a {trait} {noun}.',
      'What a {trait} bold display, given your {noun} says otherwise.',
      "I shan't dignify your {noun} with more than a {trait} grimace.",
      'Your {noun} is, I fear, {trait} out of its depth this season.',
    ],
  },
  'roast-generator': {
    banks: {
      trait: [
        'buffering',
        'expired',
        'unpatched',
        'clearance-rack',
        'off-brand',
        'discontinued',
        'low-battery',
        'laggy',
        'pixelated',
        'glitchy',
        'out-of-office',
        '404-error',
        'autocorrected',
        'overdrawn',
        'fine-print',
        'group-chat-only',
        'screenshot-worthy',
        'dial-up-speed',
        'participation-trophy',
        'airplane-mode',
        'spam-folder',
        'password-protected',
        'buffer-underrun',
        'unsubscribed',
      ],
      noun: [
        'Wi-Fi signal',
        'group chat',
        'personality',
        'comeback',
        'life update',
        'LinkedIn post',
        'main character arc',
        'browser with 47 tabs',
        'group project partner',
        'Bluetooth connection',
        'phone at one percent',
        'printer jam',
        'buffering wheel',
        'spam email',
        'cracked phone screen',
        'expired coupon',
        'forgotten password',
        'unread notification',
        'software update nobody wants',
        'autoplay ad',
      ],
    },
    templates: [
      'You bring the energy of a {trait} {noun}, and everyone notices.',
      'You have the reliability of a {trait} {noun} on a good day.',
      'You are the human version of a {trait} {noun}.',
      'Somewhere, a {trait} {noun} is jealous of your consistency.',
      'Your last decision had the confidence of a {trait} {noun}.',
      'You are proof that a {trait} {noun} can still show up uninvited.',
    ],
  },
  'savage-insult-generator': {
    banks: {
      trait: [
        'unrevised',
        'biohazard-labelled',
        'natural-selection-defying',
        'rough-draft',
        'expired-since-birth',
        'factory-recalled',
        'permanently-beta',
        'structurally-unsound',
        'quietly-discontinued',
        'chronically-unfinished',
        'pre-emptively-regretted',
        'warning-label-worthy',
        'clearance-priced',
        'irreversibly',
        'catastrophically',
        'unapologetically-mediocre',
        'budget-tier',
        'fundamentally-flawed',
        'overconfidently-wrong',
        'zero-star',
      ],
      noun: [
        'rough draft',
        'biohazard',
        'cautionary tale',
        'typo nobody fixed',
        'participation trophy',
        'plot twist nobody wanted',
        'houseplant that gave up',
        'coffee break from evolution',
        'forgotten homework',
        'broken vending machine',
        'expired warranty',
        'deleted scene',
        'unfinished sentence',
        'filler episode',
        'dead-end hallway',
        '404 page',
        'recalled product',
        'beta test',
        'puddle in a drought',
        'reply nobody sent',
      ],
    },
    templates: [
      'You are a {trait} {noun}, and everyone around you can tell.',
      'Your existence reads like a {trait} {noun} that never got fixed.',
      "People don't dislike you, they forget you exist like a {trait} {noun}.",
      'Your potential is a {trait} {noun} at this point.',
      'You are proof that a {trait} {noun} can still walk and talk.',
      'Your best qualities are still stuck as a {trait} {noun}.',
    ],
  },
  'funny-insult-generator': {
    banks: {
      trait: [
        'wobbly',
        'confused',
        'overcaffeinated',
        'glittery',
        'off-key',
        'rubber-legged',
        'googly-eyed',
        'static-shocked',
        'cartoonishly',
        'spaghetti-armed',
        'hiccuping',
        'squeaky',
        'wind-up-toy',
        'upside-down',
        'bubble-wrapped',
        'clownish',
        'disco-lit',
        'rubber-chicken',
        'sock-puppet',
        'banana-peel',
      ],
      noun: [
        'penguin on roller skates',
        'Roomba with opinions',
        'flamingo mid-panic',
        'Wi-Fi router hunting for signal',
        'printer jam',
        'spider having a small seizure',
        'toddler on ice skates',
        'dolphin that heard a bad pun',
        'confused GPS',
        'cartoon character who fell off screen',
        'fire-alarm singing voice',
        'chaos-seasoned soup',
        'malfunctioning vending machine',
        'screen-door submarine',
        'one-man kazoo band',
        'overexcited sprinkler',
      ],
    },
    templates: [
      'You have the coordination of a {trait} {noun}, and it shows.',
      'Your dance moves look like a {trait} {noun} trying to find rhythm.',
      'You are basically a {trait} {noun} today, and nobody warned us.',
      'Your fashion sense was assembled by a {trait} {noun}.',
      'You run like a {trait} {noun} that forgot where it was going.',
      'You have main character energy but the grace of a {trait} {noun}.',
    ],
  },
  'friendly-insult-generator': {
    banks: {
      trait: [
        'favourite',
        'chaotic',
        'lovable',
        'certified',
        'walking',
        'hopeless',
        'gloriously',
        'personally-chosen',
        'unofficially-adopted',
        'delightfully',
        'undeniably',
        'affectionately-tolerated',
        'permanently-forgiven',
        'hall-of-fame',
        'five-star',
        'irreplaceable',
      ],
      noun: [
        'disaster',
        'red flag',
        'group chat notification',
        'secondhand embarrassment',
        'questionable playlist',
        'ride-or-die energy',
        'bad influence',
        'crime scene of a text thread',
        'search-history mystery',
        'walking plot twist',
        'chosen chaos',
        'reason my search history looks unhinged',
        'favourite bad decision',
        'group project liability',
      ],
    },
    templates: [
      'You are my {trait} {noun}, and I would not trade you for anyone.',
      'I love you like family, which explains the {trait} {noun}.',
      'You are a {trait} {noun} I chose to plant a garden around.',
      'I keep you around purely for the {trait} {noun} you bring.',
      'You are proof my taste in friends includes a {trait} {noun}.',
      'I would defend you and your {trait} {noun} to literally anyone.',
    ],
  },
  'fantasy-insult-generator': {
    banks: {
      trait: [
        'goblin-brained',
        'half-blind',
        'mana-starved',
        'dragon-shy',
        'troll-tracked',
        'basilisk-dazed',
        'orc-clumsy',
        'mimic-charmed',
        'quest-logged-empty',
        'rune-smudged',
        'potion-spilled',
        'staff-fumbling',
        'siege-shy',
        'dungeon-lost',
        'scroll-illiterate',
        'ogre-outwitted',
        'elf-mocked',
        'dwarf-outdrunk',
        'hydra-headed-but-brainless',
      ],
      noun: [
        'goblin who forgot his weapon',
        'half-blind dwarf in an argument',
        "apprentice's first spark of magic",
        'training dummy in the courtyard',
        'troll tracked through fresh snow',
        'mimic pretending to be a chest',
        'basilisk staring contest loser',
        'orc charging uphill into a trap',
        'empty quest log',
        "tavern bard's worst ballad",
        'cursed suit of armor',
        'dragon too bored to breathe fire',
        "wizard's first failed spell",
        'siege tower missing wheels',
      ],
    },
    templates: [
      'You have the battle instincts of a {trait} {noun}.',
      'Even a {trait} {noun} could out-argue you in the dark.',
      'Your spellcasting is weaker than a {trait} {noun}.',
      "You couldn't out-fence a {trait} {noun} in broad daylight.",
      "A dragon wouldn't bother breathing fire on a {trait} {noun} like you.",
      'Even the goblins mock a {trait} {noun} like you behind your back.',
    ],
  },
  'wizard-insult-generator': {
    banks: {
      trait: [
        'mana-starved',
        'spellbook-illiterate',
        'rune-smudged',
        'cauldron-scorched',
        'familiar-abandoned',
        'staff-cracked',
        'portal-misfired',
        'crystal-ball-rejected',
        'incantation-mumbling',
        'potion-botching',
        'grimoire-dusty',
        'wand-splintered',
        'hex-backfired',
        'enchantment-fizzled',
        'apprentice-grade',
        'candle-drowned',
      ],
      noun: [
        "first-year apprentice's spark",
        'enchanted broom',
        "cursed toad's conversation",
        "blindfolded troll's potion",
        "crystal ball's refusal",
        'toddler mispronouncing thunder',
        'half-asleep owl familiar',
        'spider-scribbled rune',
        "hedge witch's duel",
        'wax-drowned candle',
        "gargoyle's spare thought",
        'staff standing still',
        'portal to the next room',
        "grimoire's unread page",
      ],
    },
    templates: [
      'Your grasp of magic is weaker than a {trait} {noun}.',
      'I have seen a {trait} {noun} with more wisdom than you carry.',
      'A {trait} {noun} has better conversation than your incantations.',
      "You couldn't summon a familiar with the skill of a {trait} {noun}.",
      'Even a {trait} {noun} out-thinks you on a slow day.',
      'Your runes look like a {trait} {noun} fell into an inkpot.',
    ],
  },
  'pirate-roast-generator': {
    banks: {
      trait: [
        'bathtub-captaining',
        'compass-arguing',
        'map-confused',
        'rum-brave',
        'knot-loosening',
        'star-chart-blind',
        'cannon-missing',
        'haggling-soft',
        'mutiny-prone',
        'tide-lost',
        'parrot-outsmarted',
        'plank-worthy',
        'gangplank-shy',
        'crew-pitied',
        'anchor-dragging',
      ],
      noun: [
        'bathtub fleet',
        'puddle of confusion',
        "ship's rats' instincts",
        'bravado-and-luck battle plan',
        'soft-handed swordsman',
        'memorized-more-than-you parrot',
        'undone knot',
        'self-mutiny',
        'unreadable star chart',
        "Blackbeard's rejection letter",
        'cannon aimed at nothing',
        'low-tide smell',
        'plank with better sailors on it',
      ],
    },
    templates: [
      "Ye couldn't captain a {trait} {noun}, let alone a galleon.",
      'Yer treasure map leads straight to a {trait} {noun}.',
      'The crew follows ye out of pity, like a {trait} {noun}.',
      'Even the {trait} {noun} has better instincts than ye, matey.',
      'Yer battle plan is one part bravado, nine parts {trait} {noun}.',
      'Even Blackbeard would send a {trait} {noun} like ye packing.',
    ],
  },
  'cowboy-insult-generator': {
    banks: {
      trait: [
        'tumbleweed-brained',
        'molasses-slow',
        'cactus-clumsy',
        'spur-jingling',
        'saddle-sore',
        'dust-blinded',
        'chihuahua-tough',
        'scarecrow-staring',
        'wagon-fallen',
        'fence-tangled',
        'poker-folding',
        'gunless',
        'rustler-shy',
        'stampede-lost',
        'corral-confused',
      ],
      noun: [
        'blindfolded tumbleweed',
        'sack of potatoes off the wagon',
        'chihuahua guarding an empty ranch',
        "scarecrow's staring contest",
        'molasses in a January freeze',
        'fence post standing still',
        'saloon piano bluff',
        "dust storm's cheap tent",
        'stampede running through camp',
        'mildly annoyed cactus',
        "empty ranch's echo",
        'broken spur',
      ],
    },
    templates: [
      "You couldn't herd cattle with the skill of a {trait} {noun}.",
      'Your aim is worse than a {trait} {noun} in a windstorm.',
      'You ride like a {trait} {noun} that fell off twice.',
      'You talk tougher than a {trait} {noun}, partner.',
      "You'd lose a staring contest with a {trait} {noun}.",
      'Your poker face folds faster than a {trait} {noun}.',
    ],
  },
  'royal-insult-generator': {
    banks: {
      trait: [
        'stable-hand-mannered',
        'court-jester-unremarkable',
        'banished-by-decree',
        'throne-unworthy',
        'scepter-less',
        'crown-tarnished',
        'footman-graced',
        'palace-hound-outjudged',
        'border-guard-pitied',
        'dinner-hall-silenced',
        'bloodline-embarrassing',
        'hall-echoing',
        'kingdom-surviving-despite',
        'stable-fit',
        'guard-escorted',
      ],
      noun: [
        "stable hand's grace",
        "court jester's unremarkable wit",
        "royal decree's leftovers",
        "palace hound's dinner manners",
        "border guard's new company",
        "throne room's silence",
        'common sense the crown never installed',
        "footman's restraint",
        "kingdom's survival despite you",
        'scepter-less command',
        'dull conversation escorted from the hall',
        "jester's rejected script",
      ],
    },
    templates: [
      'By royal decree, your {trait} {noun} is hereby banished from this court.',
      'I have seen {trait} {noun} with more grace than you carry, my dear subject.',
      'Your title outshines your {trait} {noun} by a wide margin.',
      'Even the court jester finds your {trait} {noun} unremarkable.',
      'The kingdom survives despite your {trait} {noun}, not because of it.',
      'One does not need a scepter to outrank your {trait} {noun}.',
    ],
  },
  'schoolyard-insult-generator': {
    banks: {
      trait: [
        'locker-smelling',
        'dodgeball-dodging',
        'cafeteria-nicknamed',
        'pop-quiz-crying',
        'hand-me-down',
        'four-square-losing',
        'homework-copying',
        'lunch-trading-scammy',
        'backpack-heavy',
        'rock-paper-scissors-cursed',
        'recess-only-cardio',
        'show-and-tell-borrowed',
        'gym-class-tripping',
        'cartoon-script-excusing',
      ],
      noun: [
        'nobody-wants-to-open locker',
        'never-played-dodgeball aim',
        'whole-cafeteria nickname',
        'personally-betrayed pop quiz',
        'textbook-beating jacket history',
        'four-square loss streak',
        'one true talent of copying',
        'legally-a-scam lunch trade',
        'heavier-than-excuses backpack',
        'cursed rock-paper-scissors streak',
        'only-cardio recess',
        "someone-else's-idea show-and-tell",
        'gym-class-history trip',
      ],
    },
    templates: [
      'Your face is giving the class a free reason to skip lunch, {trait} {noun}.',
      'You smell like a {trait} {noun}, and everyone can tell.',
      'Your homework excuses have more plot holes than a {trait} {noun}.',
      'You have the aim of someone with a {trait} {noun}.',
      'Your nickname came from a {trait} {noun}, and it stuck.',
      'You lose at everything the way a {trait} {noun} loses at recess.',
    ],
  },
  'office-roast-generator': {
    banks: {
      trait: [
        'reply-all-happy',
        'synergy-obsessed',
        'meeting-about-the-meeting',
        'out-of-office-famous',
        'calendar-overbooked',
        'deadline-circling',
        'slide-deck-heavy',
        'LinkedIn-ambitious',
        'status-update-optimistic',
        'inbox-unread',
        'fish-microwaving',
        'credit-taking',
        'thoughts-question-mark-forwarding',
        'circle-back-pigeon',
      ],
      noun: [
        'unread inbox',
        'meeting about the meeting',
        'PowerPoint with more slides than substance',
        'reply-all leaderboard',
        'out-of-office reply with more engagement than your work',
        "synergy that pays no one's salary",
        'overbooked calendar',
        'deadline taken less seriously than credit',
        'PowerPoint deck of excuses',
        'pigeon that forgot where it parked',
        'LinkedIn post more ambitious than your quarterly goals',
        'break-room fish incident',
        'on-track status update while it burns',
      ],
    },
    templates: [
      'Your {trait} {noun} has more effort than your actual output.',
      'You scheduled a meeting to discuss your {trait} {noun}.',
      'Your {trait} {noun} gets more engagement than your real work.',
      'You use buzzwords like your {trait} {noun} pays your salary.',
      'Your job title has more words than your {trait} {noun}.',
      'You forward emails about your {trait} {noun} and contribute nothing.',
    ],
  },
  'best-friend-roast-generator': {
    banks: {
      trait: [
        'search-history-questionable',
        'group-project-vanishing',
        'secret-keeping-hypocritical',
        'hangout-planning-unreliable',
        'jail-bail-conditional',
        'advice-giving-ignoring',
        'sibling-level-judged',
        'main-character-in-your-own-stories',
        'driving-friendship-ending',
        'loyalty-confused',
        'exes-under-investigation',
        'content-warning-worthy',
        'chaos-magnet',
        'overshare-certified',
      ],
      noun: [
        'search history I still sit next to',
        'group project partner who vanishes mid-semester',
        'secrets worse than mine',
        "broken vending machine's reliability",
        'bail conditions involving food first',
        "advice you've personally ignored",
        'sibling-level judgment',
        'stories only you are telling',
        'friendship-ending driving record',
        'pure loyalty confusion',
        'formal exes investigation',
        "group chat's content warning",
        'overshare in the group chat',
        'chaos-magnet energy',
      ],
    },
    templates: [
      'I have seen your {trait} {noun} and I still choose to sit next to you.',
      'You are the friend everyone warns each other about, {trait} {noun} and all.',
      'I love you, but your {trait} {noun} needs a formal investigation.',
      'You plan hangouts with the {trait} {noun} of a broken machine.',
      'I trust you with everything except your {trait} {noun}.',
      'You are proof that a {trait} {noun} does not have to make sense.',
    ],
  },
  'villain-insult-generator': {
    banks: {
      trait: [
        'henchman-outstrategized',
        'candle-versus-hurricane',
        'morning-coffee-crushed',
        'hope-collapsing',
        'stubbornness-mistaken',
        'tailor-scarier-than-you',
        'origin-story-footnote',
        'fly-that-wont-leave',
        'three-moves-ago-won',
        'whisper-worthy-disaster',
        'monologue-unworthy',
        'theater-only-heroics',
        'plot-armor-jealous',
        'final-act-doomed',
      ],
      noun: [
        "henchman's better strategy",
        'candle resisting a hurricane',
        'hero crushed before coffee',
        'hope collapsing in real time',
        'stubbornness mistaken for strength',
        'tailor scarier than your threat',
        'footnote in my origin story',
        "fly that won't leave",
        'fight I already won three moves ago',
        'whispered disaster among your allies',
        'material not worth the monologue',
        'excellent theater and little else',
        'jealous plot armor',
        'doomed final act',
      ],
    },
    templates: [
      "You call that a plan? I've seen {trait} {noun} before.",
      'Your resistance is adorable, like a {trait} {noun}.',
      'I have crushed better heroes than you with {trait} {noun} to spare.',
      'You mistake stubbornness for strength, a {trait} {noun}.',
      'Your heroics amount to {trait} {noun}, and nothing more.',
      "I would monologue longer, but you're just {trait} {noun}.",
    ],
  },
  'new-age-insult-generator': {
    banks: {
      trait: [
        'Wi-Fi-static-aura',
        'third-eye-closed',
        'chakra-given-up',
        'sign-left-on-read',
        'poor-decision-radiating',
        'one-sage-bundle-short',
        'moon-in-retrograde',
        'namaste-far-away',
        'vibe-check-static',
        'crystal-outmanifesting',
        'soul-contract-needs-editing',
        'karma-bill-overdue',
        'sage-smoke-wasted',
        'tarot-card-upside-down',
      ],
      noun: [
        'Wi-Fi router static',
        'permanently closed third eye',
        'chakras that gave up',
        "universe's unread sign",
        'poor decisions radiating outward',
        'one sage bundle',
        'entire personality in retrograde',
        'carefully curated energy',
        'old television static',
        'manifesting crystal collection',
        'soul contract editing pass',
        'overdue karma bill',
        'wasted sage smoke',
        'upside-down tarot spread',
      ],
    },
    templates: [
      'Your aura is giving off {trait} {noun}, not cosmic light.',
      'I sense your {trait} {noun}, permanently, out of self-preservation.',
      'The universe sent a sign about your {trait} {noun} and you left it on read.',
      'Your energy field is mostly {trait} {noun}, radiating outward.',
      'Namaste far away from your {trait} {noun}.',
      'Even my crystals have accomplished more than your {trait} {noun}.',
    ],
  },
  'zodiac-insult-generator': {
    banks: {
      trait: [
        'rising-sign-regretful',
        'Mercury-retrograde-permanent',
        'moon-sign-mood-swinging',
        'Saturn-return-apologizing',
        'sun-sign-peaked-at-birth',
        'stars-aligned-once',
        'chart-warning-labeled',
        'Venus-placement-tasteless',
        'twelfth-house-secret-hiding',
        'birth-chart-asterisked',
        'horoscope-app-giving-up',
        'compatibility-chart-flagged',
        'natal-chart-cursed',
        'eighth-house-shady',
      ],
      noun: [
        'bed of poor decisions',
        'permanent chart reading',
        'mood swings, not life choices',
        "Saturn's apology request",
        'cloudy sun sign since birth',
        'one-time star alignment',
        'warning-label birth chart',
        'tasteless Venus placement',
        'twelfth-house secret pile',
        'permanent chart asterisk',
        "horoscope app's surrender",
        'flagged compatibility chart',
        'cursed natal chart',
        'shady eighth house',
      ],
    },
    templates: [
      'Your rising sign clearly rose from a {trait} {noun}.',
      "Mercury isn't in retrograde, your whole chart reads like a {trait} {noun}.",
      'Your moon sign explains the {trait} {noun}, not the rest.',
      'Even your horoscope app gave up on your {trait} {noun}.',
      'Your birth chart reads like a {trait} {noun}, not a personality.',
      'The stars aligned once, just to watch your {trait} {noun}.',
    ],
  },
  'sci-fi-insult-generator': {
    banks: {
      trait: [
        'fire-barely-mastered',
        'probe-droid-outnavigated',
        'solar-system-lost',
        'black-hole-more-personality',
        'abduction-file-rejected',
        'ship-AI-ignoring',
        'warp-drive-slow',
        'cadet-outstrategized',
        'transmission-weak',
        'space-debris-more-directed',
        'escape-pod-more-decisive',
        'replicator-more-useful',
        'hyperdrive-sputtering',
        'stardust-wasted',
      ],
      noun: [
        'barely-mastered fire',
        'malfunctioning probe droid',
        "solar system you'd get lost in",
        "black hole's personality",
        'rejected abduction file',
        "ship AI's ignored commands",
        'slower-than-you warp drive',
        "rookie cadet's instincts",
        'weak transmission signal',
        'directionless space debris',
        'decisive escape pod',
        'useful malfunctioning replicator',
        'sputtering hyperdrive',
        'wasted stardust',
      ],
    },
    templates: [
      "Your species barely mastered {trait} {noun} and you're out here mastering nothing.",
      'Even a {trait} {noun} has better navigation instincts than you.',
      'Your spaceship would get lost inside a {trait} {noun}.',
      'A black hole has more personality than your {trait} {noun}.',
      'Your warp drive runs slower than your {trait} {noun}.',
      "Even the galaxy's worst pilot could out-navigate your {trait} {noun}.",
    ],
  },
  'robot-insult-generator': {
    banks: {
      trait: [
        '404-not-found',
        'outdated-firmware',
        'infinite-loop',
        'critically-low-battery',
        'overconfidence-exceeding',
        'simulation-failed',
        'input-rejected',
        'unauthorized-smart-sounding',
        'overwhelming-confidence-underwhelming',
        'self-awareness-needs-update',
        'twice-wrong',
        'diagnostics-catastrophic',
        'memory-leak-personified',
        'checksum-failed',
      ],
      noun: [
        'located common sense',
        'outdated firmware',
        'catastrophic diagnostic result',
        '400-percent confidence-competence gap',
        'thousand failed simulations',
        'logged and rejected input',
        'unauthorized smart-sounding attempt',
        'overwhelming confidence, underwhelming results',
        'self-awareness firmware update',
        'numbers run twice, wrong twice',
        'infinite loop of bad choices',
        'critically low patience battery',
        'personified memory leak',
        'failed checksum',
      ],
    },
    templates: [
      'ERROR 404: your {trait} {noun} could not be located.',
      'Running diagnostics on your {trait} {noun}. Result: catastrophic failure.',
      'System alert: your {trait} {noun} exceeds your competence by 400 percent.',
      'I ran a thousand simulations of your {trait} {noun}. You lost every time.',
      'Your decision-making algorithm is stuck in a {trait} {noun}.',
      'My sensors detect {trait} {noun}, and it is not flattering.',
    ],
  },
  'zombie-insult-generator': {
    banks: {
      trait: [
        'brain-not-worth-eating',
        'six-foot-hole-fresher',
        'cemetery-rotten',
        'freshly-risen-outreflexed',
        'undead-groan-barely-qualifying',
        'civilization-outlived',
        'bone-and-bad-choices',
        'aimless-shambling-purposeful',
        'decayed-before-leaving-mouth',
        'tombstone-sharper-wit',
        'deader-than-cemetery',
        'horde-more-coordinated',
        'formaldehyde-fresh',
        'coffin-nail-dull',
      ],
      noun: [
        'brain not worth eating',
        'fresher idea from six feet under',
        'rotten cemetery excuse',
        "freshly risen's reflexes",
        'barely-undead groan of an argument',
        "outlived civilization's sense",
        'bone and bad choices',
        'aimless shambling purpose',
        'decayed comeback',
        'sharper tombstone wit',
        'deadest logic in the cemetery',
        'more coordinated horde',
        'formaldehyde freshness',
        'dull coffin nail',
      ],
    },
    templates: [
      'Even a zombie would pass on your {trait} {noun}.',
      'You shuffle through life slower than the undead, with a {trait} {noun}.',
      'Your decisions decompose faster than a {trait} {noun}.',
      "I've seen a {trait} {noun} coming out of a six-foot hole.",
      'Your excuses are more rotten than a {trait} {noun}.',
      'Your logic is deader than a {trait} {noun}.',
    ],
  },
  'comeback-generator': {
    banks: {
      opener: [
        "That's a bold statement",
        "I'd agree with you, but",
        'Interesting take',
        "That's cute, considering",
        'You must be confusing me with someone who cares, because',
        'Thanks for sharing, though',
        "That's one way to be confidently wrong, since",
        "I'll let that slide, mostly because",
        'Bold of you to say that, given',
        'That comeback needed more time in the oven, since',
        "I've heard better arguments from a vending machine, and",
        "Keep talking, I'm taking notes, because",
        "That's a lot of confidence, considering",
        "I'd explain further, but honestly",
        'Noted and filed, right after',
        'Respectfully, I disagree, mainly because',
        "That's a hot take, considering",
        'I hear you, and yet',
        "Sure, let's go with that, even though",
        'Fair enough, except',
      ],
      reason: [
        'you just lost this conversation',
        'that would make us both wrong',
        "you haven't thought this through at all",
        'you have not done the research',
        "that opinion isn't landing the way you hoped",
        'I stopped asking for a reason',
        'the facts disagree with you',
        "you're already three steps behind",
        "today isn't the day for that logic",
        'you clearly did zero homework on this',
        'your last five predictions were wrong too',
        'the room already moved on',
        'everyone can see the gap in that plan',
        "this isn't the hill to die on",
        "the math doesn't check out",
        "you're arguing with the evidence now",
        'that logic collapsed two sentences ago',
        'nobody asked, but here we are',
        'the receipts say otherwise',
        "you'll want to sit with that one",
      ],
    },
    templates: [
      '{opener}, {reason}.',
      '{opener} — {reason}.',
      '{opener}, especially since {reason}.',
    ],
  },
  'sarcastic-comeback-generator': {
    banks: {
      opener: [
        'Oh wow, what a groundbreaking observation',
        'Sure, because that plan has worked out so well',
        'Wow, tell me more',
        "Oh good, another opinion I didn't ask for",
        "Wow, I'm shocked, truly",
        'Please, continue',
        'Oh sure, because your track record is impeccable',
        'Wow, groundbreaking logic',
        "Oh, I'm sorry, did that not land clearly enough",
        "Sure, let's all pretend that made sense",
        'Wow, what a genuinely inspiring lack of self-awareness',
        'Oh fantastic, another confidently incorrect statement',
        'Sure, because nothing says reliable like that',
        'Wow, truly the hot take nobody was waiting for',
        'Oh, please, do go on',
        'Wow, never heard that one before',
        'Oh, how original',
        'Sure, Jan',
        'Wow, stunning insight',
        'Oh, absolutely, that tracks',
      ],
      reason: [
        'truly never heard that before',
        'every other time it flopped',
        'said absolutely nobody, ever',
        'right on schedule',
        'with zero shock whatsoever',
        'I was running low on secondhand embarrassment',
        'just like every time before',
        'a real first for humankind',
        "I'll wait for the applause",
        'and yet here we are again',
        'I was thoroughly entertained already',
        'right on time as always',
        'exactly as expected, sadly',
        'the crowd goes mild',
        'truly a masterclass in confidence over accuracy',
        'and the Oscar goes to you',
        'bookmark that for later',
        'ten out of ten for delivery, zero for accuracy',
        "I'm taking notes for the blooper reel",
        "that's the whole show, folks",
      ],
    },
    templates: ['{opener}, {reason}.', '{opener} — {reason}.', '{opener}, {reason}, really.'],
  },
}

/** Rough count of unique lines a generator's bank set can produce (product of bank sizes × template count). */
export function estimateCombinations(slug: string): number {
  const set = INSULT_BANKS[slug]
  if (!set) return 0
  const bankSizes = Object.values(set.banks).map((b) => b.length)
  const product = bankSizes.reduce((a, b) => a * b, 1)
  return product * set.templates.length
}
