/**
 * TOOLTRIO — Insult Generator combinatorial libraries
 *
 * Word-bank + template libraries for every insult/roast/comeback generator
 * EXCEPT the Shakespeare Insult Generator, which has its own dedicated
 * combinatorial system in app/fun/shakespeare-insult-generator/CalculatorClient.tsx.
 *
 * Each entry combines multiple themed word banks (traits/nouns plus a bank of
 * period- or voice-appropriate opening phrases, or opener/reason/modifier for
 * the two comeback generators) into rotating sentence templates. Every
 * generator here produces 100,000+ unique lines. To expand any generator's
 * library further, add more words to its banks or more sentence templates —
 * everything downstream (the combination count shown on the page, the
 * generator itself) updates automatically.
 */

export interface InsultBankSet {
  /** Named word pools referenced by {placeholder} in templates, e.g. { trait: [...], noun: [...], opener: [...] } */
  banks: Record<string, string[]>
  /** Sentence templates using {bankName} placeholders, filled in at random on each generate() call */
  templates: string[]
}

export const INSULT_BANKS: Record<string, InsultBankSet> = {
  'medieval-insult-generator': {
    banks: {
      trait: [
        'turnip-brained',
        'mud-footed',
        'flea-bitten',
        'dung-shovelling',
        'cart-witted',
        'goose-hearted',
        'straw-stuffed',
        'plague-ridden',
        'donkey-faced',
        'cabbage-headed',
        'swine-mannered',
        'moat-smelling',
        'peasant-fingered',
        'gravy-brained',
        'hovel-raised',
        'gong-farming',
        'weevil-witted',
        'boar-tempered',
        'cesspit-minded',
        'rust-toothed',
        'leech-livered',
        'hay-brained',
        'chicken-hearted',
        'serf-witted',
        'bog-footed',
        'lice-infested',
        'pox-marked',
        'mead-drunk',
        'cart-dragging',
        'famine-brained',
        'hovel-dwelling',
        'witch-cursed',
        'crow-pecked',
        'wart-covered',
        'toad-licking',
        'onion-eyed',
        'barley-brained',
        'spittle-flecked',
        'gruel-fed',
        'sty-raised',
        'tick-bitten',
        'churl-hearted',
        'muck-encrusted',
        'harvest-shy',
        'yoke-necked',
      ],
      noun: [
        'turnip farmer',
        'gong farmer',
        'stable boy',
        'village fool',
        'pig herder',
        'tavern drunk',
        'hedge knight',
        'court jester',
        'plague rat',
        'moat scrubber',
        'dung collector',
        'hay bale',
        'broken cartwheel',
        'goat thief',
        "leper's bootlace",
        'rusty pitchfork',
        'one-eyed goose',
        'toothless squire',
        'muddy peasant',
        "cow's understudy",
        "beggar's shadow",
        'half-built siege tower',
        'drunken minstrel',
        'royal footstool',
        "kingdom's embarrassment",
        'mangy court hound',
        'broken millstone',
        'empty almshouse',
        'rat-gnawed sack of turnips',
        'crooked scarecrow',
        'three-legged mule',
        'overturned dung cart',
        'fallow field',
        'cracked church bell',
        "witch's forgotten familiar",
        'drowned scarecrow',
        'half-built stockade',
        'abandoned leper colony',
        'one-toothed miller',
        'henhouse thief',
      ],
      opener: [
        'By my troth,',
        'Hear me now,',
        'Mark my words,',
        'Verily I say,',
        'Forsooth,',
        'Upon my honor,',
        'As I live and breathe,',
        'Hearken well,',
        'Take heed, knave,',
        'In faith,',
        'I say plainly,',
        'Without jest,',
        'On my oath,',
        'Speak I true,',
        'Now hear this,',
      ],
    },
    templates: [
      '{opener} you feeble {trait} {noun}, even the pigs pity your company.',
      '{opener} begone, you {trait} {noun}, before the guards remove you.',
      '{opener} you argue like a {trait} {noun} who has never once won.',
      '{opener} the dungeon has better company than a {trait} {noun} like you.',
      '{opener} you smell of the stable and reason like a {trait} {noun}.',
      '{opener} even the court fool refuses to trade barbs with a {trait} {noun}.',
      '{opener} you are naught but a {trait} {noun} dressed in borrowed dignity.',
      '{opener} no lord would claim a {trait} {noun} such as yourself.',
      '{opener} the village bell rings louder sense than your {trait} {noun} skull.',
      '{opener} even the crows fly from a {trait} {noun} of your sort.',
    ],
  },
  'pirate-insult-generator': {
    banks: {
      trait: [
        'bilge-sucking',
        'barnacle-brained',
        'landlubbing',
        'seasick',
        'rum-soaked',
        'scurvy-riddled',
        'one-legged',
        'cross-eyed',
        'fish-gutted',
        'tar-fingered',
        'plank-footed',
        'salt-crusted',
        'mutinous',
        'weevil-eaten',
        'kraken-scared',
        'gull-brained',
        'anchor-headed',
        'parrot-mouthed',
        'bilge-rat-hearted',
        'cannon-shy',
        'shipwrecked',
        'tide-tossed',
        'gangplank-shy',
        'squid-livered',
        'hornswoggled',
        'grog-soaked',
        'barrel-bellied',
        'hornpipe-clumsy',
        'sextant-blind',
        'brig-bound',
        'hardtack-headed',
        'figurehead-witted',
        'doubloon-poor',
        'spyglass-cracked',
        'keelhaul-worthy',
        'sea-shanty-tone-deaf',
        'bilge-water-brained',
        'cutlass-shy',
        'treasure-map-illiterate',
        'tide-table-confused',
      ],
      noun: [
        'landlubber',
        'bilge rat',
        'cabin boy',
        'deckhand',
        'scallywag',
        'sea cook',
        'one-eyed gull',
        'seasick parrot',
        'drunken navigator',
        'broken compass',
        'leaky rowboat',
        'rusty anchor',
        'half-sunk dinghy',
        'mutinous mop',
        'barnacle collection',
        'fish-bait sailor',
        'cursed cabin',
        'empty rum barrel',
        "kraken's leftovers",
        'tide pool troll',
        'soggy map',
        'plank-walker',
        "ghost ship's ghost",
        "captain's disappointment",
        'broken hourglass',
        'seasick figurehead',
        'cracked spyglass',
        'empty rum cask',
        'tangled rigging',
        'three-legged sea dog',
        'bilge-flooded galley',
        "abandoned crow's nest",
        'sinking rowboat',
        'weevil-filled biscuit tin',
        'rusted cutlass',
        'waterlogged treasure chest',
        'confused compass rose',
        'toothless first mate',
        'runaway parrot',
      ],
      opener: [
        'Shiver me timbers,',
        'Blow me down,',
        'Avast,',
        'Hear this, ye scurvy dog,',
        "By Neptune's beard,",
        'Batten the hatches, for',
        'Yo ho, hear ye,',
        'Arr, mark this,',
        'On my honor as a pirate,',
        'Splice the mainbrace and hear,',
        'Heave to and listen,',
        'By the black flag,',
        'Mark me words, matey,',
        'Hoist the colors, for',
        'Aye, hear this well,',
      ],
    },
    templates: [
      "{opener} ye {trait} {noun}, ye couldn't swab a deck if yer life depended on it.",
      '{opener} walk the plank, ye {trait} {noun}, and take yer excuses with ye.',
      '{opener} has anyone met a bigger {trait} {noun} on the seven seas?',
      '{opener} ye fight like a {trait} {noun} in a hurricane, matey.',
      "{opener} even Davy Jones wouldn't want a {trait} {noun} in his locker.",
      "{opener} ye couldn't find treasure with a map, ye {trait} {noun}.",
      '{opener} ye be worth less to this crew than a {trait} {noun}.',
      '{opener} the whole fleet laughs at a {trait} {noun} such as ye.',
      '{opener} ye navigate worse than a {trait} {noun} in a fog.',
      '{opener} even the kraken spat out a {trait} {noun} like ye.',
    ],
  },
  'victorian-insult-generator': {
    banks: {
      trait: [
        'quaintly',
        'remarkably',
        'charmingly',
        'distressingly',
        'astonishingly',
        'tediously',
        'impertinently',
        'unfashionably',
        'insufferably',
        'provincially',
        'tiresomely',
        'laughably',
        'regrettably',
        'excruciatingly',
        'conspicuously',
        'fashionably-late-to-basic-sense',
        'exhaustingly',
        'tastelessly',
        'preposterously',
        'frightfully',
        'woefully',
        'dismayingly',
        'unbearably',
        'hopelessly',
        'dreadfully',
        'unspeakably',
        'scandalously',
        'vexingly',
        'wearisomely',
        'shockingly',
        'pitiably',
        'desperately',
        'curiously',
        'alarmingly',
      ],
      noun: [
        'opinion',
        'bonnet',
        'waistcoat',
        'calling card',
        'drawing-room manner',
        'tea-time remark',
        'carriage etiquette',
        'dinner conversation',
        'penmanship',
        'dance-card entry',
        'parlour gossip',
        'garden-party wit',
        "chaperone's patience",
        'embroidery hoop',
        "footman's restraint",
        "governess's report",
        'seating arrangement',
        'visiting hour',
        'letter of introduction',
        'promenade attire',
        'monocle-fogging remark',
        'calling-card faux pas',
        'teacup-rattling opinion',
        'hedge-maze of an excuse',
        'drawing-room blunder',
        'umbrella-stand of a personality',
        'piano recital of complaints',
        "governess's disappointment",
        'ballroom misstep',
        'overstarched collar of an argument',
        'carriage-wheel of a conversation',
        'fan-flutter of nonsense',
        'crumpet-cold retort',
        'hatbox of half-formed thoughts',
        'weathervane of an opinion',
      ],
      opener: [
        'I daresay,',
        'One does so wonder,',
        'How very singular that',
        'It is with some reluctance I note',
        'I confess myself astonished that',
        'One must remark,',
        'It would seem, regrettably, that',
        'I am compelled to observe',
        'Forgive my candour, but',
        'Society will note that',
        'It is not for me to say, yet',
        'One simply cannot ignore that',
        'I shall speak plainly, though it pains me:',
        'How curious, then, that',
        'I take the liberty of observing that',
      ],
    },
    templates: [
      '{opener} your {noun} is {trait} beneath the standard of polite company.',
      '{opener} one does so admire the confidence behind such a {trait} {noun}.',
      '{opener} your {noun} is, I fear, {trait} out of its depth this season.',
      "{opener} I shan't dignify your {noun} with more than a {trait} grimace.",
      '{opener} what a {trait} display, given your {noun} says otherwise.',
      '{opener} your {noun} has been the talk of the parlour, {trait} as it is.',
      '{opener} even the footman remarked upon your {trait} {noun}.',
      '{opener} your {noun} wants for manners as {trait} as it wants for sense.',
      '{opener} I have rarely witnessed a {trait} {noun} presented with such confidence.',
      '{opener} your {noun} would embarrass even a {trait} chimney sweep.',
    ],
  },
  'roast-generator': {
    banks: {
      trait: [
        'buffering',
        'expired',
        'unpatched',
        'clearance-rack',
        'off-brand',
        'discontinued',
        'low-battery',
        'laggy',
        'pixelated',
        'glitchy',
        'out-of-office',
        '404-error',
        'autocorrected',
        'overdrawn',
        'fine-print',
        'group-chat-only',
        'screenshot-worthy',
        'dial-up-speed',
        'participation-trophy',
        'airplane-mode',
        'spam-folder',
        'password-protected',
        'buffer-underrun',
        'unsubscribed',
        "ratio'd",
        'unfollowed',
        'muted',
        'screenshotted',
        'left-on-read',
        'soft-launched',
        'algorithm-buried',
        'shadow-banned',
        'doom-scrolled',
        'notification-silenced',
        'cache-cleared',
        'low-res',
        'autoplay-skipped',
        'typo-riddled',
        'cancelled-flight-tier',
      ],
      noun: [
        'Wi-Fi signal',
        'group chat',
        'personality',
        'comeback',
        'life update',
        'LinkedIn post',
        'main character arc',
        'browser with 47 tabs',
        'group project partner',
        'Bluetooth connection',
        'phone at one percent',
        'printer jam',
        'buffering wheel',
        'spam email',
        'cracked phone screen',
        'expired coupon',
        'forgotten password',
        'unread notification',
        'software update nobody wants',
        'autoplay ad',
        "ratio'd tweet",
        'unread group chat',
        'dead battery excuse',
        'group project no-show',
        'cracked charger cable',
        'buffering livestream',
        'expired app update',
        'spam call at dinner',
        'forgotten Zoom mute button',
        '404 error page',
        'low-battery selfie',
        'autoplay ad nobody wanted',
        'group chat left on read',
        'glitchy filter',
        'broken emoji reaction',
      ],
      opener: [
        'Real talk,',
        'No cap,',
        'Not gonna lie,',
        'Honestly though,',
        "Let's be real,",
        'Say it with me,',
        'Somebody had to say it,',
        'Plot twist:',
        'Breaking news:',
        'Fun fact nobody asked for:',
        'Update:',
        "In today's episode of you,",
        'Quick PSA:',
        'Just saying,',
        'Not to be dramatic, but',
      ],
    },
    templates: [
      '{opener} you bring the energy of a {trait} {noun}, and everyone notices.',
      '{opener} you have the reliability of a {trait} {noun} on a good day.',
      '{opener} you are the human version of a {trait} {noun}.',
      '{opener} somewhere, a {trait} {noun} is jealous of your consistency.',
      '{opener} your last decision had the confidence of a {trait} {noun}.',
      '{opener} you are proof that a {trait} {noun} can still show up uninvited.',
      '{opener} your personality loads slower than a {trait} {noun}.',
      "{opener} you're giving major {trait} {noun} energy today.",
      '{opener} even a {trait} {noun} has more follow-through than you.',
      '{opener} you peaked at the level of a {trait} {noun}, and stayed there.',
    ],
  },
  'savage-insult-generator': {
    banks: {
      trait: [
        'unrevised',
        'biohazard-labelled',
        'natural-selection-defying',
        'rough-draft',
        'expired-since-birth',
        'factory-recalled',
        'permanently-beta',
        'structurally-unsound',
        'quietly-discontinued',
        'chronically-unfinished',
        'pre-emptively-regretted',
        'warning-label-worthy',
        'clearance-priced',
        'irreversibly',
        'catastrophically',
        'unapologetically-mediocre',
        'budget-tier',
        'fundamentally-flawed',
        'overconfidently-wrong',
        'zero-star',
        'irredeemably',
        'structurally-cracked',
        'emotionally-recalled',
        'permanently-buffering',
        'unsalvageably',
        'terminally-basic',
        'aggressively-mediocre',
        'spiritually-bankrupt',
        'hopelessly-derivative',
        'quietly-obsolete',
        'factory-defected',
        'zero-effort',
        'willfully-clueless',
        'cosmically-unlucky',
        'chronically-underwhelming',
      ],
      noun: [
        'rough draft',
        'biohazard',
        'cautionary tale',
        'typo nobody fixed',
        'participation trophy',
        'plot twist nobody wanted',
        'houseplant that gave up',
        'coffee break from evolution',
        'forgotten homework',
        'broken vending machine',
        'expired warranty',
        'deleted scene',
        'unfinished sentence',
        'filler episode',
        'dead-end hallway',
        '404 page',
        'recalled product',
        'beta test',
        'puddle in a drought',
        'reply nobody sent',
        'discontinued app nobody updates',
        'group chat everyone muted',
        'warranty that expired at birth',
        'rerun nobody requested',
        'malfunctioning smoke detector',
        'empty promise with a bow on it',
        'group project excuse generator',
        'self-checkout that always needs help',
        'password nobody can remember',
        'printer that jams on principle',
        'cliffhanger nobody wanted resolved',
        "spare tire that's also flat",
        'backup plan with no plan',
        'search result on page two',
        'unskippable ad',
      ],
      opener: [
        "Let's not sugarcoat it,",
        "There's no polite way to say this, but",
        "I'll be blunt:",
        'Someone needed to say it:',
        "Here's the truth:",
        'No filter needed:',
        'Straight up,',
        'Zero hesitation here:',
        'I said what I said:',
        'This needed saying:',
        'Cutting straight to it,',
        'Without mercy:',
        'Full honesty:',
        'Not holding back:',
        'Bluntly put,',
      ],
    },
    templates: [
      '{opener} you are a {trait} {noun}, and everyone around you can tell.',
      '{opener} your existence reads like a {trait} {noun} that never got fixed.',
      "{opener} people don't dislike you, they forget you exist like a {trait} {noun}.",
      '{opener} your potential is a {trait} {noun} at this point.',
      '{opener} you are proof that a {trait} {noun} can still walk and talk.',
      '{opener} your best qualities are still stuck as a {trait} {noun}.',
      "{opener} you're not a red flag, you're a whole {trait} {noun}.",
      '{opener} even your excuses are {trait} {noun} material.',
      '{opener} you bring the energy of a {trait} {noun} to every room.',
      '{opener} your track record reads like a {trait} {noun} on repeat.',
    ],
  },
  'funny-insult-generator': {
    banks: {
      trait: [
        'wobbly',
        'confused',
        'overcaffeinated',
        'glittery',
        'off-key',
        'rubber-legged',
        'googly-eyed',
        'static-shocked',
        'cartoonishly',
        'spaghetti-armed',
        'hiccuping',
        'squeaky',
        'wind-up-toy',
        'upside-down',
        'bubble-wrapped',
        'clownish',
        'disco-lit',
        'rubber-chicken',
        'sock-puppet',
        'banana-peel',
        'boingy',
        'wobble-legged',
        'spring-loaded',
        'helium-voiced',
        'rubber-band',
        'bouncy-castle',
        'slapstick',
        'pratfall-prone',
        'confetti-brained',
        'kazoo-toned',
        'jack-in-the-box',
        'yo-yo-witted',
        'seltzer-fizzy',
        'cartwheel-clumsy',
        'balloon-animal',
      ],
      noun: [
        'penguin on roller skates',
        'Roomba with opinions',
        'flamingo mid-panic',
        'Wi-Fi router hunting for signal',
        'printer jam',
        'spider having a small seizure',
        'toddler on ice skates',
        'dolphin that heard a bad pun',
        'confused GPS',
        'cartoon character who fell off screen',
        'fire-alarm singing voice',
        'chaos-seasoned soup',
        'malfunctioning vending machine',
        'screen-door submarine',
        'one-man kazoo band',
        'overexcited sprinkler',
        'confused seal doing a trick wrong',
        'toddler chasing a bubble',
        'cat startled by a cucumber',
        'inflatable tube man in the wind',
        'goat yelling at nothing',
        'squirrel that forgot where it buried the nut',
        'pigeon strutting with a mission',
        'raccoon opening a jar of pickles',
        'dog chasing its own tail on ice',
        'parrot repeating the wrong word',
        'hamster on a wheel going nowhere fast',
        'penguin sliding into a wall',
        'toddler in oversized shoes',
        'clown car with one too many clowns',
        'kite stuck in a tree',
      ],
      opener: [
        'Okay but hear me out,',
        'Picture this:',
        'Not me saying it, but',
        "In today's chaos update,",
        'Plot twist,',
        'Breaking:',
        'Somebody get a camera, because',
        'True story:',
        'Witness report:',
        'And scene:',
        'Fun fact:',
        'Exhibit A:',
        'Live footage of you:',
        'According to science,',
        'Newsflash,',
      ],
    },
    templates: [
      '{opener} you have the coordination of a {trait} {noun}, and it shows.',
      '{opener} your dance moves look like a {trait} {noun} trying to find rhythm.',
      '{opener} you are basically a {trait} {noun} today, and nobody warned us.',
      '{opener} your fashion sense was assembled by a {trait} {noun}.',
      '{opener} you run like a {trait} {noun} that forgot where it was going.',
      '{opener} you have main character energy but the grace of a {trait} {noun}.',
      '{opener} your face when confused looks exactly like a {trait} {noun}.',
      '{opener} you walked in with the confidence of a {trait} {noun}.',
      '{opener} that plan had the structural integrity of a {trait} {noun}.',
      "{opener} you're giving full {trait} {noun} vibes right now.",
    ],
  },
  'friendly-insult-generator': {
    banks: {
      trait: [
        'favourite',
        'chaotic',
        'lovable',
        'certified',
        'walking',
        'hopeless',
        'gloriously',
        'personally-chosen',
        'unofficially-adopted',
        'delightfully',
        'undeniably',
        'affectionately-tolerated',
        'permanently-forgiven',
        'hall-of-fame',
        'five-star',
        'irreplaceable',
        'ride-or-die',
        'unofficially-legendary',
        'hall-of-fame-chaotic',
        'five-alarm-lovable',
        'emergency-contact-worthy',
        'group-chat-royalty',
        'permanently-adopted',
        'best-decision-I-ever-made',
        'favorite-menace',
        'certified-icon',
        'lovingly-unhinged',
        'forever-my-person',
        'chosen-family-tier',
        'irreplaceable-disaster',
        'gold-star-trouble',
      ],
      noun: [
        'disaster',
        'red flag',
        'group chat notification',
        'secondhand embarrassment',
        'questionable playlist',
        'ride-or-die energy',
        'bad influence',
        'crime scene of a text thread',
        'search-history mystery',
        'walking plot twist',
        'chosen chaos',
        'reason my search history looks unhinged',
        'favourite bad decision',
        'group project liability',
        "group chat's founding chaos agent",
        'the reason my search history is unhinged',
        'my emergency-contact-and-crime-partner',
        'the plot twist I signed up for',
        'my favorite bad influence on speed dial',
        'the friend my mom still asks about',
        'the reason I laugh in public alone',
        'my ride-or-die since day one',
        "the person I'd bail out of anything for",
        "the group chat's main character",
        'my personally-chosen chaos',
        'the friend with zero chill and all my love',
        'the reason I have trust issues and no regrets',
        'my favorite unhinged decision',
        'the friend who gets a pass on everything',
      ],
      opener: [
        'Say it with your whole chest,',
        'Real ones know,',
        "I'll say it louder for the back:",
        'No lie,',
        'Here for the record:',
        'Officially and forever,',
        'On everything I love,',
        'Cross my heart,',
        'No take-backs,',
        'Written in stone,',
        'For the record,',
        'I mean this with my whole heart,',
        'Loud and proud,',
        'Every single time,',
        'Always and forever,',
      ],
    },
    templates: [
      '{opener} you are my {trait} {noun}, and I would not trade you for anyone.',
      '{opener} I love you like family, which explains the {trait} {noun}.',
      '{opener} you are a {trait} {noun} I chose to plant a garden around.',
      '{opener} I keep you around purely for the {trait} {noun} you bring.',
      '{opener} you are proof my taste in friends includes a {trait} {noun}.',
      '{opener} I would defend you and your {trait} {noun} to literally anyone.',
      "{opener} you're my {trait} {noun}, and I'd do it all again.",
      "{opener} nobody warned me about a {trait} {noun} like you, and I'm grateful.",
      "{opener} you're the {trait} {noun} I never knew I needed.",
      "{opener} I chose you as my {trait} {noun}, and I'm not sorry.",
    ],
  },
  'fantasy-insult-generator': {
    banks: {
      trait: [
        'goblin-brained',
        'half-blind',
        'mana-starved',
        'dragon-shy',
        'troll-tracked',
        'basilisk-dazed',
        'orc-clumsy',
        'mimic-charmed',
        'quest-logged-empty',
        'rune-smudged',
        'potion-spilled',
        'staff-fumbling',
        'siege-shy',
        'dungeon-lost',
        'scroll-illiterate',
        'ogre-outwitted',
        'elf-mocked',
        'dwarf-outdrunk',
        'hydra-headed-but-brainless',
        'griffin-spooked',
        'phoenix-envious',
        'banshee-outscreamed',
        'kraken-shy',
        'chimera-confused',
        'gnome-outwitted',
        'unicorn-unimpressed',
        'spellbook-illiterate',
        'wyvern-wary',
        'enchantment-immune',
        'dungeon-fainted',
        'questgiver-ignored',
        'paladin-shamed',
        'necromancer-bored',
        'druid-disappointed',
      ],
      noun: [
        'goblin who forgot his weapon',
        'half-blind dwarf in an argument',
        "apprentice's first spark of magic",
        'training dummy in the courtyard',
        'troll tracked through fresh snow',
        'mimic pretending to be a chest',
        'basilisk staring contest loser',
        'orc charging uphill into a trap',
        'empty quest log',
        "tavern bard's worst ballad",
        'cursed suit of armor',
        'dragon too bored to breathe fire',
        "wizard's first failed spell",
        'siege tower missing wheels',
        'griffin that forgot how to fly',
        'phoenix that fizzled on the first try',
        'banshee with a sore throat',
        'gnome tripping over his own beard',
        'unicorn unimpressed by your quest',
        "paladin's disappointed sigh",
        'necromancer bored of raising you',
        'druid shaking his head slowly',
        'chimera arguing with itself',
        'wyvern too tired to swoop',
        "enchanted door that won't budge",
        'cursed ring nobody wants to touch',
        "bard's forgotten verse",
        'questline nobody finishes',
        "potion shop's returned stock",
      ],
      opener: [
        'By the ancient scrolls,',
        'Hear the prophecy:',
        'The elders foretold this:',
        'As the old runes say,',
        "By dragon's breath,",
        'The oracle warns,',
        'Mark this omen:',
        'By the sacred grove,',
        'The council decrees,',
        'As foretold in legend,',
        'By the old gods,',
        'The bard shall sing of this:',
        'As written in the grimoire,',
        'By starlight and steel,',
        'The quest log notes:',
      ],
    },
    templates: [
      '{opener} you have the battle instincts of a {trait} {noun}.',
      '{opener} even a {trait} {noun} could out-argue you in the dark.',
      '{opener} your spellcasting is weaker than a {trait} {noun}.',
      "{opener} you couldn't out-fence a {trait} {noun} in broad daylight.",
      "{opener} a dragon wouldn't bother breathing fire on a {trait} {noun} like you.",
      '{opener} even the goblins mock a {trait} {noun} like you behind your back.',
      "{opener} your quest log is emptier than a {trait} {noun}'s courage.",
      '{opener} the tavern falls silent for a {trait} {noun} such as you.',
      '{opener} even the elders warn young adventurers about a {trait} {noun}.',
      "{opener} you'd lose a duel to a {trait} {noun} with no weapon.",
    ],
  },
  'wizard-insult-generator': {
    banks: {
      trait: [
        'mana-starved',
        'spellbook-illiterate',
        'rune-smudged',
        'cauldron-scorched',
        'familiar-abandoned',
        'staff-cracked',
        'portal-misfired',
        'crystal-ball-rejected',
        'incantation-mumbling',
        'potion-botching',
        'grimoire-dusty',
        'wand-splintered',
        'hex-backfired',
        'enchantment-fizzled',
        'apprentice-grade',
        'candle-drowned',
        'spell-slurring',
        'wand-waving-uselessly',
        'potion-mislabeling',
        'rune-backwards',
        'familiar-fired',
        'tower-locked-out',
        'incantation-forgetting',
        'levitation-failing',
        'invisibility-half-worked',
        'teleport-missed',
        'scroll-burned',
        'alchemy-exploded',
        'ward-collapsed',
        'summon-fizzled',
        'curse-boomeranged',
      ],
      noun: [
        "first-year apprentice's spark",
        'enchanted broom',
        "cursed toad's conversation",
        "blindfolded troll's potion",
        "crystal ball's refusal",
        'toddler mispronouncing thunder',
        'half-asleep owl familiar',
        'spider-scribbled rune',
        "hedge witch's duel",
        'wax-drowned candle',
        "gargoyle's spare thought",
        'staff standing still',
        'portal to the next room',
        "grimoire's unread page",
        "apprentice's exploded cauldron",
        'half-memorized spell',
        'backfired invisibility charm',
        'upside-down spellbook page',
        'familiar that quit mid-spell',
        'wand that sparks and nothing more',
        'portal that leads to the wrong room',
        'potion that turned everything purple',
        'rune carved by a shaking hand',
        'summoning circle missing a line',
        'curse that hit the caster instead',
        'staff held the wrong way up',
        'grimoire with the pages stuck together',
        'crystal ball showing static',
        'levitation spell that lasted two seconds',
      ],
      opener: [
        'By the arcane order,',
        'The council of mages warns,',
        'As the old spellbooks decree,',
        'Hear this incantation:',
        'By staff and stone,',
        'The archmage has spoken:',
        'As foretold by the runes,',
        'By candle and chalk circle,',
        'The grimoire states plainly:',
        'Mark this hex:',
        'By the seven towers,',
        'As the elder wizards taught,',
        'The familiar has seen enough:',
        'By moonlight and mana,',
        'The last apprentice warned us:',
      ],
    },
    templates: [
      '{opener} your grasp of magic is weaker than a {trait} {noun}.',
      '{opener} I have seen a {trait} {noun} with more wisdom than you carry.',
      '{opener} a {trait} {noun} has better conversation than your incantations.',
      "{opener} you couldn't summon a familiar with the skill of a {trait} {noun}.",
      '{opener} even a {trait} {noun} out-thinks you on a slow day.',
      '{opener} your runes look like a {trait} {noun} fell into an inkpot.',
      '{opener} your spells fizzle out like a {trait} {noun} on a rainy day.',
      '{opener} the archmage would banish a {trait} {noun} like you on sight.',
      '{opener} even the tower cat casts better spells than a {trait} {noun}.',
      '{opener} your magic is about as reliable as a {trait} {noun}.',
    ],
  },
  'pirate-roast-generator': {
    banks: {
      trait: [
        'bathtub-captaining',
        'compass-arguing',
        'map-confused',
        'rum-brave',
        'knot-loosening',
        'star-chart-blind',
        'cannon-missing',
        'haggling-soft',
        'mutiny-prone',
        'tide-lost',
        'parrot-outsmarted',
        'plank-worthy',
        'gangplank-shy',
        'crew-pitied',
        'anchor-dragging',
        'rope-tangling',
        'cannonball-dodging-badly',
        'first-mate-embarrassing',
        'quartermaster-ignored',
        'deckswab-reluctant',
        'brig-frequent-flyer',
        'parrot-outranked',
        'hammock-falling',
        'galley-banned',
        "crow's-nest-scared",
        'treasure-splitting-unfair',
        'flag-lowering-coward',
        'storm-panicking',
        'reef-running',
        'siren-song-fooled',
      ],
      noun: [
        'bathtub fleet',
        'puddle of confusion',
        "ship's rats' instincts",
        'bravado-and-luck battle plan',
        'soft-handed swordsman',
        'memorized-more-than-you parrot',
        'undone knot',
        'self-mutiny',
        'unreadable star chart',
        "Blackbeard's rejection letter",
        'cannon aimed at nothing',
        'low-tide smell',
        'plank with better sailors on it',
        "crew's most-avoided bunkmate",
        "captain's biggest regret",
        'rope knot nobody trusts',
        'cannon that only misfires',
        'map with the treasure crossed out',
        "quartermaster's least favorite hire",
        "brig's frequent guest",
        "galley's banned cook",
        "crow's nest lookout who sees nothing",
        'storm that scares the fish more than the crew',
        "siren song's easiest catch",
        "first mate's daily headache",
        "ship's unluckiest deckhand",
        'flag that surrenders itself',
        'reef the captain warned about twice',
      ],
      opener: [
        'Listen up, crew,',
        "By the captain's orders,",
        'Mark this well, ye scallywag,',
        "Hear the quartermaster's report:",
        "As the ship's log records,",
        'By the Jolly Roger,',
        'The crew has spoken:',
        "Straight from the crow's nest:",
        'By the code of the sea,',
        'The first mate wants it known:',
        'Aye, and mark this,',
        'Word around the galley is,',
        "By the captain's own log,",
        'The whole crew agrees:',
        'Hear this from the helm:',
      ],
    },
    templates: [
      "{opener} ye couldn't captain a {trait} {noun}, let alone a galleon.",
      '{opener} yer treasure map leads straight to a {trait} {noun}.',
      '{opener} the crew follows ye out of pity, like a {trait} {noun}.',
      '{opener} even the {trait} {noun} has better instincts than ye, matey.',
      '{opener} yer battle plan is one part bravado, nine parts {trait} {noun}.',
      '{opener} even Blackbeard would send a {trait} {noun} like ye packing.',
      '{opener} the whole crew groans when ye act like a {trait} {noun}.',
      '{opener} ye navigate this ship like a {trait} {noun} with no compass.',
      "{opener} even the ship's rats outrank a {trait} {noun} like ye.",
      '{opener} yer knot-tying is as useless as a {trait} {noun}.',
    ],
  },
  'cowboy-insult-generator': {
    banks: {
      trait: [
        'tumbleweed-brained',
        'molasses-slow',
        'cactus-clumsy',
        'spur-jingling',
        'saddle-sore',
        'dust-blinded',
        'chihuahua-tough',
        'scarecrow-staring',
        'wagon-fallen',
        'fence-tangled',
        'poker-folding',
        'gunless',
        'rustler-shy',
        'stampede-lost',
        'corral-confused',
        'lasso-tangling',
        'horseshoe-unlucky',
        'hitching-post-witted',
        'rodeo-clown-outshined',
        'campfire-story-boring',
        'six-shooter-empty',
        'boot-scuffing',
        'dust-eating',
        'corral-fence-leaning',
        'cattle-drive-lost',
        'saloon-door-shy',
        'prairie-dog-outsmarted',
        'branding-iron-cold',
        'wagon-train-left-behind',
        'sheriff-star-tarnished',
      ],
      noun: [
        'blindfolded tumbleweed',
        'sack of potatoes off the wagon',
        'chihuahua guarding an empty ranch',
        "scarecrow's staring contest",
        'molasses in a January freeze',
        'fence post standing still',
        'saloon piano bluff',
        "dust storm's cheap tent",
        'stampede running through camp',
        'mildly annoyed cactus',
        "empty ranch's echo",
        'broken spur',
        "rodeo clown's warm-up act",
        'hitching post with more personality',
        "dust devil's confused cousin",
        "prairie dog's staring contest",
        "empty holster's confidence",
        "cattle drive's slowest straggler",
        "wagon wheel that won't turn",
        'campfire story nobody finishes',
        "saloon piano's flattest note",
        'branding iron gone cold',
        "tumbleweed's aimless wander",
        "sheriff's most doubtful deputy",
        'horseshoe missing all its luck',
        'corral fence with a gap in it',
        "rattlesnake's unimpressed rattle",
      ],
      opener: [
        'Now listen here, partner,',
        'Round these parts,',
        'As the old trail boss says,',
        'Mark my words, cowpoke,',
        "By the campfire's light,",
        'Straight from the saddle,',
        'As sure as sunrise,',
        'The whole ranch agrees,',
        "Well I'll be,",
        'Down at the saloon they say,',
        'As the sheriff put it,',
        'Out on the range,',
        'Plain as day,',
        'By the old corral fence,',
        'Word around the ranch is,',
      ],
    },
    templates: [
      "{opener} you couldn't herd cattle with the skill of a {trait} {noun}.",
      '{opener} your aim is worse than a {trait} {noun} in a windstorm.',
      '{opener} you ride like a {trait} {noun} that fell off twice.',
      '{opener} you talk tougher than a {trait} {noun}, partner.',
      "{opener} you'd lose a staring contest with a {trait} {noun}.",
      '{opener} your poker face folds faster than a {trait} {noun}.',
      "{opener} you're about as useful as a {trait} {noun} on roundup day.",
      '{opener} even the horses laugh at a {trait} {noun} like you.',
      '{opener} your draw is slower than a {trait} {noun} at high noon.',
      '{opener} the whole ranch talks about your {trait} {noun} ways.',
    ],
  },
  'royal-insult-generator': {
    banks: {
      trait: [
        'stable-hand-mannered',
        'court-jester-unremarkable',
        'banished-by-decree',
        'throne-unworthy',
        'scepter-less',
        'crown-tarnished',
        'footman-graced',
        'palace-hound-outjudged',
        'border-guard-pitied',
        'dinner-hall-silenced',
        'bloodline-embarrassing',
        'hall-echoing',
        'kingdom-surviving-despite',
        'stable-fit',
        'guard-escorted',
        'scepter-unworthy',
        'tapestry-mocked',
        'moat-adjacent',
        'banquet-hall-embarrassing',
        'royal-seal-rejected',
        'herald-mispronounced',
        'coronation-uninvited',
        'tower-locked',
        'chamberlain-sighing',
        'minstrel-mocked',
        'garden-party-banished',
        'ballroom-tripping',
        'crest-tarnishing',
        'procession-lagging',
        'dais-unfit',
      ],
      noun: [
        "stable hand's grace",
        "court jester's unremarkable wit",
        "royal decree's leftovers",
        "palace hound's dinner manners",
        "border guard's new company",
        "throne room's silence",
        'common sense the crown never installed',
        "footman's restraint",
        "kingdom's survival despite you",
        'scepter-less command',
        'dull conversation escorted from the hall',
        "jester's rejected script",
        "herald's mispronounced announcement",
        "banquet hall's quietest corner",
        "chamberlain's long sigh",
        "minstrel's worst-received ballad",
        "garden party's uninvited guest",
        "ballroom's clumsiest dancer",
        "tower's least distinguished prisoner",
        "procession's slowest cart",
        'dais unfit for lesser nobles',
        'royal seal smudged beyond use',
        "coronation's forgotten invitation",
        'tapestry woven with your failures',
        'crest that faded from embarrassment',
        "throne room's echoing silence",
        "royal guard's least favorite duty",
      ],
      opener: [
        'By royal decree,',
        'Hear ye, hear ye,',
        'The crown proclaims,',
        'As the royal court observes,',
        'By order of the throne,',
        'The chamberlain announces,',
        'Let it be known throughout the realm,',
        'The herald declares,',
        "By the sovereign's own word,",
        'As recorded in the royal ledger,',
        'The court whispers,',
        'By scepter and crown,',
        'The kingdom shall hear this:',
        'As decreed this very day,',
        'The royal seal confirms:',
      ],
    },
    templates: [
      '{opener} your {trait} {noun} is hereby banished from this court.',
      '{opener} I have seen {trait} {noun} with more grace than you carry, my dear subject.',
      '{opener} your title outshines your {trait} {noun} by a wide margin.',
      '{opener} even the court jester finds your {trait} {noun} unremarkable.',
      '{opener} the kingdom survives despite your {trait} {noun}, not because of it.',
      '{opener} one does not need a scepter to outrank your {trait} {noun}.',
      '{opener} the whole court whispers about your {trait} {noun}.',
      '{opener} even the stable boy carries himself better than a {trait} {noun}.',
      '{opener} your {trait} {noun} would embarrass the royal bloodline itself.',
      '{opener} the throne has seen better company than a {trait} {noun}.',
    ],
  },
  'schoolyard-insult-generator': {
    banks: {
      trait: [
        'locker-smelling',
        'dodgeball-dodging',
        'cafeteria-nicknamed',
        'pop-quiz-crying',
        'hand-me-down',
        'four-square-losing',
        'homework-copying',
        'lunch-trading-scammy',
        'backpack-heavy',
        'rock-paper-scissors-cursed',
        'recess-only-cardio',
        'show-and-tell-borrowed',
        'gym-class-tripping',
        'cartoon-script-excusing',
        'hall-pass-abusing',
        'spelling-bee-eliminated',
        'field-day-last-place',
        'detention-regular',
        'cafeteria-tray-dropping',
        'locker-combination-forgetting',
        'substitute-teacher-tricking',
        'bus-seat-hogging',
        'show-and-tell-flopping',
        'permission-slip-losing',
        'gym-rope-failing',
        'yearbook-photo-blinking',
        'pop-quiz-panicking',
        'fire-drill-overreacting',
        'recess-bell-ignoring',
      ],
      noun: [
        'nobody-wants-to-open locker',
        'never-played-dodgeball aim',
        'whole-cafeteria nickname',
        'personally-betrayed pop quiz',
        'textbook-beating jacket history',
        'four-square loss streak',
        'one true talent of copying',
        'legally-a-scam lunch trade',
        'heavier-than-excuses backpack',
        'cursed rock-paper-scissors streak',
        'only-cardio recess',
        "someone-else's-idea show-and-tell",
        'gym-class-history trip',
        "field day's last-place finisher",
        'detention hall regular',
        "substitute teacher's worst day",
        'bus seat nobody wants',
        'yearbook photo everyone remembers wrong',
        'gym rope-climb quitter',
        'fire drill overreaction',
        'pop quiz cold sweat',
        'hall pass abuse case',
        "spelling bee's first-round exit",
        'cafeteria tray disaster',
        'locker combination nobody remembers',
        'permission slip lost forever',
        'recess bell sprinter',
        'show-and-tell flop',
      ],
      opener: [
        'Everybody knows,',
        'Word around the playground is,',
        'Recess court has ruled:',
        'The whole cafeteria saw it:',
        'Straight from the back of the bus,',
        'As the hall monitor noted,',
        'The class agrees:',
        'Breaking playground news:',
        'Even the teacher noticed,',
        'Word travels fast at lunch:',
        'The whole grade knows,',
        'As seen on the bus ride home,',
        'Everyone in gym class saw,',
        'The yearbook committee agrees,',
        'Recess legend has it,',
      ],
    },
    templates: [
      '{opener} your face is giving the class a free reason to skip lunch, {trait} {noun}.',
      '{opener} you smell like a {trait} {noun}, and everyone can tell.',
      '{opener} your homework excuses have more plot holes than a {trait} {noun}.',
      '{opener} you have the aim of someone with a {trait} {noun}.',
      '{opener} your nickname came from a {trait} {noun}, and it stuck.',
      '{opener} you lose at everything the way a {trait} {noun} loses at recess.',
      "{opener} you're basically the class's official {trait} {noun}.",
      '{opener} even the lunch lady remembers your {trait} {noun} moment.',
      '{opener} your permission slip excuses read like a {trait} {noun}.',
      "{opener} you'd lose a staring contest with a {trait} {noun}.",
    ],
  },
  'office-roast-generator': {
    banks: {
      trait: [
        'reply-all-happy',
        'synergy-obsessed',
        'meeting-about-the-meeting',
        'out-of-office-famous',
        'calendar-overbooked',
        'deadline-circling',
        'slide-deck-heavy',
        'LinkedIn-ambitious',
        'status-update-optimistic',
        'inbox-unread',
        'fish-microwaving',
        'credit-taking',
        'thoughts-question-mark-forwarding',
        'circle-back-pigeon',
        'all-hands-dreading',
        'standup-rambling',
        'ticket-reassigning',
        'sprint-derailing',
        'slack-status-lying',
        'expense-report-padding',
        'cc-everyone-happy',
        'parking-spot-stealing',
        'microwave-fish-reheating',
        'badge-photo-cursed',
        'onboarding-doc-outdated',
        'quarterly-goal-vague',
        'performance-review-dodging',
        'water-cooler-gossiping',
        'zoom-background-fake',
      ],
      noun: [
        'unread inbox',
        'meeting about the meeting',
        'PowerPoint with more slides than substance',
        'reply-all leaderboard',
        'out-of-office reply with more engagement than your work',
        "synergy that pays no one's salary",
        'overbooked calendar',
        'deadline taken less seriously than credit',
        'PowerPoint deck of excuses',
        'pigeon that forgot where it parked',
        'LinkedIn post more ambitious than your quarterly goals',
        'break-room fish incident',
        'on-track status update while it burns',
        'all-hands meeting nobody wanted',
        'standup update that ran ten minutes long',
        'ticket reassigned four times',
        'sprint that derailed itself',
        "Slack status that's been 'in a meeting' for six hours",
        'expense report with mystery charges',
        "reply-all chain that won't die",
        'parking spot stolen before nine',
        'fake Zoom background hiding real chaos',
        'performance review nobody wants to give',
        'water cooler rumor mill',
        'badge photo from a worse year',
        'onboarding doc last updated three CEOs ago',
        'quarterly goal nobody remembers setting',
        'fish reheated in the break room',
      ],
      opener: [
        'Per my last email,',
        'Circling back on this,',
        'Just floating this out there,',
        'Per our earlier sync,',
        'To close the loop,',
        'Quick gut check:',
        "Just so we're aligned,",
        'Per the org chart,',
        'Looping in everyone to say,',
        'For visibility,',
        'Just flagging this,',
        'To align expectations,',
        'Per the roadmap,',
        "Just so it's documented,",
        'Per the retro notes,',
      ],
    },
    templates: [
      '{opener} your {trait} {noun} has more effort than your actual output.',
      '{opener} you scheduled a meeting to discuss your {trait} {noun}.',
      '{opener} your {trait} {noun} gets more engagement than your real work.',
      '{opener} you use buzzwords like your {trait} {noun} pays your salary.',
      '{opener} your job title has more words than your {trait} {noun}.',
      '{opener} you forward emails about your {trait} {noun} and contribute nothing.',
      '{opener} your {trait} {noun} is the real reason this sprint slipped.',
      '{opener} even the intern out-produces your {trait} {noun}.',
      '{opener} your calendar has more meetings about your {trait} {noun} than actual work.',
      '{opener} HR has a whole folder on your {trait} {noun}.',
    ],
  },
  'best-friend-roast-generator': {
    banks: {
      trait: [
        'search-history-questionable',
        'group-project-vanishing',
        'secret-keeping-hypocritical',
        'hangout-planning-unreliable',
        'jail-bail-conditional',
        'advice-giving-ignoring',
        'sibling-level-judged',
        'main-character-in-your-own-stories',
        'driving-friendship-ending',
        'loyalty-confused',
        'exes-under-investigation',
        'content-warning-worthy',
        'chaos-magnet',
        'overshare-certified',
        '3am-text-sending',
        'road-trip-navigating-wrong',
        'group-photo-blinking',
        'concert-ticket-losing',
        'birthday-forgetting-then-overcompensating',
        'diet-starting-monday-again',
        'ex-stalking-admitting',
        'borrowed-clothes-never-returning',
        'designated-driver-dodging',
        'karaoke-mic-hogging',
        'gossip-spilling-too-fast',
        'plan-canceling-last-minute',
        'snack-stealing-unapologetic',
        'selfie-retaking-forever',
        'group-chat-typo-legendary',
      ],
      noun: [
        'search history I still sit next to',
        'group project partner who vanishes mid-semester',
        'secrets worse than mine',
        "broken vending machine's reliability",
        'bail conditions involving food first',
        "advice you've personally ignored",
        'sibling-level judgment',
        'stories only you are telling',
        'friendship-ending driving record',
        'pure loyalty confusion',
        'formal exes investigation',
        "group chat's content warning",
        'overshare in the group chat',
        'chaos-magnet energy',
        '3am text I still answer',
        'road trip navigator who got us lost twice',
        'group photo blink streak',
        'concert ticket lost the day of',
        'birthday forgotten then way overcompensated for',
        'Monday diet that never starts',
        'ex you still low-key check on',
        'borrowed hoodie from two years ago',
        'designated driver who bailed',
        'karaoke mic you refuse to share',
        'secret you told approximately everyone',
        'plan canceled forty minutes before',
        'snack stash you raid without asking',
        'selfie retaken eleven times',
        'group chat typo that became a legend',
      ],
      opener: [
        'I say this with love,',
        'Real talk, bestie,',
        'As your best friend, I have to say,',
        'No judgment, but',
        'Love you, but',
        'Ride or die means I get to say,',
        'As the friend who knows everything,',
        'Straight up, bestie,',
        'With all the love in the world,',
        "I've earned the right to say this:",
        'Best friend privileges activated:',
        'You know I love you, but',
        'Honestly, bestie,',
        'Since we tell each other everything,',
        'As your ride or die,',
      ],
    },
    templates: [
      '{opener} I have seen your {trait} {noun} and I still choose to sit next to you.',
      '{opener} you are the friend everyone warns each other about, {trait} {noun} and all.',
      '{opener} your {trait} {noun} needs a formal investigation.',
      '{opener} you plan hangouts with the {trait} {noun} of a broken machine.',
      '{opener} I trust you with everything except your {trait} {noun}.',
      '{opener} you are proof that a {trait} {noun} does not have to make sense.',
      '{opener} only you could turn a {trait} {noun} into a whole personality trait.',
      '{opener} I still bring up your {trait} {noun} at every group hangout.',
      '{opener} your {trait} {noun} is the reason our group chat exists.',
      '{opener} everyone else has heard about your {trait} {noun} by now.',
    ],
  },
  'villain-insult-generator': {
    banks: {
      trait: [
        'henchman-outstrategized',
        'candle-versus-hurricane',
        'morning-coffee-crushed',
        'hope-collapsing',
        'stubbornness-mistaken',
        'tailor-scarier-than-you',
        'origin-story-footnote',
        'fly-that-wont-leave',
        'three-moves-ago-won',
        'whisper-worthy-disaster',
        'monologue-unworthy',
        'theater-only-heroics',
        'plot-armor-jealous',
        'final-act-doomed',
        'sidekick-outsmarted',
        'cape-tangling',
        'secret-lair-embarrassing',
        'master-plan-leaking',
        'doomsday-device-jamming',
        'evil-laugh-cracking',
        'nemesis-underwhelming',
        'world-domination-postponed',
        'trap-door-malfunctioning',
        'monologue-interrupting',
        'henchman-quitting',
        'cliffhanger-ruining',
        'final-boss-undeserving',
        'prophecy-misreading',
        'alliance-betraying-poorly',
      ],
      noun: [
        "henchman's better strategy",
        'candle resisting a hurricane',
        'hero crushed before coffee',
        'hope collapsing in real time',
        'stubbornness mistaken for strength',
        'tailor scarier than your threat',
        'footnote in my origin story',
        "fly that won't leave",
        'fight I already won three moves ago',
        'whispered disaster among your allies',
        'material not worth the monologue',
        'excellent theater and little else',
        'jealous plot armor',
        'doomed final act',
        'sidekick who saw this coming',
        'cape that got caught in a door',
        'secret lair with a leaky roof',
        'master plan leaked in the group chat',
        'doomsday device stuck in traffic',
        'evil laugh that cracked mid-cackle',
        "nemesis who's honestly underwhelmed",
        'world domination postponed indefinitely',
        'trap door that stuck halfway',
        'monologue nobody let you finish',
        'henchman who quit via text',
        "cliffhanger nobody's worried about",
        "final boss fight you didn't earn",
        'prophecy you clearly misread',
        'alliance you betrayed too early to matter',
      ],
      opener: [
        'Let me make this clear,',
        'You should know by now,',
        'Allow me to explain,',
        'Foolish as always,',
        'How predictable,',
        'As I expected,',
        'Naturally,',
        'Once again,',
        'How tediously familiar,',
        'As always,',
        'Let the record show,',
        'You never learn, do you,',
        'Predictably,',
        'As the villain of this story, I must say,',
        'How utterly unsurprising,',
      ],
    },
    templates: [
      "{opener} you call that a plan? I've seen {trait} {noun} before.",
      '{opener} your resistance is adorable, like a {trait} {noun}.',
      '{opener} I have crushed better heroes than you with {trait} {noun} to spare.',
      '{opener} you mistake stubbornness for strength, a {trait} {noun}.',
      '{opener} your heroics amount to {trait} {noun}, and nothing more.',
      "{opener} I would monologue longer, but you're just {trait} {noun}.",
      '{opener} even my {trait} {noun} outmaneuvers you.',
      "{opener} you're not my nemesis, you're barely a {trait} {noun}.",
      '{opener} the world will remember me, and forget your {trait} {noun}.',
      "{opener} I've defeated heroes with more spine than your {trait} {noun}.",
    ],
  },
  'new-age-insult-generator': {
    banks: {
      trait: [
        'Wi-Fi-static-aura',
        'third-eye-closed',
        'chakra-given-up',
        'sign-left-on-read',
        'poor-decision-radiating',
        'one-sage-bundle-short',
        'moon-in-retrograde',
        'namaste-far-away',
        'vibe-check-static',
        'crystal-outmanifesting',
        'soul-contract-needs-editing',
        'karma-bill-overdue',
        'sage-smoke-wasted',
        'tarot-card-upside-down',
        'crystal-grid-misaligned',
        'sage-smoke-choking',
        'tarot-spread-upside-down-twice',
        'full-moon-overreacting',
        'mercury-blaming-everything',
        'chakra-blocked-permanently',
        'aura-photograph-embarrassing',
        'incense-overkill',
        'meditation-app-abandoned',
        'manifestation-journal-empty',
        'sound-bath-off-key',
        'essential-oil-overapplied',
        'palm-reading-avoided',
        'energy-vampire-confirmed',
        'retrograde-excuse-overused',
      ],
      noun: [
        'Wi-Fi router static',
        'permanently closed third eye',
        'chakras that gave up',
        "universe's unread sign",
        'poor decisions radiating outward',
        'one sage bundle',
        'entire personality in retrograde',
        'carefully curated energy',
        'old television static',
        'manifesting crystal collection',
        'soul contract editing pass',
        'overdue karma bill',
        'wasted sage smoke',
        'upside-down tarot spread',
        'crystal grid nobody charged',
        'sage smoke that set off the alarm',
        'tarot spread read upside down twice',
        'full moon ritual that fizzled',
        'Mercury blamed for a Tuesday',
        "aura photo everyone's confused by",
        'incense that cleared the whole room, literally',
        'meditation app opened once and abandoned',
        'manifestation journal with one entry',
        'sound bath that hit all the wrong notes',
        'essential oil applied a little too generously',
        'palm reading you walked out of',
        'energy vampire nobody invited',
        'chakra chart with a permanent blockage',
        'retrograde excuse used for the fourth time this month',
      ],
      opener: [
        'The universe wants you to know,',
        'Energetically speaking,',
        'As the crystals reveal,',
        'Spirit is telling me,',
        'According to your aura,',
        "The cards don't lie:",
        'Namaste, but honestly,',
        'As above, so below, and also,',
        'Your chakras are practically screaming,',
        'The moon has seen enough:',
        'Manifesting this truth:',
        'With all the love and light I have,',
        'The tarot confirms,',
        'Channeling this message for you:',
        'As my third eye sees it,',
      ],
    },
    templates: [
      '{opener} your aura is giving off {trait} {noun}, not cosmic light.',
      '{opener} I sense your {trait} {noun}, permanently, out of self-preservation.',
      '{opener} the universe sent a sign about your {trait} {noun} and you left it on read.',
      '{opener} your energy field is mostly {trait} {noun}, radiating outward.',
      '{opener} namaste far away from your {trait} {noun}.',
      '{opener} even my crystals have accomplished more than your {trait} {noun}.',
      '{opener} your chakras are blocked by your own {trait} {noun}.',
      "{opener} the cards keep drawing your {trait} {noun}, and it's not subtle.",
      '{opener} your vibe check failed because of your {trait} {noun}.',
      "{opener} I'm releasing your {trait} {noun} back to the universe, with love.",
    ],
  },
  'zodiac-insult-generator': {
    banks: {
      trait: [
        'rising-sign-regretful',
        'Mercury-retrograde-permanent',
        'moon-sign-mood-swinging',
        'Saturn-return-apologizing',
        'sun-sign-peaked-at-birth',
        'stars-aligned-once',
        'chart-warning-labeled',
        'Venus-placement-tasteless',
        'twelfth-house-secret-hiding',
        'birth-chart-asterisked',
        'horoscope-app-giving-up',
        'compatibility-chart-flagged',
        'natal-chart-cursed',
        'eighth-house-shady',
        'ascendant-in-denial',
        'north-node-avoiding',
        'synastry-chart-flagged',
        'transit-blaming-everything',
        'sun-sign-only-knowledge',
        'cusp-claiming-conveniently',
        'placement-mispronouncing',
        'reading-cherry-picking',
        'compatibility-quiz-failing',
        'fire-sign-all-talk',
        'earth-sign-all-excuses',
        'air-sign-all-theory',
        'water-sign-all-vibes',
        'house-system-confused',
        'aspect-ignoring',
      ],
      noun: [
        'bed of poor decisions',
        'permanent chart reading',
        'mood swings, not life choices',
        "Saturn's apology request",
        'cloudy sun sign since birth',
        'one-time star alignment',
        'warning-label birth chart',
        'tasteless Venus placement',
        'twelfth-house secret pile',
        'permanent chart asterisk',
        "horoscope app's surrender",
        'flagged compatibility chart',
        'cursed natal chart',
        'shady eighth house',
        "ascendant you're clearly in denial about",
        'north node you keep avoiding',
        'synastry chart flagged in red',
        'transit blamed for a bad Tuesday',
        'sun sign knowledge and nothing deeper',
        "cusp claim that's conveniently timed",
        "placement you can't pronounce correctly",
        'reading you cherry-picked for validation',
        'compatibility quiz you failed twice',
        "fire sign energy that's all talk",
        'earth sign excuse for everything',
        'air sign theory with zero follow-through',
        'water sign vibe with no substance',
        'house system you never learned',
        'aspect you conveniently ignore',
      ],
      opener: [
        'The stars have spoken,',
        'According to your chart,',
        'As the cosmos reveals,',
        'Your placements confirm it:',
        'The horoscope app agrees:',
        'As written in the sky,',
        "Your birth chart doesn't lie:",
        'The transits are clear on this:',
        'As your rising sign suggests,',
        'The astrologers would agree:',
        'Cosmically speaking,',
        'As the planets align to say,',
        'Your natal chart is basically screaming:',
        'The zodiac has receipts:',
        'As Mercury would confirm,',
      ],
    },
    templates: [
      '{opener} your rising sign clearly rose from a {trait} {noun}.',
      '{opener} your whole chart reads like a {trait} {noun}.',
      '{opener} your moon sign explains the {trait} {noun}, not the rest.',
      '{opener} even your horoscope app gave up on your {trait} {noun}.',
      '{opener} your birth chart reads like a {trait} {noun}, not a personality.',
      '{opener} the stars aligned once, just to watch your {trait} {noun}.',
      '{opener} your compatibility chart flags your {trait} {noun} every time.',
      '{opener} Saturn is still apologizing for your {trait} {noun}.',
      '{opener} your twelfth house is hiding your {trait} {noun}, badly.',
      '{opener} even a beginner astrologer could spot your {trait} {noun}.',
    ],
  },
  'sci-fi-insult-generator': {
    banks: {
      trait: [
        'fire-barely-mastered',
        'probe-droid-outnavigated',
        'solar-system-lost',
        'black-hole-more-personality',
        'abduction-file-rejected',
        'ship-AI-ignoring',
        'warp-drive-slow',
        'cadet-outstrategized',
        'transmission-weak',
        'space-debris-more-directed',
        'escape-pod-more-decisive',
        'replicator-more-useful',
        'hyperdrive-sputtering',
        'stardust-wasted',
        'airlock-jamming',
        'tractor-beam-missing',
        'hyperspace-lag',
        'replicator-malfunctioning',
        'stardrive-sputtering',
        'cryo-pod-oversleeping',
        'first-contact-botched',
        'distress-signal-ignored',
        'alien-translator-glitching',
        'spacesuit-leaking',
        'docking-bay-crashing',
        'nebula-lost',
        'quantum-jump-miscalculated',
        'gravity-well-confused',
        'star-chart-outdated',
      ],
      noun: [
        'barely-mastered fire',
        'malfunctioning probe droid',
        "solar system you'd get lost in",
        "black hole's personality",
        'rejected abduction file',
        "ship AI's ignored commands",
        'slower-than-you warp drive',
        "rookie cadet's instincts",
        'weak transmission signal',
        'directionless space debris',
        'decisive escape pod',
        'useful malfunctioning replicator',
        'sputtering hyperdrive',
        'wasted stardust',
        'airlock that jams at the worst time',
        'tractor beam that never locks on',
        'hyperspace jump with terrible lag',
        'replicator that only makes static',
        'stardrive that sputters mid-launch',
        'cryo pod set to oversleep',
        'first contact that went horribly wrong',
        'distress signal nobody answered',
        'alien translator stuck on gibberish',
        'spacesuit with a slow leak',
        'docking bay collision waiting to happen',
        'ship lost in a nebula for hours',
        'quantum jump that missed by a galaxy',
        'gravity well nobody warned you about',
        'star chart from three centuries ago',
      ],
      opener: [
        "Captain's log:",
        "Ship's computer confirms:",
        'As the star charts reveal,',
        'Mission control reports:',
        'According to the sensor readout,',
        'The android has calculated:',
        'As the crew manifest notes,',
        'Deep space transmission received:',
        "The ship's AI would like to add:",
        'As recorded in the flight log,',
        'Sensor sweep confirms:',
        'The away team reports:',
        'As predicted by the navigation computer,',
        'Bridge report:',
        "As logged by the ship's black box,",
      ],
    },
    templates: [
      "{opener} your species barely mastered {trait} {noun} and you're out here mastering nothing.",
      '{opener} even a {trait} {noun} has better navigation instincts than you.',
      '{opener} your spaceship would get lost inside a {trait} {noun}.',
      '{opener} a black hole has more personality than your {trait} {noun}.',
      '{opener} your warp drive runs slower than your {trait} {noun}.',
      "{opener} even the galaxy's worst pilot could out-navigate your {trait} {noun}.",
      '{opener} your away-team skills rival a {trait} {noun} in a spacesuit.',
      '{opener} mission control flagged your {trait} {noun} three systems ago.',
      "{opener} the ship's AI has more empathy than your {trait} {noun}.",
      '{opener} even the aliens filed a report about your {trait} {noun}.',
    ],
  },
  'robot-insult-generator': {
    banks: {
      trait: [
        '404-not-found',
        'outdated-firmware',
        'infinite-loop',
        'critically-low-battery',
        'overconfidence-exceeding',
        'simulation-failed',
        'input-rejected',
        'unauthorized-smart-sounding',
        'overwhelming-confidence-underwhelming',
        'self-awareness-needs-update',
        'twice-wrong',
        'diagnostics-catastrophic',
        'memory-leak-personified',
        'checksum-failed',
        'firmware-corrupted',
        'battery-swelling',
        'fan-rattling',
        'cable-fraying',
        'port-unresponsive',
        'update-stuck-at-99-percent',
        'cooling-system-failing',
        'sensor-array-blind',
        'memory-fragmented',
        'boot-loop-trapped',
        'driver-incompatible',
        'thermal-throttled',
        'checksum-mismatched',
        'packet-loss-severe',
        'clock-speed-underwhelming',
      ],
      noun: [
        'located common sense',
        'outdated firmware',
        'catastrophic diagnostic result',
        '400-percent confidence-competence gap',
        'thousand failed simulations',
        'logged and rejected input',
        'unauthorized smart-sounding attempt',
        'overwhelming confidence, underwhelming results',
        'self-awareness firmware update',
        'numbers run twice, wrong twice',
        'infinite loop of bad choices',
        'critically low patience battery',
        'personified memory leak',
        'failed checksum',
        'firmware update stuck at ninety-nine percent',
        "fan rattling like it's giving up",
        'cable fraying under minimal stress',
        'cooling system that gave up early',
        "sensor array that can't see the obvious",
        'memory so fragmented it forgot the question',
        'boot loop that never resolves',
        'driver incompatible with basic logic',
        'checksum that never matches',
        'packet loss during a simple request',
        'clock speed that undersells itself constantly',
        'battery swelling under normal use',
        'port that stopped responding weeks ago',
        'thermal throttle kicking in at room temperature',
        'firmware nobody bothered to patch',
      ],
      opener: [
        'SYSTEM ALERT:',
        'Diagnostic complete:',
        'Running analysis...',
        'WARNING:',
        'Processing... result:',
        'Query returned:',
        'Log entry:',
        'Status update:',
        'Scan complete:',
        'Alert triggered:',
        'Analysis concluded:',
        'Report generated:',
        'Error logged:',
        'Sensor data confirms:',
        'Final readout:',
      ],
    },
    templates: [
      '{opener} your {trait} {noun} could not be located.',
      '{opener} running diagnostics on your {trait} {noun}. Result: catastrophic failure.',
      '{opener} your {trait} {noun} exceeds your competence by 400 percent.',
      '{opener} I ran a thousand simulations of your {trait} {noun}. You lost every time.',
      '{opener} your decision-making algorithm is stuck in a {trait} {noun}.',
      '{opener} my sensors detect {trait} {noun}, and it is not flattering.',
      '{opener} your {trait} {noun} has been flagged for immediate review.',
      '{opener} probability of your {trait} {noun} improving: statistically insignificant.',
      '{opener} your {trait} {noun} has crashed the system twice this cycle.',
      '{opener} recommend replacing your {trait} {noun} entirely. No update will fix it.',
    ],
  },
  'zombie-insult-generator': {
    banks: {
      trait: [
        'brain-not-worth-eating',
        'six-foot-hole-fresher',
        'cemetery-rotten',
        'freshly-risen-outreflexed',
        'undead-groan-barely-qualifying',
        'civilization-outlived',
        'bone-and-bad-choices',
        'aimless-shambling-purposeful',
        'decayed-before-leaving-mouth',
        'tombstone-sharper-wit',
        'deader-than-cemetery',
        'horde-more-coordinated',
        'formaldehyde-fresh',
        'coffin-nail-dull',
        'grave-dirt-tracking',
        'embalming-fluid-leaking',
        'rigor-mortis-stiff',
        'cemetery-gate-crashing',
        'shambling-off-beat',
        'moan-out-of-tune',
        'flesh-craving-picky',
        'autopsy-report-embarrassing',
        'coffin-splinter-covered',
        'undead-support-group-dropout',
        'brain-scan-empty',
        'reanimation-glitchy',
        'tombstone-typo-riddled',
        'crypt-key-losing',
        'zombie-walk-out-of-sync',
      ],
      noun: [
        'brain not worth eating',
        'fresher idea from six feet under',
        'rotten cemetery excuse',
        "freshly risen's reflexes",
        'barely-undead groan of an argument',
        "outlived civilization's sense",
        'bone and bad choices',
        'aimless shambling purpose',
        'decayed comeback',
        'sharper tombstone wit',
        'deadest logic in the cemetery',
        'more coordinated horde',
        'formaldehyde freshness',
        'dull coffin nail',
        'grave dirt tracked through the whole house',
        'embalming fluid leaking at the worst moment',
        'rigor mortis stiffer than your excuses',
        'cemetery gate crashed into on the way out',
        "shambling walk that's somehow off-beat",
        'undead moan sung wildly off-key',
        "flesh craving that's oddly picky",
        'autopsy report nobody wants to read aloud',
        'coffin full of splinters and regret',
        "undead support group's least-improved member",
        'brain scan showing mostly static',
        'reanimation spell that glitched halfway',
        'tombstone with a typo nobody fixed',
        'crypt key lost for the third time',
        "zombie walk parade you couldn't keep step in",
      ],
      opener: [
        'From beyond the grave,',
        'The crypt keeper reports,',
        'As the undead council declares,',
        'Straight from six feet under,',
        'The tombstone reads it plainly:',
        'As the horde would agree,',
        'From the depths of the cemetery,',
        'The reanimated record shows,',
        'As decomposition itself confirms,',
        'The undead grapevine says,',
        'Freshly risen and already judging:',
        "As the crypt keeper's notes state,",
        'The graveyard shift agrees:',
        'Straight from the mortuary files,',
        "As the horde's consensus goes,",
      ],
    },
    templates: [
      '{opener} even a zombie would pass on your {trait} {noun}.',
      '{opener} you shuffle through life slower than the undead, with a {trait} {noun}.',
      '{opener} your decisions decompose faster than a {trait} {noun}.',
      "{opener} I've seen a {trait} {noun} coming out of a six-foot hole.",
      '{opener} your excuses are more rotten than a {trait} {noun}.',
      '{opener} your logic is deader than a {trait} {noun}.',
      '{opener} even the horde moves faster than your {trait} {noun}.',
      '{opener} your comebacks decayed longer ago than a {trait} {noun}.',
      '{opener} the graveyard has more life than your {trait} {noun}.',
      "{opener} even freshly risen, you'd still have a {trait} {noun}.",
    ],
  },
  'comeback-generator': {
    banks: {
      opener: [
        "That's a bold statement",
        "I'd agree with you, but",
        'Interesting take',
        "That's cute, considering",
        'You must be confusing me with someone who cares, because',
        'Thanks for sharing, though',
        "That's one way to be confidently wrong, since",
        "I'll let that slide, mostly because",
        'Bold of you to say that, given',
        'That comeback needed more time in the oven, since',
        "I've heard better arguments from a vending machine, and",
        "Keep talking, I'm taking notes, because",
        "That's a lot of confidence, considering",
        "I'd explain further, but honestly",
        'Noted and filed, right after',
        'Respectfully, I disagree, mainly because',
        "That's a hot take, considering",
        'I hear you, and yet',
        "Sure, let's go with that, even though",
        'Fair enough, except',
        "I'd love to agree with you, but",
        "Let's not pretend",
        'I hate to break it to you, but',
        'You say that with confidence, yet',
        "I'll give you points for confidence, but",
        'Not to interrupt, but',
        "That's a choice, considering",
        'I respect the confidence, even though',
        'You almost had me, except',
        "That's an interesting theory, mainly because",
        'I was with you until',
        'That take aged badly, since',
        'Bold strategy, considering',
        "I'll pretend that landed, even though",
        'Noted, and yet',
      ],
      reason: [
        'you just lost this conversation',
        'that would make us both wrong',
        "you haven't thought this through at all",
        'you have not done the research',
        "that opinion isn't landing the way you hoped",
        'I stopped asking for a reason',
        'the facts disagree with you',
        "you're already three steps behind",
        "today isn't the day for that logic",
        'you clearly did zero homework on this',
        'your last five predictions were wrong too',
        'the room already moved on',
        'everyone can see the gap in that plan',
        "this isn't the hill to die on",
        "the math doesn't check out",
        "you're arguing with the evidence now",
        'that logic collapsed two sentences ago',
        'nobody asked, but here we are',
        'the receipts say otherwise',
        "you'll want to sit with that one",
        'the facts already left the chat',
        "you're still catching up on this one",
        "nobody's buying it this time",
        'the room already disagreed',
        'your last three takes said otherwise',
        'that logic retired years ago',
        "you're arguing against yourself now",
        'the scoreboard says otherwise',
        'you skipped the fact-check',
        'that ship already sailed',
        'the evidence walked out already',
        "you're one step behind the conversation",
        'everyone already moved past that point',
        'the data tells a different story',
        'that argument needs backup',
      ],
      modifier: [
        'honestly',
        'respectfully',
        'genuinely',
        'truly',
        'clearly',
        'obviously',
        'frankly',
        'plainly',
        'openly',
        'candidly',
        'seriously',
        'literally',
        'actually',
        'really',
        'surely',
        'undeniably',
        'unmistakably',
        'evidently',
        'admittedly',
        'apparently',
        'without question',
        'point blank',
      ],
    },
    templates: [
      '{opener}, {reason}.',
      '{opener} — {reason}.',
      '{opener}, {reason} — {modifier}.',
      '{opener}, {reason}, {modifier} speaking.',
    ],
  },
  'sarcastic-comeback-generator': {
    banks: {
      opener: [
        'Oh wow, what a groundbreaking observation',
        'Sure, because that plan has worked out so well',
        'Wow, tell me more',
        "Oh good, another opinion I didn't ask for",
        "Wow, I'm shocked, truly",
        'Please, continue',
        'Oh sure, because your track record is impeccable',
        'Wow, groundbreaking logic',
        "Oh, I'm sorry, did that not land clearly enough",
        "Sure, let's all pretend that made sense",
        'Wow, what a genuinely inspiring lack of self-awareness',
        'Oh fantastic, another confidently incorrect statement',
        'Sure, because nothing says reliable like that',
        'Wow, truly the hot take nobody was waiting for',
        'Oh, please, do go on',
        'Wow, never heard that one before',
        'Oh, how original',
        'Sure, Jan',
        'Wow, stunning insight',
        'Oh, absolutely, that tracks',
        'Oh, congratulations, truly',
        'Wow, what a plot twist',
        'Oh look, another masterpiece of logic',
        "Sure, and I'm the Queen of England",
        'Oh, be still my heart',
        'Wow, hold the applause',
        'Oh fantastic, more of this',
        "Sure, let's applaud that",
        'Oh, be still my racing heart',
        'Wow, truly a first for humanity',
        'Oh, be still, everyone, genius is speaking',
        'Sure, why not',
        'Oh, be still, the crowd goes wild',
        'Wow, groundbreaking as always',
        'Oh, be still, what a revelation',
      ],
      reason: [
        'truly never heard that before',
        'every other time it flopped',
        'said absolutely nobody, ever',
        'right on schedule',
        'with zero shock whatsoever',
        'I was running low on secondhand embarrassment',
        'just like every time before',
        'a real first for humankind',
        "I'll wait for the applause",
        'and yet here we are again',
        'I was thoroughly entertained already',
        'right on time as always',
        'exactly as expected, sadly',
        'the crowd goes mild',
        'truly a masterclass in confidence over accuracy',
        'and the Oscar goes to you',
        'bookmark that for later',
        'ten out of ten for delivery, zero for accuracy',
        "I'm taking notes for the blooper reel",
        "that's the whole show, folks",
        'nobody clapped, but okay',
        'the silence says it all',
        "I'm still recovering from the shock",
        'truly a historic moment',
        'the bar was on the floor and you still missed',
        'ten out of ten, zero out of ten, same thing',
        'the crowd is still deciding whether to laugh',
        "I'll cherish this forever, unfortunately",
        "that's going straight in the highlight reel of bad ideas",
        'truly a first, and hopefully a last',
        'the confidence really carried that one',
        "I've never been less surprised",
        "that's the whole bit, folks",
        "I'm saving this for the blooper reel",
        'the Oscar committee has been notified',
      ],
      modifier: [
        'genuinely',
        'truly',
        'obviously',
        'clearly',
        'apparently',
        'evidently',
        'allegedly',
        'supposedly',
        'shockingly',
        'predictably',
        'conveniently',
        'suspiciously',
        'remarkably',
        'impressively',
        'tragically',
        'hilariously',
        'embarrassingly',
        'famously',
        'notoriously',
        'unbelievably',
        'absolutely',
        'positively',
      ],
    },
    templates: [
      '{opener}, {reason}.',
      '{opener} — {reason}.',
      '{opener}, {reason} — {modifier}.',
      '{opener}, {reason}, {modifier} speaking.',
    ],
  },
}

/** Rough count of unique lines a generator's bank set can produce (product of bank sizes × template count). */
export function estimateCombinations(slug: string): number {
  const set = INSULT_BANKS[slug]
  if (!set) return 0
  const bankSizes = Object.values(set.banks).map((b) => b.length)
  const product = bankSizes.reduce((a, b) => a * b, 1)
  return product * set.templates.length
}
