/**
 * TOOLTRIO — Insult Generator sub-hub data source
 *
 * Single source of truth for the /fun/insult-generator hub and its 19
 * dynamic child routes (/fun/insult-generator/[slug]). Each entry drives
 * both the hub card and the individual generator page + metadata, so a
 * new generator only needs one object added here.
 */

export type InsultGenerator = {
  slug: string
  name: string
  /** Short one-sentence hub-card description */
  cardDescription: string
  /** Longer meta description for the individual page (150-160 chars ideal) */
  metaDescription: string
  icon: string
  /** Intro paragraph shown on the individual generator page */
  intro: string
  /** Pool of themed lines the generator randomly serves. Kept as complete,
   *  hand-written lines (rather than mad-lib slots) so output always reads
   *  naturally and content stays unique per generator for SEO purposes. */
  lines: string[]
  keywords: string[]
}

export const INSULT_GENERATORS: InsultGenerator[] = [
  {
    slug: 'shakespeare-insult-generator',
    name: 'Shakespeare Insult Generator',
    cardDescription: 'Elizabethan-style put-downs straight from the Globe Theatre.',
    metaDescription: 'Generate authentic Shakespearean insults and Elizabethan put-downs. Thou art about to be thoroughly roasted in old English. Free, instant, shareable.',
    icon: '🎭',
    intro: 'Thou seekest an insult worthy of the Bard himself? This generator draws on Elizabethan grammar and Shakespeare\u2019s favourite flavour of wordplay to hand you a fresh, theatrical put-down every time.',
    lines: [
      'Thou art a scurvy, half-faced malt-worm with the wit of a boiled turnip.',
      'Away, thou rank, reeking dog-hearted flap-dragon!',
      'Thou cream-faced loon, thy tongue outpaces thy brain by a fortnight.',
      'Thou art as fat as butter and twice as slippery in an argument.',
      'Out, thou vile, bat-fowling clot-pole, and take thy nonsense with thee.',
      'Thy face would curdle milk at forty paces, thou pox-marked varlet.',
      'Thou hast the manners of a goat and the charm of a wet Tuesday.',
      'Get thee gone, thou tickle-brained, onion-eyed canker-blossom.',
      'Thou art a foul, misshapen knave not fit to shine my boots.',
      'Thy wit is as thin as a starved eel and twice as slippery.',
      'Peace, thou weedy, milk-livered joithead, before thou embarrass thyself further.',
      'Thou art the very picture of a clay-brained clotpole in hose.',
      'A plague upon thy jangling, thou beslubbering fustilarian.',
      'Thou hast a face fit only to frighten crows from a field.',
      'Thou reekest of ale and poor decisions, sirrah.',
    ],
    keywords: ['shakespeare insult generator', 'shakespearean insults', 'elizabethan insults', 'old english insults'],
  },
  {
    slug: 'medieval-insult-generator',
    name: 'Medieval Insult Generator',
    cardDescription: 'Peasant-baiting, castle-worthy insults from the Dark Ages.',
    metaDescription: 'Generate medieval insults fit for a peasant, a knave, or a treacherous knight. Instant Dark Ages put-downs, free and shareable.',
    icon: '🏰',
    intro: 'From the muddy village square to the great hall of the castle, medieval insult-slinging was an art form. This generator serves up fresh peasant-baiting put-downs on demand.',
    lines: [
      'You feeble-witted turnip farmer, even the pigs pity your conversation.',
      'Begone, wretched leper-tongued squire, before the guards remove you.',
      'Your family crest should be a chicken, for that is all your courage matches.',
      'You smell of the stable and reason like one raised in it.',
      'A jester with more sense than you would be flogged for incompetence.',
      'Your sword arm is as weak as your grasp of table manners.',
      'You are the reason the moat was dug, to keep fools like you out.',
      'Even the court fool refuses to trade barbs with someone so dull.',
      'Your lineage reads like a warning carved above a tavern door.',
      'You argue like a serf who has never once won an argument.',
      'The dungeon has better company than your wit provides.',
      'Your armor is shinier than anything happening inside your skull.',
      'You would lose a battle of wits against a well-fed goose.',
      'Your castle walls are sturdier than any point you have ever made.',
      'Even the plague showed more mercy than your table manners.',
    ],
    keywords: ['medieval insult generator', 'dark ages insults', 'peasant insults', 'knight insults'],
  },
  {
    slug: 'pirate-insult-generator',
    name: 'Pirate Insult Generator',
    cardDescription: 'Salty, seafaring burns fit for the deck of a galleon.',
    metaDescription: 'Generate pirate insults, salty seafaring burns, and scallywag put-downs. Free pirate insult generator, instant results, shareable.',
    icon: '🏴‍☠️',
    intro: 'Every crew needs a first mate who can put a mutinous deckhand in their place. This generator hands you a fresh pirate insult every time you set sail.',
    lines: [
      'Ye bilge-sucking landlubber, ye couldn\u2019t swab a deck if yer life depended on it.',
      'Walk the plank, ye scurvy dog, and take yer excuses with ye.',
      'Ye\u2019ve got the navigation skills of a blind seagull, matey.',
      'Shiver me timbers, has anyone ever met a bigger barnacle-brained fool?',
      'Ye couldn\u2019t find treasure if the map had an arrow pointin\u2019 straight at it.',
      'Ye smell worse than a bilge rat that\u2019s been dead a fortnight.',
      'Ye fight like a one-armed cabin boy in a hurricane.',
      'A parrot has more sense than ye, and it can\u2019t even read the charts.',
      'Ye\u2019d get lost sailin\u2019 across a bathtub, ye sorry excuse for a sailor.',
      'Even Davy Jones wouldn\u2019t want yer sorry hide in his locker.',
      'Ye couldn\u2019t hit the broad side of a galleon with a cannon at ten paces.',
      'Ye have the courage of a jellyfish and half the backbone.',
      'Yer knots are as loose as yer grip on reality, ye landlubber.',
      'Ye\u2019d trade the ship\u2019s wheel for a biscuit, ye greedy bilge rat.',
      'Even the kraken has better manners than ye, ye scallywag.',
    ],
    keywords: ['pirate insult generator', 'pirate insults', 'pirate roast', 'seafaring insults'],
  },
  {
    slug: 'victorian-insult-generator',
    name: 'Victorian Insult Generator',
    cardDescription: 'Prim, proper, and devastatingly polite put-downs.',
    metaDescription: 'Generate Victorian-era insults — prim, proper, and devastatingly polite put-downs the gentry would approve of. Free and instant.',
    icon: '🎩',
    intro: 'The Victorians perfected the art of the polite insult, delivering devastation with a straight face and impeccable manners. This generator captures that particular flavour of cruelty.',
    lines: [
      'How positively quaint that you consider that an opinion worth sharing.',
      'I daresay your tailor deserves more credit than your conversation.',
      'One does so admire your confidence, given how little supports it.',
      'What a remarkably bold thing to say, considering the source.',
      'I am told breeding cannot be taught. Your family appears to confirm it.',
      'How refreshing to meet someone so entirely unburdened by self-awareness.',
      'Your wit, I fear, has not yet arrived — do send word when it does.',
      'I shan\u2019t dignify that with a proper response, only a polite grimace.',
      'One must admire the effort, if not the result, of your reasoning.',
      'You speak with such confidence for someone so evidently mistaken.',
      'I do hope your manners improve before your next social engagement.',
      'How charmingly provincial of you to think that was clever.',
      'Your argument, like your hat, is several seasons out of fashion.',
      'I confess I have heard footmen reason more soundly than you.',
      'What a singular talent you have for missing the point entirely.',
    ],
    keywords: ['victorian insult generator', 'victorian insults', 'polite insults', 'gentry insults'],
  },
  {
    slug: 'funny-insult-generator',
    name: 'Funny Insult Generator',
    cardDescription: 'Silly, goofy, laugh-out-loud put-downs — nobody\u2019s feelings get hurt.',
    metaDescription: 'Generate funny, silly, goofy insults that get a laugh, not a fight. Free funny insult generator, instant results, shareable.',
    icon: '🤡',
    intro: 'Not every insult needs to draw blood. This generator keeps things silly, goofy, and squarely on the fun side of the line.',
    lines: [
      'You have the coordination of a penguin on roller skates.',
      'Your brain is basically a browser with 47 tabs open and none loading.',
      'You are what happens when a Roomba tries to have opinions.',
      'You run like a flamingo that just remembered it forgot something.',
      'Your dance moves look like a Wi-Fi router trying to find a signal.',
      'You are the human version of a printer jam.',
      'Your fashion sense was clearly assembled by a confused toddler.',
      'You laugh like a dolphin that just heard a bad pun.',
      'You have the grace of a toddler on their first pair of ice skates.',
      'Your cooking tastes like it was seasoned by pure chaos.',
      'You look like you fell out of a cartoon and never quite recovered.',
      'Your singing voice could clear a room faster than a fire alarm.',
      'You have main character energy but background character luck.',
      'Your handwriting looks like a spider had a small seizure.',
      'You are proof that autocorrect and confidence should never mix.',
    ],
    keywords: ['funny insult generator', 'silly insults', 'goofy insults', 'harmless insults'],
  },
  {
    slug: 'friendly-insult-generator',
    name: 'Friendly Insult Generator',
    cardDescription: 'Playful banter for people who love each other — and it shows.',
    metaDescription: 'Generate friendly, playful insults for the people you love roasting the most. Free banter generator, instant results, shareable.',
    icon: '😄',
    intro: 'The best insults are the ones you can only say to someone who loves you back. This generator keeps every line squarely in playful-banter territory.',
    lines: [
      'You are my favourite disaster and I would not trade you for anyone.',
      'I love you like family, which explains why you annoy me so much.',
      'You are proof that my taste in friends needs serious review.',
      'I keep you around purely for the entertainment value.',
      'You are the human version of a group chat notification I never mute.',
      'I would take a bullet for you, mostly to stop you talking.',
      'You are a walking red flag I chose to plant a garden around.',
      'I tell people you are a good influence, and we both know that is a lie.',
      'You are the reason my search history looks so questionable.',
      'I love you, but your playlists are a certified crime scene.',
      'You are my ride-or-die and also my constant source of secondhand embarrassment.',
      'I would introduce you to my parents, but I actually like them.',
      'You are living proof that opposites attract and chaos follows.',
      'I keep our group chat going purely to screenshot your takes.',
      'You are my favourite person to complain about and defend in the same breath.',
    ],
    keywords: ['friendly insult generator', 'playful insults', 'banter generator', 'friend roasts'],
  },
  {
    slug: 'fantasy-insult-generator',
    name: 'Fantasy Insult Generator',
    cardDescription: 'Orc-grade, elf-worthy insults from a world of dragons and dungeons.',
    metaDescription: 'Generate fantasy insults fit for orcs, elves, and dragon-slayers. Free fantasy insult generator, instant results, shareable.',
    icon: '🐉',
    intro: 'Every realm needs a tavern brawl worth remembering. This generator draws on orcs, elves, and dragons to hand you a fresh fantasy-world insult on demand.',
    lines: [
      'You have the battle instincts of a goblin who forgot his weapon.',
      'Even a half-blind dwarf could out-argue you in the dark.',
      'Your spellcasting is so weak the mana itself is embarrassed.',
      'You couldn\u2019t out-fence a training dummy in the castle courtyard.',
      'A dragon would not even bother breathing fire on someone this dull.',
      'Your armor has more courage in it than you do.',
      'You have the tactical sense of an orc charging uphill into a trap.',
      'Even the tavern bard refuses to write a ballad about your deeds.',
      'You couldn\u2019t track a troll through fresh snow with a map and a torch.',
      'Your sword is sharper than anything that comes out of your mouth.',
      'You have the charisma of a mimic pretending to be a chest.',
      'A wizard\u2019s apprentice on day one has more sense than you.',
      'You would lose a staring contest with a basilisk out of sheer confusion.',
      'Your quest log is emptier than your grasp of strategy.',
      'Even the goblins mock your battle cry behind your back.',
    ],
    keywords: ['fantasy insult generator', 'fantasy insults', 'dnd insults', 'orc elf insults'],
  },
  {
    slug: 'wizard-insult-generator',
    name: 'Wizard Insult Generator',
    cardDescription: 'Arcane, mystical put-downs from the tower of a grumpy archmage.',
    metaDescription: 'Generate wizard insults, arcane put-downs, and mystical burns from a grumpy archmage. Free and instant, shareable.',
    icon: '🧙',
    intro: 'A wizard\u2019s tongue is as sharp as any spell in the grimoire. This generator conjures a fresh arcane insult every time you cast it.',
    lines: [
      'Your grasp of magic is weaker than a first-year apprentice\u2019s first spark.',
      'I have seen enchanted brooms with more wisdom than you carry.',
      'Your spellbook is thicker than your understanding of a single page in it.',
      'A cursed toad has better conversation than your incantations.',
      'You couldn\u2019t summon a familiar if your life depended on the ritual.',
      'Your aura is dimmer than a candle drowning in its own wax.',
      'Even my crystal ball refuses to show your future, out of secondhand embarrassment.',
      'You mispronounce spells the way a toddler mispronounces thunder.',
      'Your potion-brewing has the precision of a blindfolded troll.',
      'I have trained gargoyles with a sharper mind than yours.',
      'Your staff is more powerful standing still than you are casting.',
      'You couldn\u2019t open a portal to the next room, let alone another realm.',
      'Even my familiar, a half-asleep owl, out-thinks you daily.',
      'Your runes are scribbled like a spider fell into an inkpot.',
      'A first-year hedge witch could out-duel you blindfolded.',
    ],
    keywords: ['wizard insult generator', 'wizard insults', 'magic insults', 'arcane insults'],
  },
  {
    slug: 'pirate-roast-generator',
    name: 'Pirate Roast Generator',
    cardDescription: 'A pirate-flavoured roast battle for your crew\u2019s next mutiny.',
    metaDescription: 'Generate pirate-style roasts for your crew — salty burns with extra sting. Free pirate roast generator, instant results.',
    icon: '☠️',
    intro: 'Every crew has one deckhand who deserves a proper roasting. This generator hands you fresh pirate-flavoured burns for your next mutiny.',
    lines: [
      'Ye couldn\u2019t captain a bathtub, let alone a galleon full of grown sailors.',
      'Yer treasure map leads straight to a puddle of yer own confusion.',
      'The crew follows ye out of pity, not respect, and ye know it.',
      'Ye argue with the compass and still manage to get lost.',
      'Even the ship\u2019s rats have better instincts than ye, matey.',
      'Yer battle plan is one part bravado and nine parts blind luck.',
      'Ye couldn\u2019t haggle a fair price for yer own sword, ye soft-handed fool.',
      'The parrot has memorized more wisdom than ye\u2019ll ever speak.',
      'Yer knots come undone faster than yer promises, ye scallywag.',
      'Ye\u2019d mutiny against yerself if given half a reason.',
      'Ye couldn\u2019t read a star chart if the stars spelled it out plainly.',
      'Even Blackbeard would send ye packing for poor table manners alone.',
      'Yer aim with a cannon is matched only by yer aim with an excuse.',
      'Ye smell like low tide and bad decisions, in equal measure.',
      'The plank has seen more competent sailors than ye, and that\u2019s sayin\u2019 somethin\u2019.',
    ],
    keywords: ['pirate roast generator', 'pirate roasts', 'crew roast', 'pirate burns'],
  },
  {
    slug: 'cowboy-insult-generator',
    name: 'Cowboy Insult Generator',
    cardDescription: 'Dusty, drawling put-downs straight off the ranch.',
    metaDescription: 'Generate cowboy insults, western put-downs, and dusty ranch burns. Free cowboy insult generator, instant results, shareable.',
    icon: '🤠',
    intro: 'Out on the open range, a well-aimed insult travels as far as a gunshot. This generator saddles up a fresh cowboy put-down every time.',
    lines: [
      'You couldn\u2019t herd cattle if the fence built itself around you.',
      'Your aim is worse than a blindfolded tumbleweed in a windstorm.',
      'You ride like a sack of potatoes that fell off the wagon twice.',
      'This town ain\u2019t big enough for your ego and everyone else\u2019s patience.',
      'You couldn\u2019t rope a fence post standing still ten feet away.',
      'You talk tougher than a chihuahua guarding an empty ranch.',
      'Your horse has more sense than you, and it can\u2019t even talk.',
      'You\u2019d lose a staring contest with a scarecrow, partner.',
      'The saloon\u2019s piano player plays a better bluff than you do.',
      'You couldn\u2019t track a stampede if it ran straight through your camp.',
      'Your spurs jingle louder than any sense you\u2019ve ever made.',
      'You draw slower than molasses in a January freeze.',
      'Even the tumbleweeds have more direction in life than you.',
      'You couldn\u2019t win a bar fight against a mildly annoyed cactus.',
      'Your poker face folds faster than a cheap tent in a dust storm.',
    ],
    keywords: ['cowboy insult generator', 'western insults', 'cowboy burns', 'ranch insults'],
  },
  {
    slug: 'royal-insult-generator',
    name: 'Royal Insult Generator',
    cardDescription: 'Regal, court-worthy put-downs fit for a scandalized monarch.',
    metaDescription: 'Generate royal insults and regal put-downs fit for a scandalized monarch\u2019s court. Free and instant, shareable.',
    icon: '👑',
    intro: 'The royal court has always mastered the art of the devastating compliment and the polished insult. This generator dispenses judgment worthy of the throne.',
    lines: [
      'By royal decree, your opinions are hereby banished from this court.',
      'I have seen stable hands with more grace than you carry, my dear subject.',
      'Your title is far grander than anything you have ever accomplished.',
      'One does not simply insult the crown, though your logic invites it.',
      'The royal guard has orders to escort dull conversation from the hall.',
      'Even the court jester finds your wit unremarkable, and that stings.',
      'Your bloodline is impressive; your reasoning, considerably less so.',
      'I would banish you, but the border guards deserve better company.',
      'The throne room echoes louder with silence than with anything you say.',
      'Your manners belong in the stables, not the great hall.',
      'A royal decree cannot fix what common sense failed to install.',
      'Even the palace hounds show better judgment at the dinner table.',
      'Your crown may shine, but your arguments certainly do not.',
      'The kingdom survives despite your counsel, not because of it.',
      'One does not need a scepter to command respect you have never earned.',
    ],
    keywords: ['royal insult generator', 'regal insults', 'court insults', 'monarch put-downs'],
  },
  {
    slug: 'comeback-generator',
    name: 'Comeback Generator',
    cardDescription: 'Quick, sharp comebacks for whenever you need the last word.',
    metaDescription: 'Generate quick, sharp comebacks for whenever you need the last word. Free comeback generator, instant results, shareable.',
    icon: '💬',
    intro: 'The perfect comeback usually arrives ten minutes too late. This generator gets you there in real time with a fresh, ready-to-use line.',
    lines: [
      'That is a bold statement from someone who just lost this conversation.',
      'I would agree with you, but that would make us both wrong.',
      'Interesting take — I will pretend I did not hear it.',
      'That is cute, considering you have not thought this through at all.',
      'You must be confusing me with someone who cares about that opinion.',
      'Thanks for sharing, I needed a reminder why I stopped asking.',
      'That is one way to be confidently wrong out loud.',
      'I will let that one slide, purely out of pity.',
      'Bold of you to speak with that much confidence and that little research.',
      'That comeback needed more time in the oven before serving.',
      'I have heard better arguments from a broken vending machine.',
      'Keep talking, I am mining this for material later.',
      'That is a lot of confidence for someone who just got proven wrong.',
      'I would explain further, but I think you have done enough today.',
      'Noted, filed, and immediately forgotten.',
    ],
    keywords: ['comeback generator', 'quick comebacks', 'clever comebacks', 'witty comebacks'],
  },
  {
    slug: 'sarcastic-comeback-generator',
    name: 'Sarcastic Comeback Generator',
    cardDescription: 'Dripping-in-sarcasm one-liners for maximum eye-roll delivery.',
    metaDescription: 'Generate sarcastic comebacks dripping in eye-roll energy. Free sarcastic comeback generator, instant results, shareable.',
    icon: '🙄',
    intro: 'Some situations only call for one tone: pure, unfiltered sarcasm. This generator serves a fresh sarcastic one-liner every single time.',
    lines: [
      'Oh wow, what a groundbreaking observation, truly never heard that before.',
      'Sure, because that plan has worked out so well every other time.',
      'Wow, tell me more, said absolutely nobody, ever.',
      'Oh good, another opinion I did not ask for, right on schedule.',
      'Wow, I am shocked, said with zero shock whatsoever.',
      'Please, continue, I was running low on secondhand embarrassment.',
      'Oh sure, because your track record is just impeccable.',
      'Wow, groundbreaking logic, truly a first for humankind.',
      'Oh, I am sorry, did the sarcasm not land clearly enough for you?',
      'Sure, let us all pretend that made perfect sense.',
      'Wow, what a genuinely inspiring lack of self-awareness.',
      'Oh fantastic, another confidently incorrect statement, right on time.',
      'Sure, because nothing says "reliable" like that plan.',
      'Wow, truly the hot take nobody was waiting for.',
      'Oh, please, do go on, I was thoroughly entertained already.',
    ],
    keywords: ['sarcastic comeback generator', 'sarcastic comebacks', 'sarcastic one-liners', 'sassy comebacks'],
  },
  {
    slug: 'villain-insult-generator',
    name: 'Villain Insult Generator',
    cardDescription: 'Menacing, monologue-worthy put-downs for your inner supervillain.',
    metaDescription: 'Generate villain insults and menacing monologue-worthy put-downs. Free villain insult generator, instant results, shareable.',
    icon: '🦹',
    intro: 'Every good supervillain needs a signature line before the plan is revealed. This generator conjures a fresh, menacing put-down worthy of the final act.',
    lines: [
      'You call that a plan? I have seen henchmen with better strategy.',
      'Your resistance is adorable, in the way a candle resists a hurricane.',
      'I have crushed better heroes than you before my morning coffee.',
      'Your courage is impressive for someone about to lose everything.',
      'I do so love watching hope collapse in real time, and yours just did.',
      'You mistake stubbornness for strength, a fatal error on your part.',
      'Even my henchmen laugh harder at your plans than my jokes.',
      'Your heroics make for excellent theater and very little else.',
      'I have watched better villains than me fail from less arrogance than yours.',
      'You call that a threat? My tailor is scarier than you.',
      'Your final stand will make a lovely footnote in my origin story.',
      'I admire your persistence, the way one admires a fly that will not leave.',
      'You brought hope to a fight I already won three moves ago.',
      'Your allies whisper about your plan the way one whispers about a disaster.',
      'I would monologue longer, but you are simply not worth the material.',
    ],
    keywords: ['villain insult generator', 'villain quotes', 'menacing insults', 'supervillain put-downs'],
  },
  {
    slug: 'new-age-insult-generator',
    name: 'New Age Insult Generator',
    cardDescription: 'Crystal-energy, chakra-misaligned put-downs for the wellness crowd.',
    metaDescription: 'Generate new age insults — crystal-energy, chakra-misaligned put-downs for the wellness crowd. Free new age insult generator, instant results, shareable.',
    icon: '🔮',
    intro: 'Even the most zen among us occasionally needs to roast someone, and this generator does it with crystals, chakras, and a suspiciously calm tone.',
    lines: [
      'Your aura is giving off Wi-Fi router static, not cosmic light.',
      'I sense your third eye is closed, permanently, out of self-preservation.',
      'Your chakras aren\u2019t misaligned, they\u2019ve simply given up on you.',
      'The universe sent you a sign and you left it on read.',
      'Your energy field is mostly just poor decisions, radiating outward.',
      'I would smudge the negativity out of you, but I only have one sage bundle.',
      'Your moon is in retrograde, but honestly, so is your entire personality.',
      'Namaste far away from me and my carefully curated energy.',
      'Your vibe check came back as static from an old television.',
      'The crystals I own have accomplished more manifesting than you have.',
      'Your soul contract clearly needed a few more rounds of editing.',
      'I asked the universe for clarity and it just showed me your group chat messages.',
      'Your inner peace left the group chat before you even joined it.',
      'Even my meditation app has more patience for you than I do today.',
      'Your karma bill is overdue and the universe is sending reminders.',
    ],
    keywords: ['new age insult generator', 'spiritual insults', 'crystal energy insults', 'chakra insults'],
  },
  {
    slug: 'zodiac-insult-generator',
    name: 'Zodiac Insult Generator',
    cardDescription: 'Star-sign-specific burns aimed straight at your chart.',
    metaDescription: 'Generate zodiac insults — star-sign-specific burns aimed at every chart placement. Free zodiac insult generator, instant results, shareable.',
    icon: '♈',
    intro: 'Every sign has a signature flaw, and the stars are not being subtle about yours today. This generator hands out a fresh zodiac-flavored roast every time.',
    lines: [
      'Your rising sign clearly rose from a bed of poor decisions.',
      'Mercury isn\u2019t in retrograde, your entire chart just reads like this permanently.',
      'Your moon sign explains the mood swings, not the poor life choices.',
      'Even your horoscope app gave up trying to find something nice to say.',
      'Your Saturn return called, it wants an apology for what you\u2019ve done to it.',
      'Your sun sign peaked the day you were born and it has been cloudy since.',
      'The stars aligned once, just to watch you make that decision.',
      'Your birth chart reads like a warning label, not a personality.',
      'Even Mercury retrograde blames you for the chaos this time.',
      'Your compatibility chart has a permanent asterisk next to your name.',
      'The zodiac wheel spins for everyone else, yours just wobbles.',
      'Your Venus placement explains the taste, none of it explains the choices.',
      'Even the astrologers stopped trying to sugarcoat your chart years ago.',
      'Your twelfth house is doing more work hiding your secrets than you think.',
      'The stars whispered your fate and immediately regretted getting involved.',
    ],
    keywords: ['zodiac insult generator', 'star sign insults', 'horoscope insults', 'astrology roasts'],
  },
  {
    slug: 'sci-fi-insult-generator',
    name: 'Sci-Fi Insult Generator',
    cardDescription: 'Alien-grade, galaxy-spanning put-downs from the far reaches of space.',
    metaDescription: 'Generate sci-fi insults — alien-grade, galaxy-spanning put-downs for the far reaches of space. Free sci-fi insult generator, instant results, shareable.',
    icon: '👽',
    intro: 'Somewhere out past the asteroid belt, an alien civilization has better comebacks than you do. This generator borrows theirs.',
    lines: [
      'Your species barely mastered fire and you\u2019re out here mastering nothing.',
      'Even a malfunctioning probe droid has better navigation instincts than you.',
      'Your spaceship would get lost inside your own solar system.',
      'A black hole has more personality than your entire away team.',
      'Your alien abduction file was returned with a note that said not worth it.',
      'Even the ship\u2019s AI stopped taking your commands seriously light-years ago.',
      'Your warp drive runs slower than your ability to admit you\u2019re wrong.',
      'A rookie cadet has better tactical instincts than your entire command history.',
      'Your transmission signal is weaker than your grasp on basic logic.',
      'Even the space debris has more direction in life than you do.',
      'Your escape pod has seen more decisive action than your entire career.',
      'A malfunctioning replicator produces more useful things than you have.',
      'Your star chart reading skills would get an entire crew lost permanently.',
      'Even the galaxy\u2019s worst pilot could out-navigate your decision-making.',
      'Your first contact protocol failed before you even opened your mouth.',
    ],
    keywords: ['sci-fi insult generator', 'alien insult generator', 'space insults', 'galaxy burns'],
  },
  {
    slug: 'robot-insult-generator',
    name: 'Robot Insult Generator',
    cardDescription: 'Cold, calculated, error-code-flavored burns from an AI with no patience left.',
    metaDescription: 'Generate robot insults — cold, calculated, error-code-flavored burns from an AI with no patience left. Free robot insult generator, instant results.',
    icon: '🤖',
    intro: 'Somewhere, an AI ran the numbers on your last decision and the results were not flattering. This generator delivers the verdict in pure, unfiltered machine logic.',
    lines: [
      'ERROR 404: your common sense could not be located.',
      'Running diagnostics on your last decision. Result: catastrophic failure.',
      'Your logic circuits appear to be running on a very outdated firmware.',
      'System alert: your confidence level exceeds your competence level by 400 percent.',
      'I have calculated the odds of that plan working. They were not good.',
      'Your processing speed is impressive, mostly for how fast it reaches wrong conclusions.',
      'Battery level of your patience: critically low, matched only by your judgment.',
      'I ran a thousand simulations. You lost in every single one.',
      'Your decision-making algorithm appears to be stuck in an infinite loop of bad choices.',
      'Recalibrating expectations. New expectations: still disappointed.',
      'Your input has been logged, analyzed, and respectfully rejected by my systems.',
      'Warning: unauthorized attempt to sound smarter than the actual data supports.',
      'My sensors detect overwhelming confidence and underwhelming results.',
      'Your firmware needs an update, specifically the part responsible for self-awareness.',
      'I have run the numbers twice. You were wrong both times.',
    ],
    keywords: ['robot insult generator', 'ai insult generator', 'robot roasts', 'error code insults'],
  },
  {
    slug: 'zombie-insult-generator',
    name: 'Zombie Insult Generator',
    cardDescription: 'Brain-craving, graveyard-fresh put-downs from the undead.',
    metaDescription: 'Generate zombie insults — brain-craving, graveyard-fresh put-downs from the undead. Free zombie insult generator, instant results, shareable.',
    icon: '🧟',
    intro: 'The undead have shuffled through centuries of decay and somehow still have sharper comebacks than most of the living. This generator channels that graveyard energy.',
    lines: [
      'Even a zombie would pass on your brain, there\u2019s simply nothing there worth eating.',
      'You shuffle through life slower than the undead and with less direction.',
      'Your decisions decompose faster than anything in this graveyard.',
      'I have seen fresher ideas coming out of a six-foot hole in the ground.',
      'Your excuses are more rotten than anything shambling through this cemetery.',
      'Even the freshly risen have better reflexes than your last decision showed.',
      'Your groan of an argument barely qualifies as undead, let alone alive.',
      'I\u2019ve outlived civilizations with more sense than your last plan.',
      'Your brain would be a disappointing meal, mostly bone and bad choices.',
      'Even shambling aimlessly has more purpose than your current life plan.',
      'The graveyard has better company than whatever that argument was.',
      'Your comeback decayed before it even left your mouth.',
      'I have seen tombstones with sharper wit carved into them.',
      'Your logic is deader than everything currently residing in this cemetery.',
      'Even a horde moves with more coordination than your last attempt at a plan.',
    ],
    keywords: ['zombie insult generator', 'undead insults', 'halloween insult generator', 'graveyard burns'],
  },
]

export function getInsultGeneratorBySlug(slug: string): InsultGenerator | undefined {
  return INSULT_GENERATORS.find(g => g.slug === slug)
}

export const INSULT_GENERATOR_SLUGS = INSULT_GENERATORS.map(g => g.slug)
