import type { Metadata } from 'next'
import { generateCalculatorMetadata, generateFAQStructuredData } from '@/lib/seo/metadata'
import dynamic from 'next/dynamic'
const CalculatorClient = dynamic(() => import('./CalculatorClient'), { ssr: false, loading: () => <div className="min-h-[400px] bg-white rounded-2xl border border-gray-100 animate-pulse m-4" /> })
export const metadata: Metadata = generateCalculatorMetadata({ title: 'Alimony Tax Calculator USA 2026 | ToolTrio', description: 'Calculate the tax impact of alimony payments for both payer and recipient. Covers pre-2019 (deductible) and post-2018 TCJA (not deductible) divorce agreements.', slug: 'alimony-tax-calculator', category: 'finance', keywords: ['alimony tax calculator USA', 'alimony deduction 2026', 'TCJA alimony tax rule', 'divorce tax implications calculator USA'] })
const faqs = [('Is alimony tax-deductible in 2026?', 'It depends on when the divorce was finalized. For divorce agreements finalized before January 1, 2019, alimony is deductible by the payer and taxable income for the recipient (old law). For divorces finalized after December 31, 2018, the TCJA eliminated the deduction — alimony is neither deductible for the payer nor taxable income for the recipient. Modifying a pre-2019 agreement to expressly apply TCJA rules also changes the tax treatment.'), ('What is the difference in net cost for pre- vs post-2019 alimony?', 'Under the old law, a payer in the 32% bracket paying $30,000/year saves $9,600 in taxes, while a recipient in the 22% bracket pays $6,600 — a net tax savings to both parties of $3,000/year. Under TCJA, no deduction means the payer pays full taxes on the income used to make payments, but the recipient keeps the full amount tax-free. Judges may adjust alimony amounts based on the applicable tax rule.')]
const relatedCalculators = [{'name': 'Income Tax Calculator', 'href': '/calculators/finance/income-tax-calculator', 'icon': '📋', 'desc': 'Income tax'}, {'name': 'Child Tax Credit', 'href': '/calculators/finance/child-tax-credit-calculator', 'icon': '👶', 'desc': 'Child tax credits'}, {'name': 'Tax Bracket Calculator', 'href': '/calculators/finance/tax-bracket-calculator', 'icon': '🧾', 'desc': 'Tax brackets'}]
const structuredData = [generateFAQStructuredData(faqs)]
export default function Page() { return <>{structuredData.map((s, i) => <script key={i} type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(s) }} />)}<CalculatorClient faqs={faqs} structuredData={structuredData} relatedCalculators={relatedCalculators} /></> }
