'use client'
import Link from 'next/link'
import { ArrowRight, BadgeCheck, BookOpen, Calculator, Check, Clock3, Compass, FileText, Flame, Globe2, Heart, Map, MapPin, Navigation, Ruler, Search, ShieldCheck, Sparkles, Zap } from 'lucide-react'
import { GlobalSearch } from '@/components/ui/GlobalSearch'

const ZIP_TOOLS = [
  { name:'ZIP Code Lookup', desc:'City, state, county & timezone for any US ZIP.', href:'/zip/zip-code-lookup', icon:MapPin, badge:'Most searched' },
  { name:'ZIP Code Distance', desc:'Compare miles and kilometers between two ZIP codes.', href:'/zip/zip-code-distance', icon:Ruler, badge:'Popular' },
  { name:'ZIP+4 Lookup', desc:'Find the 4-digit extension used for mail delivery.', href:'/zip/zip-plus-4-lookup', icon:FileText, badge:'Popular' },
  { name:'ZIP Code Timezone', desc:'Instantly identify the US timezone for a ZIP.', href:'/zip/zip-to-timezone', icon:Clock3, badge:'Popular' },
  { name:'ZIP to Coordinates', desc:'Get latitude and longitude for a ZIP code.', href:'/zip/zip-to-coordinates', icon:Globe2, badge:'Popular' },
  { name:'ZIP Code Map', desc:'Explore ZIP boundaries and geographic context.', href:'/zip/zip-code-map', icon:Map, badge:null },
]
const FUN_TOOLS = [
  { name:'Shakespeare Insult Generator', desc:'Generate theatrical Elizabethan-style insults.', href:'/fun/shakespeare-insult-generator', icon:Sparkles, badge:'Featured' },
  { name:'Insult Generator', desc:'Explore themed roasts, comebacks and playful burns.', href:'/fun/insult-generator', icon:Flame, badge:'Popular' },
  { name:'Trivia Quiz', desc:'Quick random trivia for solo play or groups.', href:'/fun/trivia-quiz', icon:Calculator, badge:null },
  { name:'Zodiac Calculator', desc:'Find your sign and explore fun compatibility.', href:'/fun/zodiac-calculator', icon:Compass, badge:null },
  { name:'Love Compatibility', desc:'A lighthearted name-based compatibility score.', href:'/fun/love-compatibility', icon:Heart, badge:null },
]
const GUIDE_LINKS = [
  { title:'What Is a ZIP+4 Code? The Extra 4 Digits Explained', href:'/blog/what-is-a-zip-plus-4-code', read:'5 min read' },
  { title:'How to Find a ZIP Code From an Address', href:'/blog/how-to-find-a-zip-code-from-an-address', read:'5 min read' },
  { title:'How to Find ZIP Codes Within a Radius', href:'/blog/how-to-find-zip-codes-within-a-radius', read:'6 min read' },
  { title:'How Far Apart Are Two ZIP Codes? Distance Explained', href:'/blog/how-far-apart-are-two-zip-codes', read:'5 min read' },
  { title:'How to Find the Timezone for a ZIP Code', href:'/blog/how-to-find-a-time-zone-from-a-zip-code', read:'4 min read' },
  { title:'ZIP Code vs Postal Code: What Is the Difference?', href:'/blog/zip-code-vs-postal-code', read:'4 min read' },
]
const FAQS = [
  ['What is ToolTrio?','ToolTrio is a free utility site focused on fast US ZIP code lookups plus a secondary collection of fun generators and calculators. No signup is required.'],
  ['How do I find a city and state from a ZIP code?','Enter any 5-digit US ZIP code in ZIP Code Lookup to see its city, state, county, timezone and other available location details.'],
  ['Can I calculate the distance between two ZIP codes?','Yes. ZIP Code Distance calculates the straight-line distance between two US ZIP codes in miles and kilometers using their coordinates.'],
  ['How do I find my ZIP+4?','Use ZIP+4 Lookup to identify your base ZIP and then use the official USPS address lookup when you need the exact delivery-point suffix for a street address.'],
  ['Does ToolTrio have fun tools too?','Yes. ToolTrio has a separate Fun category with insult generators, quizzes, zodiac tools, compatibility tools and other lightweight entertainment utilities.'],
  ['Are ToolTrio tools free?','Yes. The public tools are free to use without registration or a subscription.'],
]
function ToolCard({tool,tone='zip'}:{tool:any;tone?:'zip'|'fun'}){
  const Icon=tool.icon
  return <Link href={tool.href} className={`group relative overflow-hidden rounded-2xl border bg-white/80 p-5 shadow-sm backdrop-blur-xl transition-all duration-200 hover:-translate-y-1 hover:shadow-xl ${tone==='zip'?'border-slate-200/80 hover:border-emerald-300/80':'border-slate-200/80 hover:border-fuchsia-300/80'}`}>
    <div className="absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-emerald-300/70 to-transparent opacity-0 transition-opacity group-hover:opacity-100" />
    <div className="flex items-start justify-between gap-3"><div className={`flex h-11 w-11 items-center justify-center rounded-xl border ${tone==='zip'?'border-emerald-100 bg-emerald-50 text-emerald-700':'border-fuchsia-100 bg-fuchsia-50 text-fuchsia-700'}`}><Icon className="h-5 w-5" /></div>{tool.badge&&<span className={`rounded-full px-2 py-1 text-[10px] font-bold ${tone==='zip'?'bg-emerald-50 text-emerald-700':'bg-fuchsia-50 text-fuchsia-700'}`}>{tool.badge}</span>}</div>
    <div className="mt-4 flex items-start justify-between gap-3"><div><h3 className="font-bold tracking-tight text-slate-900 group-hover:text-emerald-700">{tool.name}</h3><p className="mt-1.5 text-xs leading-5 text-slate-500">{tool.desc}</p></div><ArrowRight className="mt-1 h-4 w-4 shrink-0 text-slate-300 transition-transform group-hover:translate-x-1 group-hover:text-emerald-600" /></div>
  </Link>
}
export function HomePageClient({zipCount,funCount}:{zipCount:number;funCount:number}){
  return <main className="min-h-screen bg-[#f8fafc] text-slate-900">
    <section className="relative isolate overflow-hidden border-b border-slate-200/70"><div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_10%_15%,rgba(16,185,129,.15),transparent_30%),radial-gradient(circle_at_90%_20%,rgba(59,130,246,.10),transparent_28%),radial-gradient(circle_at_70%_85%,rgba(168,85,247,.08),transparent_30%)]" />
      <div className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8 lg:py-20"><div className="mx-auto max-w-4xl text-center">
        <div className="inline-flex items-center gap-2 rounded-full border border-emerald-200/80 bg-white/75 px-3 py-1.5 text-xs font-bold text-emerald-700 shadow-sm backdrop-blur"><BadgeCheck className="h-3.5 w-3.5"/> Free • No signup • Instant results</div>
        <h1 className="mt-6 text-4xl font-black tracking-[-0.04em] text-slate-950 sm:text-5xl lg:text-6xl">Every US ZIP utility,<br className="hidden sm:block"/> <span className="text-emerald-600">instant and free.</span></h1>
        <p className="mx-auto mt-5 max-w-2xl text-base leading-7 text-slate-600 sm:text-lg">Look up ZIP codes, compare ZIP-to-ZIP distance, find ZIP+4 information, identify timezones and coordinates — then switch to Fun when you need a little chaos.</p>
        <div className="mx-auto mt-8 max-w-2xl"><GlobalSearch className="w-full"/><div className="mt-3 flex flex-wrap items-center justify-center gap-2 text-xs text-slate-500">{['ZIP Code Lookup','ZIP Distance','ZIP+4','Timezone','Coordinates'].map(x=><span key={x} className="rounded-full border border-slate-200 bg-white/70 px-3 py-1.5">{x}</span>)}</div></div>
      </div>
      <div className="mt-12 grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-6">{ZIP_TOOLS.map((tool,i)=><div key={tool.href} className={i===0?'lg:col-span-2':'lg:col-span-1'}><ToolCard tool={tool}/></div>)}</div>
      <div className="mt-5 flex flex-wrap items-center justify-center gap-6 text-xs font-semibold text-slate-500"><span><strong className="text-slate-900">{zipCount}+</strong> ZIP tools</span><span><strong className="text-slate-900">{funCount}+</strong> Fun tools</span><span className="inline-flex items-center gap-1.5"><ShieldCheck className="h-3.5 w-3.5 text-emerald-600"/> Browser-friendly</span></div>
      </div>
    </section>
    <section className="border-b border-slate-200/70 bg-white/70 py-4 backdrop-blur"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-center gap-2 px-4 sm:px-6 lg:px-8"><span className="mr-1 text-[10px] font-black uppercase tracking-[0.18em] text-slate-400">Popular now</span>{[...ZIP_TOOLS.slice(0,5),FUN_TOOLS[0],FUN_TOOLS[1]].map(tool=><Link key={tool.href} href={tool.href} className="rounded-full border border-slate-200 bg-white px-3 py-1.5 text-[11px] font-semibold text-slate-600 shadow-sm hover:border-emerald-300 hover:text-emerald-700">{tool.name}</Link>)}</div></section>
    <section className="mx-auto max-w-7xl px-4 py-14 sm:px-6 lg:px-8"><div className="mb-6 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-emerald-600">Browse by category</p><h2 className="mt-1 text-2xl font-black tracking-tight text-slate-950 sm:text-3xl">Utilities for work. Generators for fun.</h2></div><Link href="/zip" className="inline-flex items-center gap-1 text-sm font-bold text-emerald-700">View all ZIP tools <ArrowRight className="h-4 w-4"/></Link></div>
      <div className="grid gap-8 lg:grid-cols-[1.25fr_.75fr]"><div className="rounded-3xl border border-slate-200/80 bg-white/75 p-6 shadow-sm backdrop-blur-xl"><div className="mb-5 flex items-center justify-between"><div className="flex items-center gap-2"><MapPin className="h-5 w-5 text-emerald-600"/><h3 className="font-black">ZIP Tools</h3></div><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-bold text-emerald-700">{zipCount} tools</span></div><div className="grid gap-3 sm:grid-cols-2">{ZIP_TOOLS.map(t=><ToolCard key={t.href} tool={t}/>)}</div></div>
      <div className="rounded-3xl border border-slate-200/80 bg-white/75 p-6 shadow-sm backdrop-blur-xl"><div className="mb-5 flex items-center justify-between"><div className="flex items-center gap-2"><Sparkles className="h-5 w-5 text-fuchsia-600"/><h3 className="font-black">Fun & Entertainment</h3></div><span className="rounded-full bg-fuchsia-50 px-2.5 py-1 text-xs font-bold text-fuchsia-700">{funCount} tools</span></div><div className="space-y-3">{FUN_TOOLS.map(t=><ToolCard key={t.href} tool={t} tone="fun"/>)}</div></div></div>
    </section>
    <section className="mx-auto max-w-7xl px-4 pb-14 sm:px-6 lg:px-8"><div className="rounded-3xl border border-slate-200/80 bg-slate-950 p-7 text-white shadow-xl sm:p-10"><div className="grid gap-8 lg:grid-cols-[1fr_.8fr] lg:items-center"><div><div className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/5 px-3 py-1.5 text-xs font-bold text-emerald-300"><Search className="h-3.5 w-3.5"/> One search for every tool</div><h2 className="mt-4 text-3xl font-black tracking-tight sm:text-4xl">Stop hunting through menus.</h2><p className="mt-3 max-w-xl text-sm leading-6 text-slate-300">Use the command-bar search to find ZIP utilities, Fun tools and guides from one place. Press <kbd className="rounded border border-white/20 bg-white/10 px-1.5 py-0.5 font-mono text-xs">⌘K</kbd> or <kbd className="rounded border border-white/20 bg-white/10 px-1.5 py-0.5 font-mono text-xs">Ctrl K</kbd>.</p></div><GlobalSearch className="w-full"/></div></div></section>
    <section className="mx-auto max-w-7xl px-4 pb-14 sm:px-6 lg:px-8"><div className="mb-6 flex items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-blue-600">SEO & educational hub</p><h2 className="mt-1 text-2xl font-black tracking-tight sm:text-3xl">ZIP guides people actually search for</h2></div><Link href="/blog/category/zip-codes" className="hidden items-center gap-1 text-sm font-bold text-blue-700 sm:inline-flex">All ZIP guides <ArrowRight className="h-4 w-4"/></Link></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{GUIDE_LINKS.map(g=><Link key={g.href} href={g.href} className="group rounded-2xl border border-slate-200/80 bg-white/80 p-5 shadow-sm transition-all hover:-translate-y-1 hover:border-blue-200 hover:shadow-lg"><div className="flex items-center justify-between gap-3"><span className="inline-flex items-center gap-1.5 rounded-full bg-blue-50 px-2.5 py-1 text-[10px] font-bold text-blue-700"><BookOpen className="h-3 w-3"/> ZIP Guide</span><span className="text-[10px] text-slate-400">{g.read}</span></div><h3 className="mt-4 font-bold leading-6 text-slate-900 group-hover:text-blue-700">{g.title}</h3><span className="mt-3 inline-flex items-center gap-1 text-xs font-bold text-slate-400 group-hover:text-blue-600">Read guide <ArrowRight className="h-3.5 w-3.5"/></span></Link>)}</div></section>
    <section className="mx-auto max-w-7xl px-4 pb-16 sm:px-6 lg:px-8"><div className="grid grid-cols-2 gap-3 md:grid-cols-4">{[[Zap,'Instant results','Built for quick lookups'],[ShieldCheck,'No signup','No account required'],[Check,'Free to use','No subscription gate'],[Navigation,'Works everywhere','Desktop, tablet & mobile']].map(([Icon,title,desc])=>{const I=Icon as typeof Zap;return <div key={title as string} className="rounded-2xl border border-emerald-100 bg-emerald-50/60 p-5 text-center"><I className="mx-auto h-5 w-5 text-emerald-700"/><p className="mt-2 text-sm font-black text-slate-900">{title as string}</p><p className="mt-1 text-xs text-slate-500">{desc as string}</p></div>})}</div></section>
    <section className="border-t border-slate-200/70 bg-white/60 py-16"><div className="mx-auto max-w-5xl px-4 sm:px-6 lg:px-8"><div className="mb-8 text-center"><p className="text-xs font-black uppercase tracking-[0.18em] text-slate-400">FAQ</p><h2 className="mt-2 text-3xl font-black tracking-tight">Frequently asked questions</h2></div><div className="grid gap-4 md:grid-cols-2">{FAQS.map(([q,a])=><details key={q} className="group rounded-2xl border border-slate-200/80 bg-white p-5 shadow-sm"><summary className="cursor-pointer list-none pr-6 text-sm font-bold text-slate-900">{q}</summary><p className="mt-3 text-sm leading-6 text-slate-600">{a}</p></details>)}</div></div></section>
  </main>
}
