'use client'
import { useState } from 'react'
import Link from 'next/link'
import { ChevronRight, Copy, Check, Plus, Trash2 } from 'lucide-react'
import { SEOContent } from '@/components/ui/SEOContent'
interface Props { faqs: { question: string; answer: string }[] }

export default function CalculatorClient({ faqs }: Props) {
  const [https, setHttps] = useState(true)
  const [www, setWww] = useState<'none'|'add'|'remove'>('add')
  const [hotlink, setHotlink] = useState(false)
  const [domain, setDomain] = useState('example.com')
  const [cacheAge, setCacheAge] = useState(2592000)
  const [customRedirects, setCustomRedirects] = useState([{ from: '/old-page', to: '/new-page' }])
  const [blockAgents, setBlockAgents] = useState(false)
  const [dirListing, setDirListing] = useState(true)
  const [customErrors, setCustomErrors] = useState(true)
  const [gzip, setGzip] = useState(true)
  const [copied, setCopied] = useState(false)

  const addRedirect = () => setCustomRedirects(r => [...r, { from: '', to: '' }])
  const removeRedirect = (i: number) => setCustomRedirects(r => r.filter((_,j) => j !== i))
  const updateRedirect = (i: number, k: 'from'|'to', v: string) => setCustomRedirects(r => r.map((item,j) => j===i ? {...item,[k]:v} : item))

  const htaccess = [
    '# Generated by tooltrio.com',
    'Options -Indexes',
    '',
    ...(dirListing ? [] : ['Options -Indexes', '']),
    ...(gzip ? [
      '# Enable Gzip compression',
      '<IfModule mod_deflate.c>',
      '  AddOutputFilterByType DEFLATE text/plain text/html text/css application/javascript application/json application/xml image/svg+xml',
      '</IfModule>',
      '',
    ] : []),
    ...(https ? [
      '# Force HTTPS',
      'RewriteEngine On',
      'RewriteCond %{HTTPS} off',
      'RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]',
      '',
    ] : ['RewriteEngine On', '']),
    ...(www === 'add' ? [
      `# Force www`,
      'RewriteCond %{HTTP_HOST} !^www\\. [NC]',
      `RewriteRule ^ https://www.${domain}%{REQUEST_URI} [L,R=301]`,
      '',
    ] : www === 'remove' ? [
      `# Remove www`,
      'RewriteCond %{HTTP_HOST} ^www\\.(.+)$ [NC]',
      `RewriteRule ^ https://${domain}%{REQUEST_URI} [L,R=301]`,
      '',
    ] : []),
    ...(customRedirects.filter(r => r.from && r.to).length ? [
      '# Custom 301 Redirects',
      ...customRedirects.filter(r => r.from && r.to).map(r => `Redirect 301 ${r.from} https://${www === 'add' ? 'www.' : ''}${domain}${r.to}`),
      '',
    ] : []),
    ...(hotlink ? [
      `# Prevent hotlinking`,
      'RewriteCond %{HTTP_REFERER} !^$',
      `RewriteCond %{HTTP_REFERER} !^https?://(www\\.)?${domain.replace('.','\\.')} [NC]`,
      'RewriteRule \\.(jpg|jpeg|png|gif|webp|svg)$ - [F,NC]',
      '',
    ] : []),
    ...(blockAgents ? [
      '# Block bad bots',
      'BrowserMatch "AhrefsBot" bad_bot',
      'BrowserMatch "MJ12bot" bad_bot',
      'BrowserMatch "DotBot" bad_bot',
      'BrowserMatch "SemrushBot" bad_bot',
      'Deny from env=bad_bot',
      '',
    ] : []),
    ...(customErrors ? [
      '# Custom error pages',
      'ErrorDocument 404 /404.html',
      'ErrorDocument 500 /500.html',
      '',
    ] : []),
    ...(cacheAge > 0 ? [
      '# Browser caching',
      '<IfModule mod_expires.c>',
      '  ExpiresActive On',
      `  ExpiresByType image/jpg "access plus ${Math.round(cacheAge/86400)} days"`,
      `  ExpiresByType image/png "access plus ${Math.round(cacheAge/86400)} days"`,
      `  ExpiresByType text/css "access plus ${Math.round(cacheAge/86400)} days"`,
      `  ExpiresByType application/javascript "access plus ${Math.round(cacheAge/86400)} days"`,
      '</IfModule>',
    ] : []),
  ].join('\n')

  const copy = () => { navigator.clipboard.writeText(htaccess); setCopied(true); setTimeout(()=>setCopied(false),1500) }

  return (
    <div className="max-w-5xl mx-auto px-4 py-10">
      <nav className="flex items-center gap-2 text-xs text-gray-400 mb-6">
        <Link href="/" className="hover:text-blue-600">Home</Link><ChevronRight className="w-3 h-3" />
        <Link href="/calculators/dev" className="hover:text-blue-600">Dev Tools</Link><ChevronRight className="w-3 h-3" />
        <span className="text-gray-700 font-semibold">.htaccess Generator</span>
      </nav>
      <h1 className="text-3xl font-black text-gray-900 mb-1">⚙️ .htaccess Generator</h1>
      <p className="text-gray-500 mb-6">Generate Apache .htaccess files with HTTPS redirect, WWW handling, custom redirects, hotlink protection, caching, and more.</p>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <div className="space-y-4">
          <div className="bg-white border border-gray-200 rounded-2xl p-5 shadow-sm">
            <h2 className="font-bold text-gray-900 mb-4">Site Configuration</h2>
            <div className="mb-4">
              <label className="text-xs font-bold text-gray-500 uppercase block mb-1">Your Domain</label>
              <input value={domain} onChange={e=>setDomain(e.target.value)} className="w-full border-2 border-gray-200 rounded-xl px-3 py-2.5 text-sm focus:border-blue-400 focus:outline-none" placeholder="example.com" />
            </div>
            <div className="space-y-3">
              {[
                { label: 'Force HTTPS (301 redirect)', state: https, set: setHttps },
                { label: 'Prevent hotlinking images', state: hotlink, set: setHotlink },
                { label: 'Block common bad bots', state: blockAgents, set: setBlockAgents },
                { label: 'Custom error pages (404, 500)', state: customErrors, set: setCustomErrors },
                { label: 'Enable Gzip compression', state: gzip, set: setGzip },
              ].map(item => (
                <label key={item.label} className="flex items-center gap-3 cursor-pointer">
                  <input type="checkbox" checked={item.state} onChange={e=>item.set(e.target.checked)} className="w-4 h-4 accent-blue-600" />
                  <span className="text-sm text-gray-700 font-medium">{item.label}</span>
                </label>
              ))}
            </div>
            <div className="mt-4">
              <label className="text-xs font-bold text-gray-500 uppercase block mb-2">WWW Policy</label>
              <div className="grid grid-cols-3 gap-2">
                {(['none','add','remove'] as const).map(v => (
                  <button key={v} onClick={() => setWww(v)} className={`py-2 text-xs font-bold rounded-xl capitalize border-2 ${www===v?'bg-blue-600 border-blue-600 text-white':'border-gray-200 text-gray-600 hover:border-blue-300'}`}>
                    {v === 'none' ? 'No change' : v === 'add' ? 'Add www' : 'Remove www'}
                  </button>
                ))}
              </div>
            </div>
            <div className="mt-4">
              <label className="text-xs font-bold text-gray-500 uppercase block mb-1">Browser Cache: {Math.round(cacheAge/86400)} days</label>
              <input type="range" min={0} max={31536000} step={86400} value={cacheAge} onChange={e=>setCacheAge(+e.target.value)} className="w-full" />
            </div>
          </div>

          <div className="bg-white border border-gray-200 rounded-2xl p-5 shadow-sm">
            <div className="flex items-center justify-between mb-3">
              <h2 className="font-bold text-gray-900">Custom Redirects (301)</h2>
              <button onClick={addRedirect} className="flex items-center gap-1 text-xs font-bold text-blue-600"><Plus className="w-3.5 h-3.5"/>Add</button>
            </div>
            {customRedirects.map((r, i) => (
              <div key={i} className="flex gap-2 mb-2">
                <input value={r.from} onChange={e=>updateRedirect(i,'from',e.target.value)} placeholder="/old-path" className="flex-1 border border-gray-200 rounded-xl px-2 py-1.5 text-xs font-mono focus:outline-none focus:border-blue-400" />
                <span className="text-gray-400 self-center">→</span>
                <input value={r.to} onChange={e=>updateRedirect(i,'to',e.target.value)} placeholder="/new-path" className="flex-1 border border-gray-200 rounded-xl px-2 py-1.5 text-xs font-mono focus:outline-none focus:border-blue-400" />
                <button onClick={()=>removeRedirect(i)} className="text-red-400 hover:text-red-600 p-1"><Trash2 className="w-3.5 h-3.5"/></button>
              </div>
            ))}
          </div>
        </div>

        <div className="bg-gray-950 rounded-2xl p-5">
          <div className="flex items-center justify-between mb-3">
            <span className="text-xs font-bold text-gray-400 uppercase">.htaccess Output</span>
            <button onClick={copy} className="flex items-center gap-1.5 text-xs font-bold text-green-400 hover:text-green-300">
              {copied ? <><Check className="w-3.5 h-3.5"/>Copied!</> : <><Copy className="w-3.5 h-3.5"/>Copy</>}
            </button>
          </div>
          <pre className="font-mono text-xs text-green-300 whitespace-pre overflow-auto max-h-[500px]">{htaccess}</pre>
        </div>
      </div>

      <SEOContent title=".htaccess Generator" category="dev"
        intro="The .htaccess Generator creates production-ready Apache configuration files with the most common web server directives - HTTPS forcing, www canonicalization, custom redirects, hotlink protection, browser caching, Gzip compression, and bad bot blocking - all from a visual interface without memorizing Apache rewrite syntax.\n\nApache's .htaccess files control web server behavior at the directory level and are essential for shared hosting environments (cPanel, Bluehost, SiteGround, HostGator) where you don't have access to the main Apache configuration. WordPress, Drupal, and most PHP CMS platforms rely on .htaccess for URL rewriting and security settings.

**Long-tail searches answered here:** htaccess file generator free online usa, apache htaccess rules builder free no signup, htaccess redirect generator free tool, mod rewrite rule generator free online, how to create htaccess file free generator, apache config generator free no download usa, htaccess www to non www redirect generator free, htaccess force https ssl redirect generator free usa, htaccess custom error page 404 403 generator free, htaccess block ip address rule generator free usa, htaccess cache control headers generator free, htaccess gzip compression enable free generator usa, htaccess password protect directory generator free, htaccess deny hotlinking image theft free usa, htaccess rewrite url without trailing slash free"
        howItWorks="The generator dynamically builds an .htaccess file from your selected options. HTTPS forcing uses RewriteCond %{HTTPS} off with a 301 redirect. WWW handling uses RewriteCond checking the HTTP_HOST header with a 301 redirect to the canonical domain. Custom redirects use the Redirect 301 directive. Image hotlink protection uses RewriteCond %{HTTP_REFERER} to block external image requests. Gzip uses mod_deflate AddOutputFilterByType directives. Browser caching uses mod_expires with configurable expiry times."
        benefits={[
          { title: 'Visual Configuration', text: 'Configure HTTPS, WWW policy, redirects, caching, and security options via checkboxes and inputs - no Apache directive syntax memorization needed.' },
          { title: 'Custom 301 Redirects', text: 'Add unlimited custom permanent redirects with from/to path pairs. Essential for SEO-safe URL changes during site redesigns.' },
          { title: 'Performance Optimizations', text: 'Gzip compression and browser caching directives reduce page load times - two of the most impactful performance optimizations for Apache-served websites.' },
          { title: 'Security Features', text: 'Block common SEO/scraping bots (Ahrefs, SEMrush, MJ12bot) and prevent image hotlinking that wastes bandwidth without authorization.' },
          { title: 'Real-time Output', text: 'The .htaccess code updates as you toggle options - see exactly what each setting adds to your configuration file before copying.' },
          { title: 'Download Ready', text: 'Copy the complete .htaccess content and paste into your hosting control panel or deploy directly to your server root.' },
        ]}
        useCases={[
          { title: 'Shared Hosting Setup', text: 'Configure HTTPS, www canonicalization, and browser caching for new websites on shared hosting providers that use Apache.' },
          { title: 'Website Migrations', text: 'Add custom 301 redirects for every old URL when redesigning or migrating a website to prevent link equity loss and broken links.' },
          { title: 'WordPress Security', text: 'WordPress relies on .htaccess for URL rewriting. Add hotlink protection and bad bot blocking to your existing WordPress .htaccess.' },
          { title: 'SEO Canonicalization', text: 'Force HTTPS and choose between www/non-www to establish canonical URLs - critical for preventing duplicate content Google penalties.' },
          { title: 'Bandwidth Protection', text: 'Prevent other websites from embedding your images directly, wasting your hosting bandwidth without providing any traffic in return.' },
          { title: 'Performance Tuning', text: 'Enable Gzip and browser caching to improve Core Web Vitals scores for Apache-hosted websites without modifying server configuration files.' },
        ]}
        tipsSection={`Always back up your existing .htaccess before making changes. A syntax error in .htaccess causes a 500 Internal Server Error for your entire website. Test changes in a staging environment first.\n\nFor WordPress sites, your existing .htaccess contains WordPress rewrite rules between # BEGIN WordPress and # END WordPress markers. Add custom directives above or below these markers, never inside them.\n\nThe www vs. non-www choice should be consistent across your entire web presence - DNS, HTML canonical tags, sitemap URLs, and .htaccess should all agree. Once chosen, 301-redirect from the non-canonical version and stick with it permanently.

For WordPress specifically, your .htaccess file contains the WordPress rewrite rules between # BEGIN WordPress and # END WordPress comment markers. When adding custom rules, always add them ABOVE the # BEGIN WordPress marker or BELOW the # END WordPress marker - never inside these markers, as WordPress will overwrite them when you save permalink settings.

mod_rewrite debugging is notoriously difficult. Enable RewriteLog (Apache 2.2) or trace logging (Apache 2.4: LogLevel alert rewrite:trace8 in httpd.conf) to see exactly how each request is processed through your RewriteRules. Also check Apache's error_log for 500 Internal Server Error details that .htaccess issues generate but browsers only show as generic errors.

For sites migrating from HTTP to HTTPS, the order of your redirects matters. Force HTTPS first, then canonicalize www/non-www. If you do it in the wrong order, you get double redirects (HTTP non-www -> HTTP www -> HTTPS www) which Google counts against Core Web Vitals and wastes time-to-first-byte. The correct order: 1) HTTP -> HTTPS, 2) www/non-www canonicalization.`}
        scienceSection={`Apache's .htaccess mechanism was introduced in NCSA HTTPd (Apache's predecessor) in the early 1990s and formalized in Apache 1.0 (1995). The name ".htaccess" originally stood for "hypertext access" - a per-directory access control file. Despite being over 30 years old, .htaccess remains the primary configuration mechanism for approximately 33% of all web servers (Apache serves roughly 30% of websites, mostly shared hosting environments).

mod_rewrite, Apache's URL rewriting module, was written by Ralf S. Engelschall and included in Apache 1.2 (1996). RewriteRule uses PCRE (Perl Compatible Regular Expressions) for pattern matching, making it extremely powerful but also notoriously difficult to debug. The RewriteLog directive (Apache 2.2) and trace-level logging (Apache 2.4+) are essential debugging tools when rules don't behave as expected.

According to W3Techs (2024), Apache powers approximately 28.2% of all websites, primarily on shared hosting platforms like cPanel, Bluehost, SiteGround, and HostGator - all of which use .htaccess for per-site configuration since users don't have access to the main httpd.conf.`}
        conclusion="The .htaccess Generator eliminates the need to remember Apache RewriteRule syntax for the most common web server tasks. Generate, copy, and deploy in minutes - free, private, and accurate."
      />

      <div className="mt-8 space-y-3">
        {faqs.map(f => <details key={f.question} className="bg-white border border-gray-200 rounded-xl p-4">
          <summary className="font-semibold text-gray-900 cursor-pointer">{f.question}</summary>
          <p className="text-gray-600 text-sm mt-3 leading-relaxed">{f.answer}</p>
        </details>)}
      </div>
    </div>
  )
}
