import type { Metadata } from 'next'
import { generateCalculatorMetadata, generateFAQStructuredData } from '@/lib/seo/metadata'
import dynamic from 'next/dynamic'
const CalculatorClient = dynamic(() => import('./CalculatorClient'), { ssr: false, loading: () => <div className="min-h-[400px] bg-white rounded-2xl border border-gray-100 animate-pulse m-4" /> })
export const metadata: Metadata = generateCalculatorMetadata({ title: 'FHA vs Conventional Mortgage Calculator USA 2026 | ToolTrio', description: 'Compare FHA loan vs conventional mortgage total costs, monthly payments, PMI vs MIP, and which is cheaper for your credit score and down payment in 2026.', slug: 'fha-vs-conventional-calculator', category: 'finance', keywords: ['FHA vs conventional calculator 2026', 'FHA loan vs conventional mortgage', 'FHA MIP vs PMI calculator', 'which mortgage is better FHA or conventional'] })
const faqs = [('When is FHA better than conventional?', 'FHA loans are typically better if your credit score is below 620 or your down payment is less than 5%. FHA allows credit scores as low as 580 with 3.5% down (or 500 with 10% down). However, FHA MIP (mortgage insurance premium) lasts the life of the loan if you put less than 10% down, while conventional PMI can be removed once you reach 20% equity.'), ('What is the FHA loan limit for 2026?', 'FHA loan limits for 2026 vary by county. The baseline conforming limit is $806,500 for single-family homes, with higher limits in high-cost areas (up to $1,209,750 in expensive metros like San Francisco and New York). Conventional conforming loan limits match the baseline. Jumbo loans exceed these limits and require private lender approval.')]
const relatedCalculators = [{'name': 'Mortgage Calculator', 'href': '/calculators/finance/mortgage-calculator', 'icon': '🏡', 'desc': 'Mortgage payments'}, {'name': 'Home Affordability', 'href': '/calculators/finance/home-affordability-calculator', 'icon': '💰', 'desc': 'How much house'}, {'name': 'Down Payment Calculator', 'href': '/calculators/finance/down-payment-calculator', 'icon': '💵', 'desc': 'Down payment needed'}]
const structuredData = [generateFAQStructuredData(faqs)]
export default function Page() { return <>{structuredData.map((s, i) => <script key={i} type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(s) }} />)}<CalculatorClient faqs={faqs} structuredData={structuredData} relatedCalculators={relatedCalculators} /></> }
