import type { Metadata } from 'next'
import { generateCalculatorMetadata, generateFAQStructuredData } from '@/lib/seo/metadata'
import dynamic from 'next/dynamic'
const CalculatorClient = dynamic(() => import('./CalculatorClient'), { ssr: false, loading: () => <div className="min-h-[400px] bg-white rounded-2xl border border-gray-100 animate-pulse m-4" /> })
export const metadata: Metadata = generateCalculatorMetadata({ title: 'Section 179 & Bonus Depreciation Calculator USA 2026 | ToolTrio', description: 'Calculate Section 179 and bonus depreciation deductions for business assets. 2026 bonus depreciation is 40%. Find your Year 1 tax savings.', slug: 'bonus-depreciation-calculator', category: 'finance', keywords: ['bonus depreciation calculator 2026', 'section 179 calculator', 'business asset depreciation USA', '40% bonus depreciation 2026'] })
const faqs = [('What is the 2026 bonus depreciation rate?', 'Bonus depreciation was phased down from 100% in 2022 to 80% in 2023, 60% in 2024, 40% in 2025, and 20% in 2026 under the Tax Cuts and Jobs Act phase-out schedule. Section 179 has a separate $1,220,000 deduction limit for 2026 with a phase-out starting at $3,050,000 of total asset purchases.'), ('What is the difference between Section 179 and bonus depreciation?', 'Section 179 allows you to expense up to $1,220,000 of qualifying assets in the year placed in service — but is limited to your business taxable income (you cannot create a loss). Bonus depreciation has no income limitation and can create a net operating loss. Use Section 179 first up to your income limit, then bonus depreciation for any remaining basis.')]
const relatedCalculators = [{'name': 'Business Valuation', 'href': '/calculators/finance/business-valuation-calculator', 'icon': '🏢', 'desc': 'Business value'}, {'name': 'Income Tax Calculator', 'href': '/calculators/finance/income-tax-calculator', 'icon': '📋', 'desc': 'Tax savings'}, {'name': 'Break-Even Calculator', 'href': '/calculators/finance/break-even-calculator', 'icon': '⚖️', 'desc': 'Break-even'}]
const structuredData = [generateFAQStructuredData(faqs)]
export default function Page() { return <>{structuredData.map((s, i) => <script key={i} type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(s) }} />)}<CalculatorClient faqs={faqs} structuredData={structuredData} relatedCalculators={relatedCalculators} /></> }
