import React from 'react'
type S={heading:string;text:string[]};type G={title:string;sections:S[]}
const guides:Record<string,G>={
"uwu-text-generator":{title:"Uwu Text Generator",sections:[
{heading:"How uwu transformation works",text:["An uwu transformer is a text-rewriting utility, not a numerical calculator. It changes recognizable spelling and punctuation patterns to create a playful internet style while trying to keep the original sentence understandable. Common transformations include replacing some r and l sounds with w, altering words such as 'love' or 'small' into stylized forms, adding emoticons, and inserting expressive interjections. The useful question is therefore not whether the output is mathematically accurate, but whether the transformation preserves enough of the source meaning for the intended audience.", "Transformation intensity matters. A light setting can make a few phonetic substitutions while leaving names, URLs, code, numbers, and punctuation mostly intact. A stronger setting may add faces, stutters, repeated punctuation, or decorative vocabulary. When transforming instructions, addresses, technical text, accessibility labels, or anything where exact wording matters, keep the original version because stylization can change meaning or make copy-and-paste data unusable."]},
{heading:"Unicode, punctuation, and edge cases",text:["Modern text contains emoji, accented letters, smart quotes, combining characters, URLs, @handles, hashtags, markdown, and code fragments. A robust generator should avoid corrupting these structures. Replacing characters blindly can damage a URL or source-code identifier, while splitting Unicode incorrectly can break an emoji sequence. Review transformed output whenever the input contains structured text.", "The generator is best used for casual messages, fictional dialogue, memes, character voices, and experimentation with online writing styles. It should not be treated as a translation into a language or dialect, and it should not be used to imitate a real person's speech in a way that misrepresents them. The output is stylistic text that can be edited further."]},
{heading:"Editing the result",text:["Read the generated text aloud before using it. Phonetic substitutions that look amusing in one word can become hard to parse when repeated across a long paragraph. Remove transformations from proper nouns and key terms when recognition is more important than style. If the output feels noisy, reduce added faces and interjections before undoing every spelling change.", "Keep an untouched copy of the source. That makes it easy to compare meaning, restore exact terms, or generate a second version at a different intensity. For longer content, transform a short sample first and decide on the style before processing the whole passage."]},
]},
"html-encoder":{title:"HTML Encoder",sections:[
{heading:"What HTML encoding protects",text:["HTML encoding converts characters that have syntactic meaning in markup into character references so they can be displayed as text. The critical examples are ampersand, less-than, greater-than, and quotes in contexts where quotes delimit an attribute. Encoding '<script>' as visible text prevents the browser from interpreting those angle brackets as an HTML element in that particular output context.", "Encoding is context-sensitive. Text inserted between HTML tags needs different handling from a value inserted into an HTML attribute, JavaScript string, CSS rule, or URL. An HTML encoder is therefore useful for inspecting entities and preparing literal markup examples, but secure applications should use the escaping mechanism appropriate to the exact sink rather than assuming one encoding operation solves every injection problem."]},
{heading:"Named and numeric entities",text:["A character can often be represented by a named entity such as '&amp;' or by a numeric reference such as a decimal or hexadecimal code point. Browsers decode both forms. Named entities are convenient for familiar characters, while numeric references can represent a much wider range of Unicode characters. Ordinary Unicode text does not need to be converted wholesale into entities just to be valid HTML.", "Double encoding is a common mistake. If an already encoded ampersand is encoded again, '&amp;' can become '&amp;amp;', and the page may display entity syntax instead of the intended character. Know whether your input is raw text or already escaped before processing it."]},
{heading:"Security and practical use",text:["HTML encoding is one layer of output handling, not a sanitizer for arbitrary untrusted HTML. If users are allowed to submit markup, a sanitizer with an explicit allow-list is needed to remove dangerous elements, attributes, URLs, and browser behaviors. Encoding everything is safer when the goal is plain text, but it intentionally prevents allowed markup from rendering.", "Use the tool for teaching entity syntax, embedding literal code examples, debugging malformed output, or preparing text for a known HTML context. After encoding, inspect quotes, ampersands, non-ASCII characters, and any pre-existing entities to confirm the result matches the destination."]},
]},
"loan-prepayment-calculator":{title:"Loan Prepayment Calculator",sections:[
{heading:"How prepayment changes amortization",text:["A standard amortizing loan divides each payment between interest and principal. Interest is calculated from the outstanding balance, so an extra principal payment reduces not only today's balance but also the base on which future interest is charged. The earlier a prepayment occurs, the more scheduled interest periods it can affect. This is why two equal extra payments made at different points in the loan can produce different lifetime savings.", "A useful prepayment result should separate three outcomes: the extra cash paid, the reduction in total interest, and the change in payoff date or future required payment. Some lenders keep the scheduled payment unchanged and shorten the term; others may offer a recast that lowers future payments after a large principal reduction. Those are different mechanisms and should not be mixed."]},
{heading:"Check the loan contract",text:["Confirm that extra money is applied to principal rather than treated as an advance payment of future installments. Also check for prepayment penalties, minimum amounts, recast fees, and rules for partial prepayments. Mortgages, auto loans, student loans, and business loans can have different contractual treatment.", "For variable-rate debt, future interest savings cannot be known with the same certainty as a fixed-rate amortization schedule because the rate path may change. For fixed-rate loans, the contractual rate provides a clearer benchmark for the guaranteed interest avoided by reducing principal."]},
{heading:"Prepay or use the cash elsewhere",text:["Prepayment creates a return roughly linked to the interest cost avoided, adjusted for taxes where interest is deductible. The comparison with investing should account for risk: avoiding contractual interest is very different from assuming a market portfolio will earn a particular return. Liquidity matters too, because cash sent to a lender may be difficult or expensive to access later.", "Before aggressive prepayment, consider emergency reserves and higher-rate debt. Run more than one extra-payment amount and start date. A useful plan is one that improves the balance sheet without leaving the household unable to handle an unexpected expense."]},
]},
"sp500-vs-real-estate-usa-calculator":{title:"S&P 500 vs Real Estate USA Calculator",sections:[
{heading:"Make the comparison economically consistent",text:["An S&P 500 investment and a property are fundamentally different assets. A fair comparison needs the same starting cash, holding period, contribution schedule, and treatment of leverage. For stocks, include dividends and fund expenses. For property, include the down payment, mortgage, closing costs, rent, vacancies, property tax, insurance, maintenance, capital improvements, selling costs, and remaining loan balance.", "Do not compare a leveraged property return with an unleveraged stock return without making the financing explicit. Mortgage leverage can amplify gains on the owner's equity, but it also increases fixed obligations and downside risk. The property may also produce housing services if owner-occupied, which is different from an investment rental."]},
{heading:"Total return and cash flow",text:["For the S&P 500, total return includes price appreciation plus reinvested dividends. For real estate, appreciation is only one component; net rental income and principal paydown can materially change the result. Conversely, headline home-price appreciation ignores transaction costs and recurring ownership expenses that reduce investor return.", "Use nominal or inflation-adjusted figures consistently. Historical averages are not forecasts, and national housing indexes may be poor proxies for one property in one neighborhood. A local rental property can diverge sharply from national real-estate data."]},
{heading:"Taxes, liquidity, and concentration",text:["Tax treatment depends on account type and property use. Securities can generate dividend and capital-gain taxes in taxable accounts. Rental property can involve depreciation, deductible expenses, passive-activity rules, and tax on sale. These rules can materially affect after-tax outcomes and require current jurisdiction-specific inputs.", "Stocks are generally liquid and easily diversified; a single property is concentrated, illiquid, and operationally demanding. Real estate can offer control over financing and improvements, while an index fund offers broad diversification with little management. The calculator should support a decision by exposing those tradeoffs rather than declaring one asset universally superior."]},
]},
"isa-vs-sipp-uk-calculator":{title:"ISA vs SIPP UK Calculator",sections:[
{heading:"ISA and SIPP tax wrappers",text:["A Stocks and Shares ISA generally uses money that has already been taxed, after which eligible investment growth and withdrawals are sheltered from UK income tax and capital gains tax. A SIPP is a pension wrapper: eligible contributions can receive pension tax relief, investments grow within the pension environment, and access is restricted by pension rules. Withdrawals can have taxable and tax-free components depending on current law and the individual's circumstances.", "Because the tax treatment occurs at different stages, comparing the same headline contribution can be misleading. Distinguish the amount leaving take-home pay from the gross amount invested after tax relief. For higher-rate relief that is not automatically added at source, the individual's claim process can also affect the effective cost."]},
{heading:"Access and retirement timing",text:["ISA flexibility is a major difference: withdrawals are generally accessible without waiting for pension age, subject to the specific ISA rules. SIPP money is designed for retirement and is normally inaccessible until the applicable minimum pension age. Someone funding a goal before pension access may therefore value ISA capacity even when pension tax relief looks attractive.", "Model retirement tax rather than assuming every SIPP pound is withdrawn tax-free. Future income from the State Pension, workplace pensions, annuities, employment, or property can affect the marginal rate applied to pension withdrawals."]},
{heading:"Allowances and planning",text:["Annual ISA and pension allowances, carry-forward rules, employer contributions, salary sacrifice, tapered allowances, and tax-relief limits can change. Use current HMRC rules for the tax year being modeled. Employer matching is especially important because giving it up can dominate small differences in fund fees or tax assumptions.", "Many investors use both wrappers: pension contributions for retirement tax efficiency and ISA savings for flexibility or the period before pension access. The useful output is therefore often an allocation decision rather than a winner-takes-all choice."]},
]},
"medicare-vs-private-insurance-calculator":{title:"Medicare vs Private Insurance Calculator",sections:[
{heading:"Compare total annual cost, not premium alone",text:["Health coverage comparisons need premiums plus expected cost sharing. Depending on the Medicare path, include Part B premiums, Part D or Medicare Advantage premiums, Medigap premiums, deductibles, copays, coinsurance, and drug costs. For private coverage, include the employee or individual premium, deductible, copays, coinsurance, and out-of-pocket maximum. Employer contributions should be separated from the amount the enrollee actually pays.", "A low-premium plan can be expensive for a high-utilization year, while a higher-premium plan may reduce exposure to unpredictable bills. Run low, typical, and high medical-use cases rather than relying on one expected number."]},
{heading:"Networks, drugs, and coordination",text:["Cost is not the only difference. Check whether doctors, hospitals, pharmacies, and medications are covered. Medicare Advantage plans can use networks and authorization rules; Original Medicare has a different provider structure and may be paired with Medigap and Part D. Private plans also vary widely in network breadth and formulary design.", "If a person is eligible for Medicare while covered by an employer plan, coordination-of-benefits and enrollment timing can matter. Delayed enrollment can create penalties in some circumstances, while HSA contribution eligibility changes when Medicare coverage begins. These are rule-sensitive issues that should be verified with current official guidance."]},
{heading:"Model the household correctly",text:["Spouses may not have identical eligibility or plan choices, so household comparisons sometimes require separate calculations. Retiree coverage, COBRA, ACA Marketplace coverage, employer plans, and Medicare can overlap during transitions. Include the exact months each option applies rather than annualizing a temporary premium incorrectly.", "Treat the calculator as a planning estimate, not a coverage determination. Actual claims, provider contracts, prescription tiers, income-related Medicare adjustments, and plan changes can move the final cost materially."]},
]},
"refinance-vs-invest-calculator":{title:"Refinance vs Invest Calculator",sections:[
{heading:"Define the refinance cash flow",text:["Refinancing can lower the interest rate, change the loan term, alter the monthly payment, or convert between loan types. The comparison must include closing costs, points, lender fees, appraisal or title charges where applicable, and any amount rolled into the new principal. A lower payment is not automatically a saving if it mainly comes from extending the repayment term.", "Calculate the break-even period from actual monthly savings only when the old and new loans are otherwise comparable. If the term changes, also compare total interest and remaining balance at the chosen horizon. Selling or refinancing again before the break-even date can erase the expected benefit."]},
{heading:"What investing the difference means",text:["The investment alternative should use the same cash flows. If refinancing requires upfront costs, one scenario can invest that cash instead. If refinancing lowers the monthly payment, another scenario can invest the monthly difference. Market returns are uncertain, so use a range of after-fee, after-tax assumptions rather than a single optimistic rate.", "Paying less mortgage interest is closer to a known financing benefit on a fixed-rate loan, whereas investment returns fluctuate. The comparison therefore involves risk capacity and liquidity as well as expected value."]},
{heading:"Taxes and horizon",text:["Mortgage-interest deductions, investment taxes, retirement-account treatment, and local rules can affect the comparison, but they should be included only when they actually apply to the user. Do not assume a deduction simply because mortgage interest exists.", "Use the expected time in the property as the primary horizon and inspect balances at that date. A refinance that looks attractive over 30 years may be poor for someone likely to move in three years. Conversely, a modest rate reduction can become meaningful when the balance is large and the holding period is long."]},
]},
"term-vs-whole-life-calculator":{title:"Term vs Whole Life Calculator",sections:[
{heading:"Separate insurance from accumulation",text:["Term life insurance provides a death benefit for a stated coverage period if premiums are paid and the insured dies while coverage is in force. Whole life is permanent insurance with guaranteed elements that can include cash value. Comparing them requires separating the insurance benefit from the savings or cash-value component instead of treating the whole-life premium difference as pure insurance cost.", "Use comparable death benefits and underwriting assumptions. A quote for a healthy applicant at one age cannot be fairly compared with a different benefit amount, health class, or policy design."]},
{heading:"Cash value, guarantees, and illustrations",text:["Whole-life illustrations can contain guaranteed values and non-guaranteed dividends. These should not be blended into one assumed return. Policy loans and withdrawals can reduce cash value and death benefits and may create tax consequences if a policy lapses with outstanding loans.", "Term coverage has an expiration date and renewal costs can rise sharply. If the need is temporary—such as replacing income while children are dependent or a mortgage is outstanding—the matching term matters. Permanent estate-liquidity or lifelong dependent needs may require a different analysis."]},
{heading:"Buy term and invest the difference",text:["The common 'buy term and invest the difference' comparison should actually invest the premium difference at a stated after-fee return and should account for behavior: money not automatically invested does not compound. It should also compare liquidity, volatility, taxes, and the fact that market assets do not provide the same contractual death-benefit structure.", "Insurance decisions depend on required death benefit, duration of need, budget, insurability, estate goals, and tolerance for investment risk. Use the calculator to understand cash flows, then verify policy guarantees, surrender schedules, riders, and insurer documentation before purchasing."]},
]},
"germany-etf-vs-tagesgeld-calculator":{title:"Germany ETF vs Tagesgeld Calculator",sections:[
{heading:"Risk-free cash versus market exposure",text:["Tagesgeld is an on-demand savings account whose interest rate can change, while an ETF can hold equities or bonds whose market value fluctuates. The comparison therefore should not treat both quoted returns as equally certain. Tagesgeld is useful for liquidity and short horizons; an equity ETF is generally evaluated over longer periods because short-term losses can be substantial.", "For Tagesgeld, model the advertised rate only for the period it is actually guaranteed and allow for later rate changes. Promotional Neukunden rates can expire quickly. For ETFs, use total return assumptions after fund costs and do not treat a historical average as a promised annual rate."]},
{heading:"German tax treatment",text:["Interest and investment income can be subject to German capital-income taxation, with the Sparer-Pauschbetrag and individual circumstances affecting taxable amounts. Investment funds can also involve partial exemptions depending on fund type. The calculator should state whether returns are gross or after estimated taxes.", "Taxes and thresholds change, so decision-critical calculations should use current German rules and the investor's actual allowance usage. Church tax and other personal factors can also alter net results."]},
{heading:"Deposit protection, volatility, and horizon",text:["Eligible bank deposits can fall under statutory deposit-guarantee arrangements, subject to applicable limits and institution details. ETF assets have a different legal and market-risk structure: diversification can reduce company-specific risk but does not remove market losses.", "Match the asset to the goal. Money needed for an emergency fund or near-term purchase should not be compared using a 20-year equity-return assumption. Long-term retirement money, by contrast, can make the opportunity cost of permanently holding all savings in cash more relevant."]},
]},
"i-bonds-vs-tips-calculator":{title:"I Bonds vs TIPS Calculator",sections:[
{heading:"Two different inflation protections",text:["Series I Savings Bonds and Treasury Inflation-Protected Securities both respond to inflation, but their mechanics differ. I Bonds combine a fixed rate with a semiannual inflation component and accrue value without a tradable market price. TIPS are marketable Treasury securities whose principal is adjusted with inflation and whose coupon is applied to the adjusted principal.", "Because TIPS trade in the market, their price can rise or fall with real interest rates before maturity. I Bonds do not show that market-price volatility, but they have purchase limits and redemption restrictions. These differences matter more than comparing a single displayed yield."]},
{heading:"Taxes and cash-flow timing",text:["Federal tax treatment and state/local tax treatment differ from ordinary taxable bonds, and TIPS can create taxable inflation adjustments in a taxable account even before all economic gain is received as cash. I Bond interest can generally be deferred until redemption or maturity, subject to applicable rules.", "Account location therefore matters. A TIPS fund in a retirement account has different tax logistics from an individual TIPS held in taxable form. Use current Treasury and IRS guidance for exact treatment."]},
{heading:"Holding period and deflation",text:["I Bonds cannot be redeemed during the initial lockup period and can lose recent interest when redeemed before the specified holding threshold. TIPS can be sold before maturity but then expose the investor to market price at the sale date. Holding an individual TIPS to maturity removes some price uncertainty but not inflation uncertainty.", "Both instruments have deflation-related protections, but not in identical form. Compare real purchasing-power goals, liquidity needs, purchase limits, maturity dates, and tax handling rather than assuming one is always the superior inflation hedge."]},
]},
"inflation-calculator":{title:"Inflation Calculator",sections:[
{heading:"Purchasing power and price indexes",text:["Inflation describes a change in the general price level, not a guarantee that every item rises by the same percentage. A calculator commonly applies a cumulative inflation rate to translate an amount between years or estimate how much future money is needed to match today's purchasing power. The core relationship compounds changes across periods rather than simply multiplying one annual rate by the number of years.", "When historical inflation is used, the chosen price index matters. A broad consumer index represents an average basket and may not match a household dominated by housing, healthcare, tuition, or another category. Personal inflation can therefore differ materially from headline CPI."]},
{heading:"Nominal versus real values",text:["A nominal investment return includes the effect of changing prices. Real return measures growth in purchasing power. For accurate conversion, use the multiplicative relationship between nominal growth and inflation rather than merely subtracting percentages when rates are large.", "The same distinction applies to wages and budgets. A salary that rises 4% while prices rise 5% has increased in nominal currency but lost purchasing power. Long-term plans should state whether future figures are nominal dollars or today's dollars."]},
{heading:"Forecasting limitations",text:["Future inflation is unknown and can vary from year to year. A constant assumption is useful for planning but should be tested at several rates, especially for long horizons where compounding magnifies small differences. Do not present a 30-year purchasing-power estimate as precise to the last dollar.", "Use the calculator to translate economic assumptions into understandable amounts: future cost of a goal, real value of cash, required salary growth, or inflation-adjusted return. For historical comparisons, use a consistent official index and dates that match the calculation period."]},
]},
"france-pea-vs-assurance-vie-calculator":{title:"France PEA vs Assurance Vie Calculator",sections:[
{heading:"Different French investment envelopes",text:["A PEA and an assurance-vie contract are both tax-advantaged structures, but they differ in eligible investments, withdrawal rules, contribution constraints, fees, and tax treatment. A PEA is oriented toward eligible equities and funds, while assurance vie can provide a broader menu that may include euro funds and unit-linked investments depending on the contract.", "The comparison should start with the same net contribution and investment risk. Comparing an equity-heavy PEA with a capital-oriented euro fund without acknowledging the asset-allocation difference confuses wrapper effects with investment effects."]},
{heading:"Holding period and withdrawals",text:["French tax advantages can depend on how long the wrapper has been held and on the timing and nature of withdrawals. The consequences of a PEA withdrawal and an assurance-vie rachat are not identical. Model the expected holding period and cash-access needs rather than looking only at the end value.", "Assurance-vie contracts can also have contract-level fees, fund fees, and potentially other charges. PEA costs depend on provider and investments. Small annual fee differences compound over long periods."]},
{heading:"Tax and estate considerations",text:["Taxation of gains, social contributions, allowances, and assurance-vie succession treatment can be important, but the exact rules depend on dates, age of contributions, beneficiaries, and current French law. Use current official guidance for a real decision.", "Many households can use both wrappers for different goals. The calculator is most useful when it shows net investment growth, fees, liquidity constraints, and estimated tax treatment separately, allowing the user to see which factor drives the result."]},
]},
"spain-pension-vs-etf-calculator":{title:"Spain Pension vs ETF Calculator",sections:[
{heading:"Contribution tax relief versus flexibility",text:["A Spanish pension plan can provide contribution-related tax effects within applicable limits, while a taxable ETF portfolio generally uses after-tax money and offers different liquidity. The pension benefit should be modeled as a tax deferral or reduction under current rules, not as free return. Withdrawals can later be taxed according to the rules applicable to pension benefits.", "An ETF account can usually offer more flexible access, but realized gains and distributions may create tax liabilities. Compare the same out-of-pocket contribution and explicitly show any tax saving that is reinvested rather than assuming it disappears."]},
{heading:"Investment return and fees",text:["The wrapper does not determine the underlying investment return. Compare similar asset allocations where possible. A low-cost global equity ETF and a conservative pension fund are not equivalent risk exposures. Include management, custody, fund, and plan fees because long-term fee drag can be substantial.", "Market return assumptions should be ranges, not guarantees. A pension plan can hold risky assets too, and an ETF can hold low-risk bonds; the labels alone do not define volatility."]},
{heading:"Spanish rules and retirement access",text:["Contribution limits, deduction treatment, liquidity events, retirement access, transfer rules, and taxation can change. Use current Spanish tax and pension guidance and account for the individual's marginal tax rate now and expected rate when benefits are withdrawn.", "The practical decision can be a combination: use pension contributions where the tax benefit is valuable and preserve taxable investments for flexibility. The calculator should expose that tradeoff rather than forcing a universal winner."]},
]},
"ppf-vs-nps-calculator":{title:"PPF vs NPS Calculator",sections:[
{heading:"PPF and NPS serve different retirement roles",text:["India's Public Provident Fund is a government-backed long-term savings scheme with a declared interest rate and specific contribution, maturity, extension, loan, and partial-withdrawal rules. The National Pension System is a market-linked retirement structure with asset allocation across permitted categories and retirement-exit rules. Comparing them requires separating guaranteed/declared-rate behavior from market-return assumptions.", "Use the same annual contribution and timing. PPF interest is credited according to scheme rules, while NPS outcomes depend on investment performance and charges. A high assumed NPS equity return should not be presented as guaranteed."]},
{heading:"Liquidity and retirement exit",text:["PPF has a long maturity framework with defined partial-withdrawal and extension provisions. NPS is specifically designed for retirement and can require a portion of the corpus to be used for annuity purchase under applicable exit rules, while lump-sum treatment depends on current regulations.", "These access constraints can matter as much as projected corpus. Someone who may need funds before retirement should not judge the options only by terminal value."]},
{heading:"Tax treatment and allocation",text:["Tax deductions for PPF and NPS can fall under different provisions and limits, and employer NPS contributions can have separate treatment. Tax rules and contribution limits change, so use current Indian rules for the relevant financial year.", "NPS asset allocation, rebalancing, equity limits, and annuity assumptions should be shown explicitly. PPF can complement rather than replace market-linked retirement assets. The calculator is most useful for understanding how contribution tax benefits, return assumptions, liquidity, and retirement payout structure interact."]},
]},
"vanguard-vs-fidelity-etf-calculator":{title:"Vanguard vs Fidelity ETF Calculator",sections:[
{heading:"Compare funds, not brand names",text:["Vanguard and Fidelity each offer many ETFs with different indexes, expense ratios, spreads, holdings, factor exposures, and trading characteristics. A meaningful calculator should compare specific funds pursuing comparable mandates rather than treating each provider as one investment. A total-market fund and a sector ETF are not substitutes merely because they come from competing firms.", "Start with index methodology, portfolio holdings, market-cap coverage, and tracking objective. Expense ratio matters, but a one-basis-point fee difference is usually less important than accidentally choosing a materially different exposure."]},
{heading:"Trading and tracking costs",text:["ETF ownership cost can include the published expense ratio, bid-ask spread, premium or discount to NAV, brokerage effects, and tracking difference. Highly liquid broad-market funds often trade efficiently, but smaller or specialized funds can have wider spreads.", "For long holding periods, fund expenses compound. For frequent trading or small purchases, spreads can matter more. Compare the actual dollar impact at the planned investment size and frequency."]},
{heading:"Taxes and account location",text:["ETF tax efficiency can differ because of portfolio turnover, distributions, and fund structure, while taxes also depend on whether the investment sits in a taxable or retirement account. Do not assume provider alone determines after-tax return.", "Operational preferences can still matter: brokerage integration, fractional-share availability, automatic investing, securities lending policies, customer service, and portability. The best comparison combines investment exposure and cost with the way the investor actually plans to hold and trade the fund."]},
]},
"europe-property-vs-reit-calculator":{title:"Europe Property vs REIT Calculator",sections:[
{heading:"Direct property and REITs are different exposures",text:["Buying a European property concentrates capital in a specific building and local market. A REIT or listed property fund can provide diversified exposure to many properties and sectors but trades in public markets and can be volatile. A fair comparison needs to distinguish direct ownership economics from the market value of listed real-estate companies.", "For direct property include purchase taxes, legal/notary costs, financing, maintenance, insurance, vacancy, management, renovation, local property taxes, rental income, selling costs, and remaining debt. For REITs include distributions, price changes, fund expenses, withholding taxes where relevant, and brokerage costs."]},
{heading:"Leverage and cash flow",text:["Property is often purchased with a mortgage, which amplifies the return on equity and creates mandatory debt service. A REIT comparison should either model equivalent leverage explicitly or acknowledge that one side is leveraged and the other is not.", "Rental yield should be net of realistic operating expenses and vacancy, not just annual rent divided by purchase price. REIT distribution yield is also not the same as total return because market price can change."]},
{heading:"Cross-border and liquidity issues",text:["European property taxation, transfer taxes, landlord rules, currency exposure, and transaction procedures vary substantially by country. REIT domicile and investor residence can also affect withholding and tax treatment. Use country-specific current inputs.", "Listed REITs are generally easier to buy, sell, and diversify. Direct property offers control and potential use value but can take months to transact. The calculator should make liquidity, concentration, workload, and leverage visible alongside projected return."]},
]},
"meta-tag-generator":{title:"Meta Tag Generator",sections:[
{heading:"Build metadata for the actual page",text:["A meta-tag generator should produce metadata that accurately describes one page rather than stuffing generic keywords into every route. The title element and meta description are primarily about communicating topic and intent to search users. Search engines can rewrite displayed titles or snippets, so character counts are guidelines rather than guarantees.", "Keep titles specific and distinguish pages that would otherwise look identical. Descriptions should summarize the page honestly and include the information a searcher needs to decide whether the result is relevant. Repeating the same description across hundreds of tools wastes an opportunity to explain each page."]},
{heading:"Canonical, robots, and social metadata",text:["A canonical link identifies the preferred URL among duplicates or near-duplicates, but it is a signal rather than a substitute for sound URL architecture. Robots directives control indexing and snippet behavior; accidentally generating 'noindex' can remove a page from search results.", "Open Graph and Twitter/X card metadata affect how a URL appears when shared. Use an absolute image URL, suitable dimensions, a descriptive title, and page-specific text. Social metadata does not replace visible page content."]},
{heading:"Structured data and validation",text:["Meta tags are different from structured data. JSON-LD can describe supported entities or page types, but markup must reflect content actually visible on the page and follow the relevant search-engine policies. Do not generate fake ratings, FAQs, or claims solely for rich-result eligibility.", "After generating tags, inspect the final server-rendered HTML rather than only the source component. Frameworks can merge or override metadata. Check escaping, duplicate tags, canonical URLs, locale, robots directives, and social previews before deployment."]},
]},
"euro-bonds-vs-etf-calculator":{title:"Euro Bonds vs ETF Calculator",sections:[
{heading:"Clarify what the ETF holds",text:["'Euro bonds versus ETF' is not automatically a bonds-versus-stocks comparison because an ETF can itself hold euro-denominated bonds. Define whether the ETF side represents equities, a bond index, or another asset class. Then compare duration, credit quality, currency exposure, income, volatility, and expected return on a like-for-like basis.", "For an individual bond, yield to maturity assumes contractual payments and reinvestment conditions subject to issuer credit risk. For a bond ETF, there is no single maturity date for the investor because the portfolio continually holds and replaces securities according to its index or mandate."]},
{heading:"Interest-rate and credit risk",text:["Bond prices generally move inversely to market yields, with longer duration producing greater sensitivity. Credit spreads can also widen, reducing prices even if government yields are unchanged. A bank deposit-like mental model is therefore inappropriate for marketable bonds and bond ETFs.", "Equity ETFs have different risk drivers—company earnings, valuations, economic growth, and market sentiment. A higher expected return comes with potentially much larger drawdowns."]},
{heading:"Currency, taxes, and income",text:["A euro-denominated asset is not necessarily free of currency risk if the underlying issuer or ETF holdings have exposure to other currencies. Hedged and unhedged share classes can behave differently and have different costs.", "Compare after-fee income and total return, not coupon or distribution yield alone. Taxation depends on investor residence, account type, fund domicile, and local rules. The right allocation often combines high-quality bonds for stability with growth assets rather than choosing one category exclusively."]},
]},
"europe-etf-vs-property-calculator":{title:"Europe ETF vs Property Calculator",sections:[
{heading:"Normalize the starting capital",text:["A European ETF portfolio can be purchased incrementally, while property usually requires a large deposit plus transaction costs. To compare fairly, account for every euro committed at purchase and any unused cash. If the property uses mortgage leverage, model debt service and remaining principal explicitly rather than comparing property appreciation with an unleveraged ETF return.", "ETF total return includes distributions and price changes after fund expenses. Property return can include rent, appreciation, mortgage principal reduction, and tax effects, offset by maintenance, vacancy, insurance, management, local taxes, renovations, and sale costs."]},
{heading:"Country-specific property friction",text:["European property markets differ in transfer taxes, notary/legal fees, tenant protections, financing terms, recurring taxes, and selling costs. A generic continent-wide assumption can be misleading. Use the country and city relevant to the contemplated purchase.", "Currency exposure also matters for investors whose spending currency differs from the property or ETF assets. An ETF may diversify across countries and currencies, while one property creates a concentrated local exposure."]},
{heading:"Liquidity, diversification, and effort",text:["ETFs can usually be sold in small amounts during market hours and can hold hundreds or thousands of securities. Property transactions are slow, indivisible, and operationally intensive. That illiquidity can discourage impulsive selling, but it can also make emergency access difficult.", "Model several holding periods because property transaction costs are front-loaded and can dominate short ownership periods. The calculator should support a tradeoff analysis between expected after-cost wealth, cash flow, leverage, liquidity, diversification, and personal use—not just compare headline return percentages."]},
]},
"uk-remortgage-vs-invest-calculator":{title:"UK Remortgage vs Invest Calculator",sections:[
{heading:"Measure the remortgage correctly",text:["A UK remortgage comparison should include the new mortgage rate, remaining balance, repayment term, product fee, valuation/legal costs where applicable, early repayment charge on the existing deal, and whether fees are paid upfront or added to the loan. Adding a fee to the mortgage increases the balance and causes interest to be charged on that fee.", "Compare both monthly payment and balance at the chosen horizon. Extending the term can make the payment look cheaper while increasing lifetime interest. If the borrower expects to move or refinance again, use that expected date rather than the full contractual term as the decision horizon."]},
{heading:"Investing instead of reducing mortgage cost",text:["The investment alternative should use the same available cash. Money used for an arrangement fee, lump-sum overpayment, or higher mortgage payment can instead be modeled as an investment contribution. Investment returns are uncertain and should be shown after fund fees and relevant taxes.", "A fixed mortgage cost is a contractual financing rate for the deal period; equity returns are volatile. Comparing 4% mortgage interest with an assumed 7% market return without discussing risk can make the investment option look falsely certain."]},
{heading:"UK-specific details",text:["Mortgage products can include fixed, tracker, variable, offset, and repayment structures with different overpayment allowances and early repayment charges. Check the lender's actual illustration and APRC rather than relying only on the headline rate.", "ISA or pension wrappers can change the tax treatment of investments, while mortgage-interest relief generally does not work like an ordinary investment deduction for owner-occupiers. Preserve an emergency fund and consider loan-to-value bands because reducing the balance enough to enter a better LTV tier can change available mortgage pricing."]},
]},
}
export function CalculatorBatch54DeepDive({slug}:{slug:string}){const g=guides[slug];if(!g)return null;return <section className="mt-10 space-y-6"><h2 className="text-2xl font-bold">{g.title} Guide</h2>{g.sections.map((s,i)=><div key={i} className="space-y-3"><h3 className="text-xl font-semibold">{s.heading}</h3>{s.text.map((t,j)=><p key={j}>{t}</p>)}</div>)}</section>}