import type { Metadata } from 'next'
import { generateCalculatorMetadata, generateFAQStructuredData } from '@/lib/seo/metadata'
import dynamic from 'next/dynamic'
const CalculatorClient = dynamic(() => import('./CalculatorClient'), { ssr: false, loading: () => <div className="min-h-[400px] bg-white rounded-2xl border border-gray-100 animate-pulse m-4" /> })
export const metadata: Metadata = generateCalculatorMetadata({ title: 'COBRA vs ACA Marketplace Calculator USA 2026 | ToolTrio', description: 'Compare COBRA health insurance cost vs ACA Marketplace plan with subsidy eligibility. Calculate net monthly premiums and annual savings for USA 2026.', slug: 'cobra-vs-marketplace-calculator', category: 'finance', keywords: ['COBRA vs marketplace calculator', 'ACA subsidy calculator 2026', 'health insurance comparison COBRA', 'marketplace premium calculator USA'] })
const faqs = [('How long does COBRA coverage last?', 'COBRA coverage generally lasts 18 months after job loss, 36 months for dependents after divorce or a dependent aging out. You must elect COBRA within 60 days of losing coverage. Premiums can be very expensive — you pay the full premium plus a 2% administrative fee, which is often $500-$1,500/month for a family.'), ('What income qualifies for ACA premium subsidies?', 'For 2026, premium tax credits are available for households earning between 100% and 400% of the Federal Poverty Level (FPL). Enhanced subsidies from the Inflation Reduction Act cap premiums at 8.5% of income for those above 400% FPL, with no hard income cliff. A family of 4 earning up to ~$125,000 may qualify for some subsidy. Use this calculator to see your estimated subsidy.')]
const relatedCalculators = [{'name': 'Medicare vs Private Insurance', 'href': '/calculators/finance/medicare-vs-private-insurance-calculator', 'icon': '🏥', 'desc': 'Medicare vs private'}, {'name': 'HSA vs FSA', 'href': '/calculators/finance/hsa-vs-fsa-calculator', 'icon': '💊', 'desc': 'HSA vs FSA'}, {'name': 'Health Insurance Deductible', 'href': '/calculators/finance/health-insurance-deductible-calculator', 'icon': '🏥', 'desc': 'Deductible calculator'}]
const structuredData = [generateFAQStructuredData(faqs)]
export default function Page() { return <>{structuredData.map((s, i) => <script key={i} type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(s) }} />)}<CalculatorClient faqs={faqs} structuredData={structuredData} relatedCalculators={relatedCalculators} /></> }
