// ─── Shared tool data — used by GlobalSearch ───────────────────
// Single source of truth — do not duplicate this data elsewhere

export type ToolItem = {
  name: string
  href: string
  cat: string    // lowercase: finance | health | dev | fun | zip | commodities | blog
  catLabel: string  // display: Finance | Health | Dev Tools | Fun | ZIP | Commodities
  kw: string     // search keywords from slug
}

export const TOOL_ITEMS: ToolItem[] = [
  { name: '401k Calculator', href: '/calculators/finance/401k-calculator', cat: 'finance', catLabel: 'Finance', kw: '401k calculator' },
  { name: '401k Early Withdrawal vs Loan Calculator', href: '/calculators/finance/401k-early-withdrawal-vs-loan-calculator', cat: 'finance', catLabel: 'Finance', kw: '401k early withdrawal vs loan calculator' },
  { name: '401k vs Pension Calculator', href: '/calculators/finance/401k-vs-pension-calculator', cat: 'finance', catLabel: 'Finance', kw: '401k vs pension calculator' },
  { name: '401k vs Roth IRA Calculator', href: '/calculators/finance/401k-vs-roth-ira-calculator', cat: 'finance', catLabel: 'Finance', kw: '401k vs roth ira calculator' },
  { name: '401k vs Taxable Account Calculator', href: '/calculators/finance/401k-vs-taxable-account-calculator', cat: 'finance', catLabel: 'Finance', kw: '401k vs taxable account calculator' },
  { name: '529 vs Roth IRA Education Calculator', href: '/calculators/finance/529-vs-roth-ira-education-calculator', cat: 'finance', catLabel: 'Finance', kw: '529 vs roth ira education calculator' },
  { name: '529 vs Utma Calculator', href: '/calculators/finance/529-vs-utma-calculator', cat: 'finance', catLabel: 'Finance', kw: '529 vs utma calculator' },
  { name: 'Annual Income Calculator', href: '/calculators/finance/annual-income-calculator', cat: 'finance', catLabel: 'Finance', kw: 'annual income calculator' },
  { name: 'Annuity vs Lumpsum Calculator', href: '/calculators/finance/annuity-vs-lumpsum-calculator', cat: 'finance', catLabel: 'Finance', kw: 'annuity vs lumpsum calculator' },
  { name: 'Auto Loan Calculator', href: '/calculators/finance/auto-loan-calculator', cat: 'finance', catLabel: 'Finance', kw: 'auto loan calculator' },
  { name: 'Biweekly Mortgage Calculator', href: '/calculators/finance/biweekly-mortgage-calculator', cat: 'finance', catLabel: 'Finance', kw: 'biweekly mortgage calculator' },
  { name: 'Bonds vs Cds USA Calculator', href: '/calculators/finance/bonds-vs-cds-usa-calculator', cat: 'finance', catLabel: 'Finance', kw: 'bonds vs cds usa calculator' },
  { name: 'Break Even Calculator', href: '/calculators/finance/break-even-calculator', cat: 'finance', catLabel: 'Finance', kw: 'break even calculator' },
  { name: 'Budget Calculator', href: '/calculators/finance/budget-calculator', cat: 'finance', catLabel: 'Finance', kw: 'budget calculator' },
  { name: 'Budget Planner Calculator', href: '/calculators/finance/budget-planner-calculator', cat: 'finance', catLabel: 'Finance', kw: 'budget planner calculator' },
  { name: 'Business Loan Calculator', href: '/calculators/finance/business-loan-calculator', cat: 'finance', catLabel: 'Finance', kw: 'business loan calculator' },
  { name: 'CAGR Calculator', href: '/calculators/finance/cagr-calculator', cat: 'finance', catLabel: 'Finance', kw: 'cagr calculator' },
  { name: 'Car Depreciation Calculator', href: '/calculators/finance/car-depreciation-calculator', cat: 'finance', catLabel: 'Finance', kw: 'car depreciation calculator' },
  { name: 'Car Loan Calculator', href: '/calculators/finance/car-loan-calculator', cat: 'finance', catLabel: 'Finance', kw: 'car loan calculator' },
  { name: 'Cash Out Refinance vs HELOC Calculator', href: '/calculators/finance/cash-out-refinance-vs-heloc-calculator', cat: 'finance', catLabel: 'Finance', kw: 'cash out refinance vs heloc calculator' },
  { name: 'CD Ladder Calculator', href: '/calculators/finance/cd-ladder-calculator', cat: 'finance', catLabel: 'Finance', kw: 'cd ladder calculator' },
  { name: 'CD vs HYSA Calculator', href: '/calculators/finance/cd-vs-hysa-calculator', cat: 'finance', catLabel: 'Finance', kw: 'cd vs hysa calculator' },
  { name: 'Closing Cost Calculator', href: '/calculators/finance/closing-cost-calculator', cat: 'finance', catLabel: 'Finance', kw: 'closing cost calculator' },
  { name: 'College Cost Calculator', href: '/calculators/finance/college-cost-calculator', cat: 'finance', catLabel: 'Finance', kw: 'college cost calculator' },
  { name: 'Compound Interest Calculator', href: '/calculators/finance/compound-interest-calculator', cat: 'finance', catLabel: 'Finance', kw: 'compound interest calculator' },
  { name: 'Credit Card Payoff Calculator', href: '/calculators/finance/credit-card-payoff-calculator', cat: 'finance', catLabel: 'Finance', kw: 'credit card payoff calculator' },
  { name: 'Crypto Profit Calculator', href: '/calculators/finance/crypto-profit-calculator', cat: 'finance', catLabel: 'Finance', kw: 'crypto profit calculator' },
  { name: 'Currency Converter', href: '/calculators/finance/currency-converter', cat: 'finance', catLabel: 'Finance', kw: 'currency converter' },
  { name: 'Currency Profit Calculator', href: '/calculators/finance/currency-profit-calculator', cat: 'finance', catLabel: 'Finance', kw: 'currency profit calculator' },
  { name: 'Debt Payoff Calculator', href: '/calculators/finance/debt-payoff-calculator', cat: 'finance', catLabel: 'Finance', kw: 'debt payoff calculator' },
  { name: 'Dividend Calculator', href: '/calculators/finance/dividend-calculator', cat: 'finance', catLabel: 'Finance', kw: 'dividend calculator' },
  { name: 'Dividend Growth vs Growth Stocks Calculator', href: '/calculators/finance/dividend-growth-vs-growth-stocks-calculator', cat: 'finance', catLabel: 'Finance', kw: 'dividend growth vs growth stocks calculator' },
  { name: 'Dollar Cost Averaging vs Lumpsum USA Calculator', href: '/calculators/finance/dollar-cost-averaging-vs-lumpsum-usa-calculator', cat: 'finance', catLabel: 'Finance', kw: 'dollar cost averaging vs lumpsum usa calculator' },
  { name: 'Down Payment Calculator', href: '/calculators/finance/down-payment-calculator', cat: 'finance', catLabel: 'Finance', kw: 'down payment calculator' },
  { name: 'Education Goal Calculator', href: '/calculators/finance/education-goal-calculator', cat: 'finance', catLabel: 'Finance', kw: 'education goal calculator' },
  { name: 'ELSS vs NPS Calculator', href: '/calculators/finance/elss-vs-nps-calculator', cat: 'finance', catLabel: 'Finance', kw: 'elss vs nps calculator' },
  { name: 'ELSS vs PPF Calculator', href: '/calculators/finance/elss-vs-ppf-calculator', cat: 'finance', catLabel: 'Finance', kw: 'elss vs ppf calculator' },
  { name: 'Emergency Fund Calculator', href: '/calculators/finance/emergency-fund-calculator', cat: 'finance', catLabel: 'Finance', kw: 'emergency fund calculator' },
  { name: 'EMI Calculator', href: '/calculators/finance/emi-calculator', cat: 'finance', catLabel: 'Finance', kw: 'emi calculator' },
  { name: 'EMI vs SIP Calculator', href: '/calculators/finance/emi-vs-sip-calculator', cat: 'finance', catLabel: 'Finance', kw: 'emi vs sip calculator' },
  { name: 'EPF vs NPS Calculator', href: '/calculators/finance/epf-vs-nps-calculator', cat: 'finance', catLabel: 'Finance', kw: 'epf vs nps calculator' },
  { name: 'Euro Auto Loan Calculator', href: '/calculators/finance/euro-auto-loan-calculator', cat: 'finance', catLabel: 'Finance', kw: 'euro auto loan calculator' },
  { name: 'Euro Bonds vs ETF Calculator', href: '/calculators/finance/euro-bonds-vs-etf-calculator', cat: 'finance', catLabel: 'Finance', kw: 'euro bonds vs etf calculator' },
  { name: 'Europe ETF vs Property Calculator', href: '/calculators/finance/europe-etf-vs-property-calculator', cat: 'finance', catLabel: 'Finance', kw: 'europe etf vs property calculator' },
  { name: 'Europe Growth vs Value ETF Calculator', href: '/calculators/finance/europe-growth-vs-value-etf-calculator', cat: 'finance', catLabel: 'Finance', kw: 'europe growth vs value etf calculator' },
  { name: 'Europe Msci World vs S&P500 Calculator', href: '/calculators/finance/europe-msci-world-vs-sp500-calculator', cat: 'finance', catLabel: 'Finance', kw: 'europe msci world vs sp500 calculator' },
  { name: 'Europe Property vs REIT Calculator', href: '/calculators/finance/europe-property-vs-reit-calculator', cat: 'finance', catLabel: 'Finance', kw: 'europe property vs reit calculator' },
  { name: 'European Mortgage Calculator', href: '/calculators/finance/european-mortgage-calculator', cat: 'finance', catLabel: 'Finance', kw: 'european mortgage calculator' },
  { name: 'FD Calculator', href: '/calculators/finance/fd-calculator', cat: 'finance', catLabel: 'Finance', kw: 'fd calculator' },
  { name: 'FD Comparison Calculator', href: '/calculators/finance/fd-comparison-calculator', cat: 'finance', catLabel: 'Finance', kw: 'fd comparison calculator' },
  { name: 'FIRE Calculator', href: '/calculators/finance/fire-calculator', cat: 'finance', catLabel: 'Finance', kw: 'fire calculator' },
  { name: 'FIRE Europe Calculator', href: '/calculators/finance/fire-europe-calculator', cat: 'finance', catLabel: 'Finance', kw: 'fire europe calculator' },
  { name: 'France PEA vs Assurance Vie Calculator', href: '/calculators/finance/france-pea-vs-assurance-vie-calculator', cat: 'finance', catLabel: 'Finance', kw: 'france pea vs assurance vie calculator' },
  { name: 'Germany ETF vs Tagesgeld Calculator', href: '/calculators/finance/germany-etf-vs-tagesgeld-calculator', cat: 'finance', catLabel: 'Finance', kw: 'germany etf vs tagesgeld calculator' },
  { name: 'Government Bond Calculator', href: '/calculators/finance/government-bond-calculator', cat: 'finance', catLabel: 'Finance', kw: 'government bond calculator' },
  { name: 'Gratuity Calculator', href: '/calculators/finance/gratuity-calculator', cat: 'finance', catLabel: 'Finance', kw: 'gratuity calculator' },
  { name: 'Gst Calculator', href: '/calculators/finance/gst-calculator', cat: 'finance', catLabel: 'Finance', kw: 'gst calculator' },
  { name: 'HELOC Calculator', href: '/calculators/finance/heloc-calculator', cat: 'finance', catLabel: 'Finance', kw: 'heloc calculator' },
  { name: 'Home Affordability Calculator', href: '/calculators/finance/home-affordability-calculator', cat: 'finance', catLabel: 'Finance', kw: 'home affordability calculator' },
  { name: 'Home Loan Calculator', href: '/calculators/finance/home-loan-calculator', cat: 'finance', catLabel: 'Finance', kw: 'home loan calculator' },
  { name: 'HRA Calculator', href: '/calculators/finance/hra-calculator', cat: 'finance', catLabel: 'Finance', kw: 'hra calculator' },
  { name: 'HSA vs FSA Calculator', href: '/calculators/finance/hsa-vs-fsa-calculator', cat: 'finance', catLabel: 'Finance', kw: 'hsa vs fsa calculator' },
  { name: 'I Bonds vs Tips Calculator', href: '/calculators/finance/i-bonds-vs-tips-calculator', cat: 'finance', catLabel: 'Finance', kw: 'i bonds vs tips calculator' },
  { name: 'Income Tax Calculator', href: '/calculators/finance/income-tax-calculator', cat: 'finance', catLabel: 'Finance', kw: 'income tax calculator' },
  { name: 'Index Fund vs ETF Calculator', href: '/calculators/finance/index-fund-vs-etf-calculator', cat: 'finance', catLabel: 'Finance', kw: 'index fund vs etf calculator' },
  { name: 'Inflation Calculator', href: '/calculators/finance/inflation-calculator', cat: 'finance', catLabel: 'Finance', kw: 'inflation calculator' },
  { name: 'Inflation Protected Bonds vs Stocks Calculator', href: '/calculators/finance/inflation-protected-bonds-vs-stocks-calculator', cat: 'finance', catLabel: 'Finance', kw: 'inflation protected bonds vs stocks calculator' },
  { name: 'Interest Rate Calculator', href: '/calculators/finance/interest-rate-calculator', cat: 'finance', catLabel: 'Finance', kw: 'interest rate calculator' },
  { name: 'Invoice Calculator', href: '/calculators/finance/invoice-calculator', cat: 'finance', catLabel: 'Finance', kw: 'invoice calculator' },
  { name: 'ISA Calculator', href: '/calculators/finance/isa-calculator', cat: 'finance', catLabel: 'Finance', kw: 'isa calculator' },
  { name: 'ISA vs SIPp UK Calculator', href: '/calculators/finance/isa-vs-sipp-uk-calculator', cat: 'finance', catLabel: 'Finance', kw: 'isa vs sipp uk calculator' },
  { name: 'Lease vs Buy Calculator', href: '/calculators/finance/lease-vs-buy-calculator', cat: 'finance', catLabel: 'Finance', kw: 'lease vs buy calculator' },
  { name: 'Loan Comparison Calculator', href: '/calculators/finance/loan-comparison-calculator', cat: 'finance', catLabel: 'Finance', kw: 'loan comparison calculator' },
  { name: 'Loan Prepayment Calculator', href: '/calculators/finance/loan-prepayment-calculator', cat: 'finance', catLabel: 'Finance', kw: 'loan prepayment calculator' },
  { name: 'Lumpsum Calculator', href: '/calculators/finance/lumpsum-calculator', cat: 'finance', catLabel: 'Finance', kw: 'lumpsum calculator' },
  { name: 'Lumpsum vs Gold Calculator', href: '/calculators/finance/lumpsum-vs-gold-calculator', cat: 'finance', catLabel: 'Finance', kw: 'lumpsum vs gold calculator' },
  { name: 'Lumpsum vs SIP Calculator', href: '/calculators/finance/lumpsum-vs-sip-calculator', cat: 'finance', catLabel: 'Finance', kw: 'lumpsum vs sip calculator' },
  { name: 'Medicare vs Private Insurance Calculator', href: '/calculators/finance/medicare-vs-private-insurance-calculator', cat: 'finance', catLabel: 'Finance', kw: 'medicare vs private insurance calculator' },
  { name: 'Mortgage Calculator', href: '/calculators/finance/mortgage-calculator', cat: 'finance', catLabel: 'Finance', kw: 'mortgage calculator' },
  { name: 'Mortgage Refinance Calculator', href: '/calculators/finance/mortgage-refinance-calculator', cat: 'finance', catLabel: 'Finance', kw: 'mortgage refinance calculator' },
  { name: 'Mortgage vs Renting USA Calculator', href: '/calculators/finance/mortgage-vs-renting-usa-calculator', cat: 'finance', catLabel: 'Finance', kw: 'mortgage vs renting usa calculator' },
  { name: 'Municipal Bonds vs Corporate Bonds Calculator', href: '/calculators/finance/municipal-bonds-vs-corporate-bonds-calculator', cat: 'finance', catLabel: 'Finance', kw: 'municipal bonds vs corporate bonds calculator' },
  { name: 'Mutual Fund Calculator', href: '/calculators/finance/mutual-fund-calculator', cat: 'finance', catLabel: 'Finance', kw: 'mutual fund calculator' },
  { name: 'Mutual Fund Return Calculator', href: '/calculators/finance/mutual-fund-return-calculator', cat: 'finance', catLabel: 'Finance', kw: 'mutual fund return calculator' },
  { name: 'Mutual Fund vs FD Calculator', href: '/calculators/finance/mutual-fund-vs-fd-calculator', cat: 'finance', catLabel: 'Finance', kw: 'mutual fund vs fd calculator' },
  { name: 'Net Worth Calculator', href: '/calculators/finance/net-worth-calculator', cat: 'finance', catLabel: 'Finance', kw: 'net worth calculator' },
  { name: 'Netherlands AOW vs Private Pension Calculator', href: '/calculators/finance/netherlands-aow-vs-private-pension-calculator', cat: 'finance', catLabel: 'Finance', kw: 'netherlands aow vs private pension calculator' },
  { name: 'NPS Calculator', href: '/calculators/finance/nps-calculator', cat: 'finance', catLabel: 'Finance', kw: 'nps calculator' },
  { name: 'NSC vs FD Calculator', href: '/calculators/finance/nsc-vs-fd-calculator', cat: 'finance', catLabel: 'Finance', kw: 'nsc vs fd calculator' },
  { name: 'NSC vs PPF Calculator', href: '/calculators/finance/nsc-vs-ppf-calculator', cat: 'finance', catLabel: 'Finance', kw: 'nsc vs ppf calculator' },
  { name: 'Offset Mortgage vs Savings UK Calculator', href: '/calculators/finance/offset-mortgage-vs-savings-uk-calculator', cat: 'finance', catLabel: 'Finance', kw: 'offset mortgage vs savings uk calculator' },
  { name: 'Pay Off Mortgage vs Invest Calculator', href: '/calculators/finance/pay-off-mortgage-vs-invest-calculator', cat: 'finance', catLabel: 'Finance', kw: 'pay off mortgage vs invest calculator' },
  { name: 'Paycheck Calculator', href: '/calculators/finance/paycheck-calculator', cat: 'finance', catLabel: 'Finance', kw: 'paycheck calculator' },
  { name: 'Payoff Date Calculator', href: '/calculators/finance/payoff-date-calculator', cat: 'finance', catLabel: 'Finance', kw: 'payoff date calculator' },
  { name: 'P/E Ratio Calculator', href: '/calculators/finance/pe-ratio-calculator', cat: 'finance', catLabel: 'Finance', kw: 'pe ratio calculator' },
  { name: 'Personal Loan Calculator', href: '/calculators/finance/personal-loan-calculator', cat: 'finance', catLabel: 'Finance', kw: 'personal loan calculator' },
  { name: 'PPF Calculator', href: '/calculators/finance/ppf-calculator', cat: 'finance', catLabel: 'Finance', kw: 'ppf calculator' },
  { name: 'PPF vs FD Calculator', href: '/calculators/finance/ppf-vs-fd-calculator', cat: 'finance', catLabel: 'Finance', kw: 'ppf vs fd calculator' },
  { name: 'PPF vs NPS Calculator', href: '/calculators/finance/ppf-vs-nps-calculator', cat: 'finance', catLabel: 'Finance', kw: 'ppf vs nps calculator' },
  { name: 'RD Calculator', href: '/calculators/finance/rd-calculator', cat: 'finance', catLabel: 'Finance', kw: 'rd calculator' },
  { name: 'Real Estate ROI Calculator', href: '/calculators/finance/real-estate-roi-calculator', cat: 'finance', catLabel: 'Finance', kw: 'real estate roi calculator' },
  { name: 'Real Return Calculator', href: '/calculators/finance/real-return-calculator', cat: 'finance', catLabel: 'Finance', kw: 'real return calculator' },
  { name: 'Refinance vs Invest Calculator', href: '/calculators/finance/refinance-vs-invest-calculator', cat: 'finance', catLabel: 'Finance', kw: 'refinance vs invest calculator' },
  { name: 'REIT vs Direct Property USA Calculator', href: '/calculators/finance/reit-vs-direct-property-usa-calculator', cat: 'finance', catLabel: 'Finance', kw: 'reit vs direct property usa calculator' },
  { name: 'Rent vs Buy Calculator', href: '/calculators/finance/rent-vs-buy-calculator', cat: 'finance', catLabel: 'Finance', kw: 'rent vs buy calculator' },
  { name: 'Rental Yield Calculator', href: '/calculators/finance/rental-yield-calculator', cat: 'finance', catLabel: 'Finance', kw: 'rental yield calculator' },
  { name: 'Retirement Calculator', href: '/calculators/finance/retirement-calculator', cat: 'finance', catLabel: 'Finance', kw: 'retirement calculator' },
  { name: 'ROI Calculator', href: '/calculators/finance/roi-calculator', cat: 'finance', catLabel: 'Finance', kw: 'roi calculator' },
  { name: 'Roth Conversion Calculator', href: '/calculators/finance/roth-conversion-calculator', cat: 'finance', catLabel: 'Finance', kw: 'roth conversion calculator' },
  { name: 'Roth IRA Calculator', href: '/calculators/finance/roth-ira-calculator', cat: 'finance', catLabel: 'Finance', kw: 'roth ira calculator' },
  { name: 'Roth IRA vs 401k Employer Match Calculator', href: '/calculators/finance/roth-ira-vs-401k-employer-match-calculator', cat: 'finance', catLabel: 'Finance', kw: 'roth ira vs 401k employer match calculator' },
  { name: 'Roth IRA vs HSA Calculator', href: '/calculators/finance/roth-ira-vs-hsa-calculator', cat: 'finance', catLabel: 'Finance', kw: 'roth ira vs hsa calculator' },
  { name: 'Roth IRA vs Traditional IRA Calculator', href: '/calculators/finance/roth-ira-vs-traditional-ira-calculator', cat: 'finance', catLabel: 'Finance', kw: 'roth ira vs traditional ira calculator' },
  { name: 'Salary Calculator', href: '/calculators/finance/salary-calculator', cat: 'finance', catLabel: 'Finance', kw: 'salary calculator' },
  { name: 'Salary Hike Calculator', href: '/calculators/finance/salary-hike-calculator', cat: 'finance', catLabel: 'Finance', kw: 'salary hike calculator' },
  { name: 'Savings Goal Calculator', href: '/calculators/finance/savings-goal-calculator', cat: 'finance', catLabel: 'Finance', kw: 'savings goal calculator' },
  { name: 'Savings Rate Calculator', href: '/calculators/finance/savings-rate-calculator', cat: 'finance', catLabel: 'Finance', kw: 'savings rate calculator' },
  { name: 'Senior Citizen Savings vs FD Calculator', href: '/calculators/finance/senior-citizen-savings-vs-fd-calculator', cat: 'finance', catLabel: 'Finance', kw: 'senior citizen savings vs fd calculator' },
  { name: 'Sep IRA vs Solo 401k Calculator', href: '/calculators/finance/sep-ira-vs-solo-401k-calculator', cat: 'finance', catLabel: 'Finance', kw: 'sep ira vs solo 401k calculator' },
  { name: 'Simple Interest Calculator', href: '/calculators/finance/simple-interest-calculator', cat: 'finance', catLabel: 'Finance', kw: 'simple interest calculator' },
  { name: 'SIP Calculator', href: '/calculators/finance/sip-calculator', cat: 'finance', catLabel: 'Finance', kw: 'sip calculator' },
  { name: 'SIP vs Bonds Calculator', href: '/calculators/finance/sip-vs-bonds-calculator', cat: 'finance', catLabel: 'Finance', kw: 'sip vs bonds calculator' },
  { name: 'SIP vs Crypto Calculator', href: '/calculators/finance/sip-vs-crypto-calculator', cat: 'finance', catLabel: 'Finance', kw: 'sip vs crypto calculator' },
  { name: 'SIP vs Endowment Calculator', href: '/calculators/finance/sip-vs-endowment-calculator', cat: 'finance', catLabel: 'Finance', kw: 'sip vs endowment calculator' },
  { name: 'SIP vs FD Calculator', href: '/calculators/finance/sip-vs-fd-calculator', cat: 'finance', catLabel: 'Finance', kw: 'sip vs fd calculator' },
  { name: 'SIP vs Gold Calculator', href: '/calculators/finance/sip-vs-gold-calculator', cat: 'finance', catLabel: 'Finance', kw: 'sip vs gold calculator' },
  { name: 'SIP vs Mutual Fund Direct Plan Calculator', href: '/calculators/finance/sip-vs-mutual-fund-direct-plan-calculator', cat: 'finance', catLabel: 'Finance', kw: 'sip vs mutual fund direct plan calculator' },
  { name: 'SIP vs NPS Calculator', href: '/calculators/finance/sip-vs-nps-calculator', cat: 'finance', catLabel: 'Finance', kw: 'sip vs nps calculator' },
  { name: 'SIP vs PPF Calculator', href: '/calculators/finance/sip-vs-ppf-calculator', cat: 'finance', catLabel: 'Finance', kw: 'sip vs ppf calculator' },
  { name: 'SIP vs RD Calculator', href: '/calculators/finance/sip-vs-rd-calculator', cat: 'finance', catLabel: 'Finance', kw: 'sip vs rd calculator' },
  { name: 'SIP vs Real Estate Calculator', href: '/calculators/finance/sip-vs-real-estate-calculator', cat: 'finance', catLabel: 'Finance', kw: 'sip vs real estate calculator' },
  { name: 'SIP vs Savings Account Calculator', href: '/calculators/finance/sip-vs-savings-account-calculator', cat: 'finance', catLabel: 'Finance', kw: 'sip vs savings account calculator' },
  { name: 'SIP vs Stocks Calculator', href: '/calculators/finance/sip-vs-stocks-calculator', cat: 'finance', catLabel: 'Finance', kw: 'sip vs stocks calculator' },
  { name: 'Social Security Calculator', href: '/calculators/finance/social-security-calculator', cat: 'finance', catLabel: 'Finance', kw: 'social security calculator' },
  { name: 'Social Security vs Private Pension Calculator', href: '/calculators/finance/social-security-vs-private-pension-calculator', cat: 'finance', catLabel: 'Finance', kw: 'social security vs private pension calculator' },
  { name: 'S&P500 vs Bonds Calculator', href: '/calculators/finance/sp500-vs-bonds-calculator', cat: 'finance', catLabel: 'Finance', kw: 'sp500 vs bonds calculator' },
  { name: 'S&P500 vs Real Estate USA Calculator', href: '/calculators/finance/sp500-vs-real-estate-usa-calculator', cat: 'finance', catLabel: 'Finance', kw: 'sp500 vs real estate usa calculator' },
  { name: 'Spain Pension vs ETF Calculator', href: '/calculators/finance/spain-pension-vs-etf-calculator', cat: 'finance', catLabel: 'Finance', kw: 'spain pension vs etf calculator' },
  { name: 'Step Up SIP Calculator', href: '/calculators/finance/step-up-sip-calculator', cat: 'finance', catLabel: 'Finance', kw: 'step up sip calculator' },
  { name: 'Stock Profit Calculator', href: '/calculators/finance/stock-profit-calculator', cat: 'finance', catLabel: 'Finance', kw: 'stock profit calculator' },
  { name: 'Stocks Shares ISA vs Cash ISA Calculator', href: '/calculators/finance/stocks-shares-isa-vs-cash-isa-calculator', cat: 'finance', catLabel: 'Finance', kw: 'stocks shares isa vs cash isa calculator' },
  { name: 'Student Loan Calculator', href: '/calculators/finance/student-loan-calculator', cat: 'finance', catLabel: 'Finance', kw: 'student loan calculator' },
  { name: 'Sukanya Samriddhi vs PPF Calculator', href: '/calculators/finance/sukanya-samriddhi-vs-ppf-calculator', cat: 'finance', catLabel: 'Finance', kw: 'sukanya samriddhi vs ppf calculator' },
  { name: 'SWP Calculator', href: '/calculators/finance/swp-calculator', cat: 'finance', catLabel: 'Finance', kw: 'swp calculator' },
  { name: 'Tax Bracket Calculator', href: '/calculators/finance/tax-bracket-calculator', cat: 'finance', catLabel: 'Finance', kw: 'tax bracket calculator' },
  { name: 'Term vs Ulip Calculator', href: '/calculators/finance/term-vs-ulip-calculator', cat: 'finance', catLabel: 'Finance', kw: 'term vs ulip calculator' },
  { name: 'Term vs Whole Life Calculator', href: '/calculators/finance/term-vs-whole-life-calculator', cat: 'finance', catLabel: 'Finance', kw: 'term vs whole life calculator' },
  { name: 'Tip Calculator', href: '/calculators/finance/tip-calculator', cat: 'finance', catLabel: 'Finance', kw: 'tip calculator' },
  { name: 'Traditional IRA vs Taxable Account Calculator', href: '/calculators/finance/traditional-ira-vs-taxable-account-calculator', cat: 'finance', catLabel: 'Finance', kw: 'traditional ira vs taxable account calculator' },
  { name: 'UK Buy to Let vs Stocks Calculator', href: '/calculators/finance/uk-buy-to-let-vs-stocks-calculator', cat: 'finance', catLabel: 'Finance', kw: 'uk buy to let vs stocks calculator' },
  { name: 'UK Fixed Rate vs Tracker Mortgage Calculator', href: '/calculators/finance/uk-fixed-rate-vs-tracker-mortgage-calculator', cat: 'finance', catLabel: 'Finance', kw: 'uk fixed rate vs tracker mortgage calculator' },
  { name: 'UK Help to Buy vs LISA Calculator', href: '/calculators/finance/uk-help-to-buy-vs-lisa-calculator', cat: 'finance', catLabel: 'Finance', kw: 'uk help to buy vs lisa calculator' },
  { name: 'UK Income Tax Calculator', href: '/calculators/finance/uk-income-tax-calculator', cat: 'finance', catLabel: 'Finance', kw: 'uk income tax calculator' },
  { name: 'UK Lifetime ISA vs SIPp Calculator', href: '/calculators/finance/uk-lifetime-isa-vs-sipp-calculator', cat: 'finance', catLabel: 'Finance', kw: 'uk lifetime isa vs sipp calculator' },
  { name: 'UK Pension Calculator', href: '/calculators/finance/uk-pension-calculator', cat: 'finance', catLabel: 'Finance', kw: 'uk pension calculator' },
  { name: 'UK Pension Drawdown vs Annuity Calculator', href: '/calculators/finance/uk-pension-drawdown-vs-annuity-calculator', cat: 'finance', catLabel: 'Finance', kw: 'uk pension drawdown vs annuity calculator' },
  { name: 'UK Pension vs ISA Calculator', href: '/calculators/finance/uk-pension-vs-isa-calculator', cat: 'finance', catLabel: 'Finance', kw: 'uk pension vs isa calculator' },
  { name: 'UK Premium Bonds vs Cash ISA Calculator', href: '/calculators/finance/uk-premium-bonds-vs-cash-isa-calculator', cat: 'finance', catLabel: 'Finance', kw: 'uk premium bonds vs cash isa calculator' },
  { name: 'UK Remortgage vs Invest Calculator', href: '/calculators/finance/uk-remortgage-vs-invest-calculator', cat: 'finance', catLabel: 'Finance', kw: 'uk remortgage vs invest calculator' },
  { name: 'UK Stamp Duty Calculator', href: '/calculators/finance/uk-stamp-duty-calculator', cat: 'finance', catLabel: 'Finance', kw: 'uk stamp duty calculator' },
  { name: 'UK Stocks vs Bonds Calculator', href: '/calculators/finance/uk-stocks-vs-bonds-calculator', cat: 'finance', catLabel: 'Finance', kw: 'uk stocks vs bonds calculator' },
  { name: 'Us Real Estate vs REITs Calculator', href: '/calculators/finance/us-real-estate-vs-reits-calculator', cat: 'finance', catLabel: 'Finance', kw: 'us real estate vs reits calculator' },
  { name: 'Vanguard vs Fidelity ETF Calculator', href: '/calculators/finance/vanguard-vs-fidelity-etf-calculator', cat: 'finance', catLabel: 'Finance', kw: 'vanguard vs fidelity etf calculator' },
  { name: 'Vat Calculator Europe', href: '/calculators/finance/vat-calculator-europe', cat: 'finance', catLabel: 'Finance', kw: 'vat calculator europe' },
  { name: 'Wealth Calculator', href: '/calculators/finance/wealth-calculator', cat: 'finance', catLabel: 'Finance', kw: 'wealth calculator' },
  { name: 'Weekly Budget Calculator', href: '/calculators/finance/weekly-budget-calculator', cat: 'finance', catLabel: 'Finance', kw: 'weekly budget calculator' },
  { name: 'Whole Market vs S&P500 Calculator', href: '/calculators/finance/whole-market-vs-sp500-calculator', cat: 'finance', catLabel: 'Finance', kw: 'whole market vs sp500 calculator' },
  { name: 'XIRR Calculator', href: '/calculators/finance/xirr-calculator', cat: 'finance', catLabel: 'Finance', kw: 'xirr calculator' },
  { name: 'Age Calculator', href: '/calculators/health/age-calculator', cat: 'health', catLabel: 'Health', kw: 'age calculator' },
  { name: 'Air Quality Health Calculator', href: '/calculators/health/air-quality-health-calculator', cat: 'health', catLabel: 'Health', kw: 'air quality health calculator' },
  { name: 'Alcohol Calorie Calculator', href: '/calculators/health/alcohol-calorie-calculator', cat: 'health', catLabel: 'Health', kw: 'alcohol calorie calculator' },
  { name: 'Alcohol Metabolism Calculator', href: '/calculators/health/alcohol-metabolism-calculator', cat: 'health', catLabel: 'Health', kw: 'alcohol metabolism calculator' },
  { name: 'Altitude Sickness Calculator', href: '/calculators/health/altitude-sickness-calculator', cat: 'health', catLabel: 'Health', kw: 'altitude sickness calculator' },
  { name: 'Army Body Fat Calculator', href: '/calculators/health/army-body-fat-calculator', cat: 'health', catLabel: 'Health', kw: 'army body fat calculator' },
  { name: 'Athletic Performance Calculator', href: '/calculators/health/athletic-performance-calculator', cat: 'health', catLabel: 'Health', kw: 'athletic performance calculator' },
  { name: 'Bac Calculator', href: '/calculators/health/bac-calculator', cat: 'health', catLabel: 'Health', kw: 'bac calculator' },
  { name: 'Blood Pressure Calculator', href: '/calculators/health/blood-pressure-calculator', cat: 'health', catLabel: 'Health', kw: 'blood pressure calculator' },
  { name: 'Blue Light Exposure Calculator', href: '/calculators/health/blue-light-exposure-calculator', cat: 'health', catLabel: 'Health', kw: 'blue light exposure calculator' },
  { name: 'Bmi Calculator', href: '/calculators/health/bmi-calculator', cat: 'health', catLabel: 'Health', kw: 'bmi calculator' },
  { name: 'Bmi for Children Calculator', href: '/calculators/health/bmi-for-children-calculator', cat: 'health', catLabel: 'Health', kw: 'bmi for children calculator' },
  { name: 'Bmr Calculator', href: '/calculators/health/bmr-calculator', cat: 'health', catLabel: 'Health', kw: 'bmr calculator' },
  { name: 'Body Age Calculator', href: '/calculators/health/body-age-calculator', cat: 'health', catLabel: 'Health', kw: 'body age calculator' },
  { name: 'Body Fat Calculator', href: '/calculators/health/body-fat-calculator', cat: 'health', catLabel: 'Health', kw: 'body fat calculator' },
  { name: 'Body Recomposition Calculator', href: '/calculators/health/body-recomposition-calculator', cat: 'health', catLabel: 'Health', kw: 'body recomposition calculator' },
  { name: 'Body Surface Area Calculator', href: '/calculators/health/body-surface-area-calculator', cat: 'health', catLabel: 'Health', kw: 'body surface area calculator' },
  { name: 'Breastfeeding Calorie Calculator', href: '/calculators/health/breastfeeding-calorie-calculator', cat: 'health', catLabel: 'Health', kw: 'breastfeeding calorie calculator' },
  { name: 'Breathing Exercise Calculator', href: '/calculators/health/breathing-exercise-calculator', cat: 'health', catLabel: 'Health', kw: 'breathing exercise calculator' },
  { name: 'Caffeine Half Life Calculator', href: '/calculators/health/caffeine-half-life-calculator', cat: 'health', catLabel: 'Health', kw: 'caffeine half life calculator' },
  { name: 'Calcium Calculator', href: '/calculators/health/calcium-calculator', cat: 'health', catLabel: 'Health', kw: 'calcium calculator' },
  { name: 'Calorie Burned Walking Calculator', href: '/calculators/health/calorie-burned-walking-calculator', cat: 'health', catLabel: 'Health', kw: 'calorie burned walking calculator' },
  { name: 'Calorie Calculator', href: '/calculators/health/calorie-calculator', cat: 'health', catLabel: 'Health', kw: 'calorie calculator' },
  { name: 'Calorie Deficit Calculator', href: '/calculators/health/calorie-deficit-calculator', cat: 'health', catLabel: 'Health', kw: 'calorie deficit calculator' },
  { name: 'Calories Burned Calculator', href: '/calculators/health/calories-burned-calculator', cat: 'health', catLabel: 'Health', kw: 'calories burned calculator' },
  { name: 'Cholesterol Calculator', href: '/calculators/health/cholesterol-calculator', cat: 'health', catLabel: 'Health', kw: 'cholesterol calculator' },
  { name: 'Cold Exposure Calculator', href: '/calculators/health/cold-exposure-calculator', cat: 'health', catLabel: 'Health', kw: 'cold exposure calculator' },
  { name: 'Cold Shower Benefits Calculator', href: '/calculators/health/cold-shower-benefits-calculator', cat: 'health', catLabel: 'Health', kw: 'cold shower benefits calculator' },
  { name: 'Cortisol Stress Calculator', href: '/calculators/health/cortisol-stress-calculator', cat: 'health', catLabel: 'Health', kw: 'cortisol stress calculator' },
  { name: 'Creatine Dosage Calculator', href: '/calculators/health/creatine-dosage-calculator', cat: 'health', catLabel: 'Health', kw: 'creatine dosage calculator' },
  { name: 'Creatinine Clearance Calculator', href: '/calculators/health/creatinine-clearance-calculator', cat: 'health', catLabel: 'Health', kw: 'creatinine clearance calculator' },
  { name: 'Cycling Calories Calculator', href: '/calculators/health/cycling-calories-calculator', cat: 'health', catLabel: 'Health', kw: 'cycling calories calculator' },
  { name: 'Dehydration Calculator', href: '/calculators/health/dehydration-calculator', cat: 'health', catLabel: 'Health', kw: 'dehydration calculator' },
  { name: 'Dental Health Calculator', href: '/calculators/health/dental-health-calculator', cat: 'health', catLabel: 'Health', kw: 'dental health calculator' },
  { name: 'Diabetes Risk Calculator', href: '/calculators/health/diabetes-risk-calculator', cat: 'health', catLabel: 'Health', kw: 'diabetes risk calculator' },
  { name: 'Due Date Calculator', href: '/calculators/health/due-date-calculator', cat: 'health', catLabel: 'Health', kw: 'due date calculator' },
  { name: 'Ergonomics Score Calculator', href: '/calculators/health/ergonomics-score-calculator', cat: 'health', catLabel: 'Health', kw: 'ergonomics score calculator' },
  { name: 'Eye Health Calculator', href: '/calculators/health/eye-health-calculator', cat: 'health', catLabel: 'Health', kw: 'eye health calculator' },
  { name: 'Fasting Window Calculator', href: '/calculators/health/fasting-window-calculator', cat: 'health', catLabel: 'Health', kw: 'fasting window calculator' },
  { name: 'Fat Loss Rate Calculator', href: '/calculators/health/fat-loss-rate-calculator', cat: 'health', catLabel: 'Health', kw: 'fat loss rate calculator' },
  { name: 'Fiber Intake Calculator', href: '/calculators/health/fiber-intake-calculator', cat: 'health', catLabel: 'Health', kw: 'fiber intake calculator' },
  { name: 'Flexibility Calculator', href: '/calculators/health/flexibility-calculator', cat: 'health', catLabel: 'Health', kw: 'flexibility calculator' },
  { name: 'Glycemic Load Calculator', href: '/calculators/health/glycemic-load-calculator', cat: 'health', catLabel: 'Health', kw: 'glycemic load calculator' },
  { name: 'Gratitude Health Calculator', href: '/calculators/health/gratitude-health-calculator', cat: 'health', catLabel: 'Health', kw: 'gratitude health calculator' },
  { name: 'Grip Strength Calculator', href: '/calculators/health/grip-strength-calculator', cat: 'health', catLabel: 'Health', kw: 'grip strength calculator' },
  { name: 'Gut Health Calculator', href: '/calculators/health/gut-health-calculator', cat: 'health', catLabel: 'Health', kw: 'gut health calculator' },
  { name: 'Hangover Recovery Calculator', href: '/calculators/health/hangover-recovery-calculator', cat: 'health', catLabel: 'Health', kw: 'hangover recovery calculator' },
  { name: 'Hearing Age Calculator', href: '/calculators/health/hearing-age-calculator', cat: 'health', catLabel: 'Health', kw: 'hearing age calculator' },
  { name: 'Heart Age Calculator', href: '/calculators/health/heart-age-calculator', cat: 'health', catLabel: 'Health', kw: 'heart age calculator' },
  { name: 'Heart Attack Risk Calculator', href: '/calculators/health/heart-attack-risk-calculator', cat: 'health', catLabel: 'Health', kw: 'heart attack risk calculator' },
  { name: 'Heart Rate Calculator', href: '/calculators/health/heart-rate-calculator', cat: 'health', catLabel: 'Health', kw: 'heart rate calculator' },
  { name: 'Hiit Calculator', href: '/calculators/health/hiit-calculator', cat: 'health', catLabel: 'Health', kw: 'hiit calculator' },
  { name: 'Hydration Calculator', href: '/calculators/health/hydration-calculator', cat: 'health', catLabel: 'Health', kw: 'hydration calculator' },
  { name: 'Ideal Weight Calculator', href: '/calculators/health/ideal-weight-calculator', cat: 'health', catLabel: 'Health', kw: 'ideal weight calculator' },
  { name: 'Immune Health Calculator', href: '/calculators/health/immune-health-calculator', cat: 'health', catLabel: 'Health', kw: 'immune health calculator' },
  { name: 'Infant Weight Percentile Calculator', href: '/calculators/health/infant-weight-percentile-calculator', cat: 'health', catLabel: 'Health', kw: 'infant weight percentile calculator' },
  { name: 'Inflammation Risk Calculator', href: '/calculators/health/inflammation-risk-calculator', cat: 'health', catLabel: 'Health', kw: 'inflammation risk calculator' },
  { name: 'Injury Recovery Calculator', href: '/calculators/health/injury-recovery-calculator', cat: 'health', catLabel: 'Health', kw: 'injury recovery calculator' },
  { name: 'Intermittent Fasting Calculator', href: '/calculators/health/intermittent-fasting-calculator', cat: 'health', catLabel: 'Health', kw: 'intermittent fasting calculator' },
  { name: 'Iron Intake Calculator', href: '/calculators/health/iron-intake-calculator', cat: 'health', catLabel: 'Health', kw: 'iron intake calculator' },
  { name: 'Jet Lag Calculator', href: '/calculators/health/jet-lag-calculator', cat: 'health', catLabel: 'Health', kw: 'jet lag calculator' },
  { name: 'Keto Macro Calculator', href: '/calculators/health/keto-macro-calculator', cat: 'health', catLabel: 'Health', kw: 'keto macro calculator' },
  { name: 'Kidney Function Calculator', href: '/calculators/health/kidney-function-calculator', cat: 'health', catLabel: 'Health', kw: 'kidney function calculator' },
  { name: 'Lean Body Mass Calculator', href: '/calculators/health/lean-body-mass-calculator', cat: 'health', catLabel: 'Health', kw: 'lean body mass calculator' },
  { name: 'Liver Health Calculator', href: '/calculators/health/liver-health-calculator', cat: 'health', catLabel: 'Health', kw: 'liver health calculator' },
  { name: 'Loneliness Health Calculator', href: '/calculators/health/loneliness-health-calculator', cat: 'health', catLabel: 'Health', kw: 'loneliness health calculator' },
  { name: 'Longevity Calculator', href: '/calculators/health/longevity-calculator', cat: 'health', catLabel: 'Health', kw: 'longevity calculator' },
  { name: 'Macro Calculator', href: '/calculators/health/macro-calculator', cat: 'health', catLabel: 'Health', kw: 'macro calculator' },
  { name: 'Magnesium Calculator', href: '/calculators/health/magnesium-calculator', cat: 'health', catLabel: 'Health', kw: 'magnesium calculator' },
  { name: 'Marathon Training Calculator', href: '/calculators/health/marathon-training-calculator', cat: 'health', catLabel: 'Health', kw: 'marathon training calculator' },
  { name: 'Meal Timing Calculator', href: '/calculators/health/meal-timing-calculator', cat: 'health', catLabel: 'Health', kw: 'meal timing calculator' },
  { name: 'Meditation Benefits Calculator', href: '/calculators/health/meditation-benefits-calculator', cat: 'health', catLabel: 'Health', kw: 'meditation benefits calculator' },
  { name: 'Menopause Symptom Calculator', href: '/calculators/health/menopause-symptom-calculator', cat: 'health', catLabel: 'Health', kw: 'menopause symptom calculator' },
  { name: 'Menstrual Cycle Calculator', href: '/calculators/health/menstrual-cycle-calculator', cat: 'health', catLabel: 'Health', kw: 'menstrual cycle calculator' },
  { name: 'Mental Health Score Calculator', href: '/calculators/health/mental-health-score-calculator', cat: 'health', catLabel: 'Health', kw: 'mental health score calculator' },
  { name: 'Mold Exposure Calculator', href: '/calculators/health/mold-exposure-calculator', cat: 'health', catLabel: 'Health', kw: 'mold exposure calculator' },
  { name: 'Muscle Gain Calculator', href: '/calculators/health/muscle-gain-calculator', cat: 'health', catLabel: 'Health', kw: 'muscle gain calculator' },
  { name: 'Nicotine Withdrawal Calculator', href: '/calculators/health/nicotine-withdrawal-calculator', cat: 'health', catLabel: 'Health', kw: 'nicotine withdrawal calculator' },
  { name: 'Omega3 Calculator', href: '/calculators/health/omega3-calculator', cat: 'health', catLabel: 'Health', kw: 'omega3 calculator' },
  { name: 'One Rep Max Calculator', href: '/calculators/health/one-rep-max-calculator', cat: 'health', catLabel: 'Health', kw: 'one rep max calculator' },
  { name: 'Ovulation Calculator', href: '/calculators/health/ovulation-calculator', cat: 'health', catLabel: 'Health', kw: 'ovulation calculator' },
  { name: 'Pace Calculator', href: '/calculators/health/pace-calculator', cat: 'health', catLabel: 'Health', kw: 'pace calculator' },
  { name: 'Plank Time Calculator', href: '/calculators/health/plank-time-calculator', cat: 'health', catLabel: 'Health', kw: 'plank time calculator' },
  { name: 'Posture Calculator', href: '/calculators/health/posture-calculator', cat: 'health', catLabel: 'Health', kw: 'posture calculator' },
  { name: 'Pregnancy Calculator', href: '/calculators/health/pregnancy-calculator', cat: 'health', catLabel: 'Health', kw: 'pregnancy calculator' },
  { name: 'Pregnancy Conception Calculator', href: '/calculators/health/pregnancy-conception-calculator', cat: 'health', catLabel: 'Health', kw: 'pregnancy conception calculator' },
  { name: 'Pregnancy Due Date Calculator', href: '/calculators/health/pregnancy-due-date-calculator', cat: 'health', catLabel: 'Health', kw: 'pregnancy due date calculator' },
  { name: 'Pregnancy Nutrition Calculator', href: '/calculators/health/pregnancy-nutrition-calculator', cat: 'health', catLabel: 'Health', kw: 'pregnancy nutrition calculator' },
  { name: 'Pregnancy Weight Gain Calculator', href: '/calculators/health/pregnancy-weight-gain-calculator', cat: 'health', catLabel: 'Health', kw: 'pregnancy weight gain calculator' },
  { name: 'Protein Intake Calculator', href: '/calculators/health/protein-intake-calculator', cat: 'health', catLabel: 'Health', kw: 'protein intake calculator' },
  { name: 'Protein Per Meal Calculator', href: '/calculators/health/protein-per-meal-calculator', cat: 'health', catLabel: 'Health', kw: 'protein per meal calculator' },
  { name: 'Pull Up Calculator', href: '/calculators/health/pull-up-calculator', cat: 'health', catLabel: 'Health', kw: 'pull up calculator' },
  { name: 'Pushup Calculator', href: '/calculators/health/pushup-calculator', cat: 'health', catLabel: 'Health', kw: 'pushup calculator' },
  { name: 'Resting Metabolic Rate Calculator', href: '/calculators/health/resting-metabolic-rate-calculator', cat: 'health', catLabel: 'Health', kw: 'resting metabolic rate calculator' },
  { name: 'Running Pace Calculator', href: '/calculators/health/running-pace-calculator', cat: 'health', catLabel: 'Health', kw: 'running pace calculator' },
  { name: 'Sauna Benefits Calculator', href: '/calculators/health/sauna-benefits-calculator', cat: 'health', catLabel: 'Health', kw: 'sauna benefits calculator' },
  { name: 'Shift Work Health Calculator', href: '/calculators/health/shift-work-health-calculator', cat: 'health', catLabel: 'Health', kw: 'shift work health calculator' },
  { name: 'Sit and Reach Calculator', href: '/calculators/health/sit-and-reach-calculator', cat: 'health', catLabel: 'Health', kw: 'sit and reach calculator' },
  { name: 'Skin Health Calculator', href: '/calculators/health/skin-health-calculator', cat: 'health', catLabel: 'Health', kw: 'skin health calculator' },
  { name: 'Sleep Cycle Calculator', href: '/calculators/health/sleep-cycle-calculator', cat: 'health', catLabel: 'Health', kw: 'sleep cycle calculator' },
  { name: 'Sleep Need Calculator', href: '/calculators/health/sleep-need-calculator', cat: 'health', catLabel: 'Health', kw: 'sleep need calculator' },
  { name: 'Sodium Intake Calculator', href: '/calculators/health/sodium-intake-calculator', cat: 'health', catLabel: 'Health', kw: 'sodium intake calculator' },
  { name: 'Sprint Calculator', href: '/calculators/health/sprint-calculator', cat: 'health', catLabel: 'Health', kw: 'sprint calculator' },
  { name: 'Squat Calculator', href: '/calculators/health/squat-calculator', cat: 'health', catLabel: 'Health', kw: 'squat calculator' },
  { name: 'Standing Desk Calculator', href: '/calculators/health/standing-desk-calculator', cat: 'health', catLabel: 'Health', kw: 'standing desk calculator' },
  { name: 'Steps Calculator', href: '/calculators/health/steps-calculator', cat: 'health', catLabel: 'Health', kw: 'steps calculator' },
  { name: 'Steps to Calories Calculator', href: '/calculators/health/steps-to-calories-calculator', cat: 'health', catLabel: 'Health', kw: 'steps to calories calculator' },
  { name: 'Stress Level Calculator', href: '/calculators/health/stress-level-calculator', cat: 'health', catLabel: 'Health', kw: 'stress level calculator' },
  { name: 'Stroke Risk Calculator', href: '/calculators/health/stroke-risk-calculator', cat: 'health', catLabel: 'Health', kw: 'stroke risk calculator' },
  { name: 'Sugar Intake Calculator', href: '/calculators/health/sugar-intake-calculator', cat: 'health', catLabel: 'Health', kw: 'sugar intake calculator' },
  { name: 'Sweat Rate Calculator', href: '/calculators/health/sweat-rate-calculator', cat: 'health', catLabel: 'Health', kw: 'sweat rate calculator' },
  { name: 'Swimming Calories Calculator', href: '/calculators/health/swimming-calories-calculator', cat: 'health', catLabel: 'Health', kw: 'swimming calories calculator' },
  { name: 'Target Weight Calculator', href: '/calculators/health/target-weight-calculator', cat: 'health', catLabel: 'Health', kw: 'target weight calculator' },
  { name: 'Tdee Calculator', href: '/calculators/health/tdee-calculator', cat: 'health', catLabel: 'Health', kw: 'tdee calculator' },
  { name: 'Testosterone Age Calculator', href: '/calculators/health/testosterone-age-calculator', cat: 'health', catLabel: 'Health', kw: 'testosterone age calculator' },
  { name: 'Thyroid Calculator', href: '/calculators/health/thyroid-calculator', cat: 'health', catLabel: 'Health', kw: 'thyroid calculator' },
  { name: 'Uv Exposure Calculator', href: '/calculators/health/uv-exposure-calculator', cat: 'health', catLabel: 'Health', kw: 'uv exposure calculator' },
  { name: 'Vitamin C Calculator', href: '/calculators/health/vitamin-c-calculator', cat: 'health', catLabel: 'Health', kw: 'vitamin c calculator' },
  { name: 'Vitamin D Calculator', href: '/calculators/health/vitamin-d-calculator', cat: 'health', catLabel: 'Health', kw: 'vitamin d calculator' },
  { name: 'Vo2 Max Calculator', href: '/calculators/health/vo2-max-calculator', cat: 'health', catLabel: 'Health', kw: 'vo2 max calculator' },
  { name: 'Waist to Height Ratio Calculator', href: '/calculators/health/waist-to-height-ratio-calculator', cat: 'health', catLabel: 'Health', kw: 'waist to height ratio calculator' },
  { name: 'Water Intake Calculator', href: '/calculators/health/water-intake-calculator', cat: 'health', catLabel: 'Health', kw: 'water intake calculator' },
  { name: 'Yoga Calories Calculator', href: '/calculators/health/yoga-calories-calculator', cat: 'health', catLabel: 'Health', kw: 'yoga calories calculator' },
  { name: 'Zinc Calculator', href: '/calculators/health/zinc-calculator', cat: 'health', catLabel: 'Health', kw: 'zinc calculator' },
  { name: 'Api Response Time', href: '/calculators/dev/api-response-time', cat: 'dev', catLabel: 'Dev Tools', kw: 'api response time' },
  { name: 'Aspect Ratio Tool', href: '/calculators/dev/aspect-ratio-calculator', cat: 'dev', catLabel: 'Dev Tools', kw: 'aspect ratio calculator' },
  { name: 'Bandwidth Tool', href: '/calculators/dev/bandwidth-calculator', cat: 'dev', catLabel: 'Dev Tools', kw: 'bandwidth calculator' },
  { name: 'Base Converter', href: '/calculators/dev/base-converter', cat: 'dev', catLabel: 'Dev Tools', kw: 'base converter' },
  { name: 'Base64 Encoder', href: '/calculators/dev/base64-encoder', cat: 'dev', catLabel: 'Dev Tools', kw: 'base64 encoder' },
  { name: 'Binary Text Converter', href: '/calculators/dev/binary-text-converter', cat: 'dev', catLabel: 'Dev Tools', kw: 'binary text converter' },
  { name: 'Bit Byte Converter', href: '/calculators/dev/bit-byte-converter', cat: 'dev', catLabel: 'Dev Tools', kw: 'bit byte converter' },
  { name: 'Bitwise Tool', href: '/calculators/dev/bitwise-calculator', cat: 'dev', catLabel: 'Dev Tools', kw: 'bitwise calculator' },
  { name: 'Border Radius Gen', href: '/calculators/dev/border-radius-gen', cat: 'dev', catLabel: 'Dev Tools', kw: 'border radius gen' },
  { name: 'Box Shadow Generator', href: '/calculators/dev/box-shadow-generator', cat: 'dev', catLabel: 'Dev Tools', kw: 'box shadow generator' },
  { name: 'Character Encoder', href: '/calculators/dev/character-encoder', cat: 'dev', catLabel: 'Dev Tools', kw: 'character encoder' },
  { name: 'Chmod Tool', href: '/calculators/dev/chmod-calculator', cat: 'dev', catLabel: 'Dev Tools', kw: 'chmod calculator' },
  { name: 'Cidr Tool', href: '/calculators/dev/cidr-calculator', cat: 'dev', catLabel: 'Dev Tools', kw: 'cidr calculator' },
  { name: 'Code Minifier', href: '/calculators/dev/code-minifier', cat: 'dev', catLabel: 'Dev Tools', kw: 'code minifier' },
  { name: 'Color Contrast', href: '/calculators/dev/color-contrast', cat: 'dev', catLabel: 'Dev Tools', kw: 'color contrast' },
  { name: 'Color Converter', href: '/calculators/dev/color-converter', cat: 'dev', catLabel: 'Dev Tools', kw: 'color converter' },
  { name: 'Color Palette', href: '/calculators/dev/color-palette', cat: 'dev', catLabel: 'Dev Tools', kw: 'color palette' },
  { name: 'Cron Expression', href: '/calculators/dev/cron-expression', cat: 'dev', catLabel: 'Dev Tools', kw: 'cron expression' },
  { name: 'Css Animation Gen', href: '/calculators/dev/css-animation-gen', cat: 'dev', catLabel: 'Dev Tools', kw: 'css animation gen' },
  { name: 'Css Clip Path', href: '/calculators/dev/css-clip-path', cat: 'dev', catLabel: 'Dev Tools', kw: 'css clip path' },
  { name: 'Css Filter Gen', href: '/calculators/dev/css-filter-gen', cat: 'dev', catLabel: 'Dev Tools', kw: 'css filter gen' },
  { name: 'Css Gradient Generator', href: '/calculators/dev/css-gradient-generator', cat: 'dev', catLabel: 'Dev Tools', kw: 'css gradient generator' },
  { name: 'Css Specificity', href: '/calculators/dev/css-specificity', cat: 'dev', catLabel: 'Dev Tools', kw: 'css specificity' },
  { name: 'Css Unit Converter', href: '/calculators/dev/css-unit-converter', cat: 'dev', catLabel: 'Dev Tools', kw: 'css unit converter' },
  { name: 'Csv to Json', href: '/calculators/dev/csv-to-json', cat: 'dev', catLabel: 'Dev Tools', kw: 'csv to json' },
  { name: 'Curl Builder', href: '/calculators/dev/curl-builder', cat: 'dev', catLabel: 'Dev Tools', kw: 'curl builder' },
  { name: 'Diff Checker', href: '/calculators/dev/diff-checker', cat: 'dev', catLabel: 'Dev Tools', kw: 'diff checker' },
  { name: 'Docker Compose Gen', href: '/calculators/dev/docker-compose-gen', cat: 'dev', catLabel: 'Dev Tools', kw: 'docker compose gen' },
  { name: 'Duplicate Remover', href: '/calculators/dev/duplicate-remover', cat: 'dev', catLabel: 'Dev Tools', kw: 'duplicate remover' },
  { name: 'Env File Parser', href: '/calculators/dev/env-file-parser', cat: 'dev', catLabel: 'Dev Tools', kw: 'env file parser' },
  { name: 'Epoch Converter', href: '/calculators/dev/epoch-converter', cat: 'dev', catLabel: 'Dev Tools', kw: 'epoch converter' },
  { name: 'Fake Data Generator', href: '/calculators/dev/fake-data-generator', cat: 'dev', catLabel: 'Dev Tools', kw: 'fake data generator' },
  { name: 'Favicon Generator', href: '/calculators/dev/favicon-generator', cat: 'dev', catLabel: 'Dev Tools', kw: 'favicon generator' },
  { name: 'Flex Generator', href: '/calculators/dev/flex-generator', cat: 'dev', catLabel: 'Dev Tools', kw: 'flex generator' },
  { name: 'Font Size Tool', href: '/calculators/dev/font-size-calculator', cat: 'dev', catLabel: 'Dev Tools', kw: 'font size calculator' },
  { name: 'Git Commit Gen', href: '/calculators/dev/git-commit-gen', cat: 'dev', catLabel: 'Dev Tools', kw: 'git commit gen' },
  { name: 'Gitignore Generator', href: '/calculators/dev/gitignore-generator', cat: 'dev', catLabel: 'Dev Tools', kw: 'gitignore generator' },
  { name: 'Graphql Formatter', href: '/calculators/dev/graphql-formatter', cat: 'dev', catLabel: 'Dev Tools', kw: 'graphql formatter' },
  { name: 'Grid Generator', href: '/calculators/dev/grid-generator', cat: 'dev', catLabel: 'Dev Tools', kw: 'grid generator' },
  { name: 'Hash Generator', href: '/calculators/dev/hash-generator', cat: 'dev', catLabel: 'Dev Tools', kw: 'hash generator' },
  { name: 'Htaccess Generator', href: '/calculators/dev/htaccess-generator', cat: 'dev', catLabel: 'Dev Tools', kw: 'htaccess generator' },
  { name: 'Html Encoder', href: '/calculators/dev/html-encoder', cat: 'dev', catLabel: 'Dev Tools', kw: 'html encoder' },
  { name: 'Html Entity Ref', href: '/calculators/dev/html-entity-ref', cat: 'dev', catLabel: 'Dev Tools', kw: 'html entity ref' },
  { name: 'Html to Markdown', href: '/calculators/dev/html-to-markdown', cat: 'dev', catLabel: 'Dev Tools', kw: 'html to markdown' },
  { name: 'Html Validator', href: '/calculators/dev/html-validator', cat: 'dev', catLabel: 'Dev Tools', kw: 'html validator' },
  { name: 'Http Headers Analyzer', href: '/calculators/dev/http-headers-analyzer', cat: 'dev', catLabel: 'Dev Tools', kw: 'http headers analyzer' },
  { name: 'Http Status Codes', href: '/calculators/dev/http-status-codes', cat: 'dev', catLabel: 'Dev Tools', kw: 'http status codes' },
  { name: 'Image Base64', href: '/calculators/dev/image-base64', cat: 'dev', catLabel: 'Dev Tools', kw: 'image base64' },
  { name: 'Ip Subnet Tool', href: '/calculators/dev/ip-subnet-calculator', cat: 'dev', catLabel: 'Dev Tools', kw: 'ip subnet calculator' },
  { name: 'Json Formatter', href: '/calculators/dev/json-formatter', cat: 'dev', catLabel: 'Dev Tools', kw: 'json formatter' },
  { name: 'Json Path Tester', href: '/calculators/dev/json-path-tester', cat: 'dev', catLabel: 'Dev Tools', kw: 'json path tester' },
  { name: 'Json Schema Gen', href: '/calculators/dev/json-schema-gen', cat: 'dev', catLabel: 'Dev Tools', kw: 'json schema gen' },
  { name: 'Json to Csv', href: '/calculators/dev/json-to-csv', cat: 'dev', catLabel: 'Dev Tools', kw: 'json to csv' },
  { name: 'Jwt Decoder', href: '/calculators/dev/jwt-decoder', cat: 'dev', catLabel: 'Dev Tools', kw: 'jwt decoder' },
  { name: 'Line Sorter', href: '/calculators/dev/line-sorter', cat: 'dev', catLabel: 'Dev Tools', kw: 'line sorter' },
  { name: 'Lorem Ipsum Generator', href: '/calculators/dev/lorem-ipsum-generator', cat: 'dev', catLabel: 'Dev Tools', kw: 'lorem ipsum generator' },
  { name: 'Markdown Preview', href: '/calculators/dev/markdown-preview', cat: 'dev', catLabel: 'Dev Tools', kw: 'markdown preview' },
  { name: 'Markdown Table Gen', href: '/calculators/dev/markdown-table-gen', cat: 'dev', catLabel: 'Dev Tools', kw: 'markdown table gen' },
  { name: 'Meta Tag Generator', href: '/calculators/dev/meta-tag-generator', cat: 'dev', catLabel: 'Dev Tools', kw: 'meta tag generator' },
  { name: 'Mime Type Lookup', href: '/calculators/dev/mime-type-lookup', cat: 'dev', catLabel: 'Dev Tools', kw: 'mime type lookup' },
  { name: 'Network Speed Test', href: '/calculators/dev/network-speed-test', cat: 'dev', catLabel: 'Dev Tools', kw: 'network speed test' },
  { name: 'Npm Package Search', href: '/calculators/dev/npm-package-search', cat: 'dev', catLabel: 'Dev Tools', kw: 'npm package search' },
  { name: 'Number Formatter', href: '/calculators/dev/number-formatter', cat: 'dev', catLabel: 'Dev Tools', kw: 'number formatter' },
  { name: 'Open Graph Preview', href: '/calculators/dev/open-graph-preview', cat: 'dev', catLabel: 'Dev Tools', kw: 'open graph preview' },
  { name: 'Package Json Gen', href: '/calculators/dev/package-json-gen', cat: 'dev', catLabel: 'Dev Tools', kw: 'package json gen' },
  { name: 'Password Generator', href: '/calculators/dev/password-generator', cat: 'dev', catLabel: 'Dev Tools', kw: 'password generator' },
  { name: 'Pixel Rem Converter', href: '/calculators/dev/pixel-rem-converter', cat: 'dev', catLabel: 'Dev Tools', kw: 'pixel rem converter' },
  { name: 'Regex Tester', href: '/calculators/dev/regex-tester', cat: 'dev', catLabel: 'Dev Tools', kw: 'regex tester' },
  { name: 'Responsive Breakpoints', href: '/calculators/dev/responsive-breakpoints', cat: 'dev', catLabel: 'Dev Tools', kw: 'responsive breakpoints' },
  { name: 'Robots Txt Generator', href: '/calculators/dev/robots-txt-generator', cat: 'dev', catLabel: 'Dev Tools', kw: 'robots txt generator' },
  { name: 'Rsa Key Info', href: '/calculators/dev/rsa-key-info', cat: 'dev', catLabel: 'Dev Tools', kw: 'rsa key info' },
  { name: 'Semver Tool', href: '/calculators/dev/semver-calculator', cat: 'dev', catLabel: 'Dev Tools', kw: 'semver calculator' },
  { name: 'Sql Formatter', href: '/calculators/dev/sql-formatter', cat: 'dev', catLabel: 'Dev Tools', kw: 'sql formatter' },
  { name: 'Sql Join Visualizer', href: '/calculators/dev/sql-join-visualizer', cat: 'dev', catLabel: 'Dev Tools', kw: 'sql join visualizer' },
  { name: 'String Hash Calc', href: '/calculators/dev/string-hash-calc', cat: 'dev', catLabel: 'Dev Tools', kw: 'string hash calc' },
  { name: 'String Inspector', href: '/calculators/dev/string-inspector', cat: 'dev', catLabel: 'Dev Tools', kw: 'string inspector' },
  { name: 'Svg Optimizer', href: '/calculators/dev/svg-optimizer', cat: 'dev', catLabel: 'Dev Tools', kw: 'svg optimizer' },
  { name: 'Table Generator', href: '/calculators/dev/table-generator', cat: 'dev', catLabel: 'Dev Tools', kw: 'table generator' },
  { name: 'Text Case Converter', href: '/calculators/dev/text-case-converter', cat: 'dev', catLabel: 'Dev Tools', kw: 'text case converter' },
  { name: 'Text Diff Inline', href: '/calculators/dev/text-diff-inline', cat: 'dev', catLabel: 'Dev Tools', kw: 'text diff inline' },
  { name: 'Timezone Converter', href: '/calculators/dev/timezone-converter', cat: 'dev', catLabel: 'Dev Tools', kw: 'timezone converter' },
  { name: 'Toml Formatter', href: '/calculators/dev/toml-formatter', cat: 'dev', catLabel: 'Dev Tools', kw: 'toml formatter' },
  { name: 'Unix Timestamp', href: '/calculators/dev/unix-timestamp', cat: 'dev', catLabel: 'Dev Tools', kw: 'unix timestamp' },
  { name: 'Url Encoder', href: '/calculators/dev/url-encoder', cat: 'dev', catLabel: 'Dev Tools', kw: 'url encoder' },
  { name: 'Uuid Generator', href: '/calculators/dev/uuid-generator', cat: 'dev', catLabel: 'Dev Tools', kw: 'uuid generator' },
  { name: 'Word Counter', href: '/calculators/dev/word-counter', cat: 'dev', catLabel: 'Dev Tools', kw: 'word counter' },
  { name: 'Xml Formatter', href: '/calculators/dev/xml-formatter', cat: 'dev', catLabel: 'Dev Tools', kw: 'xml formatter' },
  { name: 'Xml to Json', href: '/calculators/dev/xml-to-json', cat: 'dev', catLabel: 'Dev Tools', kw: 'xml to json' },
  { name: 'Yaml Formatter', href: '/calculators/dev/yaml-formatter', cat: 'dev', catLabel: 'Dev Tools', kw: 'yaml formatter' },
  { name: 'Z Index Manager', href: '/calculators/dev/z-index-manager', cat: 'dev', catLabel: 'Dev Tools', kw: 'z index manager' },
  { name: 'Age in Days', href: '/calculators/fun/age-in-days', cat: 'fun', catLabel: 'Fun', kw: 'age in days' },
  { name: 'Birthday Countdown', href: '/calculators/fun/birthday-countdown', cat: 'fun', catLabel: 'Fun', kw: 'birthday countdown' },
  { name: 'Calories in Beer', href: '/calculators/fun/calories-in-beer', cat: 'fun', catLabel: 'Fun', kw: 'calories in beer' },
  { name: 'Coffee Calculator', href: '/calculators/fun/coffee-calculator', cat: 'fun', catLabel: 'Fun', kw: 'coffee calculator' },
  { name: 'Compliment Generator', href: '/calculators/fun/compliment-generator', cat: 'fun', catLabel: 'Fun', kw: 'compliment generator' },
  { name: 'Emoji Translator', href: '/calculators/fun/emoji-translator', cat: 'fun', catLabel: 'Fun', kw: 'emoji translator' },
  { name: 'Fantasy Name Generator', href: '/calculators/fun/fantasy-name-generator', cat: 'fun', catLabel: 'Fun', kw: 'fantasy name generator' },
  { name: 'Fortune Cookie', href: '/calculators/fun/fortune-cookie', cat: 'fun', catLabel: 'Fun', kw: 'fortune cookie' },
  { name: 'How Rich Am I', href: '/calculators/fun/how-rich-am-i', cat: 'fun', catLabel: 'Fun', kw: 'how rich am i' },
  { name: 'Insult Generator', href: '/calculators/fun/shakespeare-insult-generator', cat: 'fun', catLabel: 'Fun', kw: 'insult generator' },
  { name: 'Life Expectancy Fun', href: '/calculators/fun/life-expectancy-fun', cat: 'fun', catLabel: 'Fun', kw: 'life expectancy fun' },
  { name: 'Love Compatibility', href: '/calculators/fun/love-compatibility', cat: 'fun', catLabel: 'Fun', kw: 'love compatibility' },
  { name: 'Lucky Number', href: '/calculators/fun/lucky-number', cat: 'fun', catLabel: 'Fun', kw: 'lucky number' },
  { name: 'Personality Quiz', href: '/calculators/fun/personality-quiz', cat: 'fun', catLabel: 'Fun', kw: 'personality quiz' },
  { name: 'Pig Latin Converter', href: '/calculators/fun/pig-latin-converter', cat: 'fun', catLabel: 'Fun', kw: 'pig latin converter' },
  { name: 'Pizza Calculator', href: '/calculators/fun/pizza-calculator', cat: 'fun', catLabel: 'Fun', kw: 'pizza calculator' },
  { name: 'Procrastination Score', href: '/calculators/fun/procrastination-score', cat: 'fun', catLabel: 'Fun', kw: 'procrastination score' },
  { name: 'Random Fact Generator', href: '/calculators/fun/random-fact-generator', cat: 'fun', catLabel: 'Fun', kw: 'random fact generator' },
  { name: 'Random Name Generator', href: '/calculators/fun/random-name-generator', cat: 'fun', catLabel: 'Fun', kw: 'random name generator' },
  { name: 'Screen Time Calculator', href: '/calculators/fun/screen-time-calculator', cat: 'fun', catLabel: 'Fun', kw: 'screen time calculator' },
  { name: 'Sleep Debt Calculator', href: '/calculators/fun/sleep-debt-calculator', cat: 'fun', catLabel: 'Fun', kw: 'sleep debt calculator' },
  { name: 'Social Media Addiction', href: '/calculators/fun/social-media-addiction', cat: 'fun', catLabel: 'Fun', kw: 'social media addiction' },
  { name: 'Superhero Name', href: '/calculators/fun/superhero-name', cat: 'fun', catLabel: 'Fun', kw: 'superhero name' },
  { name: 'Text to Morse', href: '/calculators/fun/text-to-morse', cat: 'fun', catLabel: 'Fun', kw: 'text to morse' },
  { name: 'Trivia Quiz', href: '/calculators/fun/trivia-quiz', cat: 'fun', catLabel: 'Fun', kw: 'trivia quiz' },
  { name: 'Uwu Text Generator', href: '/calculators/fun/uwu-text-generator', cat: 'fun', catLabel: 'Fun', kw: 'uwu text generator' },
  { name: 'Villain Name', href: '/calculators/fun/villain-name', cat: 'fun', catLabel: 'Fun', kw: 'villain name' },
  { name: 'Workout Excuse Generator', href: '/calculators/fun/workout-excuse-generator', cat: 'fun', catLabel: 'Fun', kw: 'workout excuse generator' },
  { name: 'Would You Rather', href: '/calculators/fun/would-you-rather', cat: 'fun', catLabel: 'Fun', kw: 'would you rather' },
  { name: 'Zodiac Calculator', href: '/calculators/fun/zodiac-calculator', cat: 'fun', catLabel: 'Fun', kw: 'zodiac calculator' },
  { name: 'Investment', href: '/blog/investment', cat: 'blog', catLabel: 'Blog', kw: 'investment' },
  { name: 'Loans', href: '/blog/loans', cat: 'blog', catLabel: 'Blog', kw: 'loans' },
  { name: 'Tax', href: '/blog/tax', cat: 'blog', catLabel: 'Blog', kw: 'tax' },
  { name: 'Health', href: '/blog/health', cat: 'blog', catLabel: 'Blog', kw: 'health' },
  { name: 'Property', href: '/blog/property', cat: 'blog', catLabel: 'Blog', kw: 'property' },
  { name: 'Commodity', href: '/blog/commodity', cat: 'blog', catLabel: 'Blog', kw: 'commodity' },
  { name: 'SIP Calculator Guide How to Grow Wealth with Systematic Investment', href: '/blog/sip-calculator-guide-how-to-grow-wealth-with-systematic-investment', cat: 'blog', catLabel: 'Blog', kw: 'sip calculator guide how to grow wealth with systematic investment' },
  { name: 'Compound Interest Guide Eighth Wonder of the World', href: '/blog/compound-interest-guide-eighth-wonder-of-the-world', cat: 'blog', catLabel: 'Blog', kw: 'compound interest guide eighth wonder of the world' },
  { name: 'Retirement Planning Guide How Much Do You Need to Retire', href: '/blog/retirement-planning-guide-how-much-do-you-need-to-retire', cat: 'blog', catLabel: 'Blog', kw: 'retirement planning guide how much do you need to retire' },
  { name: 'EMI Calculator Complete Guide Understand Home Car Personal Loans', href: '/blog/emi-calculator-complete-guide-understand-home-car-personal-loans', cat: 'blog', catLabel: 'Blog', kw: 'emi calculator complete guide understand home car personal loans' },
  { name: 'Home Loan Mortgage Guide How to Get Best Rate', href: '/blog/home-loan-mortgage-guide-how-to-get-best-rate', cat: 'blog', catLabel: 'Blog', kw: 'home loan mortgage guide how to get best rate' },
  { name: 'Gold Investment Guide India 2026', href: '/blog/gold-investment-guide-india-2026', cat: 'blog', catLabel: 'Blog', kw: 'gold investment guide india 2026' },
  { name: 'FIRE Movement India Guide 2026', href: '/blog/fire-movement-india-guide-2026', cat: 'blog', catLabel: 'Blog', kw: 'fire movement india guide 2026' },
  { name: 'Debt Payoff Strategies Avalanche vs Snowball Method', href: '/blog/debt-payoff-strategies-avalanche-vs-snowball-method', cat: 'blog', catLabel: 'Blog', kw: 'debt payoff strategies avalanche vs snowball method' },
  { name: 'Net Worth Guide How to Calculate and Grow Your Wealth', href: '/blog/net-worth-guide-how-to-calculate-and-grow-your-wealth', cat: 'blog', catLabel: 'Blog', kw: 'net worth guide how to calculate and grow your wealth' },
  { name: 'Index Fund Guide Beginners 2026', href: '/blog/index-fund-guide-beginners-2026', cat: 'blog', catLabel: 'Blog', kw: 'index fund guide beginners 2026' },
  { name: '401k vs Roth IRA Complete Guide 2026', href: '/blog/401k-vs-roth-ira-complete-guide-2026', cat: 'blog', catLabel: 'Blog', kw: '401k vs roth ira complete guide 2026' },
  { name: 'Bmi Calculator Guide Understanding Body Mass Index', href: '/blog/bmi-calculator-guide-understanding-body-mass-index', cat: 'blog', catLabel: 'Blog', kw: 'bmi calculator guide understanding body mass index' },
  { name: 'Calorie Calculator Guide Tdee Macros Weight Loss', href: '/blog/calorie-calculator-guide-tdee-macros-weight-loss', cat: 'blog', catLabel: 'Blog', kw: 'calorie calculator guide tdee macros weight loss' },
  { name: 'UK Income Tax Guide Paye National Insurance Take Home Pay 2026', href: '/blog/uk-income-tax-guide-paye-national-insurance-take-home-pay-2026', cat: 'blog', catLabel: 'Blog', kw: 'uk income tax guide paye national insurance take home pay 2026' },
  { name: 'SIP vs FD Which Is Better 2026', href: '/blog/sip-vs-fd-which-is-better-2026', cat: 'blog', catLabel: 'Blog', kw: 'sip vs fd which is better 2026' },
  { name: 'SIP vs Real Estate Complete Guide India 2026', href: '/blog/sip-vs-real-estate-complete-guide-india-2026', cat: 'blog', catLabel: 'Blog', kw: 'sip vs real estate complete guide india 2026' },
  { name: 'Best Mortgage Calculators USA 2026', href: '/blog/best-mortgage-calculators-usa-2026', cat: 'blog', catLabel: 'Blog', kw: 'best mortgage calculators usa 2026' },
  { name: 'Best Retirement Calculators USA 2026', href: '/blog/best-retirement-calculators-usa-2026', cat: 'blog', catLabel: 'Blog', kw: 'best retirement calculators usa 2026' },
  { name: 'Compound Interest Calculator Guide USA 2026', href: '/blog/compound-interest-calculator-guide-usa-2026', cat: 'blog', catLabel: 'Blog', kw: 'compound interest calculator guide usa 2026' },
  { name: 'How Much Mortgage Can I Afford USA 2026', href: '/blog/how-much-mortgage-can-i-afford-usa-2026', cat: 'blog', catLabel: 'Blog', kw: 'how much mortgage can i afford usa 2026' },
  { name: 'How to Pay Off Mortgage Early USA 2026', href: '/blog/how-to-pay-off-mortgage-early-usa-2026', cat: 'blog', catLabel: 'Blog', kw: 'how to pay off mortgage early usa 2026' },
  { name: 'Car Loan Calculator USA 2026 Rates By State', href: '/blog/car-loan-calculator-usa-2026-rates-by-state', cat: 'blog', catLabel: 'Blog', kw: 'car loan calculator usa 2026 rates by state' },
  { name: 'Tax Bracket Guide USA 2026 Marginal vs Effective', href: '/blog/tax-bracket-guide-usa-2026-marginal-vs-effective', cat: 'blog', catLabel: 'Blog', kw: 'tax bracket guide usa 2026 marginal vs effective' },
  { name: 'How Much to Save for Retirement By Age USA', href: '/blog/how-much-to-save-for-retirement-by-age-usa', cat: 'blog', catLabel: 'Blog', kw: 'how much to save for retirement by age usa' },
  { name: 'Budget 50 30 20 Rule USA Real Examples 2026', href: '/blog/budget-50-30-20-rule-usa-real-examples-2026', cat: 'blog', catLabel: 'Blog', kw: 'budget 50 30 20 rule usa real examples 2026' },
  { name: 'Annual Salary By Hourly Rate USA 2026', href: '/blog/annual-salary-by-hourly-rate-usa-2026', cat: 'blog', catLabel: 'Blog', kw: 'annual salary by hourly rate usa 2026' },
  { name: 'Down Payment How Much House USA 2026', href: '/blog/down-payment-how-much-house-usa-2026', cat: 'blog', catLabel: 'Blog', kw: 'down payment how much house usa 2026' },
  { name: 'Roth IRA vs 401k Which Is Better 2026', href: '/blog/roth-ira-vs-401k-which-is-better-2026', cat: 'blog', catLabel: 'Blog', kw: 'roth ira vs 401k which is better 2026' },
  { name: 'Wealth Building Guide USA 2026 Net Worth By Age', href: '/blog/wealth-building-guide-usa-2026-net-worth-by-age', cat: 'blog', catLabel: 'Blog', kw: 'wealth building guide usa 2026 net worth by age' },
  { name: 'How to Maximize 401k USA 2026', href: '/blog/how-to-maximize-401k-usa-2026', cat: 'blog', catLabel: 'Blog', kw: 'how to maximize 401k usa 2026' },
  { name: 'Debt Payoff Guide USA 2026', href: '/blog/debt-payoff-guide-usa-2026', cat: 'blog', catLabel: 'Blog', kw: 'debt payoff guide usa 2026' },
  { name: 'College Cost Savings Guide USA 2026', href: '/blog/college-cost-savings-guide-usa-2026', cat: 'blog', catLabel: 'Blog', kw: 'college cost savings guide usa 2026' },
  { name: 'Small Business Finance Guide USA 2026', href: '/blog/small-business-finance-guide-usa-2026', cat: 'blog', catLabel: 'Blog', kw: 'small business finance guide usa 2026' },
  { name: 'Emergency Fund Calculator Guide USA 2026', href: '/blog/emergency-fund-calculator-usa-2026', cat: 'blog', catLabel: 'Blog', kw: 'emergency fund calculator usa 2026' },
  { name: 'Compound Interest Guide USA 2026', href: '/blog/compound-interest-guide-usa-how-to-grow-money-2026', cat: 'blog', catLabel: 'Blog', kw: 'compound interest guide usa how to grow money 2026' },
  { name: 'Social Security Claiming Strategy 2026', href: '/blog/social-security-claiming-strategy-usa-2026', cat: 'blog', catLabel: 'Blog', kw: 'social security claiming strategy usa 2026' },
  { name: 'Credit Card Payoff Guide USA 2026', href: '/blog/credit-card-payoff-calculator-usa-interest-guide-2026', cat: 'blog', catLabel: 'Blog', kw: 'credit card payoff calculator usa interest guide 2026' },
  { name: 'HELOC vs Cash-Out Refinance USA 2026', href: '/blog/home-equity-heloc-vs-cashout-refinance-usa-2026', cat: 'blog', catLabel: 'Blog', kw: 'home equity heloc vs cashout refinance usa 2026' },
  { name: 'Investment Property Calculator USA 2026', href: '/blog/investment-property-calculator-usa-rental-income-2026', cat: 'blog', catLabel: 'Blog', kw: 'investment property calculator usa rental income 2026' },
  { name: 'Student Loan Payoff Guide USA 2026', href: '/blog/student-loan-payoff-strategies-usa-2026', cat: 'blog', catLabel: 'Blog', kw: 'student loan payoff strategies usa 2026' },
  { name: 'Dividend Investing Guide USA 2026', href: '/blog/dividend-investing-guide-usa-2026-passive-income', cat: 'blog', catLabel: 'Blog', kw: 'dividend investing guide usa 2026 passive income' },
  { name: 'Inflation Impact Calculator USA 2026', href: '/blog/inflation-impact-calculator-usa-2026-purchasing-power', cat: 'blog', catLabel: 'Blog', kw: 'inflation impact calculator usa 2026 purchasing power' },
  { name: 'Lease vs Buy Car Guide USA 2026', href: '/blog/lease-vs-buy-car-calculator-usa-2026', cat: 'blog', catLabel: 'Blog', kw: 'lease vs buy car calculator usa 2026' },
  { name: 'FIRE Calculator Guide USA 2026', href: '/blog/fire-calculator-guide-usa-retire-early-2026', cat: 'blog', catLabel: 'Blog', kw: 'fire calculator guide usa retire early 2026' },
  { name: 'Net Worth by Age USA 2026', href: '/blog/net-worth-by-age-usa-2026-how-do-you-compare', cat: 'blog', catLabel: 'Blog', kw: 'net worth by age usa 2026 how do you compare' },
  { name: 'HSA Triple Tax Advantage Guide 2026', href: '/blog/hsa-triple-tax-advantage-guide-usa-2026', cat: 'blog', catLabel: 'Blog', kw: 'hsa triple tax advantage guide usa 2026' },
  { name: 'Real Estate vs Stock Market USA 2026', href: '/blog/real-estate-vs-stock-market-usa-2026-which-wins', cat: 'blog', catLabel: 'Blog', kw: 'real estate vs stock market usa 2026 which wins' },
  { name: 'Mortgage Calculator', href: '/calculators/finance/mortgage-calculator', cat: 'finance', catLabel: 'Finance', kw: 'mortgage calculator' },
  { name: 'Tax Bracket 2026', href: '/calculators/finance/tax-bracket-calculator', cat: 'finance', catLabel: 'Finance', kw: 'tax bracket calculator' },
  { name: 'Budget Planner', href: '/calculators/finance/budget-planner-calculator', cat: 'finance', catLabel: 'Finance', kw: 'budget planner calculator' },
  { name: '401k Calculator', href: '/calculators/finance/401k-calculator', cat: 'finance', catLabel: 'Finance', kw: '401k calculator' },
  { name: 'HELOC Credit Line Calculator', href: '/calculators/finance/heloc-credit-line-calculator', cat: 'finance', catLabel: 'Finance', kw: 'heloc credit line calculator', icon: '🏡' },
  { name: 'Social Security Breakeven Calculator', href: '/calculators/finance/social-security-breakeven-calculator', cat: 'finance', catLabel: 'Finance', kw: 'social security breakeven calculator', icon: '🏛️' },
  { name: 'Required Minimum Distribution (RMD) Calculator', href: '/calculators/finance/required-minimum-distribution-calculator', cat: 'finance', catLabel: 'Finance', kw: 'required minimum distribution (rmd) calculator', icon: '📋' },
  { name: 'Backdoor Roth IRA Calculator', href: '/calculators/finance/backdoor-roth-ira-calculator', cat: 'finance', catLabel: 'Finance', kw: 'backdoor roth ira calculator', icon: '🚪' },
  { name: 'Mega Backdoor Roth Calculator', href: '/calculators/finance/mega-backdoor-roth-calculator', cat: 'finance', catLabel: 'Finance', kw: 'mega backdoor roth calculator', icon: '💪' },
  { name: 'SEP-IRA Calculator', href: '/calculators/finance/sep-ira-calculator', cat: 'finance', catLabel: 'Finance', kw: 'sep-ira calculator', icon: '💼' },
  { name: 'Capital Gains Tax Calculator', href: '/calculators/finance/capital-gains-tax-calculator', cat: 'finance', catLabel: 'Finance', kw: 'capital gains tax calculator', icon: '📈' },
  { name: 'Real Estate Cost Basis Calculator', href: '/calculators/finance/real-estate-cost-basis-calculator', cat: 'finance', catLabel: 'Finance', kw: 'real estate cost basis calculator', icon: '🏘️' },
  { name: 'I-Bonds Calculator', href: '/calculators/finance/i-bonds-calculator', cat: 'finance', catLabel: 'Finance', kw: 'i-bonds calculator', icon: '🏛️' },
  { name: 'HSA Investment Calculator', href: '/calculators/finance/hsa-investment-calculator', cat: 'finance', catLabel: 'Finance', kw: 'hsa investment calculator', icon: '🏥' },
  { name: 'Medicare Premium Calculator', href: '/calculators/finance/medicare-premium-calculator', cat: 'finance', catLabel: 'Finance', kw: 'medicare premium calculator', icon: '💊' },
  { name: 'Estate Tax Calculator', href: '/calculators/finance/estate-tax-calculator', cat: 'finance', catLabel: 'Finance', kw: 'estate tax calculator', icon: '⚖️' },
  { name: 'Gift Tax Calculator', href: '/calculators/finance/gift-tax-calculator', cat: 'finance', catLabel: 'Finance', kw: 'gift tax calculator', icon: '🎁' },
  { name: 'QBI Deduction Calculator', href: '/calculators/finance/qbi-deduction-calculator', cat: 'finance', catLabel: 'Finance', kw: 'qbi deduction calculator', icon: '📋' },
  { name: 'Health Insurance Deductible Calculator', href: '/calculators/finance/health-insurance-deductible-calculator', cat: 'finance', catLabel: 'Finance', kw: 'health insurance deductible calculator', icon: '💊' },
  { name: 'FSA Calculator', href: '/calculators/finance/fsa-calculator', cat: 'finance', catLabel: 'Finance', kw: 'fsa calculator', icon: '🏥' },
  { name: 'Dependent Care FSA Calculator', href: '/calculators/finance/dependent-care-fsa-calculator', cat: 'finance', catLabel: 'Finance', kw: 'dependent care fsa calculator', icon: '👶' },
  { name: 'Student Loan Forgiveness Calculator', href: '/calculators/finance/student-loan-forgiveness-calculator', cat: 'finance', catLabel: 'Finance', kw: 'student loan forgiveness calculator', icon: '🎓' },
  { name: 'Alternative Minimum Tax Calculator', href: '/calculators/finance/alternative-minimum-tax-calculator', cat: 'finance', catLabel: 'Finance', kw: 'alternative minimum tax calculator', icon: '⚠️' },
  { name: 'Self-Employment Tax Calculator', href: '/calculators/finance/self-employment-tax-calculator', cat: 'finance', catLabel: 'Finance', kw: 'self-employment tax calculator', icon: '💼' },
  { name: 'Equity Compensation Calculator', href: '/calculators/finance/equity-compensation-calculator', cat: 'finance', catLabel: 'Finance', kw: 'equity compensation calculator', icon: '📊' },
  { name: 'Net Investment Income Tax Calculator', href: '/calculators/finance/net-investment-income-tax-calculator', cat: 'finance', catLabel: 'Finance', kw: 'net investment income tax calculator', icon: '💹' },
  { name: 'Crypto Tax Calculator', href: '/calculators/finance/crypto-tax-calculator', cat: 'finance', catLabel: 'Finance', kw: 'crypto tax calculator', icon: '₿' },
  { name: 'College Savings 529 Calculator', href: '/calculators/finance/college-savings-529-calculator', cat: 'finance', catLabel: 'Finance', kw: 'college savings 529 calculator', icon: '🎓' },
  { name: 'Annual Bonus Tax Calculator', href: '/calculators/finance/annual-bonus-tax-calculator', cat: 'finance', catLabel: 'Finance', kw: 'annual bonus tax calculator', icon: '💵' },
  { name: 'Payroll Tax Calculator', href: '/calculators/finance/payroll-tax-calculator', cat: 'finance', catLabel: 'Finance', kw: 'payroll tax calculator', icon: '💵' },
  { name: 'Wealth Transfer Calculator', href: '/calculators/finance/wealth-transfer-calculator', cat: 'finance', catLabel: 'Finance', kw: 'wealth transfer calculator', icon: '👨‍👩‍👧' },
  { name: 'Student Loan vs Invest Calculator', href: '/calculators/finance/student-loan-vs-invest-calculator', cat: 'finance', catLabel: 'Finance', kw: 'student loan vs invest calculator', icon: '⚖️' },
  { name: 'Social Security Spousal Benefits Calculator', href: '/calculators/finance/social-security-spousal-calculator', cat: 'finance', catLabel: 'Finance', kw: 'social security spousal benefits calculator', icon: '👫' },
  { name: 'Home Equity Loan Calculator', href: '/calculators/finance/home-equity-loan-calculator', cat: 'finance', catLabel: 'Finance', kw: 'home equity loan calculator', icon: '🏠' },
  { name: 'Rental Property Investment Calculator', href: '/calculators/finance/rental-property-investment-calculator', cat: 'finance', catLabel: 'Finance', kw: 'rental property investment calculator', icon: '🏘️' },
  { name: 'Tax-Loss Harvesting Calculator', href: '/calculators/finance/tax-loss-harvesting-calculator', cat: 'finance', catLabel: 'Finance', kw: 'tax-loss harvesting calculator', icon: '🌿' },
  { name: 'DRIP Dividend Reinvestment Calculator', href: '/calculators/finance/drip-calculator', cat: 'finance', catLabel: 'Finance', kw: 'drip dividend reinvestment calculator', icon: '💧' },
  { name: 'Life Insurance Needs Calculator', href: '/calculators/finance/life-insurance-needs-calculator', cat: 'finance', catLabel: 'Finance', kw: 'life insurance needs calculator', icon: '🛡️' },
  { name: 'Roth Conversion Ladder Calculator', href: '/calculators/finance/roth-conversion-ladder-calculator', cat: 'finance', catLabel: 'Finance', kw: 'roth conversion ladder calculator', icon: '🪜' },
  { name: 'Inflation Impact Calculator', href: '/calculators/finance/inflation-impact-calculator', cat: 'finance', catLabel: 'Finance', kw: 'inflation impact calculator', icon: '📉' },
  { name: 'Rent Increase Calculator', href: '/calculators/finance/rent-increase-calculator', cat: 'finance', catLabel: 'Finance', kw: 'rent increase calculator', icon: '🏠' },
  { name: 'Mortgage Points Calculator', href: '/calculators/finance/mortgage-points-calculator', cat: 'finance', catLabel: 'Finance', kw: 'mortgage points calculator', icon: '📐' },
  { name: 'Salary Negotiation Calculator', href: '/calculators/finance/salary-negotiation-calculator', cat: 'finance', catLabel: 'Finance', kw: 'salary negotiation calculator', icon: '🤝' },
  { name: 'Child Tax Credit Calculator', href: '/calculators/finance/child-tax-credit-calculator', cat: 'finance', catLabel: 'Finance', kw: 'child tax credit calculator', icon: '👶' },
  { name: 'Annuity Income Calculator', href: '/calculators/finance/annuity-income-calculator', cat: 'finance', catLabel: 'Finance', kw: 'annuity income calculator', icon: '📅' },
  { name: 'Early Retirement Calculator', href: '/calculators/finance/early-retirement-calculator', cat: 'finance', catLabel: 'Finance', kw: 'early retirement calculator', icon: '🌅' },
  { name: 'HDHP vs Traditional Insurance Calculator', href: '/calculators/finance/hdhp-vs-traditional-insurance-calculator', cat: 'finance', catLabel: 'Finance', kw: 'hdhp vs traditional insurance calculator', icon: '⚕️' },
  { name: 'Cost of Debt Calculator', href: '/calculators/finance/cost-of-debt-calculator', cat: 'finance', catLabel: 'Finance', kw: 'cost of debt calculator', icon: '💳' },
  { name: 'Net Salary Calculator', href: '/calculators/finance/net-salary-calculator', cat: 'finance', catLabel: 'Finance', kw: 'net salary calculator', icon: '💰' },
  { name: 'Business Valuation Calculator', href: '/calculators/finance/business-valuation-calculator', cat: 'finance', catLabel: 'Finance', kw: 'business valuation calculator', icon: '🏢' },
  { name: 'FIRE Number Calculator', href: '/calculators/finance/fire-number-calculator', cat: 'finance', catLabel: 'Finance', kw: 'fire number calculator', icon: '🔥' },
  { name: 'Property Tax Calculator', href: '/calculators/finance/property-tax-calculator', cat: 'finance', catLabel: 'Finance', kw: 'property tax calculator', icon: '🏛️' },
  { name: 'Retirement Withdrawal Calculator', href: '/calculators/finance/retirement-withdrawal-calculator', cat: 'finance', catLabel: 'Finance', kw: 'retirement withdrawal calculator', icon: '💰' },
  { name: 'Long-Term Care Insurance Calculator', href: '/calculators/finance/long-term-care-insurance-calculator', cat: 'finance', catLabel: 'Finance', kw: 'long-term care insurance calculator', icon: '🏥' },
  { name: 'Scholarship & Financial Aid Calculator', href: '/calculators/finance/scholarship-financial-aid-calculator', cat: 'finance', catLabel: 'Finance', kw: 'scholarship & financial aid calculator', icon: '🎓' },
  { name: 'Solo 401k Calculator', href: '/calculators/finance/solo-401k-calculator', cat: 'finance', catLabel: 'Finance', kw: 'solo 401k calculator', icon: '💼' },
  { name: 'Inherited IRA Calculator', href: '/calculators/finance/inherited-ira-calculator', cat: 'finance', catLabel: 'Finance', kw: 'inherited ira calculator', icon: '📋' },
  { name: 'Mortgage Affordability Calculator', href: '/calculators/finance/mortgage-affordability-calculator', cat: 'finance', catLabel: 'Finance', kw: 'mortgage affordability calculator', icon: '🏡' },
  { name: 'College ROI Calculator', href: '/calculators/finance/college-roi-calculator', cat: 'finance', catLabel: 'Finance', kw: 'college roi calculator', icon: '🎓' },
  { name: 'House Flip Calculator', href: '/calculators/finance/house-flip-calculator', cat: 'finance', catLabel: 'Finance', kw: 'house flip calculator', icon: '🏗️' },
  { name: 'Social Security Tax Calculator', href: '/calculators/finance/social-security-tax-calculator', cat: 'finance', catLabel: 'Finance', kw: 'social security tax calculator', icon: '🏛️' },
  { name: 'Home Office Deduction Calculator', href: '/calculators/finance/home-office-deduction-calculator', cat: 'finance', catLabel: 'Finance', kw: 'home office deduction calculator', icon: '🏠' },
  { name: 'Municipal Bond Tax-Equivalent Yield Calculator', href: '/calculators/finance/municipal-bond-tax-calculator', cat: 'finance', catLabel: 'Finance', kw: 'municipal bond tax-equivalent yield calculator', icon: '🏛️' },
  { name: 'Covered Call Calculator', href: '/calculators/finance/covered-call-calculator', cat: 'finance', catLabel: 'Finance', kw: 'covered call calculator', icon: '📊' },
  { name: 'TSP vs 401k Calculator', href: '/calculators/finance/tsp-vs-401k-calculator', cat: 'finance', catLabel: 'Finance', kw: 'tsp vs 401k calculator', icon: '🏛️' },
  { name: 'Options Pricing Calculator', href: '/calculators/finance/options-pricing-calculator', cat: 'finance', catLabel: 'Finance', kw: 'options pricing calculator', icon: '📈' },
  { name: 'Estate Probate Cost Calculator', href: '/calculators/finance/estate-probate-calculator', cat: 'finance', catLabel: 'Finance', kw: 'estate probate cost calculator', icon: '⚖️' },
  { name: 'Taxable vs Roth vs Traditional Calculator', href: '/calculators/finance/taxable-vs-roth-vs-traditional-calculator', cat: 'finance', catLabel: 'Finance', kw: 'taxable vs roth vs traditional calculator', icon: '📊' },
  { name: 'Cash Value Life Insurance Calculator', href: '/calculators/finance/cash-value-life-insurance-calculator', cat: 'finance', catLabel: 'Finance', kw: 'cash value life insurance calculator', icon: '🛡️' },
  { name: 'State Tax Relocation Calculator', href: '/calculators/finance/state-tax-relocation-calculator', cat: 'finance', catLabel: 'Finance', kw: 'state tax relocation calculator', icon: '🗺️' },
  { name: 'Emergency Fund HYSA Calculator', href: '/calculators/finance/emergency-fund-hysa-calculator', cat: 'finance', catLabel: 'Finance', kw: 'emergency fund hysa calculator', icon: '🏦' },
  { name: 'Student Loan Refinance Calculator', href: '/calculators/finance/student-loan-refinance-calculator', cat: 'finance', catLabel: 'Finance', kw: 'student loan refinance calculator', icon: '🎓' },
  { name: 'Net Unrealized Appreciation Calculator', href: '/calculators/finance/net-unrealized-appreciation-calculator', cat: 'finance', catLabel: 'Finance', kw: 'net unrealized appreciation calculator', icon: '📈' },
  { name: 'Bond Ladder Calculator', href: '/calculators/finance/bond-ladder-calculator', cat: 'finance', catLabel: 'Finance', kw: 'bond ladder calculator', icon: '📊' },
  { name: 'Crypto DCA vs Lump Sum Calculator', href: '/calculators/finance/crypto-dca-calculator', cat: 'finance', catLabel: 'Finance', kw: 'crypto dca vs lump sum calculator', icon: '₿' },
  { name: 'Pension vs Lump Sum Calculator', href: '/calculators/finance/pension-vs-lump-sum-calculator', cat: 'finance', catLabel: 'Finance', kw: 'pension vs lump sum calculator', icon: '📅' },
  { name: 'Index Fund Fee Calculator', href: '/calculators/finance/index-fund-fee-calculator', cat: 'finance', catLabel: 'Finance', kw: 'index fund fee calculator', icon: '📉' },
  { name: 'I-Bond Ladder Calculator', href: '/calculators/finance/i-bond-ladder-calculator', cat: 'finance', catLabel: 'Finance', kw: 'i-bond ladder calculator', icon: '🏛️' },
  { name: 'Wealth Building Comparison Calculator', href: '/calculators/finance/wealth-building-comparison-calculator', cat: 'finance', catLabel: 'Finance', kw: 'wealth building comparison calculator', icon: '💎' },
  { name: 'Tax Withholding W-4 Calculator', href: '/calculators/finance/tax-withholding-w4-calculator', cat: 'finance', catLabel: 'Finance', kw: 'tax withholding w-4 calculator', icon: '📋' },
  { name: 'CD vs HYSA vs Money Market Calculator', href: '/calculators/finance/cd-vs-hysa-vs-money-market-calculator', cat: 'finance', catLabel: 'Finance', kw: 'cd vs hysa vs money market calculator', icon: '🏦' },
  { name: 'Car Affordability Calculator', href: '/calculators/finance/car-affordability-calculator', cat: 'finance', catLabel: 'Finance', kw: 'car affordability calculator', icon: '🚗' },
  { name: 'Cap Rate Calculator', href: '/calculators/finance/cap-rate-calculator', cat: 'finance', catLabel: 'Finance', kw: 'cap rate calculator', icon: '🏘️' },
  { name: 'Savings Rate to FIRE Calculator', href: '/calculators/finance/savings-rate-fire-calculator', cat: 'finance', catLabel: 'Finance', kw: 'savings rate to fire calculator', icon: '💹' },
  { name: 'Social Security Timing Optimizer', href: '/calculators/finance/social-security-timing-optimizer', cat: 'finance', catLabel: 'Finance', kw: 'social security timing optimizer', icon: '🏛️' },
  { name: 'Mortgage Recast Calculator', href: '/calculators/finance/mortgage-recast-calculator', cat: 'finance', catLabel: 'Finance', kw: 'mortgage recast calculator', icon: '🏠' },
  { name: 'Roth Conversion Tax Calculator', href: '/calculators/finance/roth-conversion-tax-calculator', cat: 'finance', catLabel: 'Finance', kw: 'roth conversion tax calculator', icon: '🔄' },
  { name: 'SS vs Private Pension Calculator', href: '/calculators/finance/ss-vs-private-pension-calculator', cat: 'finance', catLabel: 'Finance', kw: 'ss vs private pension calculator', icon: '📊' },
  { name: 'Conforming vs Jumbo Loan Calculator', href: '/calculators/finance/conforming-loan-limit-calculator', cat: 'finance', catLabel: 'Finance', kw: 'conforming vs jumbo loan calculator', icon: '🏠' },
  { name: 'Real Estate Syndication ROI Calculator', href: '/calculators/finance/real-estate-syndication-calculator', cat: 'finance', catLabel: 'Finance', kw: 'real estate syndication roi calculator', icon: '🏢' },
  { name: 'Mortgage vs Rent Calculator', href: '/calculators/finance/mortgage-vs-rent-calculator', cat: 'finance', catLabel: 'Finance', kw: 'mortgage vs rent calculator', icon: '⚖️' },
  { name: 'Early Mortgage Payoff Calculator', href: '/calculators/finance/early-mortgage-payoff-calculator', cat: 'finance', catLabel: 'Finance', kw: 'early mortgage payoff calculator', icon: '🏡' },
  { name: 'Credit Card Annual Fee Calculator', href: '/calculators/finance/credit-card-annual-fee-calculator', cat: 'finance', catLabel: 'Finance', kw: 'credit card annual fee calculator', icon: '💳' },
  { name: 'Gold vs Stocks Portfolio Calculator', href: '/calculators/finance/gold-vs-stocks-calculator', cat: 'finance', catLabel: 'Finance', kw: 'gold vs stocks portfolio calculator', icon: '🥇' },
  { name: 'Renters Insurance Calculator', href: '/calculators/finance/renters-insurance-calculator', cat: 'finance', catLabel: 'Finance', kw: 'renters insurance calculator', icon: '🏠' },
  { name: 'Buy vs Lease Vehicle Calculator', href: '/calculators/finance/buy-vs-lease-vehicle-calculator', cat: 'finance', catLabel: 'Finance', kw: 'buy vs lease vehicle calculator', icon: '🚗' },
  { name: 'Freelance Income Tax Calculator', href: '/calculators/finance/freelance-income-tax-calculator', cat: 'finance', catLabel: 'Finance', kw: 'freelance income tax calculator', icon: '💻' },
  { name: 'RSU Vesting Schedule Calculator', href: '/calculators/finance/vesting-schedule-calculator', cat: 'finance', catLabel: 'Finance', kw: 'rsu vesting schedule calculator', icon: '📅' },
  { name: 'S&P 500 vs Bitcoin Portfolio Calculator', href: '/calculators/finance/spy-vs-bitcoin-portfolio-calculator', cat: 'finance', catLabel: 'Finance', kw: 's&p 500 vs bitcoin portfolio calculator', icon: '₿' },
  { name: 'Paycheck Contribution Optimizer', href: '/calculators/finance/paycheck-contribution-optimizer', cat: 'finance', catLabel: 'Finance', kw: 'paycheck contribution optimizer', icon: '💵' },
  { name: 'Student Loan Forbearance Calculator', href: '/calculators/finance/student-loan-forbearance-calculator', cat: 'finance', catLabel: 'Finance', kw: 'student loan forbearance calculator', icon: '🎓' },
  { name: 'Crypto Profit Loss Tracker', href: '/calculators/finance/crypto-profit-loss-tracker', cat: 'finance', catLabel: 'Finance', kw: 'crypto profit loss tracker', icon: '₿' },
  { name: 'Tax Bracket Optimizer', href: '/calculators/finance/tax-bracket-optimizer', cat: 'finance', catLabel: 'Finance', kw: 'tax bracket optimizer', icon: '🧾' },
  { name: 'Net Worth Calculator', href: '/calculators/finance/net-worth-tracker', cat: 'finance', catLabel: 'Finance', kw: 'net worth calculator', icon: '💎' },
  { name: 'Dollar Cost Averaging vs Lump Sum Calculator', href: '/calculators/finance/dollar-cost-averaging-vs-lumpsum-usa-calculator', cat: 'finance', catLabel: 'Finance', kw: 'dollar cost averaging vs lump sum calculator', icon: '📊' },
  { name: 'BMI Calculator', href: '/calculators/health/bmi-calculator', cat: 'health', catLabel: 'Health', kw: 'bmi calculator' },
  { name: 'Roth IRA vs 401k Guide', href: '/blog/roth-ira-vs-401k-which-is-better-2026', cat: 'blog', catLabel: 'Blog', kw: 'roth ira vs 401k which is better 2026' }
]

export const TOTAL_TOOLS = 471
