import { CalculatorBatch47DeepDive } from '@/components/ui/CalculatorBatch47DeepDive'
import type { Metadata } from 'next'
import { generateCalculatorMetadata, generateFAQStructuredData, generateWebAppStructuredData } from '@/lib/seo/metadata'
import dynamic from 'next/dynamic'
const CalculatorClient = dynamic(() => import('./CalculatorClient'), {  loading: () => <div className="min-h-[400px] bg-white rounded-2xl border border-gray-100 animate-pulse m-4" /> })
export const metadata: Metadata = generateCalculatorMetadata({ title: 'Visual Acuity & Eye Health Risk Calculator 2026 | ToolTrio', description: 'Free eye health and visual acuity risk calculator 2026. Assess glaucoma risk, myopia progression, diabetic retinopathy risk, and digital eye strain from screen time, outdoor exposure, age, and family history.', slug: 'visual-acuity-risk-calculator', category: 'health', region: 'usa', keywords: ['visual acuity risk calculator', 'eye health calculator', 'glaucoma risk calculator', 'myopia progression risk calculator', 'screen time eye health calculator'] })
const relatedCalculators = [{'name': 'Diabetes Risk', 'href': '/calculators/health/diabetes-risk-calculator', 'icon': '🩸', 'desc': 'T2D risk'}, {'name': 'Blood Pressure', 'href': '/calculators/health/blood-pressure-calculator', 'icon': '🩺', 'desc': 'AHA categories'}, {'name': 'Screen Time Health', 'href': '/calculators/health/mental-fatigue-calculator', 'icon': '🖥️', 'desc': 'Screen fatigue'}, {'name': 'Age-Related Health', 'href': '/calculators/health/longevity-risk-calculator', 'icon': '♾️', 'desc': 'Longevity index'}]
const faqs = [
  {"question": "How does screen time affect eyesight?", "answer": "Prolonged near work (screens, reading) causes ciliary muscle fatigue and temporarily impairs distance focus — this is digital eye strain (asthenopia), not permanent vision change. However, there is strong evidence that reduced outdoor time in childhood increases myopia (short-sightedness) risk — outdoor light exposure stimulates dopamine release in the retina, which slows excessive eyeball elongation. Children spending < 1 hour/day outdoors have significantly higher myopia incidence. For adults, excessive screen time does not directly cause myopia progression but contributes to digital eye strain, dry eye disease, and delayed detection of other conditions."},
  {"question": "What is glaucoma and who is at risk?", "answer": "Glaucoma is a group of conditions causing optic nerve damage, usually associated with elevated intraocular pressure (IOP). It is the second leading cause of blindness worldwide, affecting 80 million people. Risk factors: age over 60, family history (10× higher risk with first-degree relative affected), Black or Hispanic ethnicity, high myopia (> -6D), thin corneas, elevated IOP, and diabetes. The insidious feature of glaucoma is that peripheral vision loss — the earliest symptom — goes unnoticed until up to 40% of optic nerve fibres are lost. This is why regular IOP screening (every 2 years from age 40-50, annually from 60+) is critical."},
  {"question": "What is diabetic retinopathy and how common is it?", "answer": "Diabetic retinopathy (DR) is the leading cause of preventable blindness in working-age adults in developed countries. After 20 years of diabetes, 99% of type 1 diabetics and 60% of type 2 diabetics have some degree of retinopathy. The condition begins as microaneurysms and haemorrhages (non-proliferative DR) and can progress to neovascularisation, vitreous haemorrhage, and tractional retinal detachment (proliferative DR). Critically, vision loss from DR is largely preventable with annual dilated fundus examinations and excellent glycaemic and blood pressure control — the DCCT trial showed intensive glucose control reduced DR incidence by 76%."}
]
export default function Page() {
  const _faqSchema = generateFAQStructuredData(faqs)
  return (<><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(_faqSchema) }} /><CalculatorClient faqs={faqs} structuredData={[generateFAQStructuredData(faqs), generateWebAppStructuredData({ name: 'Visual Acuity Risk Calculator', description: 'Free eye health and visual acuity risk calculator 2026. Assess glaucoma risk, myopia progression, di', url: 'https://tooltrio.com/calculators/health/visual-acuity-risk-calculator', category: 'HealthApplication' })]} relatedCalculators={relatedCalculators} />      <CalculatorBatch47DeepDive slug="visual-acuity-risk-calculator" />
</>)
}
