import { CalculatorBatch47DeepDive } from '@/components/ui/CalculatorBatch47DeepDive'
import type { Metadata } from 'next'
import { generateCalculatorMetadata, generateFAQStructuredData, generateWebAppStructuredData } from '@/lib/seo/metadata'
import dynamic from 'next/dynamic'
const CalculatorClient = dynamic(() => import('./CalculatorClient'), {  loading: () => <div className="min-h-[400px] bg-white rounded-2xl border border-gray-100 animate-pulse m-4" /> })
export const metadata: Metadata = generateCalculatorMetadata({ title: 'Oral Health Risk Calculator — Dental & Systemic Risk 2026 | ToolTrio', description: 'Free oral health risk calculator 2026. Assess your risk of tooth decay, gum disease, and oral cancer from brushing frequency, flossing, sugar intake, smoking, dry mouth, and dental visit history.', slug: 'oral-health-risk-calculator', category: 'health', region: 'usa', keywords: ['oral health risk calculator', 'dental health score calculator', 'gum disease risk calculator', 'tooth decay risk calculator', 'oral cancer risk calculator'] })
const relatedCalculators = [{'name': 'Dietary Inflammatory Index', 'href': '/calculators/health/dietary-inflammatory-index-calculator', 'icon': '🔬', 'desc': 'Diet inflammation'}, {'name': 'Glucose Levels', 'href': '/calculators/health/diabetes-risk-calculator', 'icon': '🩸', 'desc': 'Diabetes risk'}, {'name': 'Smoking Impact', 'href': '/calculators/health/nicotine-withdrawal-calculator', 'icon': '🚭', 'desc': 'Quit smoking'}, {'name': 'Immune Strength', 'href': '/calculators/health/immune-strength-calculator', 'icon': '🛡️', 'desc': 'Immune score'}]
const faqs = [
  {"question": "What is the connection between oral health and heart disease?", "answer": "Periodontal (gum) disease is an independent risk factor for cardiovascular disease — people with severe periodontitis have approximately 2× higher risk of heart attack and stroke compared to those with healthy gums. The mechanism involves oral bacteria entering the bloodstream through inflamed gums, contributing to systemic inflammation (elevated CRP), promoting atherosclerotic plaque formation, and directly infecting coronary plaque. Streptococcus mutans, the primary cavity-causing bacterium, has been found in atherosclerotic plaques. This bidirectional relationship is recognised by both the American Heart Association and dental organisations."},
  {"question": "How often should I see a dentist?", "answer": "Standard recommendation is a professional cleaning every 6 months for average-risk adults. Higher-risk individuals (active gum disease, diabetes, smokers, compromised immune system, high sugar diet) benefit from every 3-4 month professional cleanings. Skipping dental visits leads to progressive tartar (calculus) accumulation that cannot be removed by brushing — only professional ultrasonic scaling removes mature calculus. Undetected caries and periodontal disease progress silently; by the time symptoms appear, significant damage has typically occurred."},
  {"question": "What causes dry mouth and why does it matter for dental health?", "answer": "Dry mouth (xerostomia) dramatically accelerates tooth decay because saliva is essential for: buffering acid from bacterial metabolism, remineralising early carious lesions, washing away food debris, and providing antimicrobial peptides. Common causes: over 400 medications (antidepressants, antihistamines, antihypertensives, diuretics), diabetes, Sjögren's syndrome, radiation therapy to the head/neck, and mouth breathing. People with untreated dry mouth can develop 10+ new cavities per year. Treatment: stay hydrated, use xylitol products, prescription fluoride varnish, and discuss medication alternatives with your physician."}
]
export default function Page() {
  const _faqSchema = generateFAQStructuredData(faqs)
  return (<><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(_faqSchema) }} /><CalculatorClient faqs={faqs} structuredData={[generateFAQStructuredData(faqs), generateWebAppStructuredData({ name: 'Oral Health Risk Calculator', description: 'Free oral health risk calculator 2026. Assess your risk of tooth decay, gum disease, and oral cancer', url: 'https://tooltrio.com/calculators/health/oral-health-risk-calculator', category: 'HealthApplication' })]} relatedCalculators={relatedCalculators} />      <CalculatorBatch47DeepDive slug="oral-health-risk-calculator" />
</>)
}
