import type { Metadata } from 'next'
import { generateCalculatorMetadata, generateFAQStructuredData, generateWebAppStructuredData } from '@/lib/seo/metadata'
import dynamic from 'next/dynamic'
const CalculatorClient = dynamic(() => import('./CalculatorClient'), { ssr: false, loading: () => <div className="min-h-[400px] bg-white rounded-2xl border border-gray-100 animate-pulse m-4" /> })
export const metadata: Metadata = generateCalculatorMetadata({ title: 'Night Shift Health Calculator — Circadian Risk 2026 | ToolTrio', description: 'Free night shift health calculator 2026. Assess the health impact of shift work from years worked, frequency, sleep quality, and lifestyle habits. Includes T2D, CVD, and cancer risk from circadian disruption.', slug: 'night-shift-health-calculator', category: 'health', region: 'usa', keywords: ['night shift health calculator', 'shift work health risk calculator', 'circadian disruption health calculator', 'night shift worker health assessment', 'how bad is night shift for your health calculator'] })
const relatedCalculators = [{'name': 'Sleep Debt', 'href': '/calculators/health/sleep-debt-calculator', 'icon': '😴', 'desc': 'Sleep deprivation'}, {'name': 'Cortisol Stress', 'href': '/calculators/health/cortisol-stress-calculator', 'icon': '🧠', 'desc': 'Stress hormone'}, {'name': 'Shift Work Health', 'href': '/calculators/health/shift-work-health-calculator', 'icon': '🌙', 'desc': 'Shift work assessment'}, {'name': 'Longevity Risk', 'href': '/calculators/health/longevity-risk-calculator', 'icon': '♾️', 'desc': 'Lifespan projection'}]
const faqs = [('Why does night shift work increase disease risk?', 'Night shift work forces the body to be active during biological night — when circadian clocks in every organ are programmed for rest, repair, and fasting. This circadian misalignment disrupts the timing of cortisol, melatonin, insulin, and glucose metabolism. Epidemiological evidence is substantial: 20+ years of night shift work is associated with 36% higher T2D risk (meta-analysis, Pan et al.), 40% higher CVD mortality (rotating shifts especially), and IARC classifies prolonged night shift work as a Group 2A carcinogen (probably carcinogenic to humans) primarily for breast and prostate cancer.'), ('Can lifestyle changes reduce night shift health risks?', 'Research shows several evidence-backed strategies: (1) Strategic light management — use bright light exposure at shift start, blue-light blocking glasses on the commute home; (2) Sleep optimisation — blackout curtains, earplugs, consistent daytime sleep schedule; (3) Eating timing — avoid large meals between 2-4am (insulin sensitivity is worst during biological night); (4) Exercise — consistent timing helps anchor circadian rhythms; (5) Melatonin — 0.5mg before daytime sleep accelerates circadian shifting; (6) Social support — isolation compounds shift work health effects.'), ('What is the difference between rotating and fixed night shifts?', 'Fixed night shifts allow eventual circadian adaptation, although complete adaptation (shifting all circadian clocks) takes weeks to months. Rotating shifts prevent any adaptation — the circadian clock is perpetually misaligned, which research suggests is more harmful than fixed night work. Weekly rotation is more disruptive than monthly rotation. Forward rotation (day→evening→night) is better tolerated than backward rotation because it follows the natural delay tendency of human circadian rhythms. For health outcomes, permanent night work with excellent daytime sleep is preferable to irregular rotating schedules.')]
export default function Page() {
  const _faqSchema = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faqs.map((f: any) => ({ '@type': 'Question', name: f.question, acceptedAnswer: { '@type': 'Answer', text: f.answer } })) }
  return (<><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(_faqSchema) }} /><CalculatorClient faqs={faqs} structuredData={[generateFAQStructuredData(faqs), generateWebAppStructuredData({ name: 'Night Shift Health Impact Calculator', description: 'Free night shift health calculator 2026. Assess the health impact of shift work from years worked, f', url: 'https://tooltrio.com/calculators/health/night-shift-health-calculator', category: 'HealthApplication' })]} relatedCalculators={relatedCalculators} /></>)
}
