import type { Metadata } from 'next'
import { generateCalculatorMetadata, generateFAQStructuredData } from '@/lib/seo/metadata'
import dynamic from 'next/dynamic'
const CalculatorClient = dynamic(() => import('./CalculatorClient'), { ssr: false, loading: () => <div className="min-h-[400px] bg-white rounded-2xl border border-gray-100 animate-pulse m-4" /> })
export const metadata: Metadata = generateCalculatorMetadata({ title: 'Safe Harbor 401(k) Calculator USA 2026 | ToolTrio', description: 'Calculate Safe Harbor 401k employer contributions for small businesses. Compare basic match, enhanced match, and non-elective contribution options for 2026.', slug: 'safe-harbor-401k-calculator', category: 'finance', keywords: ['safe harbor 401k calculator', 'safe harbor 401k match 2026', 'small business 401k calculator USA', 'safe harbor nonelective contribution'] })
const faqs = [('What is a Safe Harbor 401k plan?', 'A Safe Harbor 401k automatically passes the IRS nondiscrimination tests (ADP/ACP tests) that normal 401k plans must pass annually. This allows business owners and highly compensated employees to maximize their contributions without worrying about test failures. The tradeoff is that employers must make mandatory contributions — either a match or a 3% non-elective contribution — that vest immediately.'), ('What is the best Safe Harbor match formula?', 'The Basic Match (100% of first 3% + 50% of next 2%) minimizes employer cost while satisfying Safe Harbor. The Enhanced Match (100% of first 4%) is simpler and encourages higher employee participation. The Non-Elective contribution (3% of salary to ALL eligible employees, regardless of whether they contribute) ensures all employees benefit but costs more if participation is low.')]
const relatedCalculators = [{'name': '401k Calculator', 'href': '/calculators/finance/401k-calculator', 'icon': '🏦', 'desc': '401k growth'}, {'name': 'SEP IRA vs Solo 401k', 'href': '/calculators/finance/sep-ira-vs-solo-401k-calculator', 'icon': '💼', 'desc': 'Self-employed retirement'}, {'name': 'Payroll Tax Calculator', 'href': '/calculators/finance/payroll-tax-calculator', 'icon': '📋', 'desc': 'Payroll taxes'}]
const structuredData = [generateFAQStructuredData(faqs)]
export default function Page() { return <>{structuredData.map((s, i) => <script key={i} type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(s) }} />)}<CalculatorClient faqs={faqs} structuredData={structuredData} relatedCalculators={relatedCalculators} /></> }
