import type { Metadata } from 'next'
import { generateCalculatorMetadata, generateFAQStructuredData, generateWebAppStructuredData } from '@/lib/seo/metadata'
import dynamic from 'next/dynamic'
const CalculatorClient = dynamic(() => import('./CalculatorClient'), {  loading: () => <div className="min-h-[400px] bg-white rounded-2xl border border-gray-100 animate-pulse m-4" /> })
export const metadata: Metadata = generateCalculatorMetadata({ title: 'Wound Healing Time Estimator 2026 | ToolTrio', description: 'Free wound healing calculator 2026. Estimate wound healing time from wound size, depth, location, age, diabetes, BMI, smoking, nutrition, and immune status. Includes infection risk and nutrition tips.', slug: 'wound-healing-calculator', category: 'health', region: 'usa', keywords: ['wound healing time calculator', 'how long does a wound take to heal calculator', 'wound healing estimate', 'diabetic wound healing calculator', 'wound healing factors calculator'] })
const relatedCalculators = [{'name': 'BMI Calculator', 'href': '/calculators/health/bmi-calculator', 'icon': '⚖️', 'desc': 'Body mass index'}, {'name': 'Diabetes Risk', 'href': '/calculators/health/diabetes-risk-calculator', 'icon': '🩸', 'desc': 'T2D risk'}, {'name': 'Immune Strength', 'href': '/calculators/health/immune-strength-calculator', 'icon': '🛡️', 'desc': 'Immune score'}, {'name': 'Protein Synthesis', 'href': '/calculators/health/protein-synthesis-calculator', 'icon': '💪', 'desc': 'Protein optimization'}]
const faqs = [
  {"question": "What are the 3 stages of wound healing?", "answer": "Wound healing proceeds through 3 overlapping phases: (1) Inflammation (Days 1-4): vasodilation, platelet aggregation, and neutrophil/macrophage recruitment clear debris and pathogens — redness, swelling, and warmth are normal and necessary; (2) Proliferation (Days 4 to 2-4 weeks): fibroblasts produce collagen and granulation tissue forms; angiogenesis (new blood vessel formation) supplies oxygen and nutrients; (3) Remodelling (Weeks 3 to 2+ years): collagen crosslinks reorganise, scar contracts, and tensile strength gradually increases — mature scars achieve only 70-80% of original tissue strength. Any factor that impairs circulation, immune function, or nutrition can delay or arrest any phase."},
  {"question": "Why does diabetes impair wound healing?", "answer": "Diabetes impairs wound healing through multiple mechanisms: (1) Hyperglycaemia damages neutrophil and macrophage function, reducing infection clearance; (2) Advanced glycation end-products (AGEs) stiffen collagen, impairing remodelling; (3) Peripheral neuropathy reduces pain sensation, allowing injuries to go unnoticed and worsen; (4) Peripheral vascular disease reduces tissue perfusion and oxygen delivery — the critical fuel for wound healing; (5) Impaired growth factor signalling slows fibroblast and keratinocyte migration into the wound. Diabetic foot ulcers are the leading cause of non-traumatic lower limb amputation in the US (73,000 cases/year)."},
  {"question": "What nutrition most accelerates wound healing?", "answer": "Key nutrients for wound healing: (1) Protein — 1.5-2g/kg/day supports collagen synthesis and immune function; adequate protein can reduce healing time by 25-30%; (2) Vitamin C — essential for hydroxylation of proline and lysine during collagen synthesis; 500mg/day in wound patients is supported by evidence; (3) Zinc — critical for cell division and protein synthesis; deficiency significantly impairs healing; (4) Arginine — conditionally essential amino acid that stimulates wound-related immune function; (5) Omega-3 fatty acids — modulate inflammatory phase. Malnutrition is present in up to 30-50% of hospitalised patients with non-healing wounds and is a primary correctable cause of delayed healing."}
]
export default function Page() {
  const _faqSchema = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faqs.map((f: any) => ({ '@type': 'Question', name: f.question, acceptedAnswer: { '@type': 'Answer', text: f.answer } })) }
  return (<><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(_faqSchema) }} /><CalculatorClient faqs={faqs} structuredData={[generateFAQStructuredData(faqs), generateWebAppStructuredData({ name: 'Wound Healing Time Calculator', description: 'Free wound healing calculator 2026. Estimate wound healing time from wound size, depth, location, ag', url: 'https://tooltrio.com/calculators/health/wound-healing-calculator', category: 'HealthApplication' })]} relatedCalculators={relatedCalculators} /></>)
}
