import type { Metadata } from 'next'
import { generateCalculatorMetadata, generateFAQStructuredData } from '@/lib/seo/metadata'
import dynamic from 'next/dynamic'
const CalculatorClient = dynamic(() => import('./CalculatorClient'), { ssr: false, loading: () => <div className="min-h-[400px] bg-white rounded-2xl border border-gray-100 animate-pulse m-4" /> })
export const metadata: Metadata = generateCalculatorMetadata({ title: 'Defined Benefit Pension Calculator USA 2026 | ToolTrio', description: 'Calculate your defined benefit pension monthly income, replacement rate, and lifetime benefit value. Compare early vs normal retirement options.', slug: 'defined-benefit-pension-calculator', category: 'finance', keywords: ['defined benefit pension calculator USA', 'pension benefit formula calculator', 'db pension monthly income calculator', 'pension early retirement reduction'] })
const faqs = [('How is a defined benefit pension calculated?', 'Most defined benefit pensions use a formula: Annual Benefit = Years of Service × Benefit Multiplier % × Final Average Salary. For example, with 25 years of service, a 1.5% multiplier, and a $70,000 final salary: 25 × 1.5% × $70,000 = $26,250/year ($2,187/month). The multiplier varies by employer — government plans often use 2-2.5%, while private sector plans use 1-1.5%.'), ('Is a pension or 401k better?', "Pensions provide guaranteed lifetime income regardless of market performance — valuable for longevity protection. 401k plans offer more control, portability, and potential for higher returns but carry market risk. For most workers, having both is ideal. If you have a pension, you may need less in your 401k since your base income is guaranteed. The pension replaces the 'bonds' portion of a retirement portfolio.")]
const relatedCalculators = [{'name': 'Retirement Calculator', 'href': '/calculators/finance/retirement-calculator', 'icon': '🌅', 'desc': 'Retirement planning'}, {'name': '401k vs Pension', 'href': '/calculators/finance/401k-vs-pension-calculator', 'icon': '⚖️', 'desc': 'Pension vs 401k'}, {'name': 'Social Security Calculator', 'href': '/calculators/finance/social-security-calculator', 'icon': '🏛️', 'desc': 'SS benefits'}]
const structuredData = [generateFAQStructuredData(faqs)]
export default function Page() { return <>{structuredData.map((s, i) => <script key={i} type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(s) }} />)}<CalculatorClient faqs={faqs} structuredData={structuredData} relatedCalculators={relatedCalculators} /></> }
