import { CalculatorBatch48DeepDive } from '@/components/ui/CalculatorBatch48DeepDive'
import type { Metadata } from 'next'
import { generateCalculatorMetadata, generateFAQStructuredData, generateWebAppStructuredData } from '@/lib/seo/metadata'
import dynamic from 'next/dynamic'
const CalculatorClient = dynamic(() => import('./CalculatorClient'), {
  
  loading: () => <div className="min-h-[400px] bg-white rounded-2xl border border-gray-100 animate-pulse m-4" />
})
export const metadata: Metadata = generateCalculatorMetadata({ title: 'Exercise Addiction Risk Calculator — EAI Score 2026 | ToolTrio', description: 'Free exercise addiction risk calculator based on validated EAI criteria 2026. Assess compulsive exercise patterns including guilt, anxiety, social sacrifice, and inability to reduce training.', slug: 'exercise-addiction-calculator', category: 'health', region: 'usa', keywords: ['exercise addiction calculator', 'compulsive exercise test', 'exercise addiction inventory', 'EAI score calculator', 'over-exercising risk assessment'] })
const relatedCalculators = [{'name': 'Mental Health Score', 'href': '/calculators/health/mental-health-score-calculator', 'icon': '💆', 'desc': 'PHQ-9 & GAD-7'}, {'name': 'Stress Level', 'href': '/calculators/health/stress-level-calculator', 'icon': '🧘', 'desc': 'PSS-10 score'}, {'name': 'Workout Volume', 'href': '/calculators/health/workout-volume-calculator', 'icon': '📊', 'desc': 'Training volume'}, {'name': 'Mental Fatigue', 'href': '/calculators/health/mental-fatigue-calculator', 'icon': '🧠', 'desc': 'Burnout risk'}]
const faqs = [
  {"question": "What is exercise addiction?", "answer": "Exercise addiction (EA) is a compulsive relationship with exercise characterised by loss of control over exercise behaviour, continuation despite injury or illness, withdrawal symptoms (anxiety, irritability) when unable to exercise, and prioritising exercise above relationships, work, and health. Unlike healthy athletic dedication, EA is defined by harm — the person exercises compulsively rather than by choice. Prevalence estimates range from 0.3-0.5% in general population to 1-3% in habitual exercisers, rising to over 8% in some triathlete and ultramarathon populations."},
  {"question": "How is exercise addiction different from athletic commitment?", "answer": "The distinction lies in function, not volume. Competitive athletes training 15-20 hours per week can have a completely healthy relationship with exercise — training serves their goals and they can take rest days without psychological distress. Exercise addiction is characterised by: rest day guilt or anxiety that feels unmanageable; exercising despite clear injury signals; social isolation to prioritise exercise; exercise primarily serving emotional regulation or control rather than performance or health; and inability to modify volume even when it is harming relationships or health."},
  {"question": "What causes exercise addiction?", "answer": "Exercise addiction often develops alongside eating disorders (co-occurring in 39-48% of cases), anxiety disorders, body dysmorphic disorder, and perfectionism. The neurobiological mechanism involves reward pathway sensitisation — intense exercise releases endorphins, dopamine, and serotonin, and in susceptible individuals this reward circuit can become dysregulated similarly to substance addiction. Bodybuilding and aesthetic fitness cultures can reinforce the belief that 'more is always better,' and social media amplify this. Treatment typically involves cognitive-behavioural therapy (CBT), sports psychology, and sometimes treatment of co-occurring conditions."}
]
export default function Page() {
  const _faqSchema = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faqs.map((f: any) => ({ '@type': 'Question', name: f.question, acceptedAnswer: { '@type': 'Answer', text: f.answer } })) }
  return (<><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(_faqSchema) }} /><CalculatorClient faqs={faqs} structuredData={[generateFAQStructuredData(faqs), generateWebAppStructuredData({ name: 'Exercise Addiction Risk Calculator', description: 'Free exercise addiction risk calculator based on validated EAI criteria 2026. Assess compulsive exer', url: 'https://tooltrio.com/calculators/health/exercise-addiction-calculator', category: 'HealthApplication' })]} relatedCalculators={relatedCalculators} />      <CalculatorBatch48DeepDive slug="exercise-addiction-calculator" />
</>)
}
