import type { Metadata } from 'next'
import { generateCalculatorMetadata, generateFAQStructuredData, generateWebAppStructuredData } from '@/lib/seo/metadata'
import dynamic from 'next/dynamic'
const CalculatorClient = dynamic(() => import('./CalculatorClient'))
export const metadata: Metadata = generateCalculatorMetadata({ title: 'Dehydration Status Calculator — Exercise Fluid Loss 2026 | ToolTrio', description: 'Free dehydration calculator 2026. Calculate fluid loss percentage, dehydration severity, and precise rehydration targets from exercise duration, temperature, and sweat rate.', slug: 'dehydration-status-calculator', category: 'health', region: 'usa', keywords: ['dehydration calculator', 'exercise fluid loss calculator', 'rehydration calculator', 'how much water after exercise calculator', 'dehydration symptoms by percentage'] })
const relatedCalculators = [{'name': 'Hydration Calculator', 'href': '/calculators/health/hydration-calculator', 'icon': '💧', 'desc': 'Daily water needs'}, {'name': 'Sweat Rate', 'href': '/calculators/health/sweat-rate-calculator', 'icon': '🌡️', 'desc': 'Sweat rate per hour'}, {'name': 'Electrolyte Calculator', 'href': '/calculators/health/sodium-intake-calculator', 'icon': '⚡', 'desc': 'Sodium needs'}, {'name': 'Exercise Hydration', 'href': '/calculators/health/hydration-exercise-calculator', 'icon': '🏃', 'desc': 'Pre/during/post workout'}]
const faqs = [
  {"question": "How much dehydration affects performance?", "answer": "Even 2% body weight loss from fluid deficit reduces aerobic exercise performance by 10-20% and impairs cognitive function measurably. At 4%, heat cramps risk rises significantly. At 6-8%, heat exhaustion becomes likely. Thirst is not a reliable early warning — you can be 1-2% dehydrated before thirst signals arrive. Pre-exercise hydration status matters enormously: starting exercise dehydrated compresses the performance decline curve significantly."},
  {"question": "Do electrolytes matter for rehydration?", "answer": "For exercise under 60 minutes, plain water is adequate. Beyond 60-90 minutes, especially in heat, replacing electrolytes (primarily sodium) becomes essential. Sodium drives thirst, maintains plasma volume, and prevents hyponatraemia (dangerous overhydration from drinking plain water without sodium replacement). Sports drinks providing 500-700mg sodium per litre are appropriate for prolonged endurance events. For most gym sessions, electrolyte tablets or a salty post-workout meal adequately replaces losses."},
  {"question": "What colour should my urine be?", "answer": "Urine colour is a practical hydration indicator: pale straw yellow (like lemonade) indicates good hydration. Dark amber or tea-coloured urine indicates significant dehydration — drink 500mL immediately. Bright yellow after B-vitamin supplementation is harmless. First morning urine is normally darker from overnight concentration — this is physiological, not pathological dehydration. For endurance athletes, checking urine colour before and after training is a simple, reliable hydration monitoring tool."}
]
export default function Page() {
  const _faqSchema = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faqs.map((f: any) => ({ '@type': 'Question', name: f.question, acceptedAnswer: { '@type': 'Answer', text: f.answer } })) }
  return (<><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(_faqSchema) }} /><CalculatorClient faqs={faqs} structuredData={[generateFAQStructuredData(faqs), generateWebAppStructuredData({ name: 'Dehydration Status Calculator', description: 'Free dehydration calculator 2026. Calculate fluid loss percentage, dehydration severity, and precise', url: 'https://tooltrio.com/calculators/health/dehydration-status-calculator', category: 'HealthApplication' })]} relatedCalculators={relatedCalculators} /></>)
}
