import type { Metadata } from 'next'
import { generateCalculatorMetadata, generateFAQStructuredData, generateWebAppStructuredData } from '@/lib/seo/metadata'
import dynamic from 'next/dynamic'
const CalculatorClient = dynamic(() => import('./CalculatorClient'), {
  
  loading: () => <div className="min-h-[400px] bg-white rounded-2xl border border-gray-100 animate-pulse m-4" />
})
export const metadata: Metadata = generateCalculatorMetadata({ title: 'Food Sensitivity Load Calculator 2026 | ToolTrio', description: 'Free food sensitivity load calculator 2026. Assess your cumulative sensitivity burden from gluten, dairy, eggs, soy, and nuts. Get elimination diet guidance and nutritional risk assessment.', slug: 'food-sensitivity-calculator', category: 'health', region: 'usa', keywords: ['food sensitivity calculator', 'food intolerance test online free', 'gluten sensitivity calculator', 'elimination diet calculator', 'food sensitivity load score'] })
const relatedCalculators = [{'name': 'Gut Health', 'href': '/calculators/health/gut-health-calculator', 'icon': '🦠', 'desc': 'Gut microbiome health'}, {'name': 'Dietary Inflammatory Index', 'href': '/calculators/health/dietary-inflammatory-index-calculator', 'icon': '🔬', 'desc': 'Diet inflammation score'}, {'name': 'Nutritional Deficiency', 'href': '/calculators/health/nutritional-deficiency-risk-calculator', 'icon': '🥗', 'desc': 'Deficiency risk'}, {'name': 'Inflammation Risk', 'href': '/calculators/health/inflammation-risk-calculator', 'icon': '🔴', 'desc': 'Inflammation markers'}]
const faqs = [
  {"question": "What is the difference between food allergy and food sensitivity?", "answer": "Food allergy involves IgE-mediated immune responses — immediate reactions (minutes to 2 hours) that can be life-threatening (anaphylaxis). They are diagnosed by allergen-specific IgE blood tests or skin prick tests. Food sensitivity (intolerance) involves non-IgE mechanisms — delayed reactions (hours to 72 hours) causing symptoms like bloating, brain fog, joint pain, fatigue, skin issues, and headaches. They are harder to diagnose because the delay makes cause-and-effect difficult to identify. The gold standard for identifying food sensitivities remains the elimination and reintroduction protocol — eliminating suspect foods for 3-6 weeks then reintroducing them one at a time."},
  {"question": "Are IgG food sensitivity blood tests accurate?", "answer": "Commercial IgG4 food sensitivity panels are widely sold but scientifically controversial. Major allergy societies (AAAI, BSACI) consider IgG4 food testing unreliable for diagnosing food sensitivity — elevated IgG4 antibodies to a food typically reflect normal immune exposure to that food, not pathological reaction. A positive IgG4 to wheat does not mean wheat is causing your symptoms. The American Academy of Allergy, Asthma & Immunology (AAAAI) has explicitly stated these tests should not be used to diagnose food hypersensitivity. This calculator assesses symptom burden to identify patterns warranting supervised elimination trials."},
  {"question": "How do I do a proper elimination diet?", "answer": "A strict elimination diet removes the most common reactive foods simultaneously for 4-6 weeks: gluten, dairy, eggs, soy, tree nuts, peanuts, fish/shellfish, nightshades (tomato, pepper, potato), alcohol, and caffeine. This clean baseline allows symptoms to resolve. Then foods are reintroduced one at a time, every 3-5 days, while tracking symptoms in a food diary. Any symptom reappearance within 72 hours of reintroduction suggests sensitivity to that food. Working with a registered dietitian is strongly recommended to ensure nutritional adequacy, especially during multiple-food elimination phases."}
]
export default function Page() {
  const _faqSchema = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faqs.map((f: any) => ({ '@type': 'Question', name: f.question, acceptedAnswer: { '@type': 'Answer', text: f.answer } })) }
  return (<><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(_faqSchema) }} /><CalculatorClient faqs={faqs} structuredData={[generateFAQStructuredData(faqs), generateWebAppStructuredData({ name: 'Food Sensitivity Load Calculator', description: 'Free food sensitivity load calculator 2026. Assess your cumulative sensitivity burden from gluten, d', url: 'https://tooltrio.com/calculators/health/food-sensitivity-calculator', category: 'HealthApplication' })]} relatedCalculators={relatedCalculators} /></>)
}
