import type { Metadata } from 'next'
import { generateCalculatorMetadata, generateFAQStructuredData, generateWebAppStructuredData } from '@/lib/seo/metadata'
import dynamic from 'next/dynamic'
const CalculatorClient = dynamic(() => import('./CalculatorClient'), { ssr: false, loading: () => <div className="min-h-[400px] bg-white rounded-2xl border border-gray-100 animate-pulse m-4" /> })
export const metadata: Metadata = generateCalculatorMetadata({ title: 'Sauna Health Calculator — Frequency, Temperature & CVD Benefits | ToolTrio', description: "Free sauna health calculator 2026. Score your sauna routine's cardiovascular, longevity, and recovery benefits from session frequency, duration, temperature, and sauna type. Includes HSP and growth hormone data.", slug: 'sauna-health-calculator', category: 'health', region: 'usa', keywords: ['sauna health benefits calculator', 'sauna frequency calculator', 'sauna cardiovascular benefits calculator', 'how often should I sauna calculator', 'sauna longevity calculator'] })
const relatedCalculators = [{'name': 'Heart Rate Variability', 'href': '/calculators/health/heart-rate-variability-calculator', 'icon': '💓', 'desc': 'HRV recovery score'}, {'name': 'Longevity Risk', 'href': '/calculators/health/longevity-risk-calculator', 'icon': '♾️', 'desc': 'Lifespan projection'}, {'name': 'Dehydration Status', 'href': '/calculators/health/dehydration-status-calculator', 'icon': '💧', 'desc': 'Hydration status'}, {'name': 'Metabolic Age', 'href': '/calculators/health/metabolic-age-calculator', 'icon': '⚡', 'desc': 'Metabolic vs actual age'}]
const faqs = [
  { question: 'How often should I use a sauna for cardiovascular benefits?', answer: "The landmark Kuopio Heart Study (Dr. Jari Laukkanen, 2018) of 2,315 Finnish men found dramatic dose-dependent cardiovascular benefits: 2-3 sauna sessions per week = 22% lower CVD mortality; 4-7 sessions per week = 50% lower CVD mortality vs once-weekly users. Sessions were 15-20 minutes at 80-100°C. The mechanism appears to involve repeated heat-mediated vasodilation improving endothelial function, blood pressure reduction, and heat shock protein activation. The cardiovascular adaptations mirror those of moderate aerobic exercise, which is why sauna is sometimes called 'passive cardio' — useful for those who cannot exercise intensely." },
  { question: 'What are heat shock proteins and why do they matter?', answer: 'Heat shock proteins (HSPs) are molecular chaperones produced in response to thermal stress. HSP70 and HSP90 unfold misfolded proteins, preventing cellular damage and supporting proteostasis — a key longevity mechanism. Sauna sessions at ≥ 80°C significantly upregulate HSP expression. In longevity research, HSPs are associated with cellular repair, reduced protein aggregation (relevant to neurodegenerative diseases), and improved muscle recovery. Regular sauna use also activates FOXO3 transcription factors and AMPK pathways, both associated with increased healthspan in animal models.' },
  { question: 'Is sauna safe with hypertension or heart disease?', answer: 'Most people with controlled hypertension or stable heart disease can safely use a sauna. Blood pressure initially rises slightly on entering (sympathetic response) then drops below baseline as vasodilation occurs — the net effect is hypotensive. However, individuals with very high or uncontrolled blood pressure, recent MI, unstable angina, or decompensated heart failure should consult their cardiologist first. Contraindications include aortic stenosis, recent MI (< 6 weeks), severe COPD, and acute febrile illness. The risks come primarily from dehydration and the circulatory demands of rapid temperature change.' },
]
export default function Page() {
  const _faqSchema = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faqs.map((f: any) => ({ '@type': 'Question', name: f.question, acceptedAnswer: { '@type': 'Answer', text: f.answer } })) }
  return (<><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(_faqSchema) }} /><CalculatorClient faqs={faqs} structuredData={[generateFAQStructuredData(faqs), generateWebAppStructuredData({ name: 'Sauna Health Benefits Calculator', description: "Free sauna health calculator 2026. Score your sauna routine's cardiovascular, longevity, and recover", url: 'https://tooltrio.com/calculators/health/sauna-health-calculator', category: 'HealthApplication' })]} relatedCalculators={relatedCalculators} /></>)
}
