import type { Metadata } from 'next'
import { generateCalculatorMetadata, generateFAQStructuredData } from '@/lib/seo/metadata'
import dynamic from 'next/dynamic'
const CalculatorClient = dynamic(() => import('./CalculatorClient'), { ssr: false, loading: () => <div className="min-h-[400px] bg-white rounded-2xl border border-gray-100 animate-pulse m-4" /> })
export const metadata: Metadata = generateCalculatorMetadata({ title: 'FICA Tax Calculator USA 2026 | ToolTrio', description: 'Calculate FICA taxes: Social Security and Medicare tax for employees and self-employed workers. Includes 2026 wage base limit and Additional Medicare Tax.', slug: 'fica-tax-calculator', category: 'finance', keywords: ['FICA tax calculator 2026','Social Security tax calculator USA','Medicare tax calculator','self-employed FICA tax','Additional Medicare Tax calculator'] })
const faqs = [{ question: 'What is the FICA tax rate for 2026?', answer: 'For 2026, employees pay 6.2% Social Security tax on wages up to $176,100 (the wage base) and 1.45% Medicare tax on all wages. Employers match both. Self-employed workers pay the full 15.3% (12.4% SS + 2.9% Medicare) but can deduct half as a business expense. An additional 0.9% Medicare surtax applies to wages above $200,000 (single) or $250,000 (married).' }, { question: 'Does the Social Security wage base change every year?', answer: 'Yes — the Social Security wage base is adjusted annually based on average wage growth. For 2026 it is $176,100, up from $168,600 in 2024. Once your wages exceed this cap, you stop paying Social Security tax for that year. Medicare tax has no wage cap — you pay 1.45% on all earnings.' }]
const relatedCalculators = [{ name: 'Payroll Tax Calculator', href: '/calculators/finance/payroll-tax-calculator', icon: '📋', desc: 'Full payroll taxes' }, { name: 'Paycheck Calculator', href: '/calculators/finance/paycheck-calculator', icon: '💵', desc: 'Take-home pay' }, { name: 'Self-Employment Tax', href: '/calculators/finance/self-employment-tax-calculator', icon: '💼', desc: 'SE tax calculator' }]
const structuredData = [generateFAQStructuredData(faqs)]
export default function Page() { return <>{structuredData.map((s, i) => <script key={i} type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(s) }} />)}<CalculatorClient faqs={faqs} structuredData={structuredData} relatedCalculators={relatedCalculators} /></> }
