import type { Metadata } from 'next'
import { generateCalculatorMetadata, generateFAQStructuredData, generateWebAppStructuredData } from '@/lib/seo/metadata'
import dynamic from 'next/dynamic'
const CalculatorClient = dynamic(() => import('./CalculatorClient'), {  loading: () => <div className="min-h-[400px] bg-white rounded-2xl border border-gray-100 animate-pulse m-4" /> })
export const metadata: Metadata = generateCalculatorMetadata({ title: 'Hydration for Exercise Calculator — Pre/During/Post Workout | ToolTrio', description: 'Free exercise hydration calculator 2026. Calculate exact pre-workout, during-workout, and post-workout fluid needs based on duration, intensity, temperature, altitude, and exercise type.', slug: 'hydration-exercise-calculator', category: 'health', region: 'usa', keywords: ['exercise hydration calculator', 'how much water during workout calculator', 'pre workout hydration calculator', 'sports drink calculator', 'fluid needs exercise temperature calculator'] })
const relatedCalculators = [{'name': 'Dehydration Status', 'href': '/calculators/health/dehydration-status-calculator', 'icon': '💦', 'desc': 'Fluid loss percentage'}, {'name': 'Sweat Rate', 'href': '/calculators/health/sweat-rate-calculator', 'icon': '🌡️', 'desc': 'Sweat rate per hour'}, {'name': 'Hydration Calculator', 'href': '/calculators/health/hydration-calculator', 'icon': '💧', 'desc': 'Daily water needs'}, {'name': 'Calorie Burned', 'href': '/calculators/health/calories-burned-calculator', 'icon': '🔥', 'desc': 'Calories burned'}]
const faqs = [
  {"question": "How much should I drink before exercise?", "answer": "Guidelines recommend 400–600mL (14–20 oz) of water 2 hours before exercise, and an additional 200–300mL 15–30 minutes before. However, hydration strategy should start 24 hours before important events — no last-minute water loading can compensate for arriving dehydrated. A practical pre-event check: your urine should be pale straw yellow before the warm-up."},
  {"question": "What should I drink during a long run or cycle?", "answer": "Aim to replace 70-80% of sweat losses during exercise (not 100% — slight dehydration is acceptable and avoids hyponatraemia risk from over-drinking). For exercise over 90 minutes in heat, use a sports drink with 500-700mg sodium per litre to replace electrolytes and maintain plasma volume. For events over 3 hours, consider sodium tablets or electrolyte capsules alongside water to prevent exercise-associated hyponatraemia (EAH), which caused multiple marathon deaths when athletes over-drank plain water."},
  {"question": "How much water do I need after exercise?", "answer": "The post-exercise rehydration target is 1.5× the fluid lost — the extra 50% accounts for urine losses during the rehydration process. The easiest measurement: weigh yourself before and after exercise; every kilogram lost equals approximately 1 litre of fluid deficit. So if you lost 1.5 kg, drink 2.25 L over the following hours. Rehydration should not be rushed — spreading fluid intake over 2–4 hours optimises retention versus drinking large volumes rapidly."}
]
export default function Page() {
  const _faqSchema = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faqs.map((f: any) => ({ '@type': 'Question', name: f.question, acceptedAnswer: { '@type': 'Answer', text: f.answer } })) }
  return (<><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(_faqSchema) }} /><CalculatorClient faqs={faqs} structuredData={[generateFAQStructuredData(faqs), generateWebAppStructuredData({ name: 'Hydration for Exercise Calculator', description: 'Free exercise hydration calculator 2026. Calculate exact pre-workout, during-workout, and post-worko', url: 'https://tooltrio.com/calculators/health/hydration-exercise-calculator', category: 'HealthApplication' })]} relatedCalculators={relatedCalculators} /></>)
}
