'use client'
import { useMemo, useState } from 'react'
import { CalculatorLayout } from '@/components/ui/CalculatorLayout'
import { Card, ResultCard } from '@/components/ui/Card'
import { InputField, SelectField } from '@/components/ui/InputField'
import { FAQSection } from '@/components/ui/FAQSection'
interface Props { structuredData?:object[]; faqs:any[]; relatedCalculators?:any[] }
export default function CalculatorClient({faqs,relatedCalculators,structuredData}:Props){
 const [age,setAge]=useState(35),[sex,setSex]=useState<'male'|'female'>('male'),[weight,setWeight]=useState(165),[height,setHeight]=useState(69)
 const [unit,setUnit]=useState<'imperial'|'metric'>('imperial')
 const result=useMemo(()=>{const kg=unit==='imperial'?weight*.453592:weight; const m=(unit==='imperial'?height*2.54:height)/100; const bmi=kg/(m*m); const score=Math.max(0,Math.min(100,Math.round(80-Math.abs(bmi-22)*3+(age<50?5:0)))); return {bmi:bmi.toFixed(1),score}},[age,weight,height,unit])
 return <CalculatorLayout title="Mental Wellness Lifestyle Score" description="Educational wellbeing score from selected lifestyle and body-composition inputs. It is not a mental-health diagnosis or validated screening test." icon="🧠" category="Health" structuredData={structuredData} relatedCalculators={relatedCalculators} slug="mental-health-score-calculator"><div className="grid grid-cols-1 lg:grid-cols-3 gap-6"><Card className="lg:col-span-1"><h2 className="text-base font-bold text-gray-900 mb-5">Inputs</h2><div className="space-y-4"><SelectField label="Unit" value={unit} onChange={v=>setUnit(v as any)} options={[{value:'metric',label:'Metric (kg/cm)'},{value:'imperial',label:'Imperial (lb/in)'}]}/><SelectField label="Sex" value={sex} onChange={v=>setSex(v as any)} options={[{value:'male',label:'Male'},{value:'female',label:'Female'}]}/><InputField label={`Weight (${unit==='metric'?'kg':'lb'})`} value={weight} onChange={setWeight} min={30} max={250} step={1}/><InputField label={`Height (${unit==='metric'?'cm':'in'})`} value={height} onChange={setHeight} min={120} max={220} step={1}/><InputField label="Age" value={age} onChange={setAge} min={15} max={90} step={1} suffix="yrs"/></div></Card><div className="lg:col-span-2 space-y-4"><div className="grid grid-cols-2 gap-3"><ResultCard label="Wellbeing score" value={`${result.score}/100`} highlight/><ResultCard label="BMI context" value={result.bmi}/></div><Card><h3 className="font-bold text-gray-900 mb-3">Limitations</h3><p className="text-sm text-gray-600 leading-6">This is a ToolTrio educational lifestyle score. It does not implement PHQ-9, GAD-7, WHO-5 or another validated mental-health screening instrument and should not be used to diagnose depression, anxiety, burnout or another condition.</p></Card><Card><h3 className="font-bold text-gray-900 mb-2">Safety and limitations</h3><p className="text-sm text-gray-600">Persistent or worsening symptoms, significant functional impairment, or thoughts of self-harm require appropriate professional support rather than reliance on an online score.</p></Card></div></div><div className="mt-6"><FAQSection faqs={faqs}/></div></CalculatorLayout>
}
