import type { Metadata } from 'next'
import { generateCalculatorMetadata, generateFAQStructuredData, generateWebAppStructuredData } from '@/lib/seo/metadata'
import dynamic from 'next/dynamic'
const CalculatorClient = dynamic(() => import('./CalculatorClient'))
export const metadata: Metadata = generateCalculatorMetadata({ title: 'Diet Quality Score Calculator — HEI-Style Diet Rating 2026 | ToolTrio', description: 'Free diet quality score calculator 2026. Rate your overall diet quality like the Healthy Eating Index from vegetables, fruits, whole grains, fish, ultra-processed foods, sugar, and more.', slug: 'diet-quality-score-calculator', category: 'health', region: 'usa', keywords: ['diet quality score calculator', 'healthy eating index calculator', 'HEI diet score', 'diet rating calculator', 'overall diet quality test online free'] })
const relatedCalculators = [{'name': 'Dietary Inflammatory Index', 'href': '/calculators/health/dietary-inflammatory-index-calculator', 'icon': '🔬', 'desc': 'DII score'}, {'name': 'Nutritional Deficiency Risk', 'href': '/calculators/health/nutritional-deficiency-risk-calculator', 'icon': '🥗', 'desc': 'Deficiency risk'}, {'name': 'Gut Health', 'href': '/calculators/health/gut-health-calculator', 'icon': '🦠', 'desc': 'Microbiome score'}, {'name': 'Caloric Needs', 'href': '/calculators/health/caloric-needs-calculator', 'icon': '🍽️', 'desc': 'Daily calories'}]
const faqs = [
  {"question": "How is diet quality measured scientifically?", "answer": "The Healthy Eating Index (HEI), developed by USDA, rates diet quality on a 100-point scale based on 13 components including vegetables, fruits, whole grains, dairy, protein foods, fatty acids, refined grains, sodium, added sugars, and saturated fats. Population studies consistently show HEI score strongly predicts mortality, cancer incidence, and cardiovascular events — each 10-point increase in HEI score is associated with 8-10% lower all-cause mortality. The Mediterranean Diet Score (MDS) and DASH adherence score are similar validated instruments."},
  {"question": "What is an ultra-processed food and why does it matter?", "answer": "Ultra-processed foods (NOVA Group 4) are industrial formulations with 5+ ingredients including additives, preservatives, emulsifiers, flavour enhancers, and colourants — engineered for hyperpalatability. Examples: soft drinks, packaged snacks, reconstituted meat products, breakfast cereals, flavoured yoghurts. NOVA Group 4 consumption above 20% of calorie intake is associated with dose-dependent increases in cardiovascular disease, T2D, depression, colorectal cancer, and all-cause mortality in PURE, NutriNet-Santé, and UK Biobank studies. Critically, the harm appears beyond just nutrient profile — the processing itself is a risk factor."},
  {"question": "What does research say about the Mediterranean diet?", "answer": "The Mediterranean diet consistently achieves the highest diet quality scores and has the most robust randomised trial evidence of any dietary pattern. The PREDIMED trial (7,447 high-risk adults) showed Mediterranean diet supplemented with olive oil or nuts reduced major cardiovascular events by 30% vs low-fat diet control. The MIND diet (Mediterranean-DASH for Neurodegenerative Delay) is associated with 35-53% lower risk of Alzheimer's disease. Key components: olive oil, vegetables, fish, legumes, nuts, whole grains, moderate red wine — and critically, low processed meat, refined grains, and added sugar."}
]
export default function Page() {
  const _faqSchema = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faqs.map((f: any) => ({ '@type': 'Question', name: f.question, acceptedAnswer: { '@type': 'Answer', text: f.answer } })) }
  return (<><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(_faqSchema) }} /><CalculatorClient faqs={faqs} structuredData={[generateFAQStructuredData(faqs), generateWebAppStructuredData({ name: 'Diet Quality Score Calculator', description: 'Free diet quality score calculator 2026. Rate your overall diet quality like the Healthy Eating Inde', url: 'https://tooltrio.com/calculators/health/diet-quality-score-calculator', category: 'HealthApplication' })]} relatedCalculators={relatedCalculators} /></>)
}
