import { CalculatorBatch43DeepDive } from '@/components/ui/CalculatorBatch43DeepDive'
import type { Metadata } from 'next'
import { generateCalculatorMetadata, generateFAQStructuredData, generateWebAppStructuredData } from '@/lib/seo/metadata'
import dynamic from 'next/dynamic'
const CalculatorClient = dynamic(() => import('./CalculatorClient'), {
  
  loading: () => <div className="min-h-[400px] bg-white rounded-2xl border border-gray-100 animate-pulse m-4" />
})
export const metadata: Metadata = generateCalculatorMetadata({ title: 'Genetic Height Potential Calculator — Mid-Parental Height 2026 | ToolTrio', description: "Free genetic height potential calculator 2026. Predict adult height from parents' heights using the Tanner mid-parental height formula. Includes growth range, remaining growth, and modifier factors.", slug: 'genetic-height-calculator', category: 'health', region: 'usa', keywords: ['genetic height calculator', 'mid-parental height calculator', 'predicted adult height calculator', 'how tall will I be calculator', 'height potential calculator parents'] })
const relatedCalculators = [{'name': 'BMI Calculator', 'href': '/calculators/health/bmi-calculator', 'icon': '⚖️', 'desc': 'Body mass index'}, {'name': 'Ideal Weight', 'href': '/calculators/health/ideal-weight-calculator', 'icon': '⚖️', 'desc': 'Healthy weight range'}, {'name': 'Infant Weight Percentile', 'href': '/calculators/health/infant-weight-percentile-calculator', 'icon': '👶', 'desc': 'Child growth percentile'}, {'name': 'Body Age', 'href': '/calculators/health/body-age-calculator', 'icon': '🧬', 'desc': 'Biological age'}]
const faqs = [
  { question: 'How accurate is the mid-parental height method?', answer: 'The Tanner mid-parental height formula predicts adult height with a standard deviation of approximately ±8.5 cm (±3.4 inches), meaning 95% of individuals will fall within ±17 cm of the prediction. This range reflects genuine genetic variation — even identical twins raised apart can differ by 2-3 cm due to environmental factors. The formula is a reasonable population-level predictor but cannot account for individual genetic variants from grandparents and earlier ancestors that may push height beyond parental norms.' },
  { question: 'What environmental factors affect height?', answer: 'Genetics account for approximately 60-80% of adult height variation; the remaining 20-40% is environmental. The most impactful factors: nutrition (protein, calcium, zinc, vitamin D during childhood), illness (especially chronic conditions in the first 2 years of life), sleep quality (growth hormone is secreted primarily during deep sleep — sufficient sleep duration is essential), psychosocial stress (cortisol suppresses growth hormone), and altitude (paradoxically, high-altitude populations tend to be shorter due to hypoxia affecting early growth). In developed countries with adequate nutrition, genetic potential is largely achieved; the gap between genetic potential and actual height is wider in food-insecure populations.' },
  { question: 'At what age does height growth stop?', answer: 'Girls typically complete height growth by age 14-16 (2-3 years after the peak of the adolescent growth spurt, which occurs around age 11-12). Boys typically finish growing by age 17-18 (the growth spurt peaks around age 13-14). However, minor additional growth (< 1 cm) can occur into the early 20s for some individuals as growth plate closure completes. Bone age X-rays are more reliable than chronological age for predicting remaining growth potential — open growth plates indicate potential for more growth.' },
]
export default function Page() {
  const _faqSchema = generateFAQStructuredData(faqs)
  return (<><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(_faqSchema) }} /><CalculatorClient faqs={faqs} structuredData={[generateFAQStructuredData(faqs), generateWebAppStructuredData({ name: 'Genetic Height Potential Calculator', description: "Free genetic height potential calculator 2026. Predict adult height from parents' heights using the ", url: 'https://tooltrio.com/calculators/health/genetic-height-calculator', category: 'HealthApplication' })]} relatedCalculators={relatedCalculators} />      <CalculatorBatch43DeepDive slug="genetic-height-calculator" />
</>)
}
