'use client'
import { useMemo, useState } from 'react'
import { CalculatorLayout } from '@/components/ui/CalculatorLayout'
import { Card, ResultCard } from '@/components/ui/Card'
import { InputField, SelectField } from '@/components/ui/InputField'
import { FAQSection } from '@/components/ui/FAQSection'
interface Props { faqs:any[]; structuredData:object[]; relatedCalculators?:any[] }
export default function CalculatorClient({faqs,structuredData,relatedCalculators}:Props){
 const [age,setAge]=useState(42),[sex,setSex]=useState<'male'|'female'>('male'),[supplement,setSupplement]=useState(1000),[diet,setDiet]=useState(2)
 const result=useMemo(()=>{const target=age>=71?800:600; const intake=supplement+diet*40; const upper=4000; const status=intake<target?'Below general intake target':intake<=upper?'Within general intake range':'Above adult upper intake limit'; return {target,intake,upper,status}},[age,supplement,diet])
 return <CalculatorLayout title="Vitamin D Intake & Status Context Calculator" description="Compare estimated daily vitamin D intake with general reference values. Serum vitamin D status requires a 25-hydroxyvitamin D blood test." icon="☀️" category="Health" structuredData={structuredData} relatedCalculators={relatedCalculators} slug="vitamin-d-status-calculator">
 <div className="grid grid-cols-1 lg:grid-cols-3 gap-6"><Card className="lg:col-span-1"><h2 className="text-sm font-semibold text-rose-400 uppercase tracking-wider mb-4">Inputs</h2><div className="space-y-4"><SelectField label="Sex" value={sex} onChange={v=>setSex(v as any)} options={[{value:'male',label:'Male'},{value:'female',label:'Female'}]}/><InputField label="Age" value={age} onChange={setAge} min={19} max={100} step={1} suffix="yrs"/><InputField label="Vitamin D supplement" value={supplement} onChange={setSupplement} min={0} max={10000} step={100} suffix="IU/day"/><InputField label="Dietary vitamin D" value={diet} onChange={setDiet} min={0} max={40} step={0.5} suffix="mcg/day"/></div></Card><div className="lg:col-span-2 space-y-4"><div className="grid grid-cols-2 sm:grid-cols-3 gap-3"><ResultCard label="Estimated intake" value={`${result.intake} IU/day`} highlight/><ResultCard label="General target" value={`${result.target} IU/day`}/><ResultCard label="Status" value={result.status}/></div><Card><h3 className="font-bold text-gray-900 mb-3">Methodology and limitations</h3><p className="text-sm text-gray-600 leading-6">This is an educational intake estimate. Daily intake is not the same thing as blood vitamin D status. The main laboratory indicator is serum 25(OH)D. This page does not estimate a blood concentration from sun exposure, skin tone, latitude or supplements.</p><p className="text-xs text-gray-500 mt-3">NIH notes that 600 IU/day is the recommended dietary allowance for most adults 19–70 and 800 IU/day for adults 71+, while 4,000 IU/day is the adult tolerable upper intake level.</p></Card></div></div><div className="mt-6"><FAQSection faqs={faqs}/></div></CalculatorLayout>
}
